#!/usr/bin/env python3
"""
Skript zum Hinzufügen der Top 50 St. Galler Weine zur Datenbank
Mit deutschen, englischen und französischen Beschreibungen

St. Gallen - Rheintaler Leidenschaft und Eleganz
Das Blauburgunderland par excellence
"""

import asyncio
import os
from uuid import uuid4
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

# Die 50 St. Galler Weine mit allen Details
STGALLEN_WINES = [
    {
        "name": "Zweigelt 2020",
        "winery": "tobias wein.gut",
        "region": "Berneck",
        "grape_variety": "Zweigelt",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Ein dunkler Verführer, der von schwarzen Beeren und Pfeffer flüstert – ein Wein, der die Seele in leidenschaftliche Umarmung hüllt und als bester Deutschschweizer Rotwein triumphiert.",
        "description_en": "A dark seducer whispering of black berries and pepper – a wine that wraps the soul in passionate embrace, triumphant as the best German-Swiss red wine.",
        "description_fr": "Un séducteur sombre qui murmure des baies noires et du poivre – un vin qui enveloppe l'âme dans une étreinte passionnée, triomphant comme le meilleur vin rouge suisse alémanique.",
        "food_pairings_de": ["Gegrilltes Rind", "Dunkle Schokolade"],
        "food_pairings_en": ["Grilled beef", "Dark chocolate"],
        "food_pairings_fr": ["Bœuf grillé", "Chocolat noir"],
    },
    {
        "name": "Merlot 2019",
        "winery": "tobias wein.gut",
        "region": "Berneck",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Samten und intensiv, mit Pflaume und Tabak, der wie ein alter Freund die Seele in tröstliche Wärme taucht – Gold beim Grand Prix du Vin Suisse.",
        "description_en": "Velvety and intense, with plum and tobacco, immersing the soul in comforting warmth like an old friend – Gold at the Grand Prix du Vin Suisse.",
        "description_fr": "Velouté et intense, avec de la prune et du tabac, plongeant l'âme dans une chaleur réconfortante – Or au Grand Prix du Vin Suisse.",
        "food_pairings_de": ["Lammragout", "Reifer Käse"],
        "food_pairings_en": ["Lamb ragout", "Aged cheese"],
        "food_pairings_fr": ["Ragoût d'agneau", "Fromage affiné"],
    },
    {
        "name": "Müller-Thurgau 2024",
        "winery": "Weingut Zünd",
        "region": "Altstätten",
        "grape_variety": "Müller-Thurgau",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Frisch und aromatisch, ein Hauch von Muskat und Apfel, der die Seele mit jugendlicher Lebendigkeit erfrischt.",
        "description_en": "Fresh and aromatic, a hint of muscat and apple that refreshes the soul with youthful vivacity.",
        "description_fr": "Frais et aromatique, une touche de muscat et de pomme qui rafraîchit l'âme avec une vivacité juvénile.",
        "food_pairings_de": ["Gebratener Fisch", "Sommergemüse"],
        "food_pairings_en": ["Fried fish", "Summer vegetables"],
        "food_pairings_fr": ["Poisson frit", "Légumes d'été"],
    },
    {
        "name": "Pinot Noir Barrique 2023",
        "winery": "Weingut Bad Osterfingen",
        "region": "Osterfingen",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Elegant und filigran, mit Kirsche und Leder, der die Seele in burgundische Melancholie entführt.",
        "description_en": "Elegant and delicate, with cherry and leather, transporting the soul into Burgundian melancholy.",
        "description_fr": "Élégant et délicat, avec de la cerise et du cuir, transportant l'âme dans la mélancolie bourguignonne.",
        "food_pairings_de": ["Entenbrust", "Pilzrisotto"],
        "food_pairings_en": ["Duck breast", "Mushroom risotto"],
        "food_pairings_fr": ["Magret de canard", "Risotto aux champignons"],
    },
    {
        "name": "Riesling-Sylvaner 2024",
        "winery": "Ochsentorkel Weinbau",
        "region": "Thal",
        "grape_variety": "Riesling-Sylvaner",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Knackig und mineralisch, ein Tropfen, der wie ein Rheinnebel die Seele klärt und verjüngt.",
        "description_en": "Crisp and mineral, a drop that clears and rejuvenates the soul like Rhine mist.",
        "description_fr": "Croquant et minéral, une goutte qui clarifie et rajeunit l'âme comme la brume du Rhin.",
        "food_pairings_de": ["Meeresfrüchte", "Frischer Salat"],
        "food_pairings_en": ["Seafood", "Fresh salad"],
        "food_pairings_fr": ["Fruits de mer", "Salade fraîche"],
    },
    {
        "name": "Chardonnay 2023",
        "winery": "Casa Nova Wein Pur AG",
        "region": "Walenstadt",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Cremig und golden, mit Nuss und Zitrus, der die Seele in sonnige Höhen trägt.",
        "description_en": "Creamy and golden, with nut and citrus, carrying the soul to sunny heights.",
        "description_fr": "Crémeux et doré, avec de la noix et des agrumes, portant l'âme vers des hauteurs ensoleillées.",
        "food_pairings_de": ["Gegrilltes Huhn", "Milde Tomme"],
        "food_pairings_en": ["Grilled chicken", "Mild Tomme"],
        "food_pairings_fr": ["Poulet grillé", "Tomme douce"],
    },
    {
        "name": "Pinot Noir Reblaube 2023",
        "winery": "Erich Meier",
        "region": "Uetikon am See",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Rubinrot und tief, ein Meisterwerk von Kirschen und Erde, das das Herz mit purer Eleganz erobert.",
        "description_en": "Ruby red and deep, a masterpiece of cherries and earth that conquers the heart with pure elegance.",
        "description_fr": "Rouge rubis et profond, un chef-d'œuvre de cerises et de terre qui conquiert le cœur avec une élégance pure.",
        "food_pairings_de": ["Rehrücken", "Wildgerichte"],
        "food_pairings_en": ["Saddle of venison", "Game dishes"],
        "food_pairings_fr": ["Selle de chevreuil", "Gibier"],
    },
    {
        "name": "Sauvignon Blanc 2024",
        "winery": "aagne weingut",
        "region": "Hallau",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Nervös und exotisch, mit Stachelbeere und Kräutern, der wie ein Frühlingssturm die Seele weckt.",
        "description_en": "Nervous and exotic, with gooseberry and herbs, awakening the soul like a spring storm.",
        "description_fr": "Nerveux et exotique, avec de la groseille et des herbes, éveillant l'âme comme une tempête de printemps.",
        "food_pairings_de": ["Ziegenkäse", "Asiatisches Gemüse"],
        "food_pairings_en": ["Goat cheese", "Asian vegetables"],
        "food_pairings_fr": ["Fromage de chèvre", "Légumes asiatiques"],
    },
    {
        "name": "Pinot Noir Buck 2023",
        "winery": "Weinbau Markus Ruch",
        "region": "Hallau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Fruchtig und robust, ein Pinot, der das Herz mit Beeren und Gewürzen in Ekstase versetzt.",
        "description_en": "Fruity and robust, a Pinot that sends the heart into ecstasy with berries and spices.",
        "description_fr": "Fruité et robuste, un Pinot qui met le cœur en extase avec des baies et des épices.",
        "food_pairings_de": ["BBQ", "Scharfe Wurst"],
        "food_pairings_en": ["BBQ", "Spicy sausage"],
        "food_pairings_fr": ["BBQ", "Saucisse épicée"],
    },
    {
        "name": "Malbec 2023",
        "winery": "Hedinger Weingut & Kellerei",
        "region": "Wilchingen",
        "grape_variety": "Malbec",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Würzig und intensiv, mit Brombeere und Pfeffer, der die Seele in südliche Glut taucht.",
        "description_en": "Spicy and intense, with blackberry and pepper, immersing the soul in southern heat.",
        "description_fr": "Épicé et intense, avec de la mûre et du poivre, plongeant l'âme dans la chaleur du sud.",
        "food_pairings_de": ["Dunkles Fleisch", "Schokolade"],
        "food_pairings_en": ["Dark meat", "Chocolate"],
        "food_pairings_fr": ["Viande brune", "Chocolat"],
    },
    {
        "name": "Pinot Noir Classique 2023",
        "winery": "Weingut Baumann",
        "region": "Oberhallau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Ausgewogen und sinnlich, ein Klassiker, der die Seele mit Kirschen und Samt umfängt.",
        "description_en": "Balanced and sensual, a classic that embraces the soul with cherries and velvet.",
        "description_fr": "Équilibré et sensuel, un classique qui enlace l'âme avec des cerises et du velours.",
        "food_pairings_de": ["Pasta Bolognese", "Käsefondue"],
        "food_pairings_en": ["Pasta Bolognese", "Cheese fondue"],
        "food_pairings_fr": ["Pâtes Bolognaise", "Fondue au fromage"],
    },
    {
        "name": "Crémant Brut",
        "winery": "tobias wein.gut",
        "region": "Berneck",
        "grape_variety": "Assemblage",
        "wine_color": "schaumwein",
        "price_category": "€€€",
        "description_de": "Perlender Traum, der von Blasen und Zitruspoesie erzählt – festlich und lebendig.",
        "description_en": "Sparkling dream that speaks of bubbles and citrus poetry – festive and lively.",
        "description_fr": "Rêve pétillant qui parle de bulles et de poésie d'agrumes – festif et vivant.",
        "food_pairings_de": ["Austern", "Aperitif"],
        "food_pairings_en": ["Oysters", "Aperitif"],
        "food_pairings_fr": ["Huîtres", "Apéritif"],
    },
    {
        "name": "Pinot Noir Pilgrim 2022",
        "winery": "Weingut Höcklistein",
        "region": "Rapperswil-Jona",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Reif und komplex, ein Pilger der Tiefe, der die Seele in nostalgische Wärme hüllt.",
        "description_en": "Mature and complex, a pilgrim of depth that wraps the soul in nostalgic warmth.",
        "description_fr": "Mûr et complexe, un pèlerin de la profondeur qui enveloppe l'âme d'une chaleur nostalgique.",
        "food_pairings_de": ["Roastbeef", "Pilze"],
        "food_pairings_en": ["Roast beef", "Mushrooms"],
        "food_pairings_fr": ["Rosbif", "Champignons"],
    },
    {
        "name": "Chardonnay Hedinger 2023",
        "winery": "Hedinger Weingut & Kellerei",
        "region": "Wilchingen",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Barriqué und cremig, ein Goldstück mit Nuss und Butter, das die Seele streichelt.",
        "description_en": "Barrel-aged and creamy, a golden gem with nut and butter that caresses the soul.",
        "description_fr": "Élevé en barrique et crémeux, une pépite dorée avec de la noix et du beurre qui caresse l'âme.",
        "food_pairings_de": ["Krebse", "Geflügel"],
        "food_pairings_en": ["Crayfish", "Poultry"],
        "food_pairings_fr": ["Écrevisses", "Volaille"],
    },
    {
        "name": "Pinot Noir 2023",
        "winery": "Weingut Seewer",
        "region": "Wilchingen",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Filigran und fruchtig, ein Windhauch aus Beeren, der das Herz mit Frische weckt.",
        "description_en": "Delicate and fruity, a breath of berries that awakens the heart with freshness.",
        "description_fr": "Délicat et fruité, un souffle de baies qui éveille le cœur avec fraîcheur.",
        "food_pairings_de": ["Entenbrust", "Salat"],
        "food_pairings_en": ["Duck breast", "Salad"],
        "food_pairings_fr": ["Magret de canard", "Salade"],
    },
    {
        "name": "Mousseux Brut Bio 2023",
        "winery": "Rimuss & Strada Wein",
        "region": "Hallau",
        "grape_variety": "Assemblage",
        "wine_color": "schaumwein",
        "price_category": "€€€",
        "description_de": "Bio-perlend und rein, ein Tropfen, der die Seele in festliche Ekstase versetzt.",
        "description_en": "Organic-sparkling and pure, a drop that sends the soul into festive ecstasy.",
        "description_fr": "Bio-pétillant et pur, une goutte qui met l'âme en extase festive.",
        "food_pairings_de": ["Vorspeisen", "Feiern"],
        "food_pairings_en": ["Appetizers", "Celebrations"],
        "food_pairings_fr": ["Entrées", "Célébrations"],
    },
    {
        "name": "Irma la Douce 2024",
        "winery": "aagne weingut",
        "region": "Hallau",
        "grape_variety": "Assemblage",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Verführerisch und blumig, ein Weiß, der wie ein Flüstern die Seele umgarnt.",
        "description_en": "Seductive and floral, a white that beguiles the soul like a whisper.",
        "description_fr": "Séduisant et floral, un blanc qui charme l'âme comme un murmure.",
        "food_pairings_de": ["Leichte Gerichte", "Sommerabende"],
        "food_pairings_en": ["Light dishes", "Summer evenings"],
        "food_pairings_fr": ["Plats légers", "Soirées d'été"],
    },
    {
        "name": "Pinot Noir 2023",
        "winery": "Weingut GVS Schachenmann",
        "region": "Hallau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Tief und mineralisch, mit dunklen Früchten, die wie ein Geheimnis die Seele berühren.",
        "description_en": "Deep and mineral, with dark fruits that touch the soul like a secret.",
        "description_fr": "Profond et minéral, avec des fruits sombres qui touchent l'âme comme un secret.",
        "food_pairings_de": ["Rind", "Wild"],
        "food_pairings_en": ["Beef", "Game"],
        "food_pairings_fr": ["Bœuf", "Gibier"],
    },
    {
        "name": "Riesling 2023",
        "winery": "aagne weingut",
        "region": "Hallau",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Hoch und aromatisch, ein Riesling, der die Seele auf Höhenflüge trägt.",
        "description_en": "High and aromatic, a Riesling that carries the soul to soaring heights.",
        "description_fr": "Haut et aromatique, un Riesling qui porte l'âme vers des sommets.",
        "food_pairings_de": ["Käseplatte", "Forelle"],
        "food_pairings_en": ["Cheese platter", "Trout"],
        "food_pairings_fr": ["Plateau de fromages", "Truite"],
    },
    {
        "name": "Pinot Noir Lupa 2022",
        "winery": "Weingut Bad Osterfingen",
        "region": "Osterfingen",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Trinkbar und geheimnisvoll, ein Wolf unter den Pinots, der das Herz erheitert.",
        "description_en": "Drinkable and mysterious, a wolf among Pinots that cheers the heart.",
        "description_fr": "Buvable et mystérieux, un loup parmi les Pinots qui réjouit le cœur.",
        "food_pairings_de": ["Pasta", "Brot"],
        "food_pairings_en": ["Pasta", "Bread"],
        "food_pairings_fr": ["Pâtes", "Pain"],
    },
    {
        "name": "Chardonnay 2023",
        "winery": "Weingut Ruch",
        "region": "Hallau",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Reich und honigartig, ein Traum, der die Seele umhüllt.",
        "description_en": "Rich and honeyed, a dream that envelops the soul.",
        "description_fr": "Riche et miellé, un rêve qui enveloppe l'âme.",
        "food_pairings_de": ["Foie gras", "Desserts"],
        "food_pairings_en": ["Foie gras", "Desserts"],
        "food_pairings_fr": ["Foie gras", "Desserts"],
    },
    {
        "name": "Pinot Noir 2024",
        "winery": "Hedinger Weingut & Kellerei",
        "region": "Wilchingen",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Frisch und lebendig, ein junger Wilder, der die Seele tanzen lässt.",
        "description_en": "Fresh and lively, a young wild one that makes the soul dance.",
        "description_fr": "Frais et vivant, un jeune sauvage qui fait danser l'âme.",
        "food_pairings_de": ["Grilladen", "Tapas"],
        "food_pairings_en": ["Grilled meats", "Tapas"],
        "food_pairings_fr": ["Grillades", "Tapas"],
    },
    {
        "name": "Müller-Thurgau 2023",
        "winery": "Weingut Baumann",
        "region": "Oberhallau",
        "grape_variety": "Müller-Thurgau",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Exotisch und würzig, ein Klassiker mit Twist, der die Seele verzaubert.",
        "description_en": "Exotic and spicy, a classic with a twist that enchants the soul.",
        "description_fr": "Exotique et épicé, un classique avec une touche qui enchante l'âme.",
        "food_pairings_de": ["Curry", "Vegetarisch"],
        "food_pairings_en": ["Curry", "Vegetarian"],
        "food_pairings_fr": ["Curry", "Végétarien"],
    },
    {
        "name": "Pinot Noir 2023",
        "winery": "Weingut Höcklistein",
        "region": "Rapperswil-Jona",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Tief und harmonisch, ein Meister der Balance, der die Seele beruhigt.",
        "description_en": "Deep and harmonious, a master of balance that calms the soul.",
        "description_fr": "Profond et harmonieux, un maître de l'équilibre qui apaise l'âme.",
        "food_pairings_de": ["Ente", "Schokolade"],
        "food_pairings_en": ["Duck", "Chocolate"],
        "food_pairings_fr": ["Canard", "Chocolat"],
    },
    {
        "name": "Pinot Blanc 2022",
        "winery": "aagne weingut",
        "region": "Hallau",
        "grape_variety": "Pinot Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Zart und blumig, ein Blanc, der die Seele mit Reinheit erfüllt.",
        "description_en": "Delicate and floral, a Blanc that fills the soul with purity.",
        "description_fr": "Délicat et floral, un Blanc qui remplit l'âme de pureté.",
        "food_pairings_de": ["Fisch", "Salate"],
        "food_pairings_en": ["Fish", "Salads"],
        "food_pairings_fr": ["Poisson", "Salades"],
    },
    {
        "name": "Pinot Noir 2023",
        "winery": "Weinbau Markus Ruch",
        "region": "Hallau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Samten und warm, eine Umarmung in Rot.",
        "description_en": "Velvety and warm, an embrace in red.",
        "description_fr": "Velouté et chaud, une étreinte en rouge.",
        "food_pairings_de": ["Pasta", "Käse"],
        "food_pairings_en": ["Pasta", "Cheese"],
        "food_pairings_fr": ["Pâtes", "Fromage"],
    },
    {
        "name": "Chardonnay 2024",
        "winery": "Weingut Bad Osterfingen",
        "region": "Osterfingen",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Elegant und strukturiert, ein Tanz der Aromen.",
        "description_en": "Elegant and structured, a dance of aromas.",
        "description_fr": "Élégant et structuré, une danse des arômes.",
        "food_pairings_de": ["Huhn", "Raclette"],
        "food_pairings_en": ["Chicken", "Raclette"],
        "food_pairings_fr": ["Poulet", "Raclette"],
    },
    {
        "name": "Pinot Noir 2022",
        "winery": "Weingut Höcklistein",
        "region": "Rapperswil-Jona",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Würzig und intensiv, ein Feuerwerk der Sinne.",
        "description_en": "Spicy and intense, a firework of the senses.",
        "description_fr": "Épicé et intense, un feu d'artifice des sens.",
        "food_pairings_de": ["Gewürztes Fleisch"],
        "food_pairings_en": ["Spiced meat"],
        "food_pairings_fr": ["Viande épicée"],
    },
    {
        "name": "Riesling-Silvaner 2023",
        "winery": "Hedinger Weingut & Kellerei",
        "region": "Wilchingen",
        "grape_variety": "Riesling-Silvaner",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Feminine Eleganz, ein Seidentuch der Frische.",
        "description_en": "Feminine elegance, a silk cloth of freshness.",
        "description_fr": "Élégance féminine, un tissu de soie de fraîcheur.",
        "food_pairings_de": ["Perlhuhn", "Morcheln"],
        "food_pairings_en": ["Guinea fowl", "Morels"],
        "food_pairings_fr": ["Pintade", "Morilles"],
    },
    {
        "name": "Pinot Noir GVS 2023",
        "winery": "Weingut GVS Schachenmann",
        "region": "Hallau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Präzise und tief, ein Elite-Tropfen.",
        "description_en": "Precise and deep, an elite drop.",
        "description_fr": "Précis et profond, une goutte d'élite.",
        "food_pairings_de": ["Ente", "Risotto"],
        "food_pairings_en": ["Duck", "Risotto"],
        "food_pairings_fr": ["Canard", "Risotto"],
    },
    {
        "name": "Sauvignon Blanc 2023",
        "winery": "Weingut Baumann",
        "region": "Oberhallau",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Überraschend und nuanciert, ein alter Freund.",
        "description_en": "Surprising and nuanced, an old friend.",
        "description_fr": "Surprenant et nuancé, un vieil ami.",
        "food_pairings_de": ["Foie gras", "Käse"],
        "food_pairings_en": ["Foie gras", "Cheese"],
        "food_pairings_fr": ["Foie gras", "Fromage"],
    },
    {
        "name": "Pinot Noir Aagne 2024",
        "winery": "aagne weingut",
        "region": "Hallau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Robust und kraftvoll, ein Imperator.",
        "description_en": "Robust and powerful, an emperor.",
        "description_fr": "Robuste et puissant, un empereur.",
        "food_pairings_de": ["Lamm", "Pilze"],
        "food_pairings_en": ["Lamb", "Mushrooms"],
        "food_pairings_fr": ["Agneau", "Champignons"],
    },
    {
        "name": "Müller-Thurgau 2024",
        "winery": "Weingut Ruch",
        "region": "Hallau",
        "grape_variety": "Müller-Thurgau",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Vielschichtig und freudig, ein Kinderlachen im Glas.",
        "description_en": "Multi-layered and joyful, a child's laughter in a glass.",
        "description_fr": "Multicouche et joyeux, un rire d'enfant dans un verre.",
        "food_pairings_de": ["Tapas", "Lachs"],
        "food_pairings_en": ["Tapas", "Salmon"],
        "food_pairings_fr": ["Tapas", "Saumon"],
    },
    {
        "name": "Pinot Noir Seewer 2023",
        "winery": "Weingut Seewer",
        "region": "Wilchingen",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Dynamisch und choral, eine Symphonie.",
        "description_en": "Dynamic and choral, a symphony.",
        "description_fr": "Dynamique et choral, une symphonie.",
        "food_pairings_de": ["Dunkles Fleisch"],
        "food_pairings_en": ["Dark meat"],
        "food_pairings_fr": ["Viande brune"],
    },
    {
        "name": "Chardonnay Hedinger 2023",
        "winery": "Hedinger Weingut & Kellerei",
        "region": "Wilchingen",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Aromatisch und hoch, ein Höhenflug.",
        "description_en": "Aromatic and high, a flight to the heights.",
        "description_fr": "Aromatique et haut, un vol vers les sommets.",
        "food_pairings_de": ["Käse", "Forelle"],
        "food_pairings_en": ["Cheese", "Trout"],
        "food_pairings_fr": ["Fromage", "Truite"],
    },
    {
        "name": "Pinot Noir Barrique 2022",
        "winery": "Weingut Bad Osterfingen",
        "region": "Osterfingen",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Tief und symphonisch, ein Meisterwerk.",
        "description_en": "Deep and symphonic, a masterpiece.",
        "description_fr": "Profond et symphonique, un chef-d'œuvre.",
        "food_pairings_de": ["Ente", "Ragout"],
        "food_pairings_en": ["Duck", "Ragout"],
        "food_pairings_fr": ["Canard", "Ragoût"],
    },
    {
        "name": "Riesling 2023",
        "winery": "Weinbau Markus Ruch",
        "region": "Hallau",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Blumig und leicht, ein Sommertraum.",
        "description_en": "Floral and light, a summer dream.",
        "description_fr": "Floral et léger, un rêve d'été.",
        "food_pairings_de": ["Sommergerichte"],
        "food_pairings_en": ["Summer dishes"],
        "food_pairings_fr": ["Plats d'été"],
    },
    {
        "name": "Pinot Blanc 2023",
        "winery": "Weingut Höcklistein",
        "region": "Rapperswil-Jona",
        "grape_variety": "Pinot Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Rein und traditionell, ein Bergquell.",
        "description_en": "Pure and traditional, a mountain spring.",
        "description_fr": "Pur et traditionnel, une source de montagne.",
        "food_pairings_de": ["Fisch", "Salat"],
        "food_pairings_en": ["Fish", "Salad"],
        "food_pairings_fr": ["Poisson", "Salade"],
    },
    {
        "name": "Sauvignon Blanc GVS 2024",
        "winery": "Weingut GVS Schachenmann",
        "region": "Hallau",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Würzig und orientalisch, ein Zauber.",
        "description_en": "Spicy and oriental, a spell.",
        "description_fr": "Épicé et oriental, un sortilège.",
        "food_pairings_de": ["Curry", "Vegetarisch"],
        "food_pairings_en": ["Curry", "Vegetarian"],
        "food_pairings_fr": ["Curry", "Végétarien"],
    },
    {
        "name": "Pinot Noir Baumann 2023",
        "winery": "Weingut Baumann",
        "region": "Oberhallau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Harmonisch und göttlich, eine Ekstase.",
        "description_en": "Harmonious and divine, an ecstasy.",
        "description_fr": "Harmonieux et divin, une extase.",
        "food_pairings_de": ["Entrecôte", "Schokolade"],
        "food_pairings_en": ["Entrecôte", "Chocolate"],
        "food_pairings_fr": ["Entrecôte", "Chocolat"],
    },
    {
        "name": "Chardonnay Aagne 2022",
        "winery": "aagne weingut",
        "region": "Hallau",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Strukturiert und elegant, ein Grand Cru.",
        "description_en": "Structured and elegant, a Grand Cru.",
        "description_fr": "Structuré et élégant, un Grand Cru.",
        "food_pairings_de": ["Krustentiere"],
        "food_pairings_en": ["Crustaceans"],
        "food_pairings_fr": ["Crustacés"],
    },
    {
        "name": "Pinot Noir Ruch 2023",
        "winery": "Weingut Ruch",
        "region": "Hallau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Lebendig und frisch, ein Funke.",
        "description_en": "Lively and fresh, a spark.",
        "description_fr": "Vivant et frais, une étincelle.",
        "food_pairings_de": ["Krebse", "Suppe"],
        "food_pairings_en": ["Crayfish", "Soup"],
        "food_pairings_fr": ["Écrevisses", "Soupe"],
    },
    {
        "name": "Müller-Thurgau Seewer 2023",
        "winery": "Weingut Seewer",
        "region": "Wilchingen",
        "grape_variety": "Müller-Thurgau",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Tief und reich, ein Abgrund der Aromen.",
        "description_en": "Deep and rich, an abyss of aromas.",
        "description_fr": "Profond et riche, un abîme d'arômes.",
        "food_pairings_de": ["Gewürztes"],
        "food_pairings_en": ["Spiced dishes"],
        "food_pairings_fr": ["Plats épicés"],
    },
    {
        "name": "Pinot Noir Hedinger 2024",
        "winery": "Hedinger Weingut & Kellerei",
        "region": "Wilchingen",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Elegant und zeitlos, eine Tiefe.",
        "description_en": "Elegant and timeless, a depth.",
        "description_fr": "Élégant et intemporel, une profondeur.",
        "food_pairings_de": ["Geflügel"],
        "food_pairings_en": ["Poultry"],
        "food_pairings_fr": ["Volaille"],
    },
    {
        "name": "Riesling-Silvaner 2023",
        "winery": "Weingut Bad Osterfingen",
        "region": "Osterfingen",
        "grape_variety": "Riesling-Silvaner",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Fruchtig und traurig-freudig, ein Windhauch.",
        "description_en": "Fruity and bittersweet, a breath of wind.",
        "description_fr": "Fruité et doux-amer, un souffle de vent.",
        "food_pairings_de": ["Pilze"],
        "food_pairings_en": ["Mushrooms"],
        "food_pairings_fr": ["Champignons"],
    },
    {
        "name": "Pinot Blanc Ruch 2023",
        "winery": "Weinbau Markus Ruch",
        "region": "Hallau",
        "grape_variety": "Pinot Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Ausgewogen und klassisch, eine Freude.",
        "description_en": "Balanced and classic, a joy.",
        "description_fr": "Équilibré et classique, une joie.",
        "food_pairings_de": ["Fondue"],
        "food_pairings_en": ["Fondue"],
        "food_pairings_fr": ["Fondue"],
    },
    {
        "name": "Chardonnay Höcklistein 2023",
        "winery": "Weingut Höcklistein",
        "region": "Rapperswil-Jona",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Beerig und waldig, ein Entführer.",
        "description_en": "Berry-rich and woody, an abductor.",
        "description_fr": "Riche en baies et boisé, un ravisseur.",
        "food_pairings_de": ["Lamm"],
        "food_pairings_en": ["Lamb"],
        "food_pairings_fr": ["Agneau"],
    },
    {
        "name": "Sauvignon Blanc GVS 2023",
        "winery": "Weingut GVS Schachenmann",
        "region": "Hallau",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Pfeffrig und zauberhaft, ein Orient.",
        "description_en": "Peppery and magical, an Orient.",
        "description_fr": "Poivré et magique, un Orient.",
        "food_pairings_de": ["Auberginen"],
        "food_pairings_en": ["Eggplant"],
        "food_pairings_fr": ["Aubergines"],
    },
    {
        "name": "Pinot Noir Baumann 2022",
        "winery": "Weingut Baumann",
        "region": "Oberhallau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Modern und fruchtig, eine Freude.",
        "description_en": "Modern and fruity, a delight.",
        "description_fr": "Moderne et fruité, un délice.",
        "food_pairings_de": ["Grillgemüse"],
        "food_pairings_en": ["Grilled vegetables"],
        "food_pairings_fr": ["Légumes grillés"],
    },
    {
        "name": "Mousseux Brut 2023",
        "winery": "Rimuss & Strada Wein",
        "region": "Hallau",
        "grape_variety": "Assemblage",
        "wine_color": "schaumwein",
        "price_category": "€€€",
        "description_de": "Rein und hoch, ein Gipfelblick.",
        "description_en": "Pure and high, a summit view.",
        "description_fr": "Pur et haut, une vue au sommet.",
        "food_pairings_de": ["Vorspeisen", "Käse"],
        "food_pairings_en": ["Appetizers", "Cheese"],
        "food_pairings_fr": ["Entrées", "Fromage"],
    },
]


async def add_stgallen_wines():
    """Fügt die St. Galler Weine zur Datenbank hinzu"""
    
    mongo_url = os.environ.get('MONGO_URL', 'mongodb://localhost:27017')
    db_name = os.environ.get('DB_NAME', 'test_database')
    
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    
    print("=" * 60)
    print("🍷 ST. GALLER WEINE HINZUFÜGEN")
    print("=" * 60)
    print(f"📊 Anzahl Weine: {len(STGALLEN_WINES)}")
    print()
    
    # Prüfe bestehende Weine
    existing = await db.public_wines.count_documents({"region": {"$regex": "^St. Gallen"}})
    print(f"📋 Bestehende St. Galler Weine: {existing}")
    
    added = 0
    skipped = 0
    
    for wine_data in STGALLEN_WINES:
        # Prüfe ob der Wein schon existiert
        exists = await db.public_wines.find_one({
            "name": wine_data["name"],
            "winery": wine_data["winery"]
        })
        
        if exists:
            print(f"⏭️  Übersprungen (existiert): {wine_data['name']}")
            skipped += 1
            continue
        
        # Erstelle den Wein-Eintrag
        wine = {
            "id": str(uuid4()),
            "name": wine_data["name"],
            "winery": wine_data["winery"],
            "country": "Schweiz",
            "region": f"St. Gallen - {wine_data['region']}",
            "appellation": "AOC St. Gallen",
            "grape_variety": wine_data["grape_variety"],
            "wine_color": wine_data["wine_color"],
            "year": None,
            "description_de": wine_data["description_de"],
            "description_en": wine_data["description_en"],
            "description_fr": wine_data["description_fr"],
            "tasting_notes": None,
            "food_pairings_de": wine_data["food_pairings_de"],
            "food_pairings_en": wine_data["food_pairings_en"],
            "food_pairings_fr": wine_data["food_pairings_fr"],
            "alcohol_content": None,
            "price_category": wine_data["price_category"],
            "image_url": None,
            "rating": None,
            "created_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
        }
        
        await db.public_wines.insert_one(wine)
        print(f"✅ Hinzugefügt: {wine_data['name']} ({wine_data['winery']})")
        added += 1
    
    print()
    print("=" * 60)
    print(f"🎉 FERTIG! {added} Weine hinzugefügt, {skipped} übersprungen")
    print("=" * 60)
    
    # Zeige Gesamtzahl
    total = await db.public_wines.count_documents({})
    stgallen_total = await db.public_wines.count_documents({"region": {"$regex": "^St. Gallen"}})
    print(f"\n📊 Gesamtzahl Weine in DB: {total}")
    print(f"📊 Davon St. Galler Weine: {stgallen_total}")
    
    client.close()


if __name__ == "__main__":
    asyncio.run(add_stgallen_wines())
