#!/usr/bin/env python3
"""
Skript zum Hinzufügen der Top 50 Baden-Weine zur Datenbank
Mit deutschen, englischen und französischen Beschreibungen

Baden: Das Burgunderparadies des Südens
Von der badischen Bergstraße bis zum Bodensee
"""

import asyncio
import os
from uuid import uuid4
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

# Die 50 Baden-Weine mit allen Details
BADEN_WINES = [
    {
        "name": "Malterdinger Spätburgunder GG 2024",
        "winery": "Bernhard Huber",
        "region": "Malterdingen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Ein burgundischer Traum von Kirsche, Unterholz und seidiger Tiefe – ein Wein, der die Seele in absolute Perfektion und badische Leidenschaft taucht (100 Falstaff-Punkte).",
        "description_en": "A Burgundian dream of cherry, undergrowth and silky depth – a wine that immerses the soul in absolute perfection and Baden passion (100 Falstaff points).",
        "description_fr": "Un rêve bourguignon de cerise, de sous-bois et de profondeur soyeuse – un vin qui plonge l'âme dans la perfection absolue et la passion badoise (100 points Falstaff).",
        "food_pairings_de": ["Rehrücken", "Dunkle Schokolade"],
        "food_pairings_en": ["Saddle of venison", "Dark chocolate"],
        "food_pairings_fr": ["Selle de chevreuil", "Chocolat noir"],
    },
    {
        "name": "Henkenberg Spätburgunder GG 2024",
        "winery": "Salwey",
        "region": "Oberrotweil",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Vulkanisch und kraftvoll, ein Henkenberg-Feuer von Beeren und Rauch, das das Herz mit intensiver Mineralität erobert.",
        "description_en": "Volcanic and powerful, a Henkenberg fire of berries and smoke that conquers the heart with intense minerality.",
        "description_fr": "Volcanique et puissant, un feu de Henkenberg de baies et de fumée qui conquiert le cœur avec une minéralité intense.",
        "food_pairings_de": ["Wild", "Gereifter Comté"],
        "food_pairings_en": ["Game", "Aged Comté"],
        "food_pairings_fr": ["Gibier", "Comté affiné"],
    },
    {
        "name": "Schwarzer Adler Eichberg Spätburgunder GG 2024",
        "winery": "Franz Keller",
        "region": "Oberbergen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Elegant und filigran, ein Eichberg-Juwel von Kirsche und Gewürz – ein Tropfen, der die Sinne in burgundische Ekstase versetzt.",
        "description_en": "Elegant and delicate, an Eichberg jewel of cherry and spice – a drop that sends the senses into Burgundian ecstasy.",
        "description_fr": "Élégant et délicat, un joyau d'Eichberg de cerise et d'épices – une goutte qui met les sens en extase bourguignonne.",
        "food_pairings_de": ["Entenbrust", "Pilzrisotto"],
        "food_pairings_en": ["Duck breast", "Mushroom risotto"],
        "food_pairings_fr": ["Magret de canard", "Risotto aux champignons"],
    },
    {
        "name": "Oberklamm Spätburgunder GG 2024",
        "winery": "Seeger",
        "region": "Leimen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Nordbadisch und präzise, ein Oberklamm der Finesse und Länge, der die Seele mit kühler Eleganz umfängt.",
        "description_en": "North Baden and precise, an Oberklamm of finesse and length that embraces the soul with cool elegance.",
        "description_fr": "Nord-badois et précis, un Oberklamm de finesse et de longueur qui enlace l'âme avec une élégance fraîche.",
        "food_pairings_de": ["Gegrilltes Lamm", "Milde Tomme"],
        "food_pairings_en": ["Grilled lamb", "Mild Tomme"],
        "food_pairings_fr": ["Agneau grillé", "Tomme douce"],
    },
    {
        "name": "Ihringer Winklerberg Grauburgunder GG 2024",
        "winery": "Dr. Heger",
        "region": "Ihringen",
        "grape_variety": "Grauburgunder",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Cremig und opulent, ein Winklerberg-Monument von Birne und Nuss – ein Grauburgunder der Weltklasse.",
        "description_en": "Creamy and opulent, a Winklerberg monument of pear and nut – a world-class Grauburgunder.",
        "description_fr": "Crémeux et opulent, un monument de Winklerberg de poire et de noix – un Grauburgunder de classe mondiale.",
        "food_pairings_de": ["Gegrillter Lachs", "Asiatisches Gemüse"],
        "food_pairings_en": ["Grilled salmon", "Asian vegetables"],
        "food_pairings_fr": ["Saumon grillé", "Légumes asiatiques"],
    },
    {
        "name": "Ihringer Winklerberg Spätburgunder GG 2024",
        "winery": "Stigler",
        "region": "Ihringen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Vulkanisch und tief, ein Winklerberg der Kraft und Frucht, das das Herz mit badischer Wärme erfüllt.",
        "description_en": "Volcanic and deep, a Winklerberg of power and fruit that fills the heart with Baden warmth.",
        "description_fr": "Volcanique et profond, un Winklerberg de puissance et de fruit qui remplit le cœur de chaleur badoise.",
        "food_pairings_de": ["Roastbeef", "Dunkles Fleisch"],
        "food_pairings_en": ["Roast beef", "Dark meat"],
        "food_pairings_fr": ["Rosbif", "Viande brune"],
    },
    {
        "name": "Durbacher Schlossberg Weißburgunder GG 2024",
        "winery": "Schneider",
        "region": "Durbach",
        "grape_variety": "Weißburgunder",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Ortenau-elegant und mineralisch, ein Schlossberg der Reinheit und Tiefe.",
        "description_en": "Ortenau-elegant and mineral, a Schlossberg of purity and depth.",
        "description_fr": "Ortenau-élégant et minéral, un Schlossberg de pureté et de profondeur.",
        "food_pairings_de": ["Forelle", "Ziegenkäse"],
        "food_pairings_en": ["Trout", "Goat cheese"],
        "food_pairings_fr": ["Truite", "Fromage de chèvre"],
    },
    {
        "name": "Schlatter Maltesergarten Spätburgunder GG 2024",
        "winery": "Fritz Wassmer",
        "region": "Schlatt",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Samten und würzig, ein Maltesergarten der Reife und Samtigkeit.",
        "description_en": "Velvety and spicy, a Maltesergarten of maturity and velvetiness.",
        "description_fr": "Velouté et épicé, un Maltesergarten de maturité et de velouté.",
        "food_pairings_de": ["Wildpastete", "Schokolade"],
        "food_pairings_en": ["Game pâté", "Chocolate"],
        "food_pairings_fr": ["Pâté de gibier", "Chocolat"],
    },
    {
        "name": "Kaiserstuhl Spätburgunder 2024",
        "winery": "Duijn Badenhorst",
        "region": "Kaiserstuhl",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Aufstrebend und präzise, ein Kaiserstuhl der neuen Generation, der die Seele mit moderner Eleganz weckt.",
        "description_en": "Rising and precise, a Kaiserstuhl of the new generation that awakens the soul with modern elegance.",
        "description_fr": "Montant et précis, un Kaiserstuhl de la nouvelle génération qui éveille l'âme avec une élégance moderne.",
        "food_pairings_de": ["Entenbrust", "Pilze"],
        "food_pairings_en": ["Duck breast", "Mushrooms"],
        "food_pairings_fr": ["Magret de canard", "Champignons"],
    },
    {
        "name": "Bischoffinger Enselberg Spätburgunder GG 2024",
        "winery": "Karl H. Johner",
        "region": "Bischoffingen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Enselberg-vulkanisch und intensiv, ein Feuer der Frucht.",
        "description_en": "Enselberg-volcanic and intense, a fire of fruit.",
        "description_fr": "Enselberg-volcanique et intense, un feu de fruit.",
        "food_pairings_de": ["BBQ", "Scharfe Wurst"],
        "food_pairings_en": ["BBQ", "Spicy sausage"],
        "food_pairings_fr": ["BBQ", "Saucisse épicée"],
    },
    {
        "name": "RS Reserve Spätburgunder 2023",
        "winery": "Salwey",
        "region": "Oberrotweil",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Reserve-tief und komplex, ein RS der Ewigkeit.",
        "description_en": "Reserve-deep and complex, an RS of eternity.",
        "description_fr": "Reserve-profond et complexe, un RS d'éternité.",
        "food_pairings_de": ["Rehrücken", "Blauschimmel"],
        "food_pairings_en": ["Saddle of venison", "Blue cheese"],
        "food_pairings_fr": ["Selle de chevreuil", "Bleu"],
    },
    {
        "name": "Oberrotweiler Eichberg Grauburgunder GG 2024",
        "winery": "Franz Keller",
        "region": "Oberrotweil",
        "grape_variety": "Grauburgunder",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Eichberg-cremig und golden, ein Grauburgunder der Opulenz.",
        "description_en": "Eichberg-creamy and golden, a Grauburgunder of opulence.",
        "description_fr": "Eichberg-crémeux et doré, un Grauburgunder d'opulence.",
        "food_pairings_de": ["Huhn", "Milde Raclette"],
        "food_pairings_en": ["Chicken", "Mild Raclette"],
        "food_pairings_fr": ["Poulet", "Raclette douce"],
    },
    {
        "name": "Bienenberg Weißburgunder GG 2024",
        "winery": "Bernhard Huber",
        "region": "Malterdingen",
        "grape_variety": "Weißburgunder",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Bienenberg-rein und harmonisch, ein Weißburgunder der Noblesse.",
        "description_en": "Bienenberg-pure and harmonious, a Weißburgunder of nobility.",
        "description_fr": "Bienenberg-pur et harmonieux, un Weißburgunder de noblesse.",
        "food_pairings_de": ["Meeresfrüchte", "Salat"],
        "food_pairings_en": ["Seafood", "Salad"],
        "food_pairings_fr": ["Fruits de mer", "Salade"],
    },
    {
        "name": "Königsgarten Spätburgunder GG 2024",
        "winery": "Weingut Heitlinger",
        "region": "Kraichgau",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Königsgarten-königlich und kraftvoll, ein Kraichgau-Klassiker.",
        "description_en": "Königsgarten-royal and powerful, a Kraichgau classic.",
        "description_fr": "Königsgarten-royal et puissant, un classique du Kraichgau.",
        "food_pairings_de": ["Rind", "Pilze"],
        "food_pairings_en": ["Beef", "Mushrooms"],
        "food_pairings_fr": ["Bœuf", "Champignons"],
    },
    {
        "name": "Vulkangestein Riesling GG 2024",
        "winery": "Stigler",
        "region": "Ihringen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Vulkangestein-mineralisch und strahlend, ein Riesling der Frische.",
        "description_en": "Vulkangestein-mineral and radiant, a Riesling of freshness.",
        "description_fr": "Vulkangestein-minéral et radieux, un Riesling de fraîcheur.",
        "food_pairings_de": ["Gegrillter Fisch"],
        "food_pairings_en": ["Grilled fish"],
        "food_pairings_fr": ["Poisson grillé"],
    },
    {
        "name": "Mauerberg Riesling GG 2024",
        "winery": "Schloss Neuweier",
        "region": "Baden-Baden",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Mauerberg-steil und präzise, ein Ortenau-Riesling der Eleganz.",
        "description_en": "Mauerberg-steep and precise, an Ortenau Riesling of elegance.",
        "description_fr": "Mauerberg-raide et précis, un Riesling d'Ortenau d'élégance.",
        "food_pairings_de": ["Forelle", "Gemüse"],
        "food_pairings_en": ["Trout", "Vegetables"],
        "food_pairings_fr": ["Truite", "Légumes"],
    },
    {
        "name": "Durbacher Plauelrain Spätburgunder GG 2024",
        "winery": "Andreas Männle",
        "region": "Durbach",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Plauelrain-fruchtig und tief, ein badischer Rotwein-Klassiker.",
        "description_en": "Plauelrain-fruity and deep, a Baden red wine classic.",
        "description_fr": "Plauelrain-fruité et profond, un classique du vin rouge badois.",
        "food_pairings_de": ["Lamm", "Käse"],
        "food_pairings_en": ["Lamb", "Cheese"],
        "food_pairings_fr": ["Agneau", "Fromage"],
    },
    {
        "name": "Bombacher Sommerhalde Grauburgunder GG 2024",
        "winery": "Fritz Wassmer",
        "region": "Bombach",
        "grape_variety": "Grauburgunder",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Sommerhalde-sonnig und cremig, ein Grauburgunder der Wärme.",
        "description_en": "Sommerhalde-sunny and creamy, a Grauburgunder of warmth.",
        "description_fr": "Sommerhalde-ensoleillé et crémeux, un Grauburgunder de chaleur.",
        "food_pairings_de": ["Geflügel"],
        "food_pairings_en": ["Poultry"],
        "food_pairings_fr": ["Volaille"],
    },
    {
        "name": "Baden-Baden Spätburgunder 2024",
        "winery": "Karl Trautwein",
        "region": "Baden-Baden",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Rebgut-ehrlich und saftig, ein Alltags-Rot der Freude.",
        "description_en": "Rebgut-honest and juicy, an everyday red of joy.",
        "description_fr": "Rebgut-honnête et juteux, un rouge quotidien de joie.",
        "food_pairings_de": ["Pasta", "Fondue"],
        "food_pairings_en": ["Pasta", "Fondue"],
        "food_pairings_fr": ["Pâtes", "Fondue"],
    },
    {
        "name": "Chardonnay 2024",
        "winery": "Duijn Badenhorst",
        "region": "Kaiserstuhl",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Chardonnay-opulent und modern, ein neuer Stern.",
        "description_en": "Chardonnay-opulent and modern, a new star.",
        "description_fr": "Chardonnay-opulent et moderne, une nouvelle étoile.",
        "food_pairings_de": ["Huhn", "Desserts"],
        "food_pairings_en": ["Chicken", "Desserts"],
        "food_pairings_fr": ["Poulet", "Desserts"],
    },
    {
        "name": "Oberrotweiler Grauburgunder GG 2024",
        "winery": "Salwey",
        "region": "Oberrotweil",
        "grape_variety": "Grauburgunder",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Oberrotweiler-cremig und vulkanisch.",
        "description_en": "Oberrotweiler-creamy and volcanic.",
        "description_fr": "Oberrotweiler-crémeux et volcanique.",
        "food_pairings_de": ["Asiatisch"],
        "food_pairings_en": ["Asian cuisine"],
        "food_pairings_fr": ["Cuisine asiatique"],
    },
    {
        "name": "Sommerhalde Spätburgunder GG 2024",
        "winery": "Bernhard Huber",
        "region": "Malterdingen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Sommerhalde-sonnig und tief.",
        "description_en": "Sommerhalde-sunny and deep.",
        "description_fr": "Sommerhalde-ensoleillé et profond.",
        "food_pairings_de": ["Wild"],
        "food_pairings_en": ["Game"],
        "food_pairings_fr": ["Gibier"],
    },
    {
        "name": "Achkarrer Schlossberg Weißburgunder GG 2024",
        "winery": "Dr. Heger",
        "region": "Achkarren",
        "grape_variety": "Weißburgunder",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Schlossberg-edel und mineralisch.",
        "description_en": "Schlossberg-noble and mineral.",
        "description_fr": "Schlossberg-noble et minéral.",
        "food_pairings_de": ["Parmesan"],
        "food_pairings_en": ["Parmesan"],
        "food_pairings_fr": ["Parmesan"],
    },
    {
        "name": "Heerkretz Grauburgunder GG 2024",
        "winery": "Seeger",
        "region": "Leimen",
        "grape_variety": "Grauburgunder",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Heerkretz-kühl und präzise.",
        "description_en": "Heerkretz-cool and precise.",
        "description_fr": "Heerkretz-frais et précis.",
        "food_pairings_de": ["Gemüse"],
        "food_pairings_en": ["Vegetables"],
        "food_pairings_fr": ["Légumes"],
    },
    {
        "name": "Pulverbuck Chardonnay GG 2024",
        "winery": "Franz Keller",
        "region": "Oberbergen",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Pulverbuck-cremig und tief.",
        "description_en": "Pulverbuck-creamy and deep.",
        "description_fr": "Pulverbuck-crémeux et profond.",
        "food_pairings_de": ["Krustentiere"],
        "food_pairings_en": ["Crustaceans"],
        "food_pairings_fr": ["Crustacés"],
    },
    {
        "name": "Winklerberg Riesling Auslese 2023",
        "winery": "Stigler",
        "region": "Ihringen",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Winklerberg-süß und golden.",
        "description_en": "Winklerberg-sweet and golden.",
        "description_fr": "Winklerberg-doux et doré.",
        "food_pairings_de": ["Foie gras"],
        "food_pairings_en": ["Foie gras"],
        "food_pairings_fr": ["Foie gras"],
    },
    {
        "name": "Durbacher Kochberg Riesling GG 2024",
        "winery": "Schneider",
        "region": "Durbach",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Kochberg-steil und frisch.",
        "description_en": "Kochberg-steep and fresh.",
        "description_fr": "Kochberg-raide et frais.",
        "food_pairings_de": ["Fisch"],
        "food_pairings_en": ["Fish"],
        "food_pairings_fr": ["Poisson"],
    },
    {
        "name": "Schlatter Spätburgunder Rosé 2024",
        "winery": "Fritz Wassmer",
        "region": "Schlatt",
        "grape_variety": "Spätburgunder",
        "wine_color": "rosé",
        "price_category": "€€€",
        "description_de": "Rosé-zart und sommerlich.",
        "description_en": "Rosé-delicate and summery.",
        "description_fr": "Rosé-délicat et estival.",
        "food_pairings_de": ["Salate"],
        "food_pairings_en": ["Salads"],
        "food_pairings_fr": ["Salades"],
    },
    {
        "name": "Spiegelberg Riesling GG 2024",
        "winery": "Weingut Heitlinger",
        "region": "Kraichgau",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Spiegelberg-mineralisch und klar.",
        "description_en": "Spiegelberg-mineral and clear.",
        "description_fr": "Spiegelberg-minéral et clair.",
        "food_pairings_de": ["Forelle"],
        "food_pairings_en": ["Trout"],
        "food_pairings_fr": ["Truite"],
    },
    {
        "name": "Pinot Noir Reserve 2023",
        "winery": "Duijn Badenhorst",
        "region": "Kaiserstuhl",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Reserve-tief und modern.",
        "description_en": "Reserve-deep and modern.",
        "description_fr": "Reserve-profond et moderne.",
        "food_pairings_de": ["Entrecôte"],
        "food_pairings_en": ["Entrecôte"],
        "food_pairings_fr": ["Entrecôte"],
    },
    {
        "name": "Henkenberg Grauburgunder GG 2024",
        "winery": "Salwey",
        "region": "Oberrotweil",
        "grape_variety": "Grauburgunder",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Henkenberg-vulkanisch und cremig.",
        "description_en": "Henkenberg-volcanic and creamy.",
        "description_fr": "Henkenberg-volcanique et crémeux.",
        "food_pairings_de": ["Huhn"],
        "food_pairings_en": ["Chicken"],
        "food_pairings_fr": ["Poulet"],
    },
    {
        "name": "Wildenstein Spätburgunder GG 2024",
        "winery": "Bernhard Huber",
        "region": "Malterdingen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Wildenstein-wild und intensiv.",
        "description_en": "Wildenstein-wild and intense.",
        "description_fr": "Wildenstein-sauvage et intense.",
        "food_pairings_de": ["Pilze"],
        "food_pairings_en": ["Mushrooms"],
        "food_pairings_fr": ["Champignons"],
    },
    {
        "name": "Ihringer Vorderer Winklerberg Riesling GG 2024",
        "winery": "Dr. Heger",
        "region": "Ihringen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Vorderer Winklerberg-sonnig und kraftvoll.",
        "description_en": "Vorderer Winklerberg-sunny and powerful.",
        "description_fr": "Vorderer Winklerberg-ensoleillé et puissant.",
        "food_pairings_de": ["Lamm"],
        "food_pairings_en": ["Lamb"],
        "food_pairings_fr": ["Agneau"],
    },
    {
        "name": "Goldenes Loch Riesling GG 2024",
        "winery": "Schloss Neuweier",
        "region": "Baden-Baden",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Goldenes Loch-geheimnisvoll und mineralisch.",
        "description_en": "Goldenes Loch-mysterious and mineral.",
        "description_fr": "Goldenes Loch-mystérieux et minéral.",
        "food_pairings_de": ["Käse"],
        "food_pairings_en": ["Cheese"],
        "food_pairings_fr": ["Fromage"],
    },
    {
        "name": "Bienenberg Weißburgunder GG 2024",
        "winery": "Andreas Männle",
        "region": "Durbach",
        "grape_variety": "Weißburgunder",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Bienenberg-rein und harmonisch.",
        "description_en": "Bienenberg-pure and harmonious.",
        "description_fr": "Bienenberg-pur et harmonieux.",
        "food_pairings_de": ["Gemüse"],
        "food_pairings_en": ["Vegetables"],
        "food_pairings_fr": ["Légumes"],
    },
    {
        "name": "Enselberg Spätburgunder Auslese Trocken 2023",
        "winery": "Franz Keller",
        "region": "Oberbergen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Enselberg-konzentriert und tief.",
        "description_en": "Enselberg-concentrated and deep.",
        "description_fr": "Enselberg-concentré et profond.",
        "food_pairings_de": ["Schokolade"],
        "food_pairings_en": ["Chocolate"],
        "food_pairings_fr": ["Chocolat"],
    },
    {
        "name": "Lößlehm Spätburgunder 2024",
        "winery": "Seeger",
        "region": "Leimen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Lößlehm-weich und fruchtig.",
        "description_en": "Lößlehm-soft and fruity.",
        "description_fr": "Lößlehm-doux et fruité.",
        "food_pairings_de": ["Pasta"],
        "food_pairings_en": ["Pasta"],
        "food_pairings_fr": ["Pâtes"],
    },
    {
        "name": "Vulkangestein Chardonnay GG 2024",
        "winery": "Stigler",
        "region": "Ihringen",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Vulkangestein-opulent und rauchig.",
        "description_en": "Vulkangestein-opulent and smoky.",
        "description_fr": "Vulkangestein-opulent et fumé.",
        "food_pairings_de": ["Geflügel"],
        "food_pairings_en": ["Poultry"],
        "food_pairings_fr": ["Volaille"],
    },
    {
        "name": "Bombacher Spätburgunder Reserve 2023",
        "winery": "Fritz Wassmer",
        "region": "Bombach",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Reserve-tief und reif.",
        "description_en": "Reserve-deep and ripe.",
        "description_fr": "Reserve-profond et mûr.",
        "food_pairings_de": ["Wild"],
        "food_pairings_en": ["Game"],
        "food_pairings_fr": ["Gibier"],
    },
    {
        "name": "Königsgarten Weißburgunder GG 2024",
        "winery": "Weingut Heitlinger",
        "region": "Kraichgau",
        "grape_variety": "Weißburgunder",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Königsgarten-edel und cremig.",
        "description_en": "Königsgarten-noble and creamy.",
        "description_fr": "Königsgarten-noble et crémeux.",
        "food_pairings_de": ["Salat"],
        "food_pairings_en": ["Salad"],
        "food_pairings_fr": ["Salade"],
    },
    {
        "name": "Sauvignon Blanc 2024",
        "winery": "Duijn Badenhorst",
        "region": "Kaiserstuhl",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Sauvignon-exotisch und frisch.",
        "description_en": "Sauvignon-exotic and fresh.",
        "description_fr": "Sauvignon-exotique et frais.",
        "food_pairings_de": ["Ziegenkäse"],
        "food_pairings_en": ["Goat cheese"],
        "food_pairings_fr": ["Fromage de chèvre"],
    },
    {
        "name": "RS Grauburgunder Reserve 2024",
        "winery": "Salwey",
        "region": "Oberrotweil",
        "grape_variety": "Grauburgunder",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "RS-cremig und tief.",
        "description_en": "RS-creamy and deep.",
        "description_fr": "RS-crémeux et profond.",
        "food_pairings_de": ["Huhn"],
        "food_pairings_en": ["Chicken"],
        "food_pairings_fr": ["Poulet"],
    },
    {
        "name": "R Spätburgunder 2023",
        "winery": "Bernhard Huber",
        "region": "Malterdingen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "R-reserviert und monumental.",
        "description_en": "R-reserved and monumental.",
        "description_fr": "R-réservé et monumental.",
        "food_pairings_de": ["Entrecôte"],
        "food_pairings_en": ["Entrecôte"],
        "food_pairings_fr": ["Entrecôte"],
    },
    {
        "name": "Achkarrer Schlossberg Spätburgunder GG 2024",
        "winery": "Dr. Heger",
        "region": "Achkarren",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Schlossberg-rot und vulkanisch.",
        "description_en": "Schlossberg-red and volcanic.",
        "description_fr": "Schlossberg-rouge et volcanique.",
        "food_pairings_de": ["Pilze"],
        "food_pairings_en": ["Mushrooms"],
        "food_pairings_fr": ["Champignons"],
    },
    {
        "name": "Durbacher Plauelrain Riesling Spätlese 2023",
        "winery": "Schneider",
        "region": "Durbach",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Plauelrain-spät und verlockend.",
        "description_en": "Plauelrain-late and enticing.",
        "description_fr": "Plauelrain-tardif et séduisant.",
        "food_pairings_de": ["Scharfer Thai"],
        "food_pairings_en": ["Spicy Thai"],
        "food_pairings_fr": ["Thaï épicé"],
    },
    {
        "name": "Bassgeige Spätburgunder GG 2024",
        "winery": "Franz Keller",
        "region": "Oberbergen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Bassgeige-tief und harmonisch.",
        "description_en": "Bassgeige-deep and harmonious.",
        "description_fr": "Bassgeige-profond et harmonieux.",
        "food_pairings_de": ["Roastbeef"],
        "food_pairings_en": ["Roast beef"],
        "food_pairings_fr": ["Rosbif"],
    },
    {
        "name": "Chardonnay Reserve 2024",
        "winery": "Seeger",
        "region": "Leimen",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Chardonnay-kühl und elegant.",
        "description_en": "Chardonnay-cool and elegant.",
        "description_fr": "Chardonnay-frais et élégant.",
        "food_pairings_de": ["Fisch"],
        "food_pairings_en": ["Fish"],
        "food_pairings_fr": ["Poisson"],
    },
    {
        "name": "Ihringer Winklerberg Weißburgunder GG 2024",
        "winery": "Stigler",
        "region": "Ihringen",
        "grape_variety": "Weißburgunder",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Winklerberg-cremig und sonnig.",
        "description_en": "Winklerberg-creamy and sunny.",
        "description_fr": "Winklerberg-crémeux et ensoleillé.",
        "food_pairings_de": ["Geflügel"],
        "food_pairings_en": ["Poultry"],
        "food_pairings_fr": ["Volaille"],
    },
    {
        "name": "Schlatter Maltesergarten Rosé 2024",
        "winery": "Fritz Wassmer",
        "region": "Schlatt",
        "grape_variety": "Spätburgunder",
        "wine_color": "rosé",
        "price_category": "€€€",
        "description_de": "Maltesergarten-rosa und sommerlich.",
        "description_en": "Maltesergarten-pink and summery.",
        "description_fr": "Maltesergarten-rose et estival.",
        "food_pairings_de": ["Salate"],
        "food_pairings_en": ["Salads"],
        "food_pairings_fr": ["Salades"],
    },
    {
        "name": "Bienenberg Grauburgunder GG 2024",
        "winery": "Bernhard Huber",
        "region": "Malterdingen",
        "grape_variety": "Grauburgunder",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Bienenberg-opulent und rein, ein Abschluss des badischen Burgunderzaubers.",
        "description_en": "Bienenberg-opulent and pure, a finale of Baden's Burgundian magic.",
        "description_fr": "Bienenberg-opulent et pur, un final de la magie bourguignonne badoise.",
        "food_pairings_de": ["Käseplatte", "Leichte Vorspeisen"],
        "food_pairings_en": ["Cheese platter", "Light appetizers"],
        "food_pairings_fr": ["Plateau de fromages", "Entrées légères"],
    },
]


async def add_baden_wines():
    """Fügt die Baden-Weine zur Datenbank hinzu"""
    
    mongo_url = os.environ.get('MONGO_URL', 'mongodb://localhost:27017')
    db_name = os.environ.get('DB_NAME', 'test_database')
    
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    
    print("=" * 60)
    print("🍷 BADEN-WEINE HINZUFÜGEN")
    print("   Das Burgunderparadies des Südens")
    print("=" * 60)
    print(f"📊 Anzahl Weine: {len(BADEN_WINES)}")
    print()
    
    # Prüfe bestehende Weine
    existing = await db.public_wines.count_documents({"region": {"$regex": "^Baden"}})
    print(f"📋 Bestehende Baden-Weine: {existing}")
    
    added = 0
    skipped = 0
    
    for wine_data in BADEN_WINES:
        # Prüfe ob der Wein schon existiert
        exists = await db.public_wines.find_one({
            "name": wine_data["name"],
            "winery": wine_data["winery"]
        })
        
        if exists:
            print(f"⏭️  Übersprungen (existiert): {wine_data['name']}")
            skipped += 1
            continue
        
        # Erstelle den Wein-Eintrag
        wine = {
            "id": str(uuid4()),
            "name": wine_data["name"],
            "winery": wine_data["winery"],
            "country": "Deutschland",
            "region": f"Baden - {wine_data['region']}",
            "appellation": "Baden",
            "grape_variety": wine_data["grape_variety"],
            "wine_color": wine_data["wine_color"],
            "year": None,
            "description_de": wine_data["description_de"],
            "description_en": wine_data["description_en"],
            "description_fr": wine_data["description_fr"],
            "tasting_notes": None,
            "food_pairings_de": wine_data["food_pairings_de"],
            "food_pairings_en": wine_data["food_pairings_en"],
            "food_pairings_fr": wine_data["food_pairings_fr"],
            "alcohol_content": None,
            "price_category": wine_data["price_category"],
            "image_url": None,
            "rating": None,
            "created_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
        }
        
        await db.public_wines.insert_one(wine)
        print(f"✅ Hinzugefügt: {wine_data['name']} ({wine_data['winery']})")
        added += 1
    
    print()
    print("=" * 60)
    print(f"🎉 FERTIG! {added} Weine hinzugefügt, {skipped} übersprungen")
    print("=" * 60)
    
    # Zeige Gesamtzahl
    total = await db.public_wines.count_documents({})
    baden_total = await db.public_wines.count_documents({"region": {"$regex": "^Baden"}})
    print(f"\n📊 Gesamtzahl Weine in DB: {total}")
    print(f"📊 Davon Baden-Weine: {baden_total}")
    
    client.close()


if __name__ == "__main__":
    asyncio.run(add_baden_wines())
