#!/usr/bin/env python3
"""
Skript zum Hinzufügen der Top 50 Genfer Weine zur Datenbank
Mit deutschen, englischen und französischen Beschreibungen
"""

import asyncio
import os
from uuid import uuid4
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

# Die 50 Genfer Weine mit allen Details
GENF_WINES = [
    {
        "name": "Mousseux Tradition Brut 2023",
        "winery": "Domaine des Curiades",
        "region": "Satigny",
        "grape_variety": "Assemblage",
        "wine_color": "schaumwein",
        "price_category": "€€€",
        "description_de": "Ein perlender Traum, der von goldenen Blasen und Zitruspoesie erzählt – ein Wein, der die Seele in festliche Ekstase versetzt und vergangene Feste heraufbeschwört.",
        "description_en": "A sparkling dream that speaks of golden bubbles and citrus poetry – a wine that sends the soul into festive ecstasy and evokes past celebrations.",
        "description_fr": "Un rêve pétillant qui parle de bulles dorées et de poésie d'agrumes – un vin qui envoie l'âme en extase festive et évoque les fêtes passées.",
        "food_pairings_de": ["Austern", "Frischer Ziegenkäse"],
        "food_pairings_en": ["Oysters", "Fresh goat cheese"],
        "food_pairings_fr": ["Huîtres", "Fromage de chèvre frais"],
    },
    {
        "name": "Gewürztraminer 2022",
        "winery": "Domaine Les Hutins",
        "region": "Dardagny",
        "grape_variety": "Gewürztraminer",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Exotisch und verlockend, mit Lychee und Rose, die wie ein Geheimnis aus dem Orient die Seele verzaubert – purer, aromatischer Zauber.",
        "description_en": "Exotic and alluring, with lychee and rose that enchants the soul like a secret from the Orient – pure, aromatic magic.",
        "description_fr": "Exotique et séduisant, avec du litchi et de la rose qui enchante l'âme comme un secret d'Orient – magie aromatique pure.",
        "food_pairings_de": ["Foie gras", "Würziges Curry"],
        "food_pairings_en": ["Foie gras", "Spicy curry"],
        "food_pairings_fr": ["Foie gras", "Curry épicé"],
    },
    {
        "name": "Chasselas Clémence 2021",
        "winery": "La Cave de Genève",
        "region": "Satigny",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Frisch und mineralisch, ein Chasselas, der wie ein Morgenhauch über dem See das Herz mit Apfel und Stein erfrischt und Hoffnung weckt.",
        "description_en": "Fresh and mineral, a Chasselas that refreshes the heart like a morning breeze over the lake with apple and stone, awakening hope.",
        "description_fr": "Frais et minéral, un Chasselas qui rafraîchit le cœur comme une brise matinale sur le lac avec de la pomme et de la pierre, éveillant l'espoir.",
        "food_pairings_de": ["Papet Vaudois", "Gegrillter Fisch"],
        "food_pairings_en": ["Papet Vaudois", "Grilled fish"],
        "food_pairings_fr": ["Papet Vaudois", "Poisson grillé"],
    },
    {
        "name": "Pinot Noir 2023",
        "winery": "Domaine de la Guérite",
        "region": "Russin",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Elegant und filigran, mit Kirsche und Samt, der die Seele in burgundische Melancholie taucht – ein Liebesbrief in Rot.",
        "description_en": "Elegant and delicate, with cherry and velvet that plunges the soul into Burgundian melancholy – a love letter in red.",
        "description_fr": "Élégant et délicat, avec de la cerise et du velours qui plonge l'âme dans la mélancolie bourguignonne – une lettre d'amour en rouge.",
        "food_pairings_de": ["Entenbrust", "Pilzrisotto"],
        "food_pairings_en": ["Duck breast", "Mushroom risotto"],
        "food_pairings_fr": ["Magret de canard", "Risotto aux champignons"],
    },
    {
        "name": "Gamay 2023",
        "winery": "Cave de Sézenove",
        "region": "Satigny",
        "grape_variety": "Gamay",
        "wine_color": "rot",
        "price_category": "€€",
        "description_de": "Saftig und beerig, ein Gamay, der das Herz mit wilden Beeren und erdiger Wärme in herbstliche Wälder lockt.",
        "description_en": "Juicy and berry-rich, a Gamay that lures the heart into autumn forests with wild berries and earthy warmth.",
        "description_fr": "Juteux et fruité, un Gamay qui attire le cœur dans les forêts d'automne avec des baies sauvages et une chaleur terreuse.",
        "food_pairings_de": ["Lammkoteletts", "Charcuterie"],
        "food_pairings_en": ["Lamb chops", "Charcuterie"],
        "food_pairings_fr": ["Côtelettes d'agneau", "Charcuterie"],
    },
    {
        "name": "Sauvignon Blanc 2022",
        "winery": "Domaine des Bonnettes",
        "region": "Dardagny",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Nervös und aromatisch, mit Grapefruit und Kräutern, das wie ein Bergquell die Seele klärt und verjüngt.",
        "description_en": "Nervous and aromatic, with grapefruit and herbs that clears and rejuvenates the soul like a mountain spring.",
        "description_fr": "Nerveux et aromatique, avec du pamplemousse et des herbes qui clarifie et rajeunit l'âme comme une source de montagne.",
        "food_pairings_de": ["Krebse", "Frischer Salat"],
        "food_pairings_en": ["Crayfish", "Fresh salad"],
        "food_pairings_fr": ["Écrevisses", "Salade fraîche"],
    },
    {
        "name": "Merlot 2021",
        "winery": "Domaine Grand'Cour",
        "region": "Peissy-Satigny",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Samten und fruchtig, ein Merlot, der das Herz mit Pflaume und Schokolade in tiefe, tröstliche Zufriedenheit wiegt.",
        "description_en": "Velvety and fruity, a Merlot that rocks the heart into deep, comforting satisfaction with plum and chocolate.",
        "description_fr": "Velouté et fruité, un Merlot qui berce le cœur dans une satisfaction profonde et réconfortante avec de la prune et du chocolat.",
        "food_pairings_de": ["Roastbeef", "Dunkle Schokolade"],
        "food_pairings_en": ["Roast beef", "Dark chocolate"],
        "food_pairings_fr": ["Rôti de bœuf", "Chocolat noir"],
    },
    {
        "name": "Viognier 2022",
        "winery": "Domaine de la Printanière",
        "region": "Avully",
        "grape_variety": "Viognier",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Blumig und opulent, mit Pfirsich und Gewürzen, der die Seele in sonnendurchflutete Gärten entführt.",
        "description_en": "Floral and opulent, with peach and spices that transports the soul to sun-drenched gardens.",
        "description_fr": "Floral et opulent, avec de la pêche et des épices qui transporte l'âme dans des jardins ensoleillés.",
        "food_pairings_de": ["Gegrillter Lachs", "Asiatisches Gemüse"],
        "food_pairings_en": ["Grilled salmon", "Asian vegetables"],
        "food_pairings_fr": ["Saumon grillé", "Légumes asiatiques"],
    },
    {
        "name": "Pinot Noir Réserve 2022",
        "winery": "Domaine de la Mermière",
        "region": "Satigny",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Tief und tanninreich, mit Leder und Beeren, die die Seele in alte Legenden eintauchen lassen.",
        "description_en": "Deep and tannic, with leather and berries that immerse the soul in ancient legends.",
        "description_fr": "Profond et tannique, avec du cuir et des baies qui plongent l'âme dans d'anciennes légendes.",
        "food_pairings_de": ["Rehrücken", "Dunkles Fleisch"],
        "food_pairings_en": ["Saddle of venison", "Dark meat"],
        "food_pairings_fr": ["Selle de chevreuil", "Viande brune"],
    },
    {
        "name": "Chasselas Grand Cru 2023",
        "winery": "Les Perrières",
        "region": "Satigny",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Rein und lebendig, ein Grand Cru, der wie ein Bergnebel die Seele mit Zitrus und Mineral umhüllt.",
        "description_en": "Pure and vibrant, a Grand Cru that envelops the soul with citrus and mineral like mountain mist.",
        "description_fr": "Pur et vivant, un Grand Cru qui enveloppe l'âme d'agrumes et de minéral comme la brume de montagne.",
        "food_pairings_de": ["Meeresfrüchte", "Sommergemüse"],
        "food_pairings_en": ["Seafood", "Summer vegetables"],
        "food_pairings_fr": ["Fruits de mer", "Légumes d'été"],
    },
    {
        "name": "Gamay Vieilles Vignes 2023",
        "winery": "Domaine Villard & Fils",
        "region": "Anières",
        "grape_variety": "Gamay",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Robust und fruchtig, ein Gamay, der das Herz mit Kirschen und Geheimnissen umgarnt.",
        "description_en": "Robust and fruity, a Gamay that captivates the heart with cherries and secrets.",
        "description_fr": "Robuste et fruité, un Gamay qui envoûte le cœur de cerises et de secrets.",
        "food_pairings_de": ["Pasta Bolognese", "Herzhaftes Brot"],
        "food_pairings_en": ["Pasta Bolognese", "Hearty bread"],
        "food_pairings_fr": ["Pâtes bolognaise", "Pain rustique"],
    },
    {
        "name": "Sauvignon Blanc 2022",
        "winery": "Domaine de la République et Canton de Genève",
        "region": "Lully",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Hoch und aromatisch, mit Mandeln und Nektarinen, das die Seele auf Höhenflüge trägt.",
        "description_en": "High and aromatic, with almonds and nectarines that carry the soul to great heights.",
        "description_fr": "Haut et aromatique, avec des amandes et des nectarines qui portent l'âme vers les sommets.",
        "food_pairings_de": ["Käseplatte", "Gebratenes Forellenfilet"],
        "food_pairings_en": ["Cheese platter", "Pan-fried trout fillet"],
        "food_pairings_fr": ["Plateau de fromages", "Filet de truite poêlé"],
    },
    {
        "name": "Cabernet Franc 2021",
        "winery": "Cave Les Crêtets",
        "region": "Peissy",
        "grape_variety": "Cabernet Franc",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Würzig und intensiv, ein Rot, das die Seele mit Pfeffer und Beeren in Ekstase versetzt.",
        "description_en": "Spicy and intense, a red that sends the soul into ecstasy with pepper and berries.",
        "description_fr": "Épicé et intense, un rouge qui envoie l'âme en extase avec du poivre et des baies.",
        "food_pairings_de": ["BBQ-Rippen", "Scharfe Wurst"],
        "food_pairings_en": ["BBQ ribs", "Spicy sausage"],
        "food_pairings_fr": ["Côtes BBQ", "Saucisse épicée"],
    },
    {
        "name": "Chardonnay 2023",
        "winery": "Domaine des Balisiers",
        "region": "Satigny",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Cremig und blumig, ein Chardonnay, der die Seele in goldene Sonnenuntergänge taucht.",
        "description_en": "Creamy and floral, a Chardonnay that dips the soul into golden sunsets.",
        "description_fr": "Crémeux et floral, un Chardonnay qui plonge l'âme dans des couchers de soleil dorés.",
        "food_pairings_de": ["Huhn mit Kräutern", "Milde Raclette"],
        "food_pairings_en": ["Herb chicken", "Mild Raclette"],
        "food_pairings_fr": ["Poulet aux herbes", "Raclette douce"],
    },
    {
        "name": "Rosé de Garanoir 2023",
        "winery": "Domaine du Paradis",
        "region": "Russin",
        "grape_variety": "Garanoir",
        "wine_color": "rosé",
        "price_category": "€€",
        "description_de": "Zartrosa und sommerlich, ein Rosé, der wie ein Sonnenuntergang über dem See das Herz mit Erdbeere und Frische umwebt.",
        "description_en": "Delicate pink and summery, a Rosé that weaves the heart with strawberry and freshness like a sunset over the lake.",
        "description_fr": "Rose délicat et estival, un Rosé qui tisse le cœur de fraise et de fraîcheur comme un coucher de soleil sur le lac.",
        "food_pairings_de": ["Salate mit Erdbeeren", "Leichte Wurstplatten"],
        "food_pairings_en": ["Salads with strawberries", "Light charcuterie"],
        "food_pairings_fr": ["Salades aux fraises", "Charcuterie légère"],
    },
    {
        "name": "Pinot Noir 2021",
        "winery": "Domaine de la Devinière",
        "region": "Dardagny",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Filigran und fruchtig, mit Kirschen und Leder, der das Herz mit leichter Traurigkeit und purer Freude erfüllt.",
        "description_en": "Delicate and fruity, with cherries and leather that fills the heart with gentle sadness and pure joy.",
        "description_fr": "Délicat et fruité, avec des cerises et du cuir qui remplit le cœur d'une légère tristesse et d'une joie pure.",
        "food_pairings_de": ["Entenbrust", "Pilze"],
        "food_pairings_en": ["Duck breast", "Mushrooms"],
        "food_pairings_fr": ["Magret de canard", "Champignons"],
    },
    {
        "name": "Aligoté 2023",
        "winery": "Château du Crest",
        "region": "Collex-Bossy",
        "grape_variety": "Aligoté",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Knackig und erfrischend, ein Aligoté, der wie ein Lachen die Seele weckt.",
        "description_en": "Crisp and refreshing, an Aligoté that awakens the soul like laughter.",
        "description_fr": "Croquant et rafraîchissant, un Aligoté qui éveille l'âme comme un rire.",
        "food_pairings_de": ["Fischfilet", "Salat"],
        "food_pairings_en": ["Fish fillet", "Salad"],
        "food_pairings_fr": ["Filet de poisson", "Salade"],
    },
    {
        "name": "Savagnin Blanc 2022",
        "winery": "Domaine Dugerdil",
        "region": "Avully",
        "grape_variety": "Savagnin Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Mineralisch und rein, ein Tropfen, der das Herz mit Bergfrische reinigt.",
        "description_en": "Mineral and pure, a drop that cleanses the heart with mountain freshness.",
        "description_fr": "Minéral et pur, une goutte qui purifie le cœur de fraîcheur de montagne.",
        "food_pairings_de": ["Austern", "Leichte Vorspeisen"],
        "food_pairings_en": ["Oysters", "Light appetizers"],
        "food_pairings_fr": ["Huîtres", "Amuse-bouches légers"],
    },
    {
        "name": "Assemblage Rouge L'Esprit de Genève 2021",
        "winery": "Château du Crest",
        "region": "Collex-Bossy",
        "grape_variety": "Assemblage",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Harmonisch und komplex, ein Blend, der die Seele in symphonische Tiefe taucht.",
        "description_en": "Harmonious and complex, a blend that plunges the soul into symphonic depth.",
        "description_fr": "Harmonieux et complexe, un assemblage qui plonge l'âme dans une profondeur symphonique.",
        "food_pairings_de": ["Ente", "Pilzragout"],
        "food_pairings_en": ["Duck", "Mushroom ragout"],
        "food_pairings_fr": ["Canard", "Ragoût de champignons"],
    },
    {
        "name": "Gamay 2023",
        "winery": "Les Perrières",
        "region": "Satigny",
        "grape_variety": "Gamay",
        "wine_color": "rot",
        "price_category": "€€",
        "description_de": "Frisch und ausgewogen, ein Gamay, der das Herz mit klassischer Freude erheitert.",
        "description_en": "Fresh and balanced, a Gamay that gladdens the heart with classic joy.",
        "description_fr": "Frais et équilibré, un Gamay qui réjouit le cœur d'une joie classique.",
        "food_pairings_de": ["Fondue", "Rind"],
        "food_pairings_en": ["Fondue", "Beef"],
        "food_pairings_fr": ["Fondue", "Bœuf"],
    },
    {
        "name": "Chasselas Le Clos 2022",
        "winery": "Domaine de la Printanière",
        "region": "Avully",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Elegant und strukturiert, mit Apfel und Stein, das wie ein Tanz die Seele erheitert.",
        "description_en": "Elegant and structured, with apple and stone that gladdens the soul like a dance.",
        "description_fr": "Élégant et structuré, avec de la pomme et de la pierre qui réjouit l'âme comme une danse.",
        "food_pairings_de": ["Asiatische Gerichte", "Gebratener Tofu"],
        "food_pairings_en": ["Asian dishes", "Pan-fried tofu"],
        "food_pairings_fr": ["Plats asiatiques", "Tofu poêlé"],
    },
    {
        "name": "Pinot Noir Le Palindrome 2022",
        "winery": "Les Vins de la Gara",
        "region": "Satigny",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Spiegelbildlich und tief, ein Pinot, der die Seele mit erdiger Wärme umfängt.",
        "description_en": "Mirror-like and deep, a Pinot that embraces the soul with earthy warmth.",
        "description_fr": "En miroir et profond, un Pinot qui embrasse l'âme d'une chaleur terreuse.",
        "food_pairings_de": ["Wildpastete", "Herzhafter Käse"],
        "food_pairings_en": ["Game pâté", "Hearty cheese"],
        "food_pairings_fr": ["Pâté de gibier", "Fromage corsé"],
    },
    {
        "name": "Merlot 2021",
        "winery": "Domaine Les Hutins",
        "region": "Dardagny",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Weich und fruchtig, ein Merlot, der das Herz mit warmer Umarmung beschenkt.",
        "description_en": "Soft and fruity, a Merlot that gifts the heart with a warm embrace.",
        "description_fr": "Doux et fruité, un Merlot qui offre au cœur une étreinte chaleureuse.",
        "food_pairings_de": ["Pasta mit Tomatensauce", "Käse"],
        "food_pairings_en": ["Pasta with tomato sauce", "Cheese"],
        "food_pairings_fr": ["Pâtes sauce tomate", "Fromage"],
    },
    {
        "name": "Chardonnay 2023",
        "winery": "Domaine de la Guérite",
        "region": "Russin",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Reich und honigartig, ein Surmaturé, der wie ein Traum die Seele umhüllt.",
        "description_en": "Rich and honeyed, a late harvest that envelops the soul like a dream.",
        "description_fr": "Riche et miellé, un surmaturé qui enveloppe l'âme comme un rêve.",
        "food_pairings_de": ["Foie gras", "Desserts"],
        "food_pairings_en": ["Foie gras", "Desserts"],
        "food_pairings_fr": ["Foie gras", "Desserts"],
    },
    {
        "name": "Gamay Mathurin 2023",
        "winery": "Domaine de Chafalet",
        "region": "Peissy",
        "grape_variety": "Gamay",
        "wine_color": "rot",
        "price_category": "€€",
        "description_de": "Jung und sprudelnd, ein Gamay, der die Seele mit kindlicher Freude weckt.",
        "description_en": "Young and effervescent, a Gamay that awakens the soul with childlike joy.",
        "description_fr": "Jeune et pétillant, un Gamay qui éveille l'âme d'une joie enfantine.",
        "food_pairings_de": ["Tapas", "Lachs"],
        "food_pairings_en": ["Tapas", "Salmon"],
        "food_pairings_fr": ["Tapas", "Saumon"],
    },
    {
        "name": "Sauvignon Blanc Effijie 2022",
        "winery": "Domaine Les Hutins",
        "region": "Dardagny",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Naturrein und lebendig, ein Blanc, der wie ein Gebet die Seele beruhigt.",
        "description_en": "Natural and vibrant, a Blanc that calms the soul like a prayer.",
        "description_fr": "Naturel et vivant, un Blanc qui apaise l'âme comme une prière.",
        "food_pairings_de": ["Hummer", "Milder Käse"],
        "food_pairings_en": ["Lobster", "Mild cheese"],
        "food_pairings_fr": ["Homard", "Fromage doux"],
    },
    {
        "name": "Pinot Noir 2023",
        "winery": "Domaine des Curiades",
        "region": "Satigny",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Tief und mineralisch, mit dunklen Früchten, die wie ein Geheimnis die Seele berühren.",
        "description_en": "Deep and mineral, with dark fruits that touch the soul like a secret.",
        "description_fr": "Profond et minéral, avec des fruits noirs qui touchent l'âme comme un secret.",
        "food_pairings_de": ["Rindfleisch", "Wild"],
        "food_pairings_en": ["Beef", "Game"],
        "food_pairings_fr": ["Bœuf", "Gibier"],
    },
    {
        "name": "Chasselas 2023",
        "winery": "Domaine des Alouettes",
        "region": "Satigny",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Ikonisch und tief, mit Honig und Stein, das wie ein Erbe die Seele berührt.",
        "description_en": "Iconic and deep, with honey and stone that touches the soul like a heritage.",
        "description_fr": "Iconique et profond, avec du miel et de la pierre qui touche l'âme comme un héritage.",
        "food_pairings_de": ["Geflügel", "Meeresfrüchte"],
        "food_pairings_en": ["Poultry", "Seafood"],
        "food_pairings_fr": ["Volaille", "Fruits de mer"],
    },
    {
        "name": "Cabernet Sauvignon 2021",
        "winery": "Cave Les Crêtets",
        "region": "Peissy",
        "grape_variety": "Cabernet Sauvignon",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Strukturiert und pfeffrig, ein Rot, der die Seele mit orientalischem Zauber umhüllt.",
        "description_en": "Structured and peppery, a red that envelops the soul with oriental magic.",
        "description_fr": "Structuré et poivré, un rouge qui enveloppe l'âme de magie orientale.",
        "food_pairings_de": ["Gewürzhähnchen", "Auberginen"],
        "food_pairings_en": ["Spiced chicken", "Eggplant"],
        "food_pairings_fr": ["Poulet épicé", "Aubergines"],
    },
    {
        "name": "Viognier 2023",
        "winery": "Domaine Villard & Fils",
        "region": "Anières",
        "grape_variety": "Viognier",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Exotisch und würzig, ein Weiß, der das Herz mit orientalischem Flair verzaubert.",
        "description_en": "Exotic and spicy, a white that enchants the heart with oriental flair.",
        "description_fr": "Exotique et épicé, un blanc qui enchante le cœur d'un flair oriental.",
        "food_pairings_de": ["Curry", "Vegetarische Gerichte"],
        "food_pairings_en": ["Curry", "Vegetarian dishes"],
        "food_pairings_fr": ["Curry", "Plats végétariens"],
    },
    {
        "name": "Gamay Grand'Cour 2022",
        "winery": "Domaine Grand'Cour",
        "region": "Peissy-Satigny",
        "grape_variety": "Gamay",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Monumental und samtig, ein Gamay, der die Seele in göttliche Ekstase versetzt.",
        "description_en": "Monumental and velvety, a Gamay that sends the soul into divine ecstasy.",
        "description_fr": "Monumental et velouté, un Gamay qui envoie l'âme en extase divine.",
        "food_pairings_de": ["Entrecôte", "Schokolade"],
        "food_pairings_en": ["Entrecôte", "Chocolate"],
        "food_pairings_fr": ["Entrecôte", "Chocolat"],
    },
    {
        "name": "Chasselas Coteau de Peissy 1er Cru 2023",
        "winery": "Domaine Grand'Cour",
        "region": "Peissy-Satigny",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Fruchtig und robust, ein Chasselas, der wie ein Abgrund die Seele fesselt.",
        "description_en": "Fruity and robust, a Chasselas that captivates the soul like an abyss.",
        "description_fr": "Fruité et robuste, un Chasselas qui captive l'âme comme un abîme.",
        "food_pairings_de": ["Stark gewürzte Fleischgerichte"],
        "food_pairings_en": ["Heavily spiced meat dishes"],
        "food_pairings_fr": ["Plats de viande très épicés"],
    },
    {
        "name": "Pinot Gris 2022",
        "winery": "Philippe Chevrier",
        "region": "Satigny",
        "grape_variety": "Pinot Gris",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Elegant und filigran, ein Gris, der das Herz mit burgundischer Poesie umfängt.",
        "description_en": "Elegant and delicate, a Gris that embraces the heart with Burgundian poetry.",
        "description_fr": "Élégant et délicat, un Gris qui embrasse le cœur de poésie bourguignonne.",
        "food_pairings_de": ["Ente", "Pilzgerichte"],
        "food_pairings_en": ["Duck", "Mushroom dishes"],
        "food_pairings_fr": ["Canard", "Plats aux champignons"],
    },
    {
        "name": "Assemblage de G 2021",
        "winery": "Domaine de la Guérite",
        "region": "Russin",
        "grape_variety": "Assemblage",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Frisch und blumig, ein Blend, der die Seele mit genevischer Reinheit erfüllt.",
        "description_en": "Fresh and floral, a blend that fills the soul with Genevan purity.",
        "description_fr": "Frais et floral, un assemblage qui remplit l'âme de pureté genevoise.",
        "food_pairings_de": ["Fisch", "Salate"],
        "food_pairings_en": ["Fish", "Salads"],
        "food_pairings_fr": ["Poisson", "Salades"],
    },
    {
        "name": "Merlot 2023",
        "winery": "Domaine de la Mermière",
        "region": "Satigny",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Weich und beerig, ein Merlot, der die Seele in genevische Wälder entführt.",
        "description_en": "Soft and berry-rich, a Merlot that transports the soul to Genevan forests.",
        "description_fr": "Doux et fruité, un Merlot qui transporte l'âme dans les forêts genevoises.",
        "food_pairings_de": ["Lammkoteletts", "Käse"],
        "food_pairings_en": ["Lamb chops", "Cheese"],
        "food_pairings_fr": ["Côtelettes d'agneau", "Fromage"],
    },
    {
        "name": "Sauvignon Blanc 2023",
        "winery": "Domaine des Bonnettes",
        "region": "Dardagny",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Intensiv und salzig, ein Tropfen, der das Herz mit Meeresbrise umweht.",
        "description_en": "Intense and salty, a drop that envelops the heart with sea breeze.",
        "description_fr": "Intense et salé, une goutte qui enveloppe le cœur de brise marine.",
        "food_pairings_de": ["Schalentiere", "Zitronenhähnchen"],
        "food_pairings_en": ["Shellfish", "Lemon chicken"],
        "food_pairings_fr": ["Crustacés", "Poulet au citron"],
    },
    {
        "name": "Gamay 2022",
        "winery": "Stéphane Gros",
        "region": "Dardagny",
        "grape_variety": "Gamay",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Reich und strukturiert, ein Grand Cru, der die Seele in städtischer Eleganz badet.",
        "description_en": "Rich and structured, a Grand Cru that bathes the soul in urban elegance.",
        "description_fr": "Riche et structuré, un Grand Cru qui baigne l'âme dans l'élégance urbaine.",
        "food_pairings_de": ["Krustentiere", "Geflügel"],
        "food_pairings_en": ["Crustaceans", "Poultry"],
        "food_pairings_fr": ["Crustacés", "Volaille"],
    },
    {
        "name": "Chardonnay 2023",
        "winery": "Domaine de la République",
        "region": "Lully",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Sonnig und fruchtig, ein Chardonnay, der das Herz mit sommerlicher Leichtigkeit umfängt.",
        "description_en": "Sunny and fruity, a Chardonnay that embraces the heart with summery lightness.",
        "description_fr": "Ensoleillé et fruité, un Chardonnay qui embrasse le cœur d'une légèreté estivale.",
        "food_pairings_de": ["Sommergerichte", "Frischkäse"],
        "food_pairings_en": ["Summer dishes", "Fresh cheese"],
        "food_pairings_fr": ["Plats d'été", "Fromage frais"],
    },
    {
        "name": "Pinot Noir 2023",
        "winery": "Les Vins de Philippe Chevrier",
        "region": "Satigny",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Filigran und robust, ein Pinot, der die Seele mit imperierender Kraft erhebt.",
        "description_en": "Delicate and robust, a Pinot that uplifts the soul with commanding power.",
        "description_fr": "Délicat et robuste, un Pinot qui élève l'âme d'une puissance impérieuse.",
        "food_pairings_de": ["Lamm", "Pilze"],
        "food_pairings_en": ["Lamb", "Mushrooms"],
        "food_pairings_fr": ["Agneau", "Champignons"],
    },
    {
        "name": "Rosé Blanc de Noirs 2024",
        "winery": "Les Parcelles - L. Villard",
        "region": "Satigny",
        "grape_variety": "Pinot Noir",
        "wine_color": "rosé",
        "price_category": "€€",
        "description_de": "Leicht und verlockend, ein Rosé, der wie ein Flüstern die Seele mit Sommerfreude erfüllt.",
        "description_en": "Light and alluring, a Rosé that fills the soul with summer joy like a whisper.",
        "description_fr": "Léger et séduisant, un Rosé qui remplit l'âme de joie estivale comme un murmure.",
        "food_pairings_de": ["Tapas", "Lachs"],
        "food_pairings_en": ["Tapas", "Salmon"],
        "food_pairings_fr": ["Tapas", "Saumon"],
    },
    {
        "name": "Gamaret 2021",
        "winery": "Domaine des Balisiers",
        "region": "Satigny",
        "grape_variety": "Gamaret",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Würzig und amaronig, ein Rot, das wie ein Traum die Seele umhüllt.",
        "description_en": "Spicy and Amarone-like, a red that envelops the soul like a dream.",
        "description_fr": "Épicé et amaronien, un rouge qui enveloppe l'âme comme un rêve.",
        "food_pairings_de": ["Foie gras", "Desserts"],
        "food_pairings_en": ["Foie gras", "Desserts"],
        "food_pairings_fr": ["Foie gras", "Desserts"],
    },
    {
        "name": "Chasselas 2023",
        "winery": "Domaine Les Hutins",
        "region": "Dardagny",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Mineralisch und nervös, ein Chasselas, der die Seele mit alpiner Frische weckt.",
        "description_en": "Mineral and nervous, a Chasselas that awakens the soul with alpine freshness.",
        "description_fr": "Minéral et nerveux, un Chasselas qui éveille l'âme d'une fraîcheur alpine.",
        "food_pairings_de": ["Krebse", "Kräutersuppe"],
        "food_pairings_en": ["Crayfish", "Herb soup"],
        "food_pairings_fr": ["Écrevisses", "Soupe aux herbes"],
    },
    {
        "name": "Merlot 2022",
        "winery": "Château du Crest",
        "region": "Collex-Bossy",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Tief und harmonisch, ein Assemblage, der die Seele in göttliche Ekstase versetzt.",
        "description_en": "Deep and harmonious, an assemblage that sends the soul into divine ecstasy.",
        "description_fr": "Profond et harmonieux, un assemblage qui envoie l'âme en extase divine.",
        "food_pairings_de": ["Entrecôte", "Schokolade"],
        "food_pairings_en": ["Entrecôte", "Chocolate"],
        "food_pairings_fr": ["Entrecôte", "Chocolat"],
    },
    {
        "name": "Sauvignon Gris 2023",
        "winery": "Domaine Dugerdil",
        "region": "Avully",
        "grape_variety": "Sauvignon Gris",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Zart und blumig, ein Gris, der das Herz mit genevischer Reinheit erfüllt.",
        "description_en": "Delicate and floral, a Gris that fills the heart with Genevan purity.",
        "description_fr": "Délicat et floral, un Gris qui remplit le cœur de pureté genevoise.",
        "food_pairings_de": ["Fisch", "Salate"],
        "food_pairings_en": ["Fish", "Salads"],
        "food_pairings_fr": ["Poisson", "Salades"],
    },
    {
        "name": "Pinot Noir 2023",
        "winery": "Domaine de Chafalet",
        "region": "Peissy",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Historisch und elegant, ein Wein, der die Seele mit zeitloser Tiefe berührt.",
        "description_en": "Historic and elegant, a wine that touches the soul with timeless depth.",
        "description_fr": "Historique et élégant, un vin qui touche l'âme d'une profondeur intemporelle.",
        "food_pairings_de": ["Geflügel", "Meeresfrüchte"],
        "food_pairings_en": ["Poultry", "Seafood"],
        "food_pairings_fr": ["Volaille", "Fruits de mer"],
    },
    {
        "name": "Gamay 2023",
        "winery": "Domaine de la Devinière",
        "region": "Dardagny",
        "grape_variety": "Gamay",
        "wine_color": "rot",
        "price_category": "€€",
        "description_de": "Frisch und ausgewogen, ein Gamay, der das Herz mit klassischer Freude erheitert.",
        "description_en": "Fresh and balanced, a Gamay that gladdens the heart with classic joy.",
        "description_fr": "Frais et équilibré, un Gamay qui réjouit le cœur d'une joie classique.",
        "food_pairings_de": ["Fondue", "Rind"],
        "food_pairings_en": ["Fondue", "Beef"],
        "food_pairings_fr": ["Fondue", "Bœuf"],
    },
    {
        "name": "Chasselas 2023",
        "winery": "Domaine des Alouettes",
        "region": "Satigny",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Reich und beerig, ein Chasselas, der die Seele in genevische Wälder entführt.",
        "description_en": "Rich and berry-like, a Chasselas that transports the soul to Genevan forests.",
        "description_fr": "Riche et fruité, un Chasselas qui transporte l'âme dans les forêts genevoises.",
        "food_pairings_de": ["Lammkoteletts", "Käse"],
        "food_pairings_en": ["Lamb chops", "Cheese"],
        "food_pairings_fr": ["Côtelettes d'agneau", "Fromage"],
    },
    {
        "name": "Cabernet Franc 2023",
        "winery": "Cave Les Crêtets",
        "region": "Peissy",
        "grape_variety": "Cabernet Franc",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Elegant und pfeffrig, ein Rot, der die Seele mit orientalischem Zauber umhüllt.",
        "description_en": "Elegant and peppery, a red that envelops the soul with oriental magic.",
        "description_fr": "Élégant et poivré, un rouge qui enveloppe l'âme de magie orientale.",
        "food_pairings_de": ["Gewürzhähnchen", "Auberginen"],
        "food_pairings_en": ["Spiced chicken", "Eggplant"],
        "food_pairings_fr": ["Poulet épicé", "Aubergines"],
    },
    {
        "name": "Viognier 2023",
        "winery": "Domaine Villard & Fils",
        "region": "Anières",
        "grape_variety": "Viognier",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Innovativ und fruchtig, ein Hybrid, der das Herz mit moderner Freude erfüllt.",
        "description_en": "Innovative and fruity, a hybrid that fills the heart with modern joy.",
        "description_fr": "Innovant et fruité, un hybride qui remplit le cœur d'une joie moderne.",
        "food_pairings_de": ["Grillgemüse", "Fisch"],
        "food_pairings_en": ["Grilled vegetables", "Fish"],
        "food_pairings_fr": ["Légumes grillés", "Poisson"],
    },
    {
        "name": "Mousseux Blanc Noir 2023",
        "winery": "Domaine de la République et Canton de Genève",
        "region": "Lully",
        "grape_variety": "Pinot Noir",
        "wine_color": "schaumwein",
        "price_category": "€€€",
        "description_de": "Hoch und rein, ein Mousseux, der wie ein Gipfelblick die Seele erweitert.",
        "description_en": "High and pure, a Mousseux that expands the soul like a summit view.",
        "description_fr": "Haut et pur, un Mousseux qui élargit l'âme comme une vue du sommet.",
        "food_pairings_de": ["Käseplatte", "Leichte Vorspeisen"],
        "food_pairings_en": ["Cheese platter", "Light appetizers"],
        "food_pairings_fr": ["Plateau de fromages", "Amuse-bouches légers"],
    },
]

async def add_genf_wines():
    """Fügt alle 50 Genfer Weine zur Datenbank hinzu"""
    
    client = AsyncIOMotorClient(os.environ.get('MONGO_URL'))
    db = client[os.environ.get('DB_NAME', 'test_database')]
    
    print("=" * 60)
    print("🍷 TOP 50 GENFER WEINE - Import")
    print("   Eleganz am Genfersee!")
    print("=" * 60)
    
    added = 0
    skipped = 0
    
    for wine in GENF_WINES:
        # Prüfen ob Wein bereits existiert
        existing = await db.public_wines.find_one({
            "name": wine["name"],
            "winery": wine["winery"]
        })
        
        if existing:
            print(f"  ⏭️  {wine['name']} ({wine['winery']}) - bereits vorhanden")
            skipped += 1
            continue
        
        # Wein-Dokument erstellen
        wine_doc = {
            "id": str(uuid4()),
            "name": wine["name"],
            "winery": wine["winery"],
            "country": "Schweiz",
            "region": f"Genf - {wine['region']}",
            "appellation": "AOC Genève",
            "grape_variety": wine["grape_variety"],
            "wine_color": wine["wine_color"],
            "price_category": wine["price_category"],
            "description_de": wine["description_de"],
            "description_en": wine["description_en"],
            "description_fr": wine["description_fr"],
            "food_pairings_de": wine["food_pairings_de"],
            "food_pairings_en": wine["food_pairings_en"],
            "food_pairings_fr": wine["food_pairings_fr"],
            "created_at": datetime.now(timezone.utc).isoformat(),
            "source": "Top 50 Genfer Weine - Sélection des Vins de Genève 2024, GaultMillau, Falstaff"
        }
        
        await db.public_wines.insert_one(wine_doc)
        print(f"  ✅ {wine['name']} ({wine['winery']})")
        added += 1
    
    print()
    print("=" * 60)
    print(f"🎉 IMPORT ABGESCHLOSSEN!")
    print(f"   Hinzugefügt: {added}")
    print(f"   Übersprungen: {skipped}")
    print("=" * 60)
    
    # Gesamtzahl prüfen
    total = await db.public_wines.count_documents({})
    swiss = await db.public_wines.count_documents({"country": "Schweiz"})
    genf = await db.public_wines.count_documents({"region": {"$regex": "Genf", "$options": "i"}})
    tessin = await db.public_wines.count_documents({"region": {"$regex": "Tessin", "$options": "i"}})
    waadt = await db.public_wines.count_documents({"region": {"$regex": "Waadt", "$options": "i"}})
    wallis = await db.public_wines.count_documents({"region": {"$regex": "Wallis", "$options": "i"}})
    print(f"\n📊 Datenbank-Status:")
    print(f"   Gesamte Weine: {total}")
    print(f"   Schweizer Weine: {swiss}")
    print(f"   - Genf: {genf}")
    print(f"   - Tessin: {tessin}")
    print(f"   - Waadt: {waadt}")
    print(f"   - Wallis: {wallis}")
    print(f"\n   À votre santé! 🇨🇭")

if __name__ == "__main__":
    asyncio.run(add_genf_wines())
