#!/usr/bin/env python3
"""
Skript zum Hinzufügen der Top 50 Rheingau-Weine zur Datenbank
Mit deutschen, englischen und französischen Beschreibungen

Rheingau: Die Wiege des Rieslings und der edlen Tradition
Aristokratische Eleganz von sonnigen Südhängen am Rhein
"""

import asyncio
import os
from uuid import uuid4
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

# Die 50 Rheingau-Weine mit allen Details
RHEINGAU_WINES = [
    {
        "name": "Rüdesheimer Berg Schlossberg Riesling Trocken GG 2024",
        "winery": "Georg Breuer",
        "region": "Rüdesheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Ein Monument der Präzision, strahlend und tief, mit nasser Stein und exotischer Frucht – ein Wein, der die Seele in pure Rheingau-Eleganz taucht (99 Falstaff-Punkte).",
        "description_en": "A monument of precision, radiant and deep, with wet stone and exotic fruit – a wine that immerses the soul in pure Rheingau elegance (99 Falstaff points).",
        "description_fr": "Un monument de précision, radieux et profond, avec pierre mouillée et fruits exotiques – un vin qui plonge l'âme dans l'élégance pure du Rheingau (99 points Falstaff).",
        "food_pairings_de": ["Gegrillter Fisch", "Milder Ziegenkäse"],
        "food_pairings_en": ["Grilled fish", "Mild goat cheese"],
        "food_pairings_fr": ["Poisson grillé", "Fromage de chèvre doux"],
    },
    {
        "name": "Kiedricher Gräfenberg Riesling Trocken GG 2024",
        "winery": "Robert Weil",
        "region": "Kiedrich",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Adelig und komplex, ein Gräfenberg-Juwel von Pfirsich und Mineral, das das Herz mit unendlicher Tiefe umfängt.",
        "description_en": "Noble and complex, a Gräfenberg jewel of peach and mineral that embraces the heart with infinite depth.",
        "description_fr": "Noble et complexe, un joyau de Gräfenberg de pêche et de minéral qui enlace le cœur d'une profondeur infinie.",
        "food_pairings_de": ["Hummer", "Reifer Parmesan"],
        "food_pairings_en": ["Lobster", "Aged Parmesan"],
        "food_pairings_fr": ["Homard", "Parmesan affiné"],
    },
    {
        "name": "Hochheimer Hölle Riesling Trocken GG 2024",
        "winery": "Franz Künstler",
        "region": "Hochheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Kraftvoll und brillant, ein Hölle-Feuer von Zitrus und Salz – ein Tropfen, der die Sinne in Ekstase versetzt.",
        "description_en": "Powerful and brilliant, a Hell-fire of citrus and salt – a drop that sends the senses into ecstasy.",
        "description_fr": "Puissant et brillant, un feu d'Enfer d'agrumes et de sel – une goutte qui met les sens en extase.",
        "food_pairings_de": ["Lamm", "Asiatisches Curry"],
        "food_pairings_en": ["Lamb", "Asian curry"],
        "food_pairings_fr": ["Agneau", "Curry asiatique"],
    },
    {
        "name": "Rüdesheimer Berg Rottland Riesling Trocken GG 2024",
        "winery": "Johannes Leitz",
        "region": "Rüdesheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Filigran und mineralisch, ein Rottland-Traum von Stein und Frucht, der die Seele mit jugendlicher Lebendigkeit erfrischt.",
        "description_en": "Delicate and mineral, a Rottland dream of stone and fruit that refreshes the soul with youthful vivacity.",
        "description_fr": "Délicat et minéral, un rêve de Rottland de pierre et de fruit qui rafraîchit l'âme avec une vivacité juvénile.",
        "food_pairings_de": ["Meeresfrüchte", "Sommergemüse"],
        "food_pairings_en": ["Seafood", "Summer vegetables"],
        "food_pairings_fr": ["Fruits de mer", "Légumes d'été"],
    },
    {
        "name": "Oestricher Lenchen Riesling Trockenbeerenauslese 2024",
        "winery": "Josef Spreitzer",
        "region": "Oestrich-Winkel",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Golden und konzentriert, ein Eisberg der Süße, der wie ein Wunder die Seele verzaubert (98+ Falstaff).",
        "description_en": "Golden and concentrated, an iceberg of sweetness that enchants the soul like a miracle (98+ Falstaff).",
        "description_fr": "Doré et concentré, un iceberg de douceur qui enchante l'âme comme un miracle (98+ Falstaff).",
        "food_pairings_de": ["Foie gras", "Blauschimmelkäse"],
        "food_pairings_en": ["Foie gras", "Blue cheese"],
        "food_pairings_fr": ["Foie gras", "Fromage bleu"],
    },
    {
        "name": "Oestricher Doosberg Riesling Trocken GG 2024",
        "winery": "Peter Jakob Kühn",
        "region": "Oestrich",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Biodynamisch und tief, ein Doosberg der Natürlichkeit, das das Herz mit erdiger Harmonie umfängt.",
        "description_en": "Biodynamic and deep, a Doosberg of naturalness that embraces the heart with earthy harmony.",
        "description_fr": "Biodynamique et profond, un Doosberg de naturalité qui enlace le cœur d'une harmonie terreuse.",
        "food_pairings_de": ["Geflügel", "Pilzrisotto"],
        "food_pairings_en": ["Poultry", "Mushroom risotto"],
        "food_pairings_fr": ["Volaille", "Risotto aux champignons"],
    },
    {
        "name": "Silberlack Riesling Trocken GG 2024",
        "winery": "Schloss Johannisberg",
        "region": "Johannisberg",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Legendär und strahlend, ein Silberlack der Noblesse, der die Seele in historische Tiefe taucht.",
        "description_en": "Legendary and radiant, a Silberlack of nobility that immerses the soul in historical depth.",
        "description_fr": "Légendaire et radieux, un Silberlack de noblesse qui plonge l'âme dans une profondeur historique.",
        "food_pairings_de": ["Gegrillter Lachs", "Milde Tomme"],
        "food_pairings_en": ["Grilled salmon", "Mild Tomme"],
        "food_pairings_fr": ["Saumon grillé", "Tomme douce"],
    },
    {
        "name": "Assmannshäuser Höllenberg Spätburgunder GG 2024",
        "winery": "August Kesseler",
        "region": "Assmannshausen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Rot und leidenschaftlich, ein Höllenberg-Feuer von Kirsche und Gewürz – der König der Rheingau-Roten.",
        "description_en": "Red and passionate, a Höllenberg fire of cherry and spice – the king of Rheingau reds.",
        "description_fr": "Rouge et passionné, un feu de Höllenberg de cerise et d'épices – le roi des rouges du Rheingau.",
        "food_pairings_de": ["Wild", "Dunkles Fleisch"],
        "food_pairings_en": ["Game", "Dark meat"],
        "food_pairings_fr": ["Gibier", "Viande brune"],
    },
    {
        "name": "Schlossberg Riesling Trocken GG 2024",
        "winery": "Schloss Vollrads",
        "region": "Winkel",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Klassisch und mineralisch, ein Schlossberg der Tradition, der das Herz mit purer Reinheit erfüllt.",
        "description_en": "Classic and mineral, a Schlossberg of tradition that fills the heart with pure purity.",
        "description_fr": "Classique et minéral, un Schlossberg de tradition qui remplit le cœur de pureté pure.",
        "food_pairings_de": ["Forelle", "Salat"],
        "food_pairings_en": ["Trout", "Salad"],
        "food_pairings_fr": ["Truite", "Salade"],
    },
    {
        "name": "Lorcher Seligmacher Riesling Trocken GG 2024",
        "winery": "Eva Fricke",
        "region": "Lorch",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Aufstrebend und präzise, ein Seligmacher der Frische, der die Seele mit moderner Eleganz weckt.",
        "description_en": "Rising and precise, a Seligmacher of freshness that awakens the soul with modern elegance.",
        "description_fr": "Montant et précis, un Seligmacher de fraîcheur qui éveille l'âme avec une élégance moderne.",
        "food_pairings_de": ["Vegetarisch", "Käse"],
        "food_pairings_en": ["Vegetarian", "Cheese"],
        "food_pairings_fr": ["Végétarien", "Fromage"],
    },
    {
        "name": "Hochheimer Kirchenstück Riesling Trocken GG 2024",
        "winery": "Domdechant Werner",
        "region": "Hochheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Kirchenwürdig und tief, ein Stück der Geschichte in flüssiger Form.",
        "description_en": "Church-worthy and deep, a piece of history in liquid form.",
        "description_fr": "Digne d'une église et profond, un morceau d'histoire sous forme liquide.",
        "food_pairings_de": ["Ente", "Pilze"],
        "food_pairings_en": ["Duck", "Mushrooms"],
        "food_pairings_fr": ["Canard", "Champignons"],
    },
    {
        "name": "Rüdesheimer Riesling Sekt Extra Brut NV",
        "winery": "Weingut Barth",
        "region": "Hattenheim",
        "grape_variety": "Riesling",
        "wine_color": "schaumwein",
        "price_category": "€€€",
        "description_de": "Perlend und lebendig, ein Sekt, der die Seele in festliche Ekstase versetzt.",
        "description_en": "Sparkling and lively, a Sekt that sends the soul into festive ecstasy.",
        "description_fr": "Pétillant et vivant, un Sekt qui met l'âme en extase festive.",
        "food_pairings_de": ["Aperitif", "Austern"],
        "food_pairings_en": ["Aperitif", "Oysters"],
        "food_pairings_fr": ["Apéritif", "Huîtres"],
    },
    {
        "name": "Hochheimer Domdechaney Riesling Trocken GG 2024",
        "winery": "Franz Künstler",
        "region": "Hochheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Domdechaney-adelig und kraftvoll, ein Monument der Mineralität.",
        "description_en": "Domdechaney-noble and powerful, a monument of minerality.",
        "description_fr": "Domdechaney-noble et puissant, un monument de minéralité.",
        "food_pairings_de": ["Rind", "BBQ"],
        "food_pairings_en": ["Beef", "BBQ"],
        "food_pairings_fr": ["Bœuf", "BBQ"],
    },
    {
        "name": "Rüdesheimer Drachenstein Riesling Trocken 2024",
        "winery": "Johannes Leitz",
        "region": "Rüdesheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Drachenstark und feurig, ein Drache der Aromen.",
        "description_en": "Dragon-strong and fiery, a dragon of aromas.",
        "description_fr": "Fort comme un dragon et fougueux, un dragon d'arômes.",
        "food_pairings_de": ["Scharfer Thai", "Käse"],
        "food_pairings_en": ["Spicy Thai", "Cheese"],
        "food_pairings_fr": ["Thaï épicé", "Fromage"],
    },
    {
        "name": "Rauenthaler Nonnenberg Riesling Trocken GG 2024",
        "winery": "Georg Breuer",
        "region": "Rauenthal",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Nonnen-rein und harmonisch, ein Berg der Stille.",
        "description_en": "Nun-pure and harmonious, a mountain of silence.",
        "description_fr": "Pur comme une nonne et harmonieux, une montagne de silence.",
        "food_pairings_de": ["Geflügel", "Gemüse"],
        "food_pairings_en": ["Poultry", "Vegetables"],
        "food_pairings_fr": ["Volaille", "Légumes"],
    },
    {
        "name": "Kiedricher Monte Vacano Riesling Trocken 2024",
        "winery": "Robert Weil",
        "region": "Kiedrich",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Exotisch und tief, ein Vacano der Verführung.",
        "description_en": "Exotic and deep, a Vacano of seduction.",
        "description_fr": "Exotique et profond, un Vacano de séduction.",
        "food_pairings_de": ["Asiatisch", "Desserts"],
        "food_pairings_en": ["Asian cuisine", "Desserts"],
        "food_pairings_fr": ["Cuisine asiatique", "Desserts"],
    },
    {
        "name": "Assmannshäuser Spätburgunder Trocken GG 2024",
        "winery": "August Kesseler",
        "region": "Assmannshausen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Samten und würzig, ein Rot der Leidenschaft.",
        "description_en": "Velvety and spicy, a red of passion.",
        "description_fr": "Velouté et épicé, un rouge de passion.",
        "food_pairings_de": ["Roastbeef", "Schokolade"],
        "food_pairings_en": ["Roast beef", "Chocolate"],
        "food_pairings_fr": ["Rosbif", "Chocolat"],
    },
    {
        "name": "Hallgartener Hendelberg Riesling Trocken GG 2024",
        "winery": "Josef Spreitzer",
        "region": "Hallgarten",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Hendelberg-wild und intensiv, ein Aufstieg zur Perfektion.",
        "description_en": "Hendelberg-wild and intense, an ascent to perfection.",
        "description_fr": "Hendelberg-sauvage et intense, une ascension vers la perfection.",
        "food_pairings_de": ["Wildgerichte"],
        "food_pairings_en": ["Game dishes"],
        "food_pairings_fr": ["Plats de gibier"],
    },
    {
        "name": "Jacobus Riesling Trocken 2024",
        "winery": "Peter Jakob Kühn",
        "region": "Oestrich",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Jakobus-segnend und ausgewogen, ein Segen für die Seele.",
        "description_en": "Jacobus-blessing and balanced, a blessing for the soul.",
        "description_fr": "Jacobus-bénissant et équilibré, une bénédiction pour l'âme.",
        "food_pairings_de": ["Fisch", "Salat"],
        "food_pairings_en": ["Fish", "Salad"],
        "food_pairings_fr": ["Poisson", "Salade"],
    },
    {
        "name": "Rosalack Riesling Kabinett 2024",
        "winery": "Schloss Johannisberg",
        "region": "Johannisberg",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Zart und tänzerisch, ein Rosalack der Jugend.",
        "description_en": "Delicate and dancing, a Rosalack of youth.",
        "description_fr": "Délicat et dansant, un Rosalack de jeunesse.",
        "food_pairings_de": ["Aperitif", "Leichte Vorspeisen"],
        "food_pairings_en": ["Aperitif", "Light appetizers"],
        "food_pairings_fr": ["Apéritif", "Entrées légères"],
    },
    {
        "name": "Hochheimer Stielweg Alte Reben Riesling GG 2024",
        "winery": "Franz Künstler",
        "region": "Hochheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Alte Reben-weise und tief, ein Stielweg der Weisheit.",
        "description_en": "Old vines-wise and deep, a Stielweg of wisdom.",
        "description_fr": "Vieilles vignes-sage et profond, un Stielweg de sagesse.",
        "food_pairings_de": ["Parmesan", "Hummer"],
        "food_pairings_en": ["Parmesan", "Lobster"],
        "food_pairings_fr": ["Parmesan", "Homard"],
    },
    {
        "name": "Ehrenfels Riesling Trocken GG 2024",
        "winery": "Johannes Leitz",
        "region": "Rüdesheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Ehrenvoll und strahlend, ein Fels der Stärke.",
        "description_en": "Honorable and radiant, a rock of strength.",
        "description_fr": "Honorable et radieux, un roc de force.",
        "food_pairings_de": ["Lamm", "Pilze"],
        "food_pairings_en": ["Lamb", "Mushrooms"],
        "food_pairings_fr": ["Agneau", "Champignons"],
    },
    {
        "name": "Kiedricher Turmberg Riesling TBA 2023",
        "winery": "Robert Weil",
        "region": "Kiedrich",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Turmhoch und golden, eine Beerenauslese der Ewigkeit.",
        "description_en": "Tower-high and golden, a Beerenauslese of eternity.",
        "description_fr": "Haut comme une tour et doré, une Beerenauslese d'éternité.",
        "food_pairings_de": ["Desserts", "Blauschimmel"],
        "food_pairings_en": ["Desserts", "Blue cheese"],
        "food_pairings_fr": ["Desserts", "Bleu"],
    },
    {
        "name": "Rüdesheimer Berg Roseneck Riesling Trocken GG 2024",
        "winery": "Georg Breuer",
        "region": "Rüdesheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Rosen-duftend und filigran, ein Roseneck der Poesie.",
        "description_en": "Rose-scented and delicate, a Roseneck of poetry.",
        "description_fr": "Parfumé à la rose et délicat, un Roseneck de poésie.",
        "food_pairings_de": ["Meeresfrüchte"],
        "food_pairings_en": ["Seafood"],
        "food_pairings_fr": ["Fruits de mer"],
    },
    {
        "name": "Der König Spätburgunder GG 2024",
        "winery": "August Kesseler",
        "region": "Assmannshausen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Königlich und robust, ein König der Roten.",
        "description_en": "Royal and robust, a king of reds.",
        "description_fr": "Royal et robuste, un roi des rouges.",
        "food_pairings_de": ["Dunkles Fleisch", "Schokolade"],
        "food_pairings_en": ["Dark meat", "Chocolate"],
        "food_pairings_fr": ["Viande brune", "Chocolat"],
    },
    {
        "name": "Riesling Kabinett 2024",
        "winery": "Schloss Vollrads",
        "region": "Winkel",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Leicht und fruchtig, ein Kabinett der Freude.",
        "description_en": "Light and fruity, a Kabinett of joy.",
        "description_fr": "Léger et fruité, un Kabinett de joie.",
        "food_pairings_de": ["Salat", "Aperitif"],
        "food_pairings_en": ["Salad", "Aperitif"],
        "food_pairings_fr": ["Salade", "Apéritif"],
    },
    {
        "name": "Krone Riesling Trocken GG 2024",
        "winery": "Eva Fricke",
        "region": "Lorch",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Krone-würdig und präzise, ein Aufsteiger-Traum.",
        "description_en": "Crown-worthy and precise, a rising star dream.",
        "description_fr": "Digne d'une couronne et précis, un rêve d'étoile montante.",
        "food_pairings_de": ["Vegetarisch", "Käse"],
        "food_pairings_en": ["Vegetarian", "Cheese"],
        "food_pairings_fr": ["Végétarien", "Fromage"],
    },
    {
        "name": "Rheingau Riesling Estate 2024",
        "winery": "Franz Künstler",
        "region": "Hochheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Estate-ehrlich und saftig, ein Alltags-Juwel.",
        "description_en": "Estate-honest and juicy, an everyday jewel.",
        "description_fr": "Estate-honnête et juteux, un joyau quotidien.",
        "food_pairings_de": ["Fisch", "Fondue"],
        "food_pairings_en": ["Fish", "Fondue"],
        "food_pairings_fr": ["Poisson", "Fondue"],
    },
    {
        "name": "Quarzit Riesling Trocken 2024",
        "winery": "Peter Jakob Kühn",
        "region": "Oestrich",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Quarzit-mineralisch und biodynamisch, ein Stein der Reinheit.",
        "description_en": "Quarzit-mineral and biodynamic, a stone of purity.",
        "description_fr": "Quarzit-minéral et biodynamique, une pierre de pureté.",
        "food_pairings_de": ["Gemüse", "Tofu"],
        "food_pairings_en": ["Vegetables", "Tofu"],
        "food_pairings_fr": ["Légumes", "Tofu"],
    },
    {
        "name": "Grünlack Riesling Spätlese 2024",
        "winery": "Schloss Johannisberg",
        "region": "Johannisberg",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Spät und verlockend, ein Grünlack der Süße.",
        "description_en": "Late and enticing, a Grünlack of sweetness.",
        "description_fr": "Tardif et séduisant, un Grünlack de douceur.",
        "food_pairings_de": ["Scharfes Essen", "Käse"],
        "food_pairings_en": ["Spicy food", "Cheese"],
        "food_pairings_fr": ["Plats épicés", "Fromage"],
    },
    {
        "name": "Charta Riesling Trocken 2024",
        "winery": "Josef Spreitzer",
        "region": "Oestrich-Winkel",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Charta-klassisch und ausgewogen, ein Traditionsträger.",
        "description_en": "Charta-classic and balanced, a tradition bearer.",
        "description_fr": "Charta-classique et équilibré, un porteur de tradition.",
        "food_pairings_de": ["Geflügel"],
        "food_pairings_en": ["Poultry"],
        "food_pairings_fr": ["Volaille"],
    },
    {
        "name": "Magic Mountain Riesling Trocken 2024",
        "winery": "Johannes Leitz",
        "region": "Rüdesheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Magisch und kraftvoll, ein Berg der Wunder.",
        "description_en": "Magical and powerful, a mountain of wonders.",
        "description_fr": "Magique et puissant, une montagne de merveilles.",
        "food_pairings_de": ["Lamm", "BBQ"],
        "food_pairings_en": ["Lamb", "BBQ"],
        "food_pairings_fr": ["Agneau", "BBQ"],
    },
    {
        "name": "Monte Vacano Riesling Trocken 2024",
        "winery": "Robert Weil",
        "region": "Kiedrich",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Vacano-exotisch und tief, ein Geheimnis.",
        "description_en": "Vacano-exotic and deep, a secret.",
        "description_fr": "Vacano-exotique et profond, un secret.",
        "food_pairings_de": ["Asiatisch", "Desserts"],
        "food_pairings_en": ["Asian cuisine", "Desserts"],
        "food_pairings_fr": ["Cuisine asiatique", "Desserts"],
    },
    {
        "name": "Cuvée Max Spätburgunder 2024",
        "winery": "August Kesseler",
        "region": "Assmannshausen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Cuvée-harmonisch und rot, ein Max der Leidenschaft.",
        "description_en": "Cuvée-harmonious and red, a Max of passion.",
        "description_fr": "Cuvée-harmonieux et rouge, un Max de passion.",
        "food_pairings_de": ["Wild"],
        "food_pairings_en": ["Game"],
        "food_pairings_fr": ["Gibier"],
    },
    {
        "name": "Sauvage Riesling Trocken 2024",
        "winery": "Georg Breuer",
        "region": "Rüdesheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Sauvage-wild und ungezähmt, ein Naturtraum.",
        "description_en": "Sauvage-wild and untamed, a nature dream.",
        "description_fr": "Sauvage-sauvage et indomptable, un rêve de nature.",
        "food_pairings_de": ["Pilze", "Vegetarisch"],
        "food_pairings_en": ["Mushrooms", "Vegetarian"],
        "food_pairings_fr": ["Champignons", "Végétarien"],
    },
    {
        "name": "Riesling Auslese 2023",
        "winery": "Schloss Vollrads",
        "region": "Winkel",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Auslese-süß und golden, ein Schatz.",
        "description_en": "Auslese-sweet and golden, a treasure.",
        "description_fr": "Auslese-doux et doré, un trésor.",
        "food_pairings_de": ["Foie gras"],
        "food_pairings_en": ["Foie gras"],
        "food_pairings_fr": ["Foie gras"],
    },
    {
        "name": "Kirchenstück Riesling GG 2024",
        "winery": "Franz Künstler",
        "region": "Hochheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Kirchen-heilig und tief, ein Stück Paradies.",
        "description_en": "Church-holy and deep, a piece of paradise.",
        "description_fr": "Saint d'église et profond, un morceau de paradis.",
        "food_pairings_de": ["Parmesan"],
        "food_pairings_en": ["Parmesan"],
        "food_pairings_fr": ["Parmesan"],
    },
    {
        "name": "Rheingau Riesling Trocken 2024",
        "winery": "Eva Fricke",
        "region": "Lorch",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Frisch und aufstrebend, ein Fricke der Zukunft.",
        "description_en": "Fresh and rising, a Fricke of the future.",
        "description_fr": "Frais et montant, un Fricke de l'avenir.",
        "food_pairings_de": ["Salat", "Fisch"],
        "food_pairings_en": ["Salad", "Fish"],
        "food_pairings_fr": ["Salade", "Poisson"],
    },
    {
        "name": "Höllenberg Spätburgunder Alte Reben 2024",
        "winery": "August Kesseler",
        "region": "Assmannshausen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Alte Reben-tief und rot, ein Höllenberg der Reife.",
        "description_en": "Old vines-deep and red, a Höllenberg of maturity.",
        "description_fr": "Vieilles vignes-profond et rouge, un Höllenberg de maturité.",
        "food_pairings_de": ["Roastbeef"],
        "food_pairings_en": ["Roast beef"],
        "food_pairings_fr": ["Rosbif"],
    },
    {
        "name": "Hallgartener Hendelberg GG 2024",
        "winery": "Peter Jakob Kühn",
        "region": "Hallgarten",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Hendelberg-biodynamisch und mineralisch.",
        "description_en": "Hendelberg-biodynamic and mineral.",
        "description_fr": "Hendelberg-biodynamique et minéral.",
        "food_pairings_de": ["Gemüse"],
        "food_pairings_en": ["Vegetables"],
        "food_pairings_fr": ["Légumes"],
    },
    {
        "name": "Riesling Kabinett 2024",
        "winery": "Robert Weil",
        "region": "Kiedrich",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Kabinett-leicht und tänzerisch, ein Einstieg in die Noblesse.",
        "description_en": "Kabinett-light and dancing, an entry into nobility.",
        "description_fr": "Kabinett-léger et dansant, une entrée dans la noblesse.",
        "food_pairings_de": ["Aperitif"],
        "food_pairings_en": ["Aperitif"],
        "food_pairings_fr": ["Apéritif"],
    },
    {
        "name": "Rüdesheimer Berg Kaisersteinfels GG 2024",
        "winery": "Johannes Leitz",
        "region": "Rüdesheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Kaiserlich und steil, ein Fels der Majestät.",
        "description_en": "Imperial and steep, a rock of majesty.",
        "description_fr": "Impérial et raide, un roc de majesté.",
        "food_pairings_de": ["Lamm"],
        "food_pairings_en": ["Lamb"],
        "food_pairings_fr": ["Agneau"],
    },
    {
        "name": "Nonnenberg Riesling Auslese 2023",
        "winery": "Georg Breuer",
        "region": "Rauenthal",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Nonnen-süß und geheimnisvoll.",
        "description_en": "Nun-sweet and mysterious.",
        "description_fr": "Doux comme une nonne et mystérieux.",
        "food_pairings_de": ["Desserts"],
        "food_pairings_en": ["Desserts"],
        "food_pairings_fr": ["Desserts"],
    },
    {
        "name": "Pfaffenberg Riesling GG 2024",
        "winery": "Franz Künstler",
        "region": "Hochheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Pfaffenberg-monopol und titanisch.",
        "description_en": "Pfaffenberg-monopole and titanic.",
        "description_fr": "Pfaffenberg-monopole et titanique.",
        "food_pairings_de": ["Krustentiere"],
        "food_pairings_en": ["Crustaceans"],
        "food_pairings_fr": ["Crustacés"],
    },
    {
        "name": "Riesling Auslese 2023",
        "winery": "Schloss Johannisberg",
        "region": "Johannisberg",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Auslese-historisch und golden.",
        "description_en": "Auslese-historic and golden.",
        "description_fr": "Auslese-historique et doré.",
        "food_pairings_de": ["Blauschimmel"],
        "food_pairings_en": ["Blue cheese"],
        "food_pairings_fr": ["Bleu"],
    },
    {
        "name": "Lenchen Riesling Spätlese 2024",
        "winery": "Josef Spreitzer",
        "region": "Oestrich",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Lenchen-spät und verlockend.",
        "description_en": "Lenchen-late and enticing.",
        "description_fr": "Lenchen-tardif et séduisant.",
        "food_pairings_de": ["Scharfer Thai"],
        "food_pairings_en": ["Spicy Thai"],
        "food_pairings_fr": ["Thaï épicé"],
    },
    {
        "name": "Gräfenberg Riesling Spätlese 2024",
        "winery": "Robert Weil",
        "region": "Kiedrich",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Gräfenberg-spät und edel.",
        "description_en": "Gräfenberg-late and noble.",
        "description_fr": "Gräfenberg-tardif et noble.",
        "food_pairings_de": ["Käseplatte"],
        "food_pairings_en": ["Cheese platter"],
        "food_pairings_fr": ["Plateau de fromages"],
    },
    {
        "name": "Assmannshäuser Spätburgunder Rosé 2024",
        "winery": "August Kesseler",
        "region": "Assmannshausen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rosé",
        "price_category": "€€€",
        "description_de": "Rosé-zart und sommerlich.",
        "description_en": "Rosé-delicate and summery.",
        "description_fr": "Rosé-délicat et estival.",
        "food_pairings_de": ["Salate"],
        "food_pairings_en": ["Salads"],
        "food_pairings_fr": ["Salades"],
    },
    {
        "name": "Lorcher Krone Riesling Auslese 2023",
        "winery": "Eva Fricke",
        "region": "Lorch",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Krone-süß und aufstrebend.",
        "description_en": "Krone-sweet and rising.",
        "description_fr": "Krone-doux et montant.",
        "food_pairings_de": ["Desserts"],
        "food_pairings_en": ["Desserts"],
        "food_pairings_fr": ["Desserts"],
    },
    {
        "name": "Riesling Erstes Gewächs 2024",
        "winery": "Schloss Vollrads",
        "region": "Winkel",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Erstes Gewächs-klassisch und rein, ein Abschluss der Rheingau-Seele.",
        "description_en": "Erstes Gewächs-classic and pure, a finale of the Rheingau soul.",
        "description_fr": "Erstes Gewächs-classique et pur, un final de l'âme du Rheingau.",
        "food_pairings_de": ["Forelle", "Leichte Vorspeisen"],
        "food_pairings_en": ["Trout", "Light appetizers"],
        "food_pairings_fr": ["Truite", "Entrées légères"],
    },
]


async def add_rheingau_wines():
    """Fügt die Rheingau-Weine zur Datenbank hinzu"""
    
    mongo_url = os.environ.get('MONGO_URL', 'mongodb://localhost:27017')
    db_name = os.environ.get('DB_NAME', 'test_database')
    
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    
    print("=" * 60)
    print("🍷 RHEINGAU-WEINE HINZUFÜGEN")
    print("   Die Wiege des Rieslings und der edlen Tradition")
    print("=" * 60)
    print(f"📊 Anzahl Weine: {len(RHEINGAU_WINES)}")
    print()
    
    # Prüfe bestehende Weine
    existing = await db.public_wines.count_documents({"region": {"$regex": "^Rheingau"}})
    print(f"📋 Bestehende Rheingau-Weine: {existing}")
    
    added = 0
    skipped = 0
    
    for wine_data in RHEINGAU_WINES:
        # Prüfe ob der Wein schon existiert
        exists = await db.public_wines.find_one({
            "name": wine_data["name"],
            "winery": wine_data["winery"]
        })
        
        if exists:
            print(f"⏭️  Übersprungen (existiert): {wine_data['name']}")
            skipped += 1
            continue
        
        # Erstelle den Wein-Eintrag
        wine = {
            "id": str(uuid4()),
            "name": wine_data["name"],
            "winery": wine_data["winery"],
            "country": "Deutschland",
            "region": f"Rheingau - {wine_data['region']}",
            "appellation": "Rheingau",
            "grape_variety": wine_data["grape_variety"],
            "wine_color": wine_data["wine_color"],
            "year": None,
            "description_de": wine_data["description_de"],
            "description_en": wine_data["description_en"],
            "description_fr": wine_data["description_fr"],
            "tasting_notes": None,
            "food_pairings_de": wine_data["food_pairings_de"],
            "food_pairings_en": wine_data["food_pairings_en"],
            "food_pairings_fr": wine_data["food_pairings_fr"],
            "alcohol_content": None,
            "price_category": wine_data["price_category"],
            "image_url": None,
            "rating": None,
            "created_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
        }
        
        await db.public_wines.insert_one(wine)
        print(f"✅ Hinzugefügt: {wine_data['name']} ({wine_data['winery']})")
        added += 1
    
    print()
    print("=" * 60)
    print(f"🎉 FERTIG! {added} Weine hinzugefügt, {skipped} übersprungen")
    print("=" * 60)
    
    # Zeige Gesamtzahl
    total = await db.public_wines.count_documents({})
    rheingau_total = await db.public_wines.count_documents({"region": {"$regex": "^Rheingau"}})
    print(f"\n📊 Gesamtzahl Weine in DB: {total}")
    print(f"📊 Davon Rheingau-Weine: {rheingau_total}")
    
    client.close()


if __name__ == "__main__":
    asyncio.run(add_rheingau_wines())
