#!/usr/bin/env python3
"""
Skript zum Hinzufügen der Top 50 Franken-Weine zur Datenbank
Mit deutschen, englischen und französischen Beschreibungen

Franken: Die Heimat des Bocksbeutels und der trockenen Seele
Silvaner von mineralischer Tiefe, Spätburgunder von burgundischer Finesse
"""

import asyncio
import os
from uuid import uuid4
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

# Die 50 Franken-Weine mit allen Details
FRANKEN_WINES = [
    {
        "name": "Würzburger Stein Silvaner GG 2024",
        "winery": "Juliusspital",
        "region": "Würzburg",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€€",
        "description_de": "Ein monumentaler Stein-Silvaner von Kräutern, Apfel und salziger Mineralität – ein Wein, der die Seele in pure fränkische Kraft und Tiefe taucht (99 Falstaff-Punkte).",
        "description_en": "A monumental Stein Silvaner of herbs, apple and salty minerality – a wine that immerses the soul in pure Franconian power and depth (99 Falstaff points).",
        "description_fr": "Un Silvaner Stein monumental aux herbes, à la pomme et à la minéralité salée – un vin qui plonge l'âme dans la pure puissance et profondeur franconienne (99 points Falstaff).",
        "food_pairings_de": ["Schweinshaxe", "Milder Ziegenkäse"],
        "food_pairings_en": ["Pork knuckle", "Mild goat cheese"],
        "food_pairings_fr": ["Jarret de porc", "Fromage de chèvre doux"],
    },
    {
        "name": "Iphöfer Julius-Echter-Berg Silvaner GG 2024",
        "winery": "Hans Wirsching",
        "region": "Iphofen",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€€",
        "description_de": "Adelig und präzise, ein Julius-Echter-Berg-Juwel von Birne und Stein – ein Tropfen, der das Herz mit trockener Noblesse umfängt.",
        "description_en": "Noble and precise, a Julius-Echter-Berg jewel of pear and stone – a drop that embraces the heart with dry nobility.",
        "description_fr": "Noble et précis, un joyau du Julius-Echter-Berg de poire et de pierre – une goutte qui enlace le cœur avec une noblesse sèche.",
        "food_pairings_de": ["Gegrillter Zander", "Reifer Parmesan"],
        "food_pairings_en": ["Grilled pike-perch", "Aged Parmesan"],
        "food_pairings_fr": ["Sandre grillé", "Parmesan affiné"],
    },
    {
        "name": "Bürgstadter Centgrafenberg Spätburgunder GG 2024",
        "winery": "Rudolf Fürst",
        "region": "Bürgstadt",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Rot und leidenschaftlich, ein Centgrafenberg-Feuer von Kirsche und Gewürz – der König der fränkischen Roten.",
        "description_en": "Red and passionate, a Centgrafenberg fire of cherry and spice – the king of Franconian reds.",
        "description_fr": "Rouge et passionné, un feu de Centgrafenberg de cerise et d'épices – le roi des rouges franconiens.",
        "food_pairings_de": ["Rehrücken", "Dunkle Schokolade"],
        "food_pairings_en": ["Saddle of venison", "Dark chocolate"],
        "food_pairings_fr": ["Selle de chevreuil", "Chocolat noir"],
    },
    {
        "name": "Küchenmeister Silvaner GG 2024",
        "winery": "Paul Weltner",
        "region": "Rödelsee",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Küchenmeister-kraftvoll und mineralisch, ein Silvaner der Intensität und Länge.",
        "description_en": "Küchenmeister-powerful and mineral, a Silvaner of intensity and length.",
        "description_fr": "Küchenmeister-puissant et minéral, un Silvaner d'intensité et de longueur.",
        "food_pairings_de": ["Schweinebraten", "Pilzrisotto"],
        "food_pairings_en": ["Roast pork", "Mushroom risotto"],
        "food_pairings_fr": ["Rôti de porc", "Risotto aux champignons"],
    },
    {
        "name": "Escherndorfer Lump Silvaner GG 2024",
        "winery": "Horst Sauer",
        "region": "Escherndorf",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€€",
        "description_de": "Lump-ig und brillant, ein Escherndorfer Traum von Apfel und Salz – ein Wein, der die Sinne in Ekstase versetzt.",
        "description_en": "Lump-ish and brilliant, an Escherndorf dream of apple and salt – a wine that sends the senses into ecstasy.",
        "description_fr": "Lump-esque et brillant, un rêve d'Escherndorf de pomme et de sel – un vin qui met les sens en extase.",
        "food_pairings_de": ["Gegrillter Fisch", "Milde Tomme"],
        "food_pairings_en": ["Grilled fish", "Mild Tomme"],
        "food_pairings_fr": ["Poisson grillé", "Tomme douce"],
    },
    {
        "name": "Randersackerer Pfülben Silvaner GG 2024",
        "winery": "Zeintheresienhof",
        "region": "Randersacker",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Pfülben-tief und harmonisch, ein Silvaner der Frucht und Mineralität.",
        "description_en": "Pfülben-deep and harmonious, a Silvaner of fruit and minerality.",
        "description_fr": "Pfülben-profond et harmonieux, un Silvaner de fruit et de minéralité.",
        "food_pairings_de": ["Forelle", "Sommergemüse"],
        "food_pairings_en": ["Trout", "Summer vegetables"],
        "food_pairings_fr": ["Truite", "Légumes d'été"],
    },
    {
        "name": "Würzburger Stein-Harfe Silvaner GG 2024",
        "winery": "Bürgerspital",
        "region": "Würzburg",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€€",
        "description_de": "Stein-Harfe-musikalisch und präzise, ein Harfe der Reinheit.",
        "description_en": "Stein-Harfe-musical and precise, a harp of purity.",
        "description_fr": "Stein-Harfe-musical et précis, une harpe de pureté.",
        "food_pairings_de": ["Meeresfrüchte", "Salat"],
        "food_pairings_en": ["Seafood", "Salad"],
        "food_pairings_fr": ["Fruits de mer", "Salade"],
    },
    {
        "name": "Bürgstadter Berg Spätburgunder GG 2024",
        "winery": "Rudolf Fürst",
        "region": "Bürgstadt",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Berg-steil und seidig, ein Rot der burgundischen Finesse.",
        "description_en": "Berg-steep and silky, a red of Burgundian finesse.",
        "description_fr": "Berg-escarpé et soyeux, un rouge de finesse bourguignonne.",
        "food_pairings_de": ["Wild", "Gereifter Comté"],
        "food_pairings_en": ["Game", "Aged Comté"],
        "food_pairings_fr": ["Gibier", "Comté affiné"],
    },
    {
        "name": "Sommeracher Katzenkopf Silvaner GG 2024",
        "winery": "Schmitts Kinder",
        "region": "Sommerach",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Katzenkopf-katzenhaft und tief, ein Silvaner der Eigenständigkeit.",
        "description_en": "Katzenkopf-cat-like and deep, a Silvaner of independence.",
        "description_fr": "Katzenkopf-félin et profond, un Silvaner d'indépendance.",
        "food_pairings_de": ["Schwein", "Käseplatte"],
        "food_pairings_en": ["Pork", "Cheese plate"],
        "food_pairings_fr": ["Porc", "Plateau de fromages"],
    },
    {
        "name": "Sulzfelder Maustal Silvaner GG 2024",
        "winery": "Luckert Zehnthof",
        "region": "Sulzfeld",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Maustal-mineralisch und saftig, ein fränkischer Klassiker.",
        "description_en": "Maustal-mineral and juicy, a Franconian classic.",
        "description_fr": "Maustal-minéral et juteux, un classique franconien.",
        "food_pairings_de": ["Fisch", "Fondue"],
        "food_pairings_en": ["Fish", "Fondue"],
        "food_pairings_fr": ["Poisson", "Fondue"],
    },
    {
        "name": "Würzburger Innere Leiste Silvaner GG 2024",
        "winery": "Juliusspital",
        "region": "Würzburg",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€€",
        "description_de": "Innere Leiste-innerlich und tief, ein Stück Würzburger Seele.",
        "description_en": "Innere Leiste-inner and deep, a piece of Würzburg soul.",
        "description_fr": "Innere Leiste-intérieur et profond, un morceau d'âme de Würzburg.",
        "food_pairings_de": ["Ente", "Pilze"],
        "food_pairings_en": ["Duck", "Mushrooms"],
        "food_pairings_fr": ["Canard", "Champignons"],
    },
    {
        "name": "Iphöfer Kronsberg Silvaner GG 2024",
        "winery": "Hans Wirsching",
        "region": "Iphofen",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€€",
        "description_de": "Kronsberg-krönend und kraftvoll, ein Berg der Mineralität.",
        "description_en": "Kronsberg-crowning and powerful, a mountain of minerality.",
        "description_fr": "Kronsberg-couronnant et puissant, une montagne de minéralité.",
        "food_pairings_de": ["Rind", "BBQ"],
        "food_pairings_en": ["Beef", "BBQ"],
        "food_pairings_fr": ["Bœuf", "BBQ"],
    },
    {
        "name": "Tradition Spätburgunder 2024",
        "winery": "Rudolf Fürst",
        "region": "Bürgstadt",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Tradition-ehrlich und rot, ein Alltags-Rot der Freude.",
        "description_en": "Tradition-honest and red, an everyday red of joy.",
        "description_fr": "Tradition-honnête et rouge, un rouge quotidien de joie.",
        "food_pairings_de": ["Pasta", "Fondue"],
        "food_pairings_en": ["Pasta", "Fondue"],
        "food_pairings_fr": ["Pâtes", "Fondue"],
    },
    {
        "name": "Escherndorfer Am Lumpen Silvaner Erste Lage 2024",
        "winery": "Horst Sauer",
        "region": "Escherndorf",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Am Lumpen-lumpig und intensiv, ein Silvaner der Frische.",
        "description_en": "Am Lumpen-ragged and intense, a Silvaner of freshness.",
        "description_fr": "Am Lumpen-déchiré et intense, un Silvaner de fraîcheur.",
        "food_pairings_de": ["Scharfes Thai", "Käse"],
        "food_pairings_en": ["Spicy Thai", "Cheese"],
        "food_pairings_fr": ["Thai épicé", "Fromage"],
    },
    {
        "name": "Rödelseer Küchenmeister Riesling GG 2024",
        "winery": "Paul Weltner",
        "region": "Rödelsee",
        "grape_variety": "Riesling",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Riesling-kühl und präzise, ein rarer Franken-Riesling.",
        "description_en": "Riesling-cool and precise, a rare Franconian Riesling.",
        "description_fr": "Riesling-frais et précis, un rare Riesling franconien.",
        "food_pairings_de": ["Gegrillter Lachs"],
        "food_pairings_en": ["Grilled salmon"],
        "food_pairings_fr": ["Saumon grillé"],
    },
    {
        "name": "Randersackerer Sonnenstuhl Silvaner GG 2024",
        "winery": "Zeintheresienhof",
        "region": "Randersacker",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Sonnenstuhl-sonnig und warm, ein Stuhl der Harmonie.",
        "description_en": "Sonnenstuhl-sunny and warm, a chair of harmony.",
        "description_fr": "Sonnenstuhl-ensoleillé et chaud, une chaise d'harmonie.",
        "food_pairings_de": ["Geflügel", "Gemüse"],
        "food_pairings_en": ["Poultry", "Vegetables"],
        "food_pairings_fr": ["Volaille", "Légumes"],
    },
    {
        "name": "Würzburger Pfaffenberg Silvaner GG 2024",
        "winery": "Bürgerspital",
        "region": "Würzburg",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€€",
        "description_de": "Pfaffenberg-pfäffisch und tief, ein Berg der Noblesse.",
        "description_en": "Pfaffenberg-priestly and deep, a mountain of nobility.",
        "description_fr": "Pfaffenberg-sacerdotal et profond, une montagne de noblesse.",
        "food_pairings_de": ["Wildgerichte"],
        "food_pairings_en": ["Game dishes"],
        "food_pairings_fr": ["Plats de gibier"],
    },
    {
        "name": "Sommeracher Silvaner Trocken 2024",
        "winery": "Schmitts Kinder",
        "region": "Sommerach",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€",
        "description_de": "Sommeracher-sommerlich und saftig, ein Alltags-Silvaner.",
        "description_en": "Sommerach-summery and juicy, an everyday Silvaner.",
        "description_fr": "Sommerach-estival et juteux, un Silvaner quotidien.",
        "food_pairings_de": ["Salat", "Aperitif"],
        "food_pairings_en": ["Salad", "Aperitif"],
        "food_pairings_fr": ["Salade", "Apéritif"],
    },
    {
        "name": "Randersackerer Pfülben Rieslaner Auslese 2023",
        "winery": "Luckert Zehnthof",
        "region": "Randersacker",
        "grape_variety": "Rieslaner",
        "wine_color": "weiß",
        "price_category": "€€€€€",
        "description_de": "Rieslaner-süß und golden, ein rarer Schatz.",
        "description_en": "Rieslaner-sweet and golden, a rare treasure.",
        "description_fr": "Rieslaner-doux et doré, un trésor rare.",
        "food_pairings_de": ["Desserts", "Blauschimmel"],
        "food_pairings_en": ["Desserts", "Blue cheese"],
        "food_pairings_fr": ["Desserts", "Bleu"],
    },
    {
        "name": "Klingenberger Spätburgunder GG 2024",
        "winery": "Rudolf Fürst",
        "region": "Klingenberg",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Klingenberger-rot und mineralisch, ein Main-Rot der Tiefe.",
        "description_en": "Klingenberg-red and mineral, a Main red of depth.",
        "description_fr": "Klingenberg-rouge et minéral, un rouge du Main de profondeur.",
        "food_pairings_de": ["Roastbeef"],
        "food_pairings_en": ["Roast beef"],
        "food_pairings_fr": ["Rosbif"],
    },
    {
        "name": "Iphöfer Silvaner GG 2024",
        "winery": "Juliusspital",
        "region": "Iphofen",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Iphöfer-klassisch und tief.",
        "description_en": "Iphofen-classic and deep.",
        "description_fr": "Iphofen-classique et profond.",
        "food_pairings_de": ["Schwein"],
        "food_pairings_en": ["Pork"],
        "food_pairings_fr": ["Porc"],
    },
    {
        "name": "Kronsberg Scheurebe Trocken 2024",
        "winery": "Hans Wirsching",
        "region": "Iphofen",
        "grape_variety": "Scheurebe",
        "wine_color": "weiß",
        "price_category": "€€€",
        "description_de": "Scheurebe-aromatisch und frisch.",
        "description_en": "Scheurebe-aromatic and fresh.",
        "description_fr": "Scheurebe-aromatique et frais.",
        "food_pairings_de": ["Asiatisch"],
        "food_pairings_en": ["Asian cuisine"],
        "food_pairings_fr": ["Cuisine asiatique"],
    },
    {
        "name": "Escherndorfer Fürstenberg Silvaner GG 2024",
        "winery": "Horst Sauer",
        "region": "Escherndorf",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€€",
        "description_de": "Fürstenberg-fürstlich und mineralisch.",
        "description_en": "Fürstenberg-princely and mineral.",
        "description_fr": "Fürstenberg-princier et minéral.",
        "food_pairings_de": ["Parmesan"],
        "food_pairings_en": ["Parmesan"],
        "food_pairings_fr": ["Parmesan"],
    },
    {
        "name": "Rödelseer Müller-Thurgau Trocken 2024",
        "winery": "Paul Weltner",
        "region": "Rödelsee",
        "grape_variety": "Müller-Thurgau",
        "wine_color": "weiß",
        "price_category": "€€",
        "description_de": "Müller-Thurgau-leicht und fruchtig.",
        "description_en": "Müller-Thurgau-light and fruity.",
        "description_fr": "Müller-Thurgau-léger et fruité.",
        "food_pairings_de": ["Aperitif"],
        "food_pairings_en": ["Aperitif"],
        "food_pairings_fr": ["Apéritif"],
    },
    {
        "name": "Randersackerer Marsberg Riesling GG 2024",
        "winery": "Zeintheresienhof",
        "region": "Randersacker",
        "grape_variety": "Riesling",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Marsberg-kraftvoll und tief.",
        "description_en": "Marsberg-powerful and deep.",
        "description_fr": "Marsberg-puissant et profond.",
        "food_pairings_de": ["Lamm"],
        "food_pairings_en": ["Lamb"],
        "food_pairings_fr": ["Agneau"],
    },
    {
        "name": "Würzburger Abtsberg Silvaner GG 2024",
        "winery": "Bürgerspital",
        "region": "Würzburg",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Abtsberg-abtlich und harmonisch.",
        "description_en": "Abtsberg-abbatial and harmonious.",
        "description_fr": "Abtsberg-abbatial et harmonieux.",
        "food_pairings_de": ["Pilze"],
        "food_pairings_en": ["Mushrooms"],
        "food_pairings_fr": ["Champignons"],
    },
    {
        "name": "Sommeracher Spätburgunder GG 2024",
        "winery": "Schmitts Kinder",
        "region": "Sommerach",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Spätburgunder-rot und seidig.",
        "description_en": "Spätburgunder-red and silky.",
        "description_fr": "Spätburgunder-rouge et soyeux.",
        "food_pairings_de": ["Entrecôte"],
        "food_pairings_en": ["Entrecôte"],
        "food_pairings_fr": ["Entrecôte"],
    },
    {
        "name": "Sulzfelder Cyriakusberg Silvaner GG 2024",
        "winery": "Luckert Zehnthof",
        "region": "Sulzfeld",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Cyriakusberg-heilig und mineralisch.",
        "description_en": "Cyriakusberg-holy and mineral.",
        "description_fr": "Cyriakusberg-sacré et minéral.",
        "food_pairings_de": ["Käse"],
        "food_pairings_en": ["Cheese"],
        "food_pairings_fr": ["Fromage"],
    },
    {
        "name": "Centgrafenberg Frühburgunder GG 2024",
        "winery": "Rudolf Fürst",
        "region": "Bürgstadt",
        "grape_variety": "Frühburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Frühburgunder-früh und lebendig.",
        "description_en": "Frühburgunder-early and lively.",
        "description_fr": "Frühburgunder-précoce et vif.",
        "food_pairings_de": ["Grilladen"],
        "food_pairings_en": ["Grilled meats"],
        "food_pairings_fr": ["Grillades"],
    },
    {
        "name": "Würzburger Stein Riesling GG 2024",
        "winery": "Juliusspital",
        "region": "Würzburg",
        "grape_variety": "Riesling",
        "wine_color": "weiß",
        "price_category": "€€€€€",
        "description_de": "Stein-Riesling-rar und strahlend.",
        "description_en": "Stein-Riesling-rare and radiant.",
        "description_fr": "Stein-Riesling-rare et radieux.",
        "food_pairings_de": ["Forelle"],
        "food_pairings_en": ["Trout"],
        "food_pairings_fr": ["Truite"],
    },
    {
        "name": "Iphöfer Kalb Silvaner GG 2024",
        "winery": "Hans Wirsching",
        "region": "Iphofen",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Kalb-kraftvoll und tief.",
        "description_en": "Kalb-powerful and deep.",
        "description_fr": "Kalb-puissant et profond.",
        "food_pairings_de": ["Schwein"],
        "food_pairings_en": ["Pork"],
        "food_pairings_fr": ["Porc"],
    },
    {
        "name": "Escherndorfer Berg Silvaner GG 2024",
        "winery": "Horst Sauer",
        "region": "Escherndorf",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Berg-steil und intensiv.",
        "description_en": "Berg-steep and intense.",
        "description_fr": "Berg-escarpé et intense.",
        "food_pairings_de": ["Pilze"],
        "food_pairings_en": ["Mushrooms"],
        "food_pairings_fr": ["Champignons"],
    },
    {
        "name": "Rödelseer Schwanleite Silvaner GG 2024",
        "winery": "Paul Weltner",
        "region": "Rödelsee",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Schwanleite-elegant und mineralisch.",
        "description_en": "Schwanleite-elegant and mineral.",
        "description_fr": "Schwanleite-élégant et minéral.",
        "food_pairings_de": ["Gemüse"],
        "food_pairings_en": ["Vegetables"],
        "food_pairings_fr": ["Légumes"],
    },
    {
        "name": "Randersackerer Lämmerberg Silvaner GG 2024",
        "winery": "Zeintheresienhof",
        "region": "Randersacker",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Lämmerberg-sanft und tief.",
        "description_en": "Lämmerberg-gentle and deep.",
        "description_fr": "Lämmerberg-doux et profond.",
        "food_pairings_de": ["Geflügel"],
        "food_pairings_en": ["Poultry"],
        "food_pairings_fr": ["Volaille"],
    },
    {
        "name": "Würzburger Innere Leiste Rieslaner Auslese 2023",
        "winery": "Bürgerspital",
        "region": "Würzburg",
        "grape_variety": "Rieslaner",
        "wine_color": "weiß",
        "price_category": "€€€€€",
        "description_de": "Rieslaner-süß und golden.",
        "description_en": "Rieslaner-sweet and golden.",
        "description_fr": "Rieslaner-doux et doré.",
        "food_pairings_de": ["Desserts"],
        "food_pairings_en": ["Desserts"],
        "food_pairings_fr": ["Desserts"],
    },
    {
        "name": "Sommeracher Katzenkopf Müller-Thurgau 2024",
        "winery": "Schmitts Kinder",
        "region": "Sommerach",
        "grape_variety": "Müller-Thurgau",
        "wine_color": "weiß",
        "price_category": "€€",
        "description_de": "Katzenkopf-leicht und frisch.",
        "description_en": "Katzenkopf-light and fresh.",
        "description_fr": "Katzenkopf-léger et frais.",
        "food_pairings_de": ["Aperitif"],
        "food_pairings_en": ["Aperitif"],
        "food_pairings_fr": ["Apéritif"],
    },
    {
        "name": "Sulzfelder Spätburgunder GG 2024",
        "winery": "Luckert Zehnthof",
        "region": "Sulzfeld",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Spätburgunder-rot und harmonisch.",
        "description_en": "Spätburgunder-red and harmonious.",
        "description_fr": "Spätburgunder-rouge et harmonieux.",
        "food_pairings_de": ["Wild"],
        "food_pairings_en": ["Game"],
        "food_pairings_fr": ["Gibier"],
    },
    {
        "name": "Hundsrück Spätburgunder GG 2024",
        "winery": "Rudolf Fürst",
        "region": "Bürgstadt",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Hundsrück-wild und tief.",
        "description_en": "Hundsrück-wild and deep.",
        "description_fr": "Hundsrück-sauvage et profond.",
        "food_pairings_de": ["Schokolade"],
        "food_pairings_en": ["Chocolate"],
        "food_pairings_fr": ["Chocolat"],
    },
    {
        "name": "Würzburger Pfaffenberg Silvaner Spätlese 2023",
        "winery": "Juliusspital",
        "region": "Würzburg",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Pfaffenberg-spät und verlockend.",
        "description_en": "Pfaffenberg-late and enticing.",
        "description_fr": "Pfaffenberg-tardif et séduisant.",
        "food_pairings_de": ["Scharfes Thai"],
        "food_pairings_en": ["Spicy Thai"],
        "food_pairings_fr": ["Thai épicé"],
    },
    {
        "name": "Iphöfer Julius-Echter-Berg Scheurebe Spätlese 2023",
        "winery": "Hans Wirsching",
        "region": "Iphofen",
        "grape_variety": "Scheurebe",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Scheurebe-aromatisch und süß.",
        "description_en": "Scheurebe-aromatic and sweet.",
        "description_fr": "Scheurebe-aromatique et doux.",
        "food_pairings_de": ["Desserts"],
        "food_pairings_en": ["Desserts"],
        "food_pairings_fr": ["Desserts"],
    },
    {
        "name": "Escherndorfer Lump Riesling GG 2024",
        "winery": "Horst Sauer",
        "region": "Escherndorf",
        "grape_variety": "Riesling",
        "wine_color": "weiß",
        "price_category": "€€€€€",
        "description_de": "Lump-Riesling-rar und mineralisch.",
        "description_en": "Lump-Riesling-rare and mineral.",
        "description_fr": "Lump-Riesling-rare et minéral.",
        "food_pairings_de": ["Fisch"],
        "food_pairings_en": ["Fish"],
        "food_pairings_fr": ["Poisson"],
    },
    {
        "name": "Rödelseer Küchenmeister Bacchus 2024",
        "winery": "Paul Weltner",
        "region": "Rödelsee",
        "grape_variety": "Bacchus",
        "wine_color": "weiß",
        "price_category": "€€",
        "description_de": "Bacchus-duftend und fruchtig.",
        "description_en": "Bacchus-fragrant and fruity.",
        "description_fr": "Bacchus-parfumé et fruité.",
        "food_pairings_de": ["Asiatisch"],
        "food_pairings_en": ["Asian cuisine"],
        "food_pairings_fr": ["Cuisine asiatique"],
    },
    {
        "name": "Randersackerer Sonnenstuhl Müller-Thurgau 2024",
        "winery": "Zeintheresienhof",
        "region": "Randersacker",
        "grape_variety": "Müller-Thurgau",
        "wine_color": "weiß",
        "price_category": "€€",
        "description_de": "Sonnenstuhl-sonnig und leicht.",
        "description_en": "Sonnenstuhl-sunny and light.",
        "description_fr": "Sonnenstuhl-ensoleillé et léger.",
        "food_pairings_de": ["Aperitif"],
        "food_pairings_en": ["Aperitif"],
        "food_pairings_fr": ["Apéritif"],
    },
    {
        "name": "Würzburger Stein Silvaner Auslese 2023",
        "winery": "Bürgerspital",
        "region": "Würzburg",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€€",
        "description_de": "Stein-süß und konzentriert.",
        "description_en": "Stein-sweet and concentrated.",
        "description_fr": "Stein-doux et concentré.",
        "food_pairings_de": ["Blauschimmel"],
        "food_pairings_en": ["Blue cheese"],
        "food_pairings_fr": ["Bleu"],
    },
    {
        "name": "Sommeracher Silvaner Spätlese 2023",
        "winery": "Schmitts Kinder",
        "region": "Sommerach",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€",
        "description_de": "Spätlese-verlockend und golden.",
        "description_en": "Spätlese-enticing and golden.",
        "description_fr": "Spätlese-séduisant et doré.",
        "food_pairings_de": ["Käseplatte"],
        "food_pairings_en": ["Cheese plate"],
        "food_pairings_fr": ["Plateau de fromages"],
    },
    {
        "name": "Sulzfelder Weißburgunder GG 2024",
        "winery": "Luckert Zehnthof",
        "region": "Sulzfeld",
        "grape_variety": "Weißburgunder",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Weißburgunder-cremig und edel.",
        "description_en": "Weißburgunder-creamy and noble.",
        "description_fr": "Weißburgunder-crémeux et noble.",
        "food_pairings_de": ["Geflügel"],
        "food_pairings_en": ["Poultry"],
        "food_pairings_fr": ["Volaille"],
    },
    {
        "name": "Bürgstadter Berg Weißburgunder GG 2024",
        "winery": "Rudolf Fürst",
        "region": "Bürgstadt",
        "grape_variety": "Weißburgunder",
        "wine_color": "weiß",
        "price_category": "€€€€",
        "description_de": "Berg-weiß und mineralisch.",
        "description_en": "Berg-white and mineral.",
        "description_fr": "Berg-blanc et minéral.",
        "food_pairings_de": ["Gemüse"],
        "food_pairings_en": ["Vegetables"],
        "food_pairings_fr": ["Légumes"],
    },
    {
        "name": "Iphöfer Silvaner Trocken 2024",
        "winery": "Juliusspital",
        "region": "Iphofen",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€",
        "description_de": "Trocken-sauber und charakterstark.",
        "description_en": "Dry-clean and full of character.",
        "description_fr": "Sec-propre et plein de caractère.",
        "food_pairings_de": ["Schwein"],
        "food_pairings_en": ["Pork"],
        "food_pairings_fr": ["Porc"],
    },
    {
        "name": "Kronsberg Riesling Trocken 2024",
        "winery": "Hans Wirsching",
        "region": "Iphofen",
        "grape_variety": "Riesling",
        "wine_color": "weiß",
        "price_category": "€€€",
        "description_de": "Riesling-frisch und rar.",
        "description_en": "Riesling-fresh and rare.",
        "description_fr": "Riesling-frais et rare.",
        "food_pairings_de": ["Forelle"],
        "food_pairings_en": ["Trout"],
        "food_pairings_fr": ["Truite"],
    },
    {
        "name": "Escherndorfer Lump Silvaner Auslese 2023",
        "winery": "Horst Sauer",
        "region": "Escherndorf",
        "grape_variety": "Silvaner",
        "wine_color": "weiß",
        "price_category": "€€€€€",
        "description_de": "Lump-auslese-golden und tief, ein Abschluss der fränkischen Trockenheit und Seele.",
        "description_en": "Lump-auslese-golden and deep, a finale of Franconian dryness and soul.",
        "description_fr": "Lump-auslese-doré et profond, un finale de sécheresse et d'âme franconienne.",
        "food_pairings_de": ["Desserts", "Milder Käse"],
        "food_pairings_en": ["Desserts", "Mild cheese"],
        "food_pairings_fr": ["Desserts", "Fromage doux"],
    },
]


async def add_franken_wines():
    """Fügt alle 50 Franken-Weine zur Datenbank hinzu"""
    
    mongo_url = os.environ.get("MONGO_URL")
    db_name = os.environ.get("DB_NAME", "test_database")
    
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    
    print("=" * 60)
    print("🍷 FRANKEN-WEINE HINZUFÜGEN")
    print("=" * 60)
    print(f"📊 Anzahl Weine: {len(FRANKEN_WINES)}")
    print()
    
    # Prüfen wie viele Weine schon existieren
    existing_count = await db.public_wines.count_documents({"region": {"$in": [
        "Würzburg", "Iphofen", "Bürgstadt", "Rödelsee", "Escherndorf",
        "Randersacker", "Sommerach", "Sulzfeld", "Klingenberg"
    ]}})
    
    if existing_count > 0:
        print(f"⚠️  Es existieren bereits {existing_count} Franken-Weine in der Datenbank")
        print("   Lösche bestehende Einträge...")
        await db.public_wines.delete_many({"region": {"$in": [
            "Würzburg", "Iphofen", "Bürgstadt", "Rödelsee", "Escherndorf",
            "Randersacker", "Sommerach", "Sulzfeld", "Klingenberg"
        ]}})
        print("   ✅ Bestehende Einträge gelöscht")
        print()
    
    # Weine für die Datenbank vorbereiten
    wines_to_insert = []
    
    for wine in FRANKEN_WINES:
        wine_doc = {
            "id": str(uuid4()),
            "name": wine["name"],
            "winery": wine["winery"],
            "grape_variety": wine["grape_variety"],
            "region": wine["region"],
            "country": "Deutschland",
            "year": 2024 if "2024" in wine["name"] else 2023,
            "wine_color": wine["wine_color"],
            "price_category": wine["price_category"],
            "description_de": wine["description_de"],
            "description_en": wine["description_en"],
            "description_fr": wine["description_fr"],
            "food_pairings_de": wine["food_pairings_de"],
            "food_pairings_en": wine["food_pairings_en"],
            "food_pairings_fr": wine["food_pairings_fr"],
            "created_at": datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z'),
            "updated_at": datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z'),
        }
        wines_to_insert.append(wine_doc)
    
    # Bulk insert
    result = await db.public_wines.insert_many(wines_to_insert)
    
    print(f"✅ {len(result.inserted_ids)} Franken-Weine erfolgreich hinzugefügt!")
    print()
    
    # Statistiken
    print("📊 Statistiken nach Region:")
    regions = ["Würzburg", "Iphofen", "Bürgstadt", "Rödelsee", "Escherndorf", "Randersacker", "Sommerach", "Sulzfeld", "Klingenberg"]
    for region in regions:
        count = await db.public_wines.count_documents({"region": region, "country": "Deutschland"})
        if count > 0:
            print(f"   {region}: {count} Weine")
    
    print()
    total = await db.public_wines.count_documents({})
    print(f"📈 Gesamtzahl Weine in der Datenbank: {total}")
    
    client.close()


if __name__ == "__main__":
    asyncio.run(add_franken_wines())
