workflows:
  ios-workflow:
    name: iOS App Store Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "Wine Pairing.xcworkspace"
        XCODE_SCHEME: "Wine Pairing"
        BUNDLE_ID: "online.wine-pairing"
        TEAM_ID: "9EXPJ92538"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Set Team ID in project
        script: |
          sed -i '' 's/DEVELOPMENT_TEAM = "";/DEVELOPMENT_TEAM = 9EXPJ92538;/g' "Wine Pairing.xcodeproj/project.pbxproj"
          sed -i '' 's/DEVELOPMENT_TEAM = .*;/DEVELOPMENT_TEAM = 9EXPJ92538;/g' "Wine Pairing.xcodeproj/project.pbxproj"
      - name: Build iOS App
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/Wine\ Pairing.xcarchive \
            DEVELOPMENT_TEAM="9EXPJ92538" \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            archive
      - name: Create unsigned IPA
        script: |
          mkdir -p build/ios/ipa
          cd build/Wine\ Pairing.xcarchive/Products/Applications
          zip -r ../../../ios/ipa/WinePairing-unsigned.ipa .
    artifacts:
      - build/ios/ipa/*.ipa
      - build/*.xcarchive