workflows:
  ios-workflow:
    name: iOS App Store Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      vars:
        XCODE_WORKSPACE: "Wine Pairing.xcworkspace"
        XCODE_SCHEME: "Wine Pairing"
        BUNDLE_ID: "online.wine-pairing"
        TEAM_ID: "9EXPJ92538"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Set Team ID in project
        script: |
          sed -i '' 's/DEVELOPMENT_TEAM = "";/DEVELOPMENT_TEAM = 9EXPJ92538;/g' "Wine Pairing.xcodeproj/project.pbxproj"
          sed -i '' 's/DEVELOPMENT_TEAM = .*;/DEVELOPMENT_TEAM = 9EXPJ92538;/g' "Wine Pairing.xcodeproj/project.pbxproj"
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Set up keychain
        script: |
          keychain initialize
          keychain add-certificates
      - name: Set up profiles
        script: |
          xcode-project use-profiles
      - name: Build iOS App
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/Wine\ Pairing.xcarchive \
            DEVELOPMENT_TEAM="9EXPJ92538" \
            archive
      - name: Create IPA
        script: |
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/*.xcarchive
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true