workflows:
  ios-workflow:
    name: iOS App Store Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods
        script: pod install
      - name: Build iOS
        script: |
          xcodebuild build -workspace "Wine Pairing.xcworkspace" -scheme "Wine Pairing" CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/ios/ipa/*.ipa