#!/usr/bin/env python3
"""
Skript zum Hinzufügen der Top 50 Schaffhauser Weine zur Datenbank
Mit deutschen, englischen und französischen Beschreibungen

Schaffhausen - Blauburgunderland am Rhein
"""

import asyncio
import os
from uuid import uuid4
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

# Die 50 Schaffhauser Weine mit allen Details
SCHAFFHAUSEN_WINES = [
    {
        "name": "Pinot Noir Reblaube 2023",
        "winery": "Erich Meier",
        "region": "Uetikon am See",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Ein rubinroter Poet, der von dunklen Kirschen und Vanilleflüstern erzählt – ein Wein, der die Seele in sanfte, tanninreiche Umarmung hüllt und vergangene Herbsttage heraufbeschwört.",
        "description_en": "A ruby-red poet speaking of dark cherries and vanilla whispers – a wine that wraps the soul in a soft, tannic embrace and evokes past autumn days.",
        "description_fr": "Un poète rouge rubis parlant de cerises noires et de murmures de vanille – un vin qui enveloppe l'âme dans une étreinte douce et tannique.",
        "food_pairings_de": ["Gebratenes Huhn mit Kräutern", "Tomme Vaudoise"],
        "food_pairings_en": ["Roasted chicken with herbs", "Tomme Vaudoise"],
        "food_pairings_fr": ["Poulet rôti aux herbes", "Tomme Vaudoise"],
    },
    {
        "name": "Sauvignon Blanc 2024",
        "winery": "aagne weingut",
        "region": "Hallau",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Frisch und mineralisch, ein Blanc, der wie ein Morgenhauch über dem Rhein das Herz mit Zitrus und Stein erfrischt und Hoffnung weckt.",
        "description_en": "Fresh and mineral, a Blanc that refreshes the heart with citrus and stone like a morning breeze over the Rhine, awakening hope.",
        "description_fr": "Frais et minéral, un Blanc qui rafraîchit le cœur avec des agrumes et de la pierre comme une brise matinale sur le Rhin.",
        "food_pairings_de": ["Papet Vaudois", "Gegrillter Fisch"],
        "food_pairings_en": ["Papet Vaudois", "Grilled fish"],
        "food_pairings_fr": ["Papet Vaudois", "Poisson grillé"],
    },
    {
        "name": "Pinot Noir 2023",
        "winery": "Weingut Bad Osterfingen",
        "region": "Osterfingen",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Elegant und filigran, mit Kirsche und Samt, der die Seele in burgundische Melancholie taucht – ein Liebesbrief in Rot, der das Herz mit leichter Traurigkeit und purer Freude erfüllt.",
        "description_en": "Elegant and delicate, with cherry and velvet, plunging the soul into Burgundian melancholy – a love letter in red filling the heart with gentle sadness and pure joy.",
        "description_fr": "Élégant et délicat, avec de la cerise et du velours, plongeant l'âme dans la mélancolie bourguignonne – une lettre d'amour en rouge.",
        "food_pairings_de": ["Entenbrust", "Pilzrisotto"],
        "food_pairings_en": ["Duck breast", "Mushroom risotto"],
        "food_pairings_fr": ["Magret de canard", "Risotto aux champignons"],
    },
    {
        "name": "Chardonnay 2023",
        "winery": "Weingut Bad Osterfingen",
        "region": "Osterfingen",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Reich und blumig, ein Chardonnay, der die Seele in goldene Sonnenuntergänge taucht – cremig, mit Nuss und Zitrus, wie ein Traum der Klettgau-Hügel.",
        "description_en": "Rich and floral, a Chardonnay that immerses the soul in golden sunsets – creamy, with nut and citrus, like a dream of the Klettgau hills.",
        "description_fr": "Riche et floral, un Chardonnay qui plonge l'âme dans des couchers de soleil dorés – crémeux, avec de la noix et des agrumes.",
        "food_pairings_de": ["Huhn mit Kräutern", "Raclette"],
        "food_pairings_en": ["Chicken with herbs", "Raclette"],
        "food_pairings_fr": ["Poulet aux herbes", "Raclette"],
    },
    {
        "name": "Alte Reben Eisenhalde 2022",
        "winery": "GVS Schachenmann AG",
        "region": "Hallau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Tief und tanninreich, mit Leder und Beeren, die die Seele in alte Legenden eintauchen lassen – ein Monument aus Frucht und Finesse.",
        "description_en": "Deep and tannic, with leather and berries that immerse the soul in ancient legends – a monument of fruit and finesse.",
        "description_fr": "Profond et tannique, avec du cuir et des baies qui plongent l'âme dans les légendes anciennes – un monument de fruit et de finesse.",
        "food_pairings_de": ["Rehrücken", "Dunkles Fleisch"],
        "food_pairings_en": ["Saddle of venison", "Dark meat"],
        "food_pairings_fr": ["Selle de chevreuil", "Viande brune"],
    },
    {
        "name": "Mousseux Brut Bio 2023",
        "winery": "Rimuss & Strada Wein",
        "region": "Hallau",
        "grape_variety": "Assemblage",
        "wine_color": "schaumwein",
        "price_category": "€€€",
        "description_de": "Perlender Traum, der von goldenen Blasen und reifen Birnen erzählt – ein Wein, der die Seele in festliche Ekstase versetzt und vergangene Feste heraufbeschwört.",
        "description_en": "A sparkling dream speaking of golden bubbles and ripe pears – a wine that sends the soul into festive ecstasy and evokes past celebrations.",
        "description_fr": "Un rêve pétillant parlant de bulles dorées et de poires mûres – un vin qui envoie l'âme en extase festive.",
        "food_pairings_de": ["Austern", "Frischer Ziegenkäse"],
        "food_pairings_en": ["Oysters", "Fresh goat cheese"],
        "food_pairings_fr": ["Huîtres", "Fromage de chèvre frais"],
    },
    {
        "name": "Irma la Douce 2024",
        "winery": "aagne weingut",
        "region": "Hallau",
        "grape_variety": "Assemblage",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Nervös und aromatisch, mit Grapefruit und Kräutern, der wie ein Bergquell die Seele klärt und verjüngt.",
        "description_en": "Nervous and aromatic, with grapefruit and herbs, clearing and rejuvenating the soul like a mountain spring.",
        "description_fr": "Nerveux et aromatique, avec du pamplemousse et des herbes, purifiant et rajeunissant l'âme comme une source de montagne.",
        "food_pairings_de": ["Krebse", "Frischer Salat"],
        "food_pairings_en": ["Crayfish", "Fresh salad"],
        "food_pairings_fr": ["Écrevisses", "Salade fraîche"],
    },
    {
        "name": "Pinot Noir Buck 2023",
        "winery": "Weinbau Markus Ruch",
        "region": "Hallau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Robust und beerig, ein Pinot, der das Herz mit wilden Beeren und erdiger Wärme in herbstliche Wälder lockt.",
        "description_en": "Robust and berry-filled, a Pinot that lures the heart into autumn forests with wild berries and earthy warmth.",
        "description_fr": "Robuste et fruité, un Pinot qui attire le cœur dans les forêts d'automne avec des baies sauvages et une chaleur terreuse.",
        "food_pairings_de": ["Lammkoteletts", "Wildpastete"],
        "food_pairings_en": ["Lamb chops", "Game pâté"],
        "food_pairings_fr": ["Côtelettes d'agneau", "Pâté de gibier"],
    },
    {
        "name": "Riesling-Silvaner 2022",
        "winery": "Hedinger Weingut & Kellerei",
        "region": "Wilchingen",
        "grape_variety": "Riesling-Silvaner",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Frisch und aromatisch, mit Apfel und Kräutern, der wie ein erstes Erwachen im Frühling das Herz erfrischt.",
        "description_en": "Fresh and aromatic, with apple and herbs, refreshing the heart like the first awakening in spring.",
        "description_fr": "Frais et aromatique, avec de la pomme et des herbes, rafraîchissant le cœur comme le premier réveil au printemps.",
        "food_pairings_de": ["Austern", "Ziegenkäse-Platte"],
        "food_pairings_en": ["Oysters", "Goat cheese platter"],
        "food_pairings_fr": ["Huîtres", "Plateau de fromage de chèvre"],
    },
    {
        "name": "Pinot Noir Classique 2023",
        "winery": "Weingut Baumann",
        "region": "Oberhallau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Sinnlich und legendär, mit Kirsche und Gewürz, der das Herz mit unvergesslicher Tiefe umfängt – ein Geniestreich der Schaffhauser Seele.",
        "description_en": "Sensual and legendary, with cherry and spice, embracing the heart with unforgettable depth – a masterstroke of the Schaffhausen soul.",
        "description_fr": "Sensuel et légendaire, avec de la cerise et des épices, embrassant le cœur avec une profondeur inoubliable.",
        "food_pairings_de": ["Ente", "Pilzragout"],
        "food_pairings_en": ["Duck", "Mushroom ragout"],
        "food_pairings_fr": ["Canard", "Ragoût de champignons"],
    },
    {
        "name": "Malbec 2023",
        "winery": "Hedinger Weingut & Kellerei",
        "region": "Wilchingen",
        "grape_variety": "Malbec",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Opulent und harmonisch, mit Pflaume und Eiche, das wie ein warmer Föhn die Seele streichelt.",
        "description_en": "Opulent and harmonious, with plum and oak, caressing the soul like a warm Föhn wind.",
        "description_fr": "Opulent et harmonieux, avec de la prune et du chêne, caressant l'âme comme un foehn chaud.",
        "food_pairings_de": ["Gegrillter Lachs", "Asiatisches Gemüse"],
        "food_pairings_en": ["Grilled salmon", "Asian vegetables"],
        "food_pairings_fr": ["Saumon grillé", "Légumes asiatiques"],
    },
    {
        "name": "Pinot Noir Pilgrim 2022",
        "winery": "Weingut Höcklistein",
        "region": "Rapperswil-Jona",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Reif und filigran, ein Alter Reben-Traum von Beeren und Erde, der die Seele in nostalgische Wärme hüllt.",
        "description_en": "Mature and delicate, an old vine dream of berries and earth, wrapping the soul in nostalgic warmth.",
        "description_fr": "Mûr et délicat, un rêve de vieilles vignes de baies et de terre, enveloppant l'âme de chaleur nostalgique.",
        "food_pairings_de": ["Roastbeef", "Dunkle Schokolade"],
        "food_pairings_en": ["Roast beef", "Dark chocolate"],
        "food_pairings_fr": ["Rôti de bœuf", "Chocolat noir"],
    },
    {
        "name": "Chardonnay Hedinger 2023",
        "winery": "Hedinger Weingut & Kellerei",
        "region": "Wilchingen",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Cremig und großes Gold, mit Apfel und Haselnuss, der die Seele mit barriquerter Tiefe berührt.",
        "description_en": "Creamy and great gold, with apple and hazelnut, touching the soul with barrel-aged depth.",
        "description_fr": "Crémeux et grand or, avec de la pomme et de la noisette, touchant l'âme avec une profondeur de barrique.",
        "food_pairings_de": ["Krebse", "Frischer Salat"],
        "food_pairings_en": ["Crayfish", "Fresh salad"],
        "food_pairings_fr": ["Écrevisses", "Salade fraîche"],
    },
    {
        "name": "Pinot Noir Klettgau 2023",
        "winery": "Weinbau von Tscharner",
        "region": "Schaffhausen",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Robust und fruchtig, ein Pinot, der das Herz mit wilden Beeren und erdiger Wärme in herbstliche Wälder lockt.",
        "description_en": "Robust and fruity, a Pinot that lures the heart into autumn forests with wild berries and earthy warmth.",
        "description_fr": "Robuste et fruité, un Pinot qui attire le cœur dans les forêts d'automne avec des baies sauvages.",
        "food_pairings_de": ["Lammkoteletts", "Pilzragout"],
        "food_pairings_en": ["Lamb chops", "Mushroom ragout"],
        "food_pairings_fr": ["Côtelettes d'agneau", "Ragoût de champignons"],
    },
    {
        "name": "Pinot Noir Réserve 2023",
        "winery": "Weingut Landolt",
        "region": "Schaffhausen",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Frisch und blumig, ein Rot, das die Seele in goldene Sonnenuntergänge taucht – cremig, mit Nuss und Zitrus.",
        "description_en": "Fresh and floral, a red that immerses the soul in golden sunsets – creamy, with nut and citrus.",
        "description_fr": "Frais et floral, un rouge qui plonge l'âme dans des couchers de soleil dorés – crémeux.",
        "food_pairings_de": ["Huhn mit Kräutern", "Raclette"],
        "food_pairings_en": ["Chicken with herbs", "Raclette"],
        "food_pairings_fr": ["Poulet aux herbes", "Raclette"],
    },
    {
        "name": "Pinot Noir Gian-Battista 2022",
        "winery": "Weingut Donatsch",
        "region": "Klettgau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Einzellagen-Extraklasse, samtig und würzig, ein Rot, das die Seele mit Pfeffer und Beeren in Ekstase versetzt.",
        "description_en": "Single vineyard excellence, velvety and spicy, a red that sends the soul into ecstasy with pepper and berries.",
        "description_fr": "Excellence de parcelle unique, velouté et épicé, un rouge qui envoie l'âme en extase.",
        "food_pairings_de": ["BBQ-Rippen", "Scharfe Wurst"],
        "food_pairings_en": ["BBQ ribs", "Spicy sausage"],
        "food_pairings_fr": ["Côtes BBQ", "Saucisse épicée"],
    },
    {
        "name": "Sauvignon Blanc 2023",
        "winery": "Weingut Baumann",
        "region": "Oberhallau",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Meisterwerk und streng, mit Mandel und Säure, der wie ein Hohelied die Seele erhebt.",
        "description_en": "A masterpiece, austere with almond and acidity, elevating the soul like a song of songs.",
        "description_fr": "Un chef-d'œuvre, austère avec de l'amande et de l'acidité, élevant l'âme comme un cantique.",
        "food_pairings_de": ["Käseplatte", "Gebratenes Forellenfilet"],
        "food_pairings_en": ["Cheese platter", "Pan-fried trout fillet"],
        "food_pairings_fr": ["Plateau de fromages", "Filet de truite poêlé"],
    },
    {
        "name": "Pinot Noir Saliser Grande Selection 2023",
        "winery": "Georg Schlegel",
        "region": "Schaffhausen",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "20/20-Pinot mit enormem Potenzial, fruchtig und robust, der das Herz mit imperierender Kraft erhebt.",
        "description_en": "20/20 Pinot with enormous potential, fruity and robust, elevating the heart with imperial power.",
        "description_fr": "Pinot 20/20 avec un potentiel énorme, fruité et robuste, élevant le cœur avec une puissance impériale.",
        "food_pairings_de": ["Wild", "Pilze"],
        "food_pairings_en": ["Game", "Mushrooms"],
        "food_pairings_fr": ["Gibier", "Champignons"],
    },
    {
        "name": "Riesling 2023",
        "winery": "aagne weingut",
        "region": "Hallau",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Nervös und aromatisch, mit Grapefruit und Kräutern, das wie ein Bergnebel die Seele klärt.",
        "description_en": "Nervous and aromatic, with grapefruit and herbs, clearing the soul like mountain mist.",
        "description_fr": "Nerveux et aromatique, avec du pamplemousse et des herbes, purifiant l'âme comme la brume de montagne.",
        "food_pairings_de": ["Meeresfrüchte", "Sommergemüse"],
        "food_pairings_en": ["Seafood", "Summer vegetables"],
        "food_pairings_fr": ["Fruits de mer", "Légumes d'été"],
    },
    {
        "name": "Pinot Noir Lupa 2022",
        "winery": "Weingut Bad Osterfingen",
        "region": "Osterfingen",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Unvergleichlich trinkbar, mit Kirschen und Geheimnissen, der das Herz mit leichter Freude erheitert.",
        "description_en": "Incomparably drinkable, with cherries and secrets, cheering the heart with light joy.",
        "description_fr": "Incomparablement buvable, avec des cerises et des secrets, égayant le cœur d'une joie légère.",
        "food_pairings_de": ["Pasta Bolognese", "Herzhaftes Brot"],
        "food_pairings_en": ["Pasta Bolognese", "Hearty bread"],
        "food_pairings_fr": ["Pâtes bolognaise", "Pain rustique"],
    },
    {
        "name": "Chardonnay Réserve 2023",
        "winery": "Weingut Ruch",
        "region": "Hallau",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Reich und honigartig, ein Surmaturé, der wie ein Traum die Seele umhüllt.",
        "description_en": "Rich and honeyed, a surmaturé that wraps the soul like a dream.",
        "description_fr": "Riche et miellé, un surmaturé qui enveloppe l'âme comme un rêve.",
        "food_pairings_de": ["Foie gras", "Desserts"],
        "food_pairings_en": ["Foie gras", "Desserts"],
        "food_pairings_fr": ["Foie gras", "Desserts"],
    },
    {
        "name": "Pinot Noir 2024",
        "winery": "Hedinger Weingut & Kellerei",
        "region": "Wilchingen",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Filigran und fruchtig, ein Windhauch aus Kirschen, der das Herz mit alpiner Frische weckt.",
        "description_en": "Delicate and fruity, a breath of cherries that awakens the heart with Alpine freshness.",
        "description_fr": "Délicat et fruité, un souffle de cerises qui éveille le cœur avec la fraîcheur alpine.",
        "food_pairings_de": ["Entenbrust", "Pilze"],
        "food_pairings_en": ["Duck breast", "Mushrooms"],
        "food_pairings_fr": ["Magret de canard", "Champignons"],
    },
    {
        "name": "Müller-Thurgau 2023",
        "winery": "Weingut Baumann",
        "region": "Oberhallau",
        "grape_variety": "Müller-Thurgau",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Exotisch und würzig, mit Apfel und Gewürzen, die wie ein Geheimnis die Seele verzaubern.",
        "description_en": "Exotic and spicy, with apple and spices that enchant the soul like a secret.",
        "description_fr": "Exotique et épicé, avec de la pomme et des épices qui enchantent l'âme comme un secret.",
        "food_pairings_de": ["Asiatische Gerichte", "Gebratener Tofu"],
        "food_pairings_en": ["Asian dishes", "Fried tofu"],
        "food_pairings_fr": ["Plats asiatiques", "Tofu frit"],
    },
    {
        "name": "Pinot Noir Sélection 2023",
        "winery": "Weingut Seewer",
        "region": "Wilchingen",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Tief und mineralisch, mit dunklen Früchten, die wie ein Abgrund die Seele fesselt.",
        "description_en": "Deep and mineral, with dark fruits that captivate the soul like an abyss.",
        "description_fr": "Profond et minéral, avec des fruits noirs qui captivent l'âme comme un abîme.",
        "food_pairings_de": ["Rindfleisch", "Wild"],
        "food_pairings_en": ["Beef", "Game"],
        "food_pairings_fr": ["Bœuf", "Gibier"],
    },
    {
        "name": "Pinot Blanc 2022",
        "winery": "aagne weingut",
        "region": "Hallau",
        "grape_variety": "Pinot Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Zart und blumig, ein Blanc, der die Seele mit schaffhauser Reinheit erfüllt – frisch und nervös.",
        "description_en": "Delicate and floral, a Blanc that fills the soul with Schaffhausen purity – fresh and nervous.",
        "description_fr": "Délicat et floral, un Blanc qui remplit l'âme de pureté schaffhousoise – frais et nerveux.",
        "food_pairings_de": ["Fisch", "Salate"],
        "food_pairings_en": ["Fish", "Salads"],
        "food_pairings_fr": ["Poisson", "Salades"],
    },
    {
        "name": "Pinot Noir Premium 2023",
        "winery": "Weinbau Markus Ruch",
        "region": "Hallau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Samten und fruchtig, ein Pinot, der das Herz mit warmer Umarmung beschenkt.",
        "description_en": "Velvety and fruity, a Pinot that gifts the heart with a warm embrace.",
        "description_fr": "Velouté et fruité, un Pinot qui offre au cœur une étreinte chaleureuse.",
        "food_pairings_de": ["Pasta mit Tomatensauce", "Käse"],
        "food_pairings_en": ["Pasta with tomato sauce", "Cheese"],
        "food_pairings_fr": ["Pâtes à la sauce tomate", "Fromage"],
    },
    {
        "name": "Chardonnay 2024",
        "winery": "Weingut Bad Osterfingen",
        "region": "Osterfingen",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Elegant und strukturiert, mit Apfel und Mineral, das wie ein Tanz die Seele erheitert.",
        "description_en": "Elegant and structured, with apple and mineral, cheering the soul like a dance.",
        "description_fr": "Élégant et structuré, avec de la pomme et du minéral, égayant l'âme comme une danse.",
        "food_pairings_de": ["Huhn mit Kräutern", "Raclette"],
        "food_pairings_en": ["Chicken with herbs", "Raclette"],
        "food_pairings_fr": ["Poulet aux herbes", "Raclette"],
    },
    {
        "name": "Pinot Noir Alte Reben 2022",
        "winery": "Weingut Höcklistein",
        "region": "Rapperswil-Jona",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Würzig und intensiv, ein Rot, das die Seele mit orientalischem Zauber umhüllt.",
        "description_en": "Spicy and intense, a red that wraps the soul in oriental magic.",
        "description_fr": "Épicé et intense, un rouge qui enveloppe l'âme de magie orientale.",
        "food_pairings_de": ["Gewürzhähnchen", "Auberginen"],
        "food_pairings_en": ["Spiced chicken", "Eggplant"],
        "food_pairings_fr": ["Poulet épicé", "Aubergines"],
    },
    {
        "name": "Riesling-Silvaner 2023",
        "winery": "Hedinger Weingut & Kellerei",
        "region": "Wilchingen",
        "grape_variety": "Riesling-Silvaner",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Feminine Eleganz, mit Veilchen und Säure, der das Herz mit Seide und Feuer erobert.",
        "description_en": "Feminine elegance, with violet and acidity, conquering the heart with silk and fire.",
        "description_fr": "Élégance féminine, avec de la violette et de l'acidité, conquérant le cœur avec de la soie et du feu.",
        "food_pairings_de": ["Perlhuhn mit Morcheln"],
        "food_pairings_en": ["Guinea fowl with morels"],
        "food_pairings_fr": ["Pintade aux morilles"],
    },
    {
        "name": "Pinot Noir Klettgauer 2023",
        "winery": "GVS Schachenmann AG",
        "region": "Hallau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Präzise und charaktervoll, ein Neuling der Elite, der die Seele mit erdiger Wärme umfängt.",
        "description_en": "Precise and characterful, a newcomer to the elite, embracing the soul with earthy warmth.",
        "description_fr": "Précis et plein de caractère, un nouveau venu dans l'élite, embrassant l'âme avec une chaleur terreuse.",
        "food_pairings_de": ["Ente", "Pilzrisotto"],
        "food_pairings_en": ["Duck", "Mushroom risotto"],
        "food_pairings_fr": ["Canard", "Risotto aux champignons"],
    },
    {
        "name": "Sauvignon Blanc Réserve 2023",
        "winery": "Weingut Baumann",
        "region": "Oberhallau",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Überraschend und tief, mit Nuss und Zitrus, das wie ein alter Freund die Seele in nostalgische Wärme hüllt.",
        "description_en": "Surprising and deep, with nut and citrus, wrapping the soul in nostalgic warmth like an old friend.",
        "description_fr": "Surprenant et profond, avec de la noix et des agrumes, enveloppant l'âme de chaleur nostalgique.",
        "food_pairings_de": ["Foie gras", "Reifer Käse"],
        "food_pairings_en": ["Foie gras", "Aged cheese"],
        "food_pairings_fr": ["Foie gras", "Fromage affiné"],
    },
    {
        "name": "Pinot Noir Tradition 2024",
        "winery": "aagne weingut",
        "region": "Hallau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Filigran und robust, ein Pinot, der die Seele mit imperierender Kraft erhebt.",
        "description_en": "Delicate yet robust, a Pinot that elevates the soul with imperial power.",
        "description_fr": "Délicat mais robuste, un Pinot qui élève l'âme avec une puissance impériale.",
        "food_pairings_de": ["Lamm", "Pilze"],
        "food_pairings_en": ["Lamb", "Mushrooms"],
        "food_pairings_fr": ["Agneau", "Champignons"],
    },
    {
        "name": "Müller-Thurgau 2024",
        "winery": "Weingut Ruch",
        "region": "Hallau",
        "grape_variety": "Müller-Thurgau",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Frisch und vielschichtig, ein Weiß, der das Herz mit kindlicher Freude weckt.",
        "description_en": "Fresh and multilayered, a white that awakens the heart with childlike joy.",
        "description_fr": "Frais et complexe, un blanc qui éveille le cœur avec une joie enfantine.",
        "food_pairings_de": ["Tapas", "Lachs"],
        "food_pairings_en": ["Tapas", "Salmon"],
        "food_pairings_fr": ["Tapas", "Saumon"],
    },
    {
        "name": "Pinot Noir Harmonie 2023",
        "winery": "Weingut Seewer",
        "region": "Wilchingen",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Dynamisch und harmonisch, ein Neuling, der wie ein Chor die Seele erhebt.",
        "description_en": "Dynamic and harmonious, a newcomer that elevates the soul like a choir.",
        "description_fr": "Dynamique et harmonieux, un nouveau venu qui élève l'âme comme un chœur.",
        "food_pairings_de": ["Dunkles Fleisch"],
        "food_pairings_en": ["Dark meat"],
        "food_pairings_fr": ["Viande brune"],
    },
    {
        "name": "Chardonnay Premium 2023",
        "winery": "Hedinger Weingut & Kellerei",
        "region": "Wilchingen",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Hoch und aromatisch, mit Mandeln und Nektarinen, das die Seele auf Höhenflüge trägt.",
        "description_en": "High and aromatic, with almonds and nectarines, carrying the soul to soaring heights.",
        "description_fr": "Haut et aromatique, avec des amandes et des nectarines, portant l'âme vers les sommets.",
        "food_pairings_de": ["Käseplatte", "Forelle"],
        "food_pairings_en": ["Cheese platter", "Trout"],
        "food_pairings_fr": ["Plateau de fromages", "Truite"],
    },
    {
        "name": "Pinot Noir Barrique 2022",
        "winery": "Weingut Bad Osterfingen",
        "region": "Osterfingen",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Barriqué und tief, ein Pinot, der die Seele in symphonische Tiefe taucht.",
        "description_en": "Barrel-aged and deep, a Pinot that plunges the soul into symphonic depth.",
        "description_fr": "Élevé en barrique et profond, un Pinot qui plonge l'âme dans une profondeur symphonique.",
        "food_pairings_de": ["Ente", "Pilzragout"],
        "food_pairings_en": ["Duck", "Mushroom ragout"],
        "food_pairings_fr": ["Canard", "Ragoût de champignons"],
    },
    {
        "name": "Riesling Premium 2023",
        "winery": "Weinbau Markus Ruch",
        "region": "Hallau",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Opulent und blumig, ein Tropfen, der das Herz mit sommerlicher Leichtigkeit umfängt.",
        "description_en": "Opulent and floral, a drop that embraces the heart with summery lightness.",
        "description_fr": "Opulent et floral, une goutte qui embrasse le cœur avec une légèreté estivale.",
        "food_pairings_de": ["Sommergerichte", "Frischkäse"],
        "food_pairings_en": ["Summer dishes", "Fresh cheese"],
        "food_pairings_fr": ["Plats d'été", "Fromage frais"],
    },
    {
        "name": "Pinot Blanc 2023",
        "winery": "Weingut Höcklistein",
        "region": "Rapperswil-Jona",
        "grape_variety": "Pinot Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Traditionell und rein, ein Tropfen, der das Herz mit Bergfrische reinigt.",
        "description_en": "Traditional and pure, a drop that cleanses the heart with mountain freshness.",
        "description_fr": "Traditionnel et pur, une goutte qui purifie le cœur avec la fraîcheur de la montagne.",
        "food_pairings_de": ["Fischfilet", "Salat"],
        "food_pairings_en": ["Fish fillet", "Salad"],
        "food_pairings_fr": ["Filet de poisson", "Salade"],
    },
    {
        "name": "Sauvignon Blanc 2024",
        "winery": "GVS Schachenmann AG",
        "region": "Hallau",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Exotisch und würzig, ein Weiß, der das Herz mit orientalischem Flair verzaubert.",
        "description_en": "Exotic and spicy, a white that enchants the heart with oriental flair.",
        "description_fr": "Exotique et épicé, un blanc qui enchante le cœur avec un flair oriental.",
        "food_pairings_de": ["Curry", "Vegetarische Gerichte"],
        "food_pairings_en": ["Curry", "Vegetarian dishes"],
        "food_pairings_fr": ["Curry", "Plats végétariens"],
    },
    {
        "name": "Pinot Noir Grand Cru 2023",
        "winery": "Weingut Baumann",
        "region": "Oberhallau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Komplex und harmonisch, ein Assemblage, der die Seele in göttliche Ekstase versetzt.",
        "description_en": "Complex and harmonious, an assemblage that sends the soul into divine ecstasy.",
        "description_fr": "Complexe et harmonieux, un assemblage qui envoie l'âme en extase divine.",
        "food_pairings_de": ["Entrecôte", "Schokolade"],
        "food_pairings_en": ["Entrecôte", "Chocolate"],
        "food_pairings_fr": ["Entrecôte", "Chocolat"],
    },
    {
        "name": "Chardonnay Grand Cru 2022",
        "winery": "aagne weingut",
        "region": "Hallau",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Reich und strukturiert, ein Grand Cru, der die Seele in städtischer Eleganz badet.",
        "description_en": "Rich and structured, a Grand Cru that bathes the soul in urban elegance.",
        "description_fr": "Riche et structuré, un Grand Cru qui baigne l'âme dans l'élégance urbaine.",
        "food_pairings_de": ["Krustentiere", "Geflügel"],
        "food_pairings_en": ["Crustaceans", "Poultry"],
        "food_pairings_fr": ["Crustacés", "Volaille"],
    },
    {
        "name": "Pinot Noir Seeblick 2023",
        "winery": "Weingut Ruch",
        "region": "Hallau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Nervös und lebendig, ein Funke Glycin und Grapefruit, der das Herz mit alpiner Frische weckt.",
        "description_en": "Nervous and lively, a spark of glycine and grapefruit that awakens the heart with Alpine freshness.",
        "description_fr": "Nerveux et vif, une étincelle de glycine et de pamplemousse qui éveille le cœur avec la fraîcheur alpine.",
        "food_pairings_de": ["Krebse", "Kräutersuppe"],
        "food_pairings_en": ["Crayfish", "Herb soup"],
        "food_pairings_fr": ["Écrevisses", "Soupe aux herbes"],
    },
    {
        "name": "Müller-Thurgau Spätlese 2023",
        "winery": "Weingut Seewer",
        "region": "Wilchingen",
        "grape_variety": "Müller-Thurgau",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Tief und aromatisch, ein Rot, das wie ein Abgrund die Seele fesselt.",
        "description_en": "Deep and aromatic, capturing the soul like an abyss.",
        "description_fr": "Profond et aromatique, captivant l'âme comme un abîme.",
        "food_pairings_de": ["Stark gewürzte Fleischgerichte"],
        "food_pairings_en": ["Heavily spiced meat dishes"],
        "food_pairings_fr": ["Plats de viande très épicés"],
    },
    {
        "name": "Pinot Noir Classic 2024",
        "winery": "Hedinger Weingut & Kellerei",
        "region": "Wilchingen",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Historisch und elegant, ein Wein, der die Seele mit zeitloser Tiefe berührt.",
        "description_en": "Historic and elegant, a wine that touches the soul with timeless depth.",
        "description_fr": "Historique et élégant, un vin qui touche l'âme avec une profondeur intemporelle.",
        "food_pairings_de": ["Geflügel", "Meeresfrüchte"],
        "food_pairings_en": ["Poultry", "Seafood"],
        "food_pairings_fr": ["Volaille", "Fruits de mer"],
    },
    {
        "name": "Riesling-Silvaner Premium 2023",
        "winery": "Weingut Bad Osterfingen",
        "region": "Osterfingen",
        "grape_variety": "Riesling-Silvaner",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Filigran und fruchtig, ein Windhauch aus Kirschen, der das Herz mit leichter Traurigkeit und purer Freude erfüllt.",
        "description_en": "Delicate and fruity, a breath of cherries that fills the heart with gentle sadness and pure joy.",
        "description_fr": "Délicat et fruité, un souffle de cerises qui remplit le cœur d'une douce tristesse et d'une joie pure.",
        "food_pairings_de": ["Entenbrust", "Pilze"],
        "food_pairings_en": ["Duck breast", "Mushrooms"],
        "food_pairings_fr": ["Magret de canard", "Champignons"],
    },
    {
        "name": "Pinot Blanc Harmonie 2023",
        "winery": "Weinbau Markus Ruch",
        "region": "Hallau",
        "grape_variety": "Pinot Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Frisch und ausgewogen, ein Blanc, der das Herz mit klassischer Freude erheitert.",
        "description_en": "Fresh and balanced, a Blanc that cheers the heart with classic joy.",
        "description_fr": "Frais et équilibré, un Blanc qui égaye le cœur avec une joie classique.",
        "food_pairings_de": ["Fondue", "Rind"],
        "food_pairings_en": ["Fondue", "Beef"],
        "food_pairings_fr": ["Fondue", "Bœuf"],
    },
    {
        "name": "Chardonnay Vieilles Vignes 2023",
        "winery": "Weingut Höcklistein",
        "region": "Rapperswil-Jona",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Reich und beerig, ein Chardonnay, der die Seele in schaffhauser Wälder entführt.",
        "description_en": "Rich and berry-filled, a Chardonnay that transports the soul to Schaffhausen forests.",
        "description_fr": "Riche et fruité, un Chardonnay qui transporte l'âme dans les forêts schaffhousoises.",
        "food_pairings_de": ["Lammkoteletts", "Käse"],
        "food_pairings_en": ["Lamb chops", "Cheese"],
        "food_pairings_fr": ["Côtelettes d'agneau", "Fromage"],
    },
    {
        "name": "Sauvignon Blanc Premium 2023",
        "winery": "GVS Schachenmann AG",
        "region": "Hallau",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Elegant und pfeffrig, ein Blanc, der die Seele mit orientalischem Zauber umhüllt.",
        "description_en": "Elegant and peppery, a Blanc that wraps the soul in oriental magic.",
        "description_fr": "Élégant et poivré, un Blanc qui enveloppe l'âme de magie orientale.",
        "food_pairings_de": ["Gewürzhähnchen", "Auberginen"],
        "food_pairings_en": ["Spiced chicken", "Eggplant"],
        "food_pairings_fr": ["Poulet épicé", "Aubergines"],
    },
    {
        "name": "Pinot Noir Innovation 2022",
        "winery": "Weingut Baumann",
        "region": "Oberhallau",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Innovativ und fruchtig, ein Hybrid, der das Herz mit moderner Freude erfüllt.",
        "description_en": "Innovative and fruity, a hybrid that fills the heart with modern joy.",
        "description_fr": "Innovant et fruité, un hybride qui remplit le cœur de joie moderne.",
        "food_pairings_de": ["Grillgemüse", "Fisch"],
        "food_pairings_en": ["Grilled vegetables", "Fish"],
        "food_pairings_fr": ["Légumes grillés", "Poisson"],
    },
    {
        "name": "Mousseux Brut 2023",
        "winery": "Rimuss & Strada Wein",
        "region": "Hallau",
        "grape_variety": "Assemblage",
        "wine_color": "schaumwein",
        "price_category": "€€€",
        "description_de": "Hoch und rein, ein Mousseux, der wie ein Gipfelblick die Seele erweitert.",
        "description_en": "High and pure, a Mousseux that expands the soul like a summit view.",
        "description_fr": "Haut et pur, un Mousseux qui élargit l'âme comme une vue du sommet.",
        "food_pairings_de": ["Käseplatte", "Leichte Vorspeisen"],
        "food_pairings_en": ["Cheese platter", "Light appetizers"],
        "food_pairings_fr": ["Plateau de fromages", "Entrées légères"],
    },
]


async def add_schaffhausen_wines():
    """Add the Top 50 Schaffhausen wines to the database"""
    
    mongo_url = os.environ.get("MONGO_URL")
    db_name = os.environ.get("DB_NAME", "wine_sommelier")
    
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    
    print("=" * 60)
    print("🍇 TOP 50 SCHAFFHAUSER WEINE - IMPORT")
    print("   Blauburgunderland am Rhein")
    print("=" * 60)
    print()
    
    added = 0
    skipped = 0
    
    for wine in SCHAFFHAUSEN_WINES:
        # Check if wine already exists
        existing = await db.public_wines.find_one({
            "name": wine["name"],
            "winery": wine["winery"]
        })
        
        if existing:
            print(f"  ⏭️  {wine['name']} ({wine['winery']}) - bereits vorhanden")
            skipped += 1
            continue
        
        wine_doc = {
            "id": str(uuid4()),
            "name": wine["name"],
            "winery": wine["winery"],
            "country": "Schweiz",
            "region": f"Schaffhausen - {wine['region']}",
            "appellation": "AOC Schaffhausen",
            "grape_variety": wine["grape_variety"],
            "wine_color": wine["wine_color"],
            "price_category": wine["price_category"],
            "description_de": wine["description_de"],
            "description_en": wine["description_en"],
            "description_fr": wine["description_fr"],
            "food_pairings_de": wine["food_pairings_de"],
            "food_pairings_en": wine["food_pairings_en"],
            "food_pairings_fr": wine["food_pairings_fr"],
            "created_at": datetime.now(timezone.utc).isoformat(),
            "source": "Top 50 Schaffhauser Weine - Expovina Best-of 2025, Falstaff Weinguide 2025, GaultMillau, Grand Prix du Vin Suisse"
        }
        
        await db.public_wines.insert_one(wine_doc)
        print(f"  ✅ {wine['name']} ({wine['winery']})")
        added += 1
    
    print()
    print("=" * 60)
    print(f"🎉 IMPORT ABGESCHLOSSEN!")
    print(f"   Hinzugefügt: {added}")
    print(f"   Übersprungen: {skipped}")
    print("=" * 60)
    
    # Gesamtzahl prüfen
    total = await db.public_wines.count_documents({})
    swiss = await db.public_wines.count_documents({"country": "Schweiz"})
    schaffhausen = await db.public_wines.count_documents({"region": {"$regex": "Schaffhausen", "$options": "i"}})
    zuerich = await db.public_wines.count_documents({"region": {"$regex": "Zürich", "$options": "i"}})
    neuenburg = await db.public_wines.count_documents({"region": {"$regex": "Neuenburg", "$options": "i"}})
    graubuenden = await db.public_wines.count_documents({"region": {"$regex": "Graubünden", "$options": "i"}})
    genf = await db.public_wines.count_documents({"region": {"$regex": "Genf", "$options": "i"}})
    tessin = await db.public_wines.count_documents({"region": {"$regex": "Tessin", "$options": "i"}})
    waadt = await db.public_wines.count_documents({"region": {"$regex": "Waadt", "$options": "i"}})
    wallis = await db.public_wines.count_documents({"region": {"$regex": "Wallis", "$options": "i"}})
    
    print(f"\n📊 Datenbank-Status:")
    print(f"   Gesamte Weine: {total}")
    print(f"   Schweizer Weine: {swiss}")
    print(f"   - Schaffhausen: {schaffhausen}")
    print(f"   - Zürich: {zuerich}")
    print(f"   - Neuenburg: {neuenburg}")
    print(f"   - Graubünden: {graubuenden}")
    print(f"   - Genf: {genf}")
    print(f"   - Tessin: {tessin}")
    print(f"   - Waadt: {waadt}")
    print(f"   - Wallis: {wallis}")
    print(f"\n   Prost aus dem Blauburgunderland! 🍇🇨🇭")

if __name__ == "__main__":
    asyncio.run(add_schaffhausen_wines())
