#!/usr/bin/env python3
"""
Skript zum Hinzufügen der Top 50 Nahe-Weine zur Datenbank
Mit deutschen, englischen und französischen Beschreibungen

Nahe: Die verborgene Perle der Mineralität und Eleganz
Rieslinge von atemberaubender Präzision
"""

import asyncio
import os
from uuid import uuid4
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

# Die 50 Nahe-Weine mit allen Details
NAHE_WINES = [
    {
        "name": "Oberhäuser Brücke Riesling Spätlese 2024",
        "winery": "Dönnhoff",
        "region": "Oberhausen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Ein legendärer Tropfen von unendlicher Tiefe, Pfirsich, Honig und salziger Mineralität – ein Wein, der die Seele in absolute Perfektion und Nahe-Magie taucht (100 Falstaff-Punkte).",
        "description_en": "A legendary drop of infinite depth, peach, honey and salty minerality – a wine that immerses the soul in absolute perfection and Nahe magic (100 Falstaff points).",
        "description_fr": "Une goutte légendaire de profondeur infinie, pêche, miel et minéralité salée – un vin qui plonge l'âme dans la perfection absolue et la magie de la Nahe (100 points Falstaff).",
        "food_pairings_de": ["Foie gras", "Blauschimmelkäse"],
        "food_pairings_en": ["Foie gras", "Blue cheese"],
        "food_pairings_fr": ["Foie gras", "Fromage bleu"],
    },
    {
        "name": "Dorsheimer Pittermännchen Riesling GG 2024",
        "winery": "Schlossgut Diel",
        "region": "Dorsheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Vulkanisch und präzise, ein Pittermännchen-Juwel von Zitrus und Stein – ein Tropfen, der das Herz mit kraftvoller Eleganz umfängt.",
        "description_en": "Volcanic and precise, a Pittermännchen jewel of citrus and stone – a drop that embraces the heart with powerful elegance.",
        "description_fr": "Volcanique et précis, un joyau de Pittermännchen d'agrumes et de pierre – une goutte qui enlace le cœur d'une élégance puissante.",
        "food_pairings_de": ["Hummer", "Reifer Parmesan"],
        "food_pairings_en": ["Lobster", "Aged Parmesan"],
        "food_pairings_fr": ["Homard", "Parmesan affiné"],
    },
    {
        "name": "Monzinger Frühlingsplätzchen Riesling GG 2024",
        "winery": "Emrich-Schönleber",
        "region": "Monzingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Frühlingsfrisch und mineralisch, ein Frühlingsplätzchen der Leichtigkeit und Tiefe, das die Sinne in Ekstase versetzt.",
        "description_en": "Spring-fresh and mineral, a Frühlingsplätzchen of lightness and depth that sends the senses into ecstasy.",
        "description_fr": "Frais comme le printemps et minéral, un Frühlingsplätzchen de légèreté et de profondeur qui met les sens en extase.",
        "food_pairings_de": ["Gegrillter Fisch", "Milder Ziegenkäse"],
        "food_pairings_en": ["Grilled fish", "Mild goat cheese"],
        "food_pairings_fr": ["Poisson grillé", "Fromage de chèvre doux"],
    },
    {
        "name": "Münsterer Pittersberg Riesling GG 2024",
        "winery": "Kruger-Rumpf",
        "region": "Münster-Sarmsheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Filigran und strahlend, ein Pittersberg-Traum von Apfel und Salz, der die Seele mit jugendlicher Lebendigkeit erfrischt.",
        "description_en": "Delicate and radiant, a Pittersberg dream of apple and salt that refreshes the soul with youthful vivacity.",
        "description_fr": "Délicat et radieux, un rêve de Pittersberg de pomme et de sel qui rafraîchit l'âme avec une vivacité juvénile.",
        "food_pairings_de": ["Meeresfrüchte", "Sommergemüse"],
        "food_pairings_en": ["Seafood", "Summer vegetables"],
        "food_pairings_fr": ["Fruits de mer", "Légumes d'été"],
    },
    {
        "name": "Niederhäuser Hermannshöhle Riesling GG 2024",
        "winery": "Gut Hermannsberg",
        "region": "Niederhausen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Monumental und komplex, ein Hermannshöhle-Monument der Mineralität – ein Wein, der das Herz mit uriger Kraft verzaubert.",
        "description_en": "Monumental and complex, a Hermannshöhle monument of minerality – a wine that enchants the heart with primal power.",
        "description_fr": "Monumental et complexe, un monument de Hermannshöhle de minéralité – un vin qui enchante le cœur avec une puissance primale.",
        "food_pairings_de": ["Lamm", "Pilzrisotto"],
        "food_pairings_en": ["Lamb", "Mushroom risotto"],
        "food_pairings_fr": ["Agneau", "Risotto aux champignons"],
    },
    {
        "name": "Bockenauer Felseneck Riesling GG 2024",
        "winery": "Schäfer-Fröhlich",
        "region": "Bockenau",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Steil und explosiv, ein Felseneck der Intensität und Frische, das die Seele mit moderner Brillanz weckt.",
        "description_en": "Steep and explosive, a Felseneck of intensity and freshness that awakens the soul with modern brilliance.",
        "description_fr": "Raide et explosif, un Felseneck d'intensité et de fraîcheur qui éveille l'âme avec une brillance moderne.",
        "food_pairings_de": ["Asiatisches Curry", "Gereifter Gouda"],
        "food_pairings_en": ["Asian curry", "Aged Gouda"],
        "food_pairings_fr": ["Curry asiatique", "Gouda affiné"],
    },
    {
        "name": "Norheimer Dellchen Riesling GG 2024",
        "winery": "Dönnhoff",
        "region": "Norheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Dellchen-geheimnisvoll und tief, ein Nahe-Juwel der Harmonie.",
        "description_en": "Dellchen-mysterious and deep, a Nahe jewel of harmony.",
        "description_fr": "Dellchen-mystérieux et profond, un joyau de la Nahe d'harmonie.",
        "food_pairings_de": ["Gegrillter Lachs", "Milde Tomme"],
        "food_pairings_en": ["Grilled salmon", "Mild Tomme"],
        "food_pairings_fr": ["Saumon grillé", "Tomme douce"],
    },
    {
        "name": "Monzinger Halenberg Riesling GG 2024",
        "winery": "Emrich-Schönleber",
        "region": "Monzingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Halenberg-kühl und mineralisch, ein Berg der Reinheit.",
        "description_en": "Halenberg-cool and mineral, a mountain of purity.",
        "description_fr": "Halenberg-frais et minéral, une montagne de pureté.",
        "food_pairings_de": ["Forelle", "Salat"],
        "food_pairings_en": ["Trout", "Salad"],
        "food_pairings_fr": ["Truite", "Salade"],
    },
    {
        "name": "Kupfergrube Riesling GG 2024",
        "winery": "Gut Hermannsberg",
        "region": "Niederhausen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Kupfergrube-vulkanisch und rauchig, ein Schatz der Tiefe.",
        "description_en": "Kupfergrube-volcanic and smoky, a treasure of depth.",
        "description_fr": "Kupfergrube-volcanique et fumé, un trésor de profondeur.",
        "food_pairings_de": ["Wild", "Dunkles Fleisch"],
        "food_pairings_en": ["Game", "Dark meat"],
        "food_pairings_fr": ["Gibier", "Viande brune"],
    },
    {
        "name": "Binger Scharlachberg Riesling GG 2024",
        "winery": "Kruger-Rumpf",
        "region": "Bingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Scharlachberg-rot und kraftvoll, ein Feuer der Frucht.",
        "description_en": "Scharlachberg-red and powerful, a fire of fruit.",
        "description_fr": "Scharlachberg-rouge et puissant, un feu de fruit.",
        "food_pairings_de": ["BBQ", "Scharfe Wurst"],
        "food_pairings_en": ["BBQ", "Spicy sausage"],
        "food_pairings_fr": ["BBQ", "Saucisse épicée"],
    },
    {
        "name": "Dorsheimer Burgberg Riesling GG 2024",
        "winery": "Schlossgut Diel",
        "region": "Dorsheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Burgberg-adelig und tief, ein Stück Paradies.",
        "description_en": "Burgberg-noble and deep, a piece of paradise.",
        "description_fr": "Burgberg-noble et profond, un morceau de paradis.",
        "food_pairings_de": ["Ente", "Pilze"],
        "food_pairings_en": ["Duck", "Mushrooms"],
        "food_pairings_fr": ["Canard", "Champignons"],
    },
    {
        "name": "Hermannshöhle Riesling Spätlese 2024",
        "winery": "Dönnhoff",
        "region": "Niederhausen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Spät und verlockend, ein Hermannshöhle der Süße.",
        "description_en": "Late and enticing, a Hermannshöhle of sweetness.",
        "description_fr": "Tardif et séduisant, un Hermannshöhle de douceur.",
        "food_pairings_de": ["Scharfer Thai", "Käse"],
        "food_pairings_en": ["Spicy Thai", "Cheese"],
        "food_pairings_fr": ["Thaï épicé", "Fromage"],
    },
    {
        "name": "Felsenberg Riesling GG 2024",
        "winery": "Schäfer-Fröhlich",
        "region": "Schlossböckelheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Felsenberg-steil und intensiv, ein Fels der Leidenschaft.",
        "description_en": "Felsenberg-steep and intense, a rock of passion.",
        "description_fr": "Felsenberg-raide et intense, un roc de passion.",
        "food_pairings_de": ["Lamm", "Pilze"],
        "food_pairings_en": ["Lamb", "Mushrooms"],
        "food_pairings_fr": ["Agneau", "Champignons"],
    },
    {
        "name": "Halgans Riesling Trocken 2024",
        "winery": "Emrich-Schönleber",
        "region": "Monzingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Halgans-ehrlich und saftig, ein Alltags-Juwel.",
        "description_en": "Halgans-honest and juicy, an everyday jewel.",
        "description_fr": "Halgans-honnête et juteux, un joyau quotidien.",
        "food_pairings_de": ["Fisch", "Fondue"],
        "food_pairings_en": ["Fish", "Fondue"],
        "food_pairings_fr": ["Poisson", "Fondue"],
    },
    {
        "name": "Steinberg Riesling GG 2024",
        "winery": "Gut Hermannsberg",
        "region": "Niederhausen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Steinberg-steinig und präzise, ein Stein der Reinheit.",
        "description_en": "Steinberg-stony and precise, a stone of purity.",
        "description_fr": "Steinberg-pierreux et précis, une pierre de pureté.",
        "food_pairings_de": ["Vegetarisch", "Käse"],
        "food_pairings_en": ["Vegetarian", "Cheese"],
        "food_pairings_fr": ["Végétarien", "Fromage"],
    },
    {
        "name": "Im Pitterberg Riesling Auslese 2023",
        "winery": "Kruger-Rumpf",
        "region": "Münster-Sarmsheim",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Pitterberg-süß und golden, ein Schatz der Konzentration.",
        "description_en": "Pitterberg-sweet and golden, a treasure of concentration.",
        "description_fr": "Pitterberg-doux et doré, un trésor de concentration.",
        "food_pairings_de": ["Desserts"],
        "food_pairings_en": ["Desserts"],
        "food_pairings_fr": ["Desserts"],
    },
    {
        "name": "Kreuznacher Krötenpfuhl Riesling GG 2024",
        "winery": "Dönnhoff",
        "region": "Kreuznach",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Krötenpfuhl-geheimnisvoll und mineralisch.",
        "description_en": "Krötenpfuhl-mysterious and mineral.",
        "description_fr": "Krötenpfuhl-mystérieux et minéral.",
        "food_pairings_de": ["Geflügel"],
        "food_pairings_en": ["Poultry"],
        "food_pairings_fr": ["Volaille"],
    },
    {
        "name": "Goldloch Riesling GG 2024",
        "winery": "Schlossgut Diel",
        "region": "Dorsheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Goldloch-golden und tief, ein Loch der Wunder.",
        "description_en": "Goldloch-golden and deep, a hole of wonders.",
        "description_fr": "Goldloch-doré et profond, un trou de merveilles.",
        "food_pairings_de": ["Roastbeef"],
        "food_pairings_en": ["Roast beef"],
        "food_pairings_fr": ["Rosbif"],
    },
    {
        "name": "Stromberg Riesling GG 2024",
        "winery": "Schäfer-Fröhlich",
        "region": "Bockenau",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Stromberg-kraftvoll und langlebig, ein Strom der Energie.",
        "description_en": "Stromberg-powerful and long-lived, a stream of energy.",
        "description_fr": "Stromberg-puissant et longévif, un courant d'énergie.",
        "food_pairings_de": ["Rind"],
        "food_pairings_en": ["Beef"],
        "food_pairings_fr": ["Bœuf"],
    },
    {
        "name": "Mineral Riesling Trocken 2024",
        "winery": "Emrich-Schönleber",
        "region": "Monzingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Mineral-pur und trocken, ein Nahe-Klassiker.",
        "description_en": "Mineral-pure and dry, a Nahe classic.",
        "description_fr": "Mineral-pur et sec, un classique de la Nahe.",
        "food_pairings_de": ["Salat", "Aperitif"],
        "food_pairings_en": ["Salad", "Aperitif"],
        "food_pairings_fr": ["Salade", "Apéritif"],
    },
    {
        "name": "Rotenberg Riesling GG 2024",
        "winery": "Gut Hermannsberg",
        "region": "Niederhausen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Rotenberg-rot und vulkanisch.",
        "description_en": "Rotenberg-red and volcanic.",
        "description_fr": "Rotenberg-rouge et volcanique.",
        "food_pairings_de": ["Wild"],
        "food_pairings_en": ["Game"],
        "food_pairings_fr": ["Gibier"],
    },
    {
        "name": "Dautenpflänzer Riesling GG 2024",
        "winery": "Kruger-Rumpf",
        "region": "Münster-Sarmsheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Dautenpflänzer-fruchtig und tief.",
        "description_en": "Dautenpflänzer-fruity and deep.",
        "description_fr": "Dautenpflänzer-fruité et profond.",
        "food_pairings_de": ["Pilze"],
        "food_pairings_en": ["Mushrooms"],
        "food_pairings_fr": ["Champignons"],
    },
    {
        "name": "Tonschiefer Riesling Trocken 2024",
        "winery": "Dönnhoff",
        "region": "Oberhausen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Tonschiefer-mineralisch und sauber.",
        "description_en": "Tonschiefer-mineral and clean.",
        "description_fr": "Tonschiefer-minéral et propre.",
        "food_pairings_de": ["Fisch"],
        "food_pairings_en": ["Fish"],
        "food_pairings_fr": ["Poisson"],
    },
    {
        "name": "Halenberg Riesling Auslese 2023",
        "winery": "Schäfer-Fröhlich",
        "region": "Monzingen",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Halenberg-süß und intensiv.",
        "description_en": "Halenberg-sweet and intense.",
        "description_fr": "Halenberg-doux et intense.",
        "food_pairings_de": ["Foie gras"],
        "food_pairings_en": ["Foie gras"],
        "food_pairings_fr": ["Foie gras"],
    },
    {
        "name": "Caroline Riesling Spätlese 2024",
        "winery": "Schlossgut Diel",
        "region": "Dorsheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Caroline-zart und verlockend.",
        "description_en": "Caroline-delicate and enticing.",
        "description_fr": "Caroline-délicat et séduisant.",
        "food_pairings_de": ["Desserts"],
        "food_pairings_en": ["Desserts"],
        "food_pairings_fr": ["Desserts"],
    },
    {
        "name": "Frühlingsplätzchen Riesling Auslese 2023",
        "winery": "Emrich-Schönleber",
        "region": "Monzingen",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Frühlingsplätzchen-golden und frisch.",
        "description_en": "Frühlingsplätzchen-golden and fresh.",
        "description_fr": "Frühlingsplätzchen-doré et frais.",
        "food_pairings_de": ["Blauschimmel"],
        "food_pairings_en": ["Blue cheese"],
        "food_pairings_fr": ["Bleu"],
    },
    {
        "name": "Vom Vulkan Riesling Trocken 2024",
        "winery": "Gut Hermannsberg",
        "region": "Niederhausen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Vom Vulkan-rauchig und kraftvoll.",
        "description_en": "Vom Vulkan-smoky and powerful.",
        "description_fr": "Vom Vulkan-fumé et puissant.",
        "food_pairings_de": ["Lamm"],
        "food_pairings_en": ["Lamb"],
        "food_pairings_fr": ["Agneau"],
    },
    {
        "name": "Rheinberg Riesling GG 2024",
        "winery": "Kruger-Rumpf",
        "region": "Bingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Rheinberg-flüssig und elegant.",
        "description_en": "Rheinberg-fluid and elegant.",
        "description_fr": "Rheinberg-fluide et élégant.",
        "food_pairings_de": ["Krustentiere"],
        "food_pairings_en": ["Crustaceans"],
        "food_pairings_fr": ["Crustacés"],
    },
    {
        "name": "Roxheimer Höllenpfad Riesling GG 2024",
        "winery": "Dönnhoff",
        "region": "Roxheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Höllenpfad-feurig und tief.",
        "description_en": "Höllenpfad-fiery and deep.",
        "description_fr": "Höllenpfad-fougueux et profond.",
        "food_pairings_de": ["Asiatisch"],
        "food_pairings_en": ["Asian cuisine"],
        "food_pairings_fr": ["Cuisine asiatique"],
    },
    {
        "name": "Vulkangestein Riesling Trocken 2024",
        "winery": "Schäfer-Fröhlich",
        "region": "Bockenau",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Vulkangestein-wild und mineralisch.",
        "description_en": "Vulkangestein-wild and mineral.",
        "description_fr": "Vulkangestein-sauvage et minéral.",
        "food_pairings_de": ["Gemüse"],
        "food_pairings_en": ["Vegetables"],
        "food_pairings_fr": ["Légumes"],
    },
    {
        "name": "Pittermännchen Riesling Auslese 2023",
        "winery": "Schlossgut Diel",
        "region": "Dorsheim",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Pittermännchen-süß und geheimnisvoll.",
        "description_en": "Pittermännchen-sweet and mysterious.",
        "description_fr": "Pittermännchen-doux et mystérieux.",
        "food_pairings_de": ["Käseplatte"],
        "food_pairings_en": ["Cheese platter"],
        "food_pairings_fr": ["Plateau de fromages"],
    },
    {
        "name": "Enkircher Riesling GG 2024",
        "winery": "Emrich-Schönleber",
        "region": "Monzingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Enkircher-historisch und tief.",
        "description_en": "Enkircher-historic and deep.",
        "description_fr": "Enkircher-historique et profond.",
        "food_pairings_de": ["Parmesan"],
        "food_pairings_en": ["Parmesan"],
        "food_pairings_fr": ["Parmesan"],
    },
    {
        "name": "Justus Riesling Trocken 2024",
        "winery": "Gut Hermannsberg",
        "region": "Niederhausen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Justus-gerecht und ausgewogen.",
        "description_en": "Justus-fair and balanced.",
        "description_fr": "Justus-juste et équilibré.",
        "food_pairings_de": ["Geflügel"],
        "food_pairings_en": ["Poultry"],
        "food_pairings_fr": ["Volaille"],
    },
    {
        "name": "Kapellenberg Riesling GG 2024",
        "winery": "Kruger-Rumpf",
        "region": "Münster-Sarmsheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Kapellenberg-kirchenwürdig und mineralisch.",
        "description_en": "Kapellenberg-church-worthy and mineral.",
        "description_fr": "Kapellenberg-digne d'une église et minéral.",
        "food_pairings_de": ["Forelle"],
        "food_pairings_en": ["Trout"],
        "food_pairings_fr": ["Truite"],
    },
    {
        "name": "Leistenberg Riesling Kabinett 2024",
        "winery": "Dönnhoff",
        "region": "Oberhausen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Leistenberg-leicht und tänzerisch.",
        "description_en": "Leistenberg-light and dancing.",
        "description_fr": "Leistenberg-léger et dansant.",
        "food_pairings_de": ["Aperitif"],
        "food_pairings_en": ["Aperitif"],
        "food_pairings_fr": ["Apéritif"],
    },
    {
        "name": "Felseneck Riesling Auslese 2023",
        "winery": "Schäfer-Fröhlich",
        "region": "Bockenau",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Felseneck-süß und konzentriert.",
        "description_en": "Felseneck-sweet and concentrated.",
        "description_fr": "Felseneck-doux et concentré.",
        "food_pairings_de": ["Desserts"],
        "food_pairings_en": ["Desserts"],
        "food_pairings_fr": ["Desserts"],
    },
    {
        "name": "Burgberg Riesling Spätlese 2024",
        "winery": "Schlossgut Diel",
        "region": "Dorsheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Burgberg-spät und edel.",
        "description_en": "Burgberg-late and noble.",
        "description_fr": "Burgberg-tardif et noble.",
        "food_pairings_de": ["Scharfer Thai"],
        "food_pairings_en": ["Spicy Thai"],
        "food_pairings_fr": ["Thaï épicé"],
    },
    {
        "name": "Mineral Riesling Auslese 2023",
        "winery": "Emrich-Schönleber",
        "region": "Monzingen",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Mineral-süß und rein.",
        "description_en": "Mineral-sweet and pure.",
        "description_fr": "Mineral-doux et pur.",
        "food_pairings_de": ["Blauschimmel"],
        "food_pairings_en": ["Blue cheese"],
        "food_pairings_fr": ["Bleu"],
    },
    {
        "name": "Kupfergrube Riesling Auslese 2023",
        "winery": "Gut Hermannsberg",
        "region": "Niederhausen",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Kupfergrube-golden und rauchig.",
        "description_en": "Kupfergrube-golden and smoky.",
        "description_fr": "Kupfergrube-doré et fumé.",
        "food_pairings_de": ["Foie gras"],
        "food_pairings_en": ["Foie gras"],
        "food_pairings_fr": ["Foie gras"],
    },
    {
        "name": "Im Pitterberg Riesling Spätlese 2024",
        "winery": "Kruger-Rumpf",
        "region": "Münster-Sarmsheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Im Pitterberg-verlockend und fruchtig.",
        "description_en": "Im Pitterberg-enticing and fruity.",
        "description_fr": "Im Pitterberg-séduisant et fruité.",
        "food_pairings_de": ["Käse"],
        "food_pairings_en": ["Cheese"],
        "food_pairings_fr": ["Fromage"],
    },
    {
        "name": "Schlossböckelheimer Kupfergrube Riesling GG 2024",
        "winery": "Dönnhoff",
        "region": "Schlossböckelheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Kupfergrube-kraftvoll und tief.",
        "description_en": "Kupfergrube-powerful and deep.",
        "description_fr": "Kupfergrube-puissant et profond.",
        "food_pairings_de": ["Wild"],
        "food_pairings_en": ["Game"],
        "food_pairings_fr": ["Gibier"],
    },
    {
        "name": "Bockenauer Riesling Trocken 2024",
        "winery": "Schäfer-Fröhlich",
        "region": "Bockenau",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Bockenauer-sauber und lebendig.",
        "description_en": "Bockenauer-clean and lively.",
        "description_fr": "Bockenauer-propre et vivant.",
        "food_pairings_de": ["Salat"],
        "food_pairings_en": ["Salad"],
        "food_pairings_fr": ["Salade"],
    },
    {
        "name": "Nahesteiner Riesling Trocken 2024",
        "winery": "Schlossgut Diel",
        "region": "Dorsheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Nahesteiner-ehrlich und mineralisch.",
        "description_en": "Nahesteiner-honest and mineral.",
        "description_fr": "Nahesteiner-honnête et minéral.",
        "food_pairings_de": ["Fisch"],
        "food_pairings_en": ["Fish"],
        "food_pairings_fr": ["Poisson"],
    },
    {
        "name": "Halgans Riesling Spätlese 2024",
        "winery": "Emrich-Schönleber",
        "region": "Monzingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Halgans-spät und harmonisch.",
        "description_en": "Halgans-late and harmonious.",
        "description_fr": "Halgans-tardif et harmonieux.",
        "food_pairings_de": ["Asiatisch"],
        "food_pairings_en": ["Asian cuisine"],
        "food_pairings_fr": ["Cuisine asiatique"],
    },
    {
        "name": "Rotenberg Riesling Auslese 2023",
        "winery": "Gut Hermannsberg",
        "region": "Niederhausen",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Rotenberg-süß und vulkanisch.",
        "description_en": "Rotenberg-sweet and volcanic.",
        "description_fr": "Rotenberg-doux et volcanique.",
        "food_pairings_de": ["Desserts"],
        "food_pairings_en": ["Desserts"],
        "food_pairings_fr": ["Desserts"],
    },
    {
        "name": "Scharlachberg Riesling Spätlese 2024",
        "winery": "Kruger-Rumpf",
        "region": "Bingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Scharlachberg-verlockend und rot.",
        "description_en": "Scharlachberg-enticing and red.",
        "description_fr": "Scharlachberg-séduisant et rouge.",
        "food_pairings_de": ["Käseplatte"],
        "food_pairings_en": ["Cheese platter"],
        "food_pairings_fr": ["Plateau de fromages"],
    },
    {
        "name": "Kreuznacher Kahlenberg Riesling Trocken 2024",
        "winery": "Dönnhoff",
        "region": "Kreuznach",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Kahlenberg-trocken und strahlend.",
        "description_en": "Kahlenberg-dry and radiant.",
        "description_fr": "Kahlenberg-sec et radieux.",
        "food_pairings_de": ["Geflügel"],
        "food_pairings_en": ["Poultry"],
        "food_pairings_fr": ["Volaille"],
    },
    {
        "name": "Stromberg Riesling Auslese 2023",
        "winery": "Schäfer-Fröhlich",
        "region": "Bockenau",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Stromberg-konzentriert und tief.",
        "description_en": "Stromberg-concentrated and deep.",
        "description_fr": "Stromberg-concentré et profond.",
        "food_pairings_de": ["Blauschimmel"],
        "food_pairings_en": ["Blue cheese"],
        "food_pairings_fr": ["Bleu"],
    },
    {
        "name": "Goldloch Riesling Auslese 2023",
        "winery": "Schlossgut Diel",
        "region": "Dorsheim",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Goldloch-golden und geheimnisvoll.",
        "description_en": "Goldloch-golden and mysterious.",
        "description_fr": "Goldloch-doré et mystérieux.",
        "food_pairings_de": ["Foie gras"],
        "food_pairings_en": ["Foie gras"],
        "food_pairings_fr": ["Foie gras"],
    },
    {
        "name": "Monzinger Halenberg Riesling Auslese 2023",
        "winery": "Emrich-Schönleber",
        "region": "Monzingen",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Halenberg-harmonisch und golden, ein Abschluss der Nahe-Mineralität.",
        "description_en": "Halenberg-harmonious and golden, a finale of Nahe minerality.",
        "description_fr": "Halenberg-harmonieux et doré, un final de la minéralité de la Nahe.",
        "food_pairings_de": ["Leichte Desserts", "Milder Käse"],
        "food_pairings_en": ["Light desserts", "Mild cheese"],
        "food_pairings_fr": ["Desserts légers", "Fromage doux"],
    },
]


async def add_nahe_wines():
    """Fügt die Nahe-Weine zur Datenbank hinzu"""
    
    mongo_url = os.environ.get('MONGO_URL', 'mongodb://localhost:27017')
    db_name = os.environ.get('DB_NAME', 'test_database')
    
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    
    print("=" * 60)
    print("🍷 NAHE-WEINE HINZUFÜGEN")
    print("   Die verborgene Perle der Mineralität")
    print("=" * 60)
    print(f"📊 Anzahl Weine: {len(NAHE_WINES)}")
    print()
    
    # Prüfe bestehende Weine
    existing = await db.public_wines.count_documents({"region": {"$regex": "^Nahe"}})
    print(f"📋 Bestehende Nahe-Weine: {existing}")
    
    added = 0
    skipped = 0
    
    for wine_data in NAHE_WINES:
        # Prüfe ob der Wein schon existiert
        exists = await db.public_wines.find_one({
            "name": wine_data["name"],
            "winery": wine_data["winery"]
        })
        
        if exists:
            print(f"⏭️  Übersprungen (existiert): {wine_data['name']}")
            skipped += 1
            continue
        
        # Erstelle den Wein-Eintrag
        wine = {
            "id": str(uuid4()),
            "name": wine_data["name"],
            "winery": wine_data["winery"],
            "country": "Deutschland",
            "region": f"Nahe - {wine_data['region']}",
            "appellation": "Nahe",
            "grape_variety": wine_data["grape_variety"],
            "wine_color": wine_data["wine_color"],
            "year": None,
            "description_de": wine_data["description_de"],
            "description_en": wine_data["description_en"],
            "description_fr": wine_data["description_fr"],
            "tasting_notes": None,
            "food_pairings_de": wine_data["food_pairings_de"],
            "food_pairings_en": wine_data["food_pairings_en"],
            "food_pairings_fr": wine_data["food_pairings_fr"],
            "alcohol_content": None,
            "price_category": wine_data["price_category"],
            "image_url": None,
            "rating": None,
            "created_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
        }
        
        await db.public_wines.insert_one(wine)
        print(f"✅ Hinzugefügt: {wine_data['name']} ({wine_data['winery']})")
        added += 1
    
    print()
    print("=" * 60)
    print(f"🎉 FERTIG! {added} Weine hinzugefügt, {skipped} übersprungen")
    print("=" * 60)
    
    # Zeige Gesamtzahl
    total = await db.public_wines.count_documents({})
    nahe_total = await db.public_wines.count_documents({"region": {"$regex": "^Nahe"}})
    print(f"\n📊 Gesamtzahl Weine in DB: {total}")
    print(f"📊 Davon Nahe-Weine: {nahe_total}")
    
    client.close()


if __name__ == "__main__":
    asyncio.run(add_nahe_wines())
