#!/usr/bin/env python3
"""
Skript zum Hinzufügen der Top 50 Pfalz-Weine zur Datenbank
Mit deutschen, englischen und französischen Beschreibungen

Pfalz: Die sonnige Seele des Südens
Paradies der Vielfalt mit mediterraner Wärme
"""

import asyncio
import os
from uuid import uuid4
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

# Die 50 Pfalz-Weine mit allen Details
PFALZ_WINES = [
    {
        "name": "Im Sonnenschein Riesling GG 2024",
        "winery": "Ökonomierat Rebholz",
        "region": "Siebeldingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Ein strahlendes Meisterwerk von Pfirsich, Kräutern und salziger Mineralität – ein Wein, der die Seele in pure, sonnendurchflutete Freiheit taucht (100 Falstaff-Punkte).",
        "description_en": "A radiant masterpiece of peach, herbs and salty minerality – a wine that immerses the soul in pure, sun-drenched freedom (100 Falstaff points).",
        "description_fr": "Un chef-d'œuvre radieux de pêche, d'herbes et de minéralité salée – un vin qui plonge l'âme dans une liberté pure et ensoleillée (100 points Falstaff).",
        "food_pairings_de": ["Gegrillter Zander", "Milder Ziegenkäse"],
        "food_pairings_en": ["Grilled pike-perch", "Mild goat cheese"],
        "food_pairings_fr": ["Sandre grillé", "Fromage de chèvre doux"],
    },
    {
        "name": "Forster Pechstein Riesling GG 2024",
        "winery": "Bürklin-Wolf",
        "region": "Deidesheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Tief und vulkanisch, ein Pechstein-Monument von Rauch, Zitrus und unendlicher Länge – ein Tropfen, der das Herz mit biodynamischer Kraft erobert.",
        "description_en": "Deep and volcanic, a Pechstein monument of smoke, citrus and endless length – a drop that conquers the heart with biodynamic power.",
        "description_fr": "Profond et volcanique, un monument de Pechstein de fumée, d'agrumes et de longueur infinie – une goutte qui conquiert le cœur avec une force biodynamique.",
        "food_pairings_de": ["Hummer", "Reifer Parmesan"],
        "food_pairings_en": ["Lobster", "Aged Parmesan"],
        "food_pairings_fr": ["Homard", "Parmesan affiné"],
    },
    {
        "name": "Idig Riesling GG 2024",
        "winery": "A. Christmann",
        "region": "Gimmeldingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Königlich und präzise, ein Idig der absoluten Perfektion, der die Seele mit salziger Tiefe und Frucht verzaubert.",
        "description_en": "Royal and precise, an Idig of absolute perfection that enchants the soul with salty depth and fruit.",
        "description_fr": "Royal et précis, un Idig de perfection absolue qui enchante l'âme avec une profondeur salée et du fruit.",
        "food_pairings_de": ["Asiatisches Curry", "Gereifter Gouda"],
        "food_pairings_en": ["Asian curry", "Aged Gouda"],
        "food_pairings_fr": ["Curry asiatique", "Gouda affiné"],
    },
    {
        "name": "Forster Jesuitengarten Riesling GG 2024",
        "winery": "Bassermann-Jordan",
        "region": "Deidesheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Historisch und edel, ein Jesuitengarten-Juwel von Pfirsich und Stein – ein Wein, der das Herz mit aristokratischer Harmonie umfängt.",
        "description_en": "Historic and noble, a Jesuitengarten jewel of peach and stone – a wine that embraces the heart with aristocratic harmony.",
        "description_fr": "Historique et noble, un joyau de Jesuitengarten de pêche et de pierre – un vin qui enlace le cœur d'une harmonie aristocratique.",
        "food_pairings_de": ["Gegrillter Lachs", "Milde Tomme"],
        "food_pairings_en": ["Grilled salmon", "Mild Tomme"],
        "food_pairings_fr": ["Saumon grillé", "Tomme douce"],
    },
    {
        "name": "Deidesheimer Grainhübel Riesling GG 2024",
        "winery": "Von Winning",
        "region": "Deidesheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Explosiv und mineralisch, ein Grainhübel-Feuerwerk von Zitrus und Salz, das die Sinne in Ekstase versetzt.",
        "description_en": "Explosive and mineral, a Grainhübel firework of citrus and salt that sends the senses into ecstasy.",
        "description_fr": "Explosif et minéral, un feu d'artifice de Grainhübel d'agrumes et de sel qui met les sens en extase.",
        "food_pairings_de": ["Meeresfrüchte", "Sommergemüse"],
        "food_pairings_en": ["Seafood", "Summer vegetables"],
        "food_pairings_fr": ["Fruits de mer", "Légumes d'été"],
    },
    {
        "name": "Forster Ungeheuer Riesling GG 2024",
        "winery": "Acham-Magin",
        "region": "Forst",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Mythisch und kraftvoll, ein Ungeheuer der Frucht und Mineralität, das die Seele mit wilder Schönheit bezwingt.",
        "description_en": "Mythical and powerful, a Monster of fruit and minerality that conquers the soul with wild beauty.",
        "description_fr": "Mythique et puissant, un Monstre de fruit et de minéralité qui conquiert l'âme avec une beauté sauvage.",
        "food_pairings_de": ["Lamm", "Pilzrisotto"],
        "food_pairings_en": ["Lamb", "Mushroom risotto"],
        "food_pairings_fr": ["Agneau", "Risotto aux champignons"],
    },
    {
        "name": "Kastanienbusch Riesling GG R 2023",
        "winery": "Ökonomierat Rebholz",
        "region": "Siebeldingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Rotboden-Legende, tief und komplex, ein Kastanienbusch der Ewigkeit – ein Wein, der das Herz mit roter Erde und Feuer berührt.",
        "description_en": "Red soil legend, deep and complex, a Kastanienbusch of eternity – a wine that touches the heart with red earth and fire.",
        "description_fr": "Légende de sol rouge, profond et complexe, un Kastanienbusch d'éternité – un vin qui touche le cœur avec de la terre rouge et du feu.",
        "food_pairings_de": ["Wild", "Dunkles Fleisch"],
        "food_pairings_en": ["Game", "Dark meat"],
        "food_pairings_fr": ["Gibier", "Viande brune"],
    },
    {
        "name": "Kastanienbusch Spätburgunder GG 2024",
        "winery": "Dr. Wehrheim",
        "region": "Birkweiler",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Samten und würzig, ein roter Traum von Kirsche und Gewürz – der König der Pfälzer Roten.",
        "description_en": "Velvety and spicy, a red dream of cherry and spice – the king of Palatinate reds.",
        "description_fr": "Velouté et épicé, un rêve rouge de cerise et d'épices – le roi des rouges du Palatinat.",
        "food_pairings_de": ["Rehrücken", "Schokolade"],
        "food_pairings_en": ["Saddle of venison", "Chocolate"],
        "food_pairings_fr": ["Selle de chevreuil", "Chocolat"],
    },
    {
        "name": "Forster Kirchenstück Riesling GG 2024",
        "winery": "Von Buhl",
        "region": "Forst",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Kirchenwürdig und strahlend, ein Kirchenstück der Noblesse, das die Seele in göttliche Harmonie taucht.",
        "description_en": "Church-worthy and radiant, a Kirchenstück of nobility that immerses the soul in divine harmony.",
        "description_fr": "Digne d'une église et radieux, un Kirchenstück de noblesse qui plonge l'âme dans une harmonie divine.",
        "food_pairings_de": ["Forelle", "Salat"],
        "food_pairings_en": ["Trout", "Salad"],
        "food_pairings_fr": ["Truite", "Salade"],
    },
    {
        "name": "Laumersheimer Kirschgarten Riesling GG 2024",
        "winery": "Philipp Kuhn",
        "region": "Laumersheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Aufstrebend und präzise, ein Kirschgarten der Frische und Tiefe, der das Herz mit moderner Eleganz weckt.",
        "description_en": "Rising and precise, a Kirschgarten of freshness and depth that awakens the heart with modern elegance.",
        "description_fr": "Montant et précis, un Kirschgarten de fraîcheur et de profondeur qui éveille le cœur avec une élégance moderne.",
        "food_pairings_de": ["Vegetarisch", "Käse"],
        "food_pairings_en": ["Vegetarian", "Cheese"],
        "food_pairings_fr": ["Végétarien", "Fromage"],
    },
    {
        "name": "Deidesheimer Hohenmorgen Riesling GG 2024",
        "winery": "Bassermann-Jordan",
        "region": "Deidesheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Hohenmorgen-adelig und tief, ein Stück Paradies in flüssiger Form.",
        "description_en": "Hohenmorgen-noble and deep, a piece of paradise in liquid form.",
        "description_fr": "Hohenmorgen-noble et profond, un morceau de paradis sous forme liquide.",
        "food_pairings_de": ["Ente", "Pilze"],
        "food_pairings_en": ["Duck", "Mushrooms"],
        "food_pairings_fr": ["Canard", "Champignons"],
    },
    {
        "name": "Sauvignon Blanc S 2024",
        "winery": "Ökonomierat Rebholz",
        "region": "Siebeldingen",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Exotisch und intensiv, ein Sauvignon der Weltklasse, der die Seele mit Stachelbeere und Feuer entzündet.",
        "description_en": "Exotic and intense, a world-class Sauvignon that ignites the soul with gooseberry and fire.",
        "description_fr": "Exotique et intense, un Sauvignon de classe mondiale qui enflamme l'âme avec de la groseille et du feu.",
        "food_pairings_de": ["Ziegenkäse", "Asiatisch"],
        "food_pairings_en": ["Goat cheese", "Asian cuisine"],
        "food_pairings_fr": ["Fromage de chèvre", "Cuisine asiatique"],
    },
    {
        "name": "Kirschgarten Spätburgunder GG 2024",
        "winery": "Knipser",
        "region": "Laumersheim",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Rot und leidenschaftlich, ein Kirschgarten der Reife und Samtigkeit.",
        "description_en": "Red and passionate, a Kirschgarten of maturity and velvetiness.",
        "description_fr": "Rouge et passionné, un Kirschgarten de maturité et de velouté.",
        "food_pairings_de": ["Roastbeef", "BBQ"],
        "food_pairings_en": ["Roast beef", "BBQ"],
        "food_pairings_fr": ["Rosbif", "BBQ"],
    },
    {
        "name": "Forster Freundstück Riesling GG 2024",
        "winery": "Bürklin-Wolf",
        "region": "Forst",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Freundschaftlich und tief, ein Freundstück der Harmonie.",
        "description_en": "Friendly and deep, a Freundstück of harmony.",
        "description_fr": "Amical et profond, un Freundstück d'harmonie.",
        "food_pairings_de": ["Geflügel", "Gemüse"],
        "food_pairings_en": ["Poultry", "Vegetables"],
        "food_pairings_fr": ["Volaille", "Légumes"],
    },
    {
        "name": "Forster Elster Riesling GG 2024",
        "winery": "Acham-Magin",
        "region": "Forst",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Elster-lebendig und mineralisch, ein Flug der Frische.",
        "description_en": "Elster-lively and mineral, a flight of freshness.",
        "description_fr": "Elster-vif et minéral, un vol de fraîcheur.",
        "food_pairings_de": ["Meeresfrüchte"],
        "food_pairings_en": ["Seafood"],
        "food_pairings_fr": ["Fruits de mer"],
    },
    {
        "name": "Pechstein Riesling GG 2024",
        "winery": "Von Winning",
        "region": "Deidesheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Vulkanisch und rauchig, ein Pechstein der Intensität.",
        "description_en": "Volcanic and smoky, a Pechstein of intensity.",
        "description_fr": "Volcanique et fumé, un Pechstein d'intensité.",
        "food_pairings_de": ["Scharfer Thai", "Käse"],
        "food_pairings_en": ["Spicy Thai", "Cheese"],
        "food_pairings_fr": ["Thaï épicé", "Fromage"],
    },
    {
        "name": "Im Sonnenschein Weißburgunder GG 2024",
        "winery": "Ökonomierat Rebholz",
        "region": "Siebeldingen",
        "grape_variety": "Weißburgunder",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Weiß und cremig, ein Sonnenschein der Eleganz.",
        "description_en": "White and creamy, a Sonnenschein of elegance.",
        "description_fr": "Blanc et crémeux, un Sonnenschein d'élégance.",
        "food_pairings_de": ["Gegrilltes Huhn"],
        "food_pairings_en": ["Grilled chicken"],
        "food_pairings_fr": ["Poulet grillé"],
    },
    {
        "name": "Gimmeldinger Mandelgarten Riesling GG 2024",
        "winery": "A. Christmann",
        "region": "Gimmeldingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Mandelgarten-duftend und filigran, ein Garten der Poesie.",
        "description_en": "Mandelgarten-fragrant and delicate, a garden of poetry.",
        "description_fr": "Mandelgarten-parfumé et délicat, un jardin de poésie.",
        "food_pairings_de": ["Salat", "Fisch"],
        "food_pairings_en": ["Salad", "Fish"],
        "food_pairings_fr": ["Salade", "Poisson"],
    },
    {
        "name": "Kallstadter Saumagen Riesling GG 2024",
        "winery": "Koehler-Ruprecht",
        "region": "Kallstadt",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Saumagen-kraftvoll und langlebig, ein Klassiker der Tradition.",
        "description_en": "Saumagen-powerful and long-lived, a classic of tradition.",
        "description_fr": "Saumagen-puissant et longévif, un classique de la tradition.",
        "food_pairings_de": ["Schwein", "Fondue"],
        "food_pairings_en": ["Pork", "Fondue"],
        "food_pairings_fr": ["Porc", "Fondue"],
    },
    {
        "name": "Cuvée X Rot 2023",
        "winery": "Knipser",
        "region": "Laumersheim",
        "grape_variety": "Cuvée",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Cuvée-harmonisch und tief, ein X der Leidenschaft.",
        "description_en": "Cuvée-harmonious and deep, an X of passion.",
        "description_fr": "Cuvée-harmonieux et profond, un X de passion.",
        "food_pairings_de": ["Wild", "Schokolade"],
        "food_pairings_en": ["Game", "Chocolate"],
        "food_pairings_fr": ["Gibier", "Chocolat"],
    },
    {
        "name": "Ruppertsberger Reiterpfad Riesling GG 2024",
        "winery": "Bassermann-Jordan",
        "region": "Ruppertsberg",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Reiterpfad-elegant und mineralisch.",
        "description_en": "Reiterpfad-elegant and mineral.",
        "description_fr": "Reiterpfad-élégant et minéral.",
        "food_pairings_de": ["Parmesan", "Hummer"],
        "food_pairings_en": ["Parmesan", "Lobster"],
        "food_pairings_fr": ["Parmesan", "Homard"],
    },
    {
        "name": "Armand Riesling Kabinett 2024",
        "winery": "Von Buhl",
        "region": "Deidesheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Zart und tänzerisch, ein Kabinett der Jugend.",
        "description_en": "Delicate and dancing, a Kabinett of youth.",
        "description_fr": "Délicat et dansant, un Kabinett de jeunesse.",
        "food_pairings_de": ["Aperitif"],
        "food_pairings_en": ["Aperitif"],
        "food_pairings_fr": ["Apéritif"],
    },
    {
        "name": "Birkweiler Kastanienbusch Weißburgunder GG 2024",
        "winery": "Dr. Wehrheim",
        "region": "Birkweiler",
        "grape_variety": "Weißburgunder",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Weiß und nuanciert, ein Kastanienbusch der Reinheit.",
        "description_en": "White and nuanced, a Kastanienbusch of purity.",
        "description_fr": "Blanc et nuancé, un Kastanienbusch de pureté.",
        "food_pairings_de": ["Gemüse"],
        "food_pairings_en": ["Vegetables"],
        "food_pairings_fr": ["Légumes"],
    },
    {
        "name": "Großkarlbacher Burgweg Riesling GG 2024",
        "winery": "Philipp Kuhn",
        "region": "Großkarlbach",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Burgweg-kraftvoll und tief.",
        "description_en": "Burgweg-powerful and deep.",
        "description_fr": "Burgweg-puissant et profond.",
        "food_pairings_de": ["Lamm"],
        "food_pairings_en": ["Lamb"],
        "food_pairings_fr": ["Agneau"],
    },
    {
        "name": "Ganz Horn Riesling GG 2024",
        "winery": "Ökonomierat Rebholz",
        "region": "Siebeldingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Ganz Horn-integral und biodynamisch.",
        "description_en": "Ganz Horn-integral and biodynamic.",
        "description_fr": "Ganz Horn-intégral et biodynamique.",
        "food_pairings_de": ["Pilze"],
        "food_pairings_en": ["Mushrooms"],
        "food_pairings_fr": ["Champignons"],
    },
    {
        "name": "Pferdskopf Spätburgunder GG 2024",
        "winery": "A. Christmann",
        "region": "Gimmeldingen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Pferdskopf-rot und robust.",
        "description_en": "Pferdskopf-red and robust.",
        "description_fr": "Pferdskopf-rouge et robuste.",
        "food_pairings_de": ["Dunkles Fleisch"],
        "food_pairings_en": ["Dark meat"],
        "food_pairings_fr": ["Viande brune"],
    },
    {
        "name": "Gaisböhl Riesling GG 2024",
        "winery": "Bürklin-Wolf",
        "region": "Ruppertsberg",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Gaisböhl-Monopol und edel.",
        "description_en": "Gaisböhl-monopole and noble.",
        "description_fr": "Gaisböhl-monopole et noble.",
        "food_pairings_de": ["Krustentiere"],
        "food_pairings_en": ["Crustaceans"],
        "food_pairings_fr": ["Crustacés"],
    },
    {
        "name": "Mandelpfad Riesling GG 2024",
        "winery": "Knipser",
        "region": "Laumersheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Mandelpfad-duftend und intensiv.",
        "description_en": "Mandelpfad-fragrant and intense.",
        "description_fr": "Mandelpfad-parfumé et intense.",
        "food_pairings_de": ["Asiatisch"],
        "food_pairings_en": ["Asian cuisine"],
        "food_pairings_fr": ["Cuisine asiatique"],
    },
    {
        "name": "Kieselberg Riesling GG 2024",
        "winery": "Von Winning",
        "region": "Deidesheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Kieselberg-steinig und präzise.",
        "description_en": "Kieselberg-stony and precise.",
        "description_fr": "Kieselberg-pierreux et précis.",
        "food_pairings_de": ["Fisch"],
        "food_pairings_en": ["Fish"],
        "food_pairings_fr": ["Poisson"],
    },
    {
        "name": "Muskateller Trocken 2024",
        "winery": "Ökonomierat Rebholz",
        "region": "Siebeldingen",
        "grape_variety": "Muskateller",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Muskateller-aromatisch und verlockend.",
        "description_en": "Muskateller-aromatic and enticing.",
        "description_fr": "Muskateller-aromatique et séduisant.",
        "food_pairings_de": ["Desserts"],
        "food_pairings_en": ["Desserts"],
        "food_pairings_fr": ["Desserts"],
    },
    {
        "name": "Deidesheimer Kalkofen Riesling GG 2024",
        "winery": "Bassermann-Jordan",
        "region": "Deidesheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Kalkofen-mineralisch und tief.",
        "description_en": "Kalkofen-mineral and deep.",
        "description_fr": "Kalkofen-minéral et profond.",
        "food_pairings_de": ["Geflügel"],
        "food_pairings_en": ["Poultry"],
        "food_pairings_fr": ["Volaille"],
    },
    {
        "name": "Kirchenstück Spätburgunder GG 2024",
        "winery": "Acham-Magin",
        "region": "Forst",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Kirchenstück-rot und heilig.",
        "description_en": "Kirchenstück-red and holy.",
        "description_fr": "Kirchenstück-rouge et sacré.",
        "food_pairings_de": ["Wild"],
        "food_pairings_en": ["Game"],
        "food_pairings_fr": ["Gibier"],
    },
    {
        "name": "Sauvignon Blanc Reserve 2024",
        "winery": "Philipp Kuhn",
        "region": "Laumersheim",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Sauvignon-exotisch und intensiv.",
        "description_en": "Sauvignon-exotic and intense.",
        "description_fr": "Sauvignon-exotique et intense.",
        "food_pairings_de": ["Ziegenkäse"],
        "food_pairings_en": ["Goat cheese"],
        "food_pairings_fr": ["Fromage de chèvre"],
    },
    {
        "name": "Mandelberg Spätburgunder GG 2024",
        "winery": "Dr. Wehrheim",
        "region": "Birkweiler",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Mandelberg-würzig und tief.",
        "description_en": "Mandelberg-spicy and deep.",
        "description_fr": "Mandelberg-épicé et profond.",
        "food_pairings_de": ["Roastbeef"],
        "food_pairings_en": ["Roast beef"],
        "food_pairings_fr": ["Rosbif"],
    },
    {
        "name": "Pechstein Riesling Auslese 2023",
        "winery": "Von Buhl",
        "region": "Forst",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Pechstein-süß und rauchig.",
        "description_en": "Pechstein-sweet and smoky.",
        "description_fr": "Pechstein-doux et fumé.",
        "food_pairings_de": ["Foie gras"],
        "food_pairings_en": ["Foie gras"],
        "food_pairings_fr": ["Foie gras"],
    },
    {
        "name": "Chardonnay Reserve 2024",
        "winery": "Ökonomierat Rebholz",
        "region": "Siebeldingen",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Chardonnay-cremig und edel.",
        "description_en": "Chardonnay-creamy and noble.",
        "description_fr": "Chardonnay-crémeux et noble.",
        "food_pairings_de": ["Huhn"],
        "food_pairings_en": ["Chicken"],
        "food_pairings_fr": ["Poulet"],
    },
    {
        "name": "Meerspinne Riesling GG 2024",
        "winery": "A. Christmann",
        "region": "Gimmeldingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Meerspinne-mineralisch und wild.",
        "description_en": "Meerspinne-mineral and wild.",
        "description_fr": "Meerspinne-minéral et sauvage.",
        "food_pairings_de": ["Meeresfrüchte"],
        "food_pairings_en": ["Seafood"],
        "food_pairings_fr": ["Fruits de mer"],
    },
    {
        "name": "Steinbuckel Riesling GG 2024",
        "winery": "Knipser",
        "region": "Laumersheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Steinbuckel-steil und kraftvoll.",
        "description_en": "Steinbuckel-steep and powerful.",
        "description_fr": "Steinbuckel-raide et puissant.",
        "food_pairings_de": ["Lamm"],
        "food_pairings_en": ["Lamb"],
        "food_pairings_fr": ["Agneau"],
    },
    {
        "name": "Ruppertsberger Gaisböhl Riesling TBA 2023",
        "winery": "Bürklin-Wolf",
        "region": "Ruppertsberg",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Gaisböhl-golden und konzentriert.",
        "description_en": "Gaisböhl-golden and concentrated.",
        "description_fr": "Gaisböhl-doré et concentré.",
        "food_pairings_de": ["Blauschimmel"],
        "food_pairings_en": ["Blue cheese"],
        "food_pairings_fr": ["Bleu"],
    },
    {
        "name": "Königsbacher Ölberg Riesling GG 2024",
        "winery": "A. Christmann",
        "region": "Königsbach",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Ölberg-ölglatt und tief.",
        "description_en": "Ölberg-oil-smooth and deep.",
        "description_fr": "Ölberg-lisse comme l'huile et profond.",
        "food_pairings_de": ["Parmesan"],
        "food_pairings_en": ["Parmesan"],
        "food_pairings_fr": ["Parmesan"],
    },
    {
        "name": "Forster Ungeheuer Riesling Spätlese 2024",
        "winery": "Von Winning",
        "region": "Forst",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Ungeheuer-spät und verlockend.",
        "description_en": "Ungeheuer-late and enticing.",
        "description_fr": "Ungeheuer-tardif et séduisant.",
        "food_pairings_de": ["Scharfer Thai"],
        "food_pairings_en": ["Spicy Thai"],
        "food_pairings_fr": ["Thaï épicé"],
    },
    {
        "name": "Siebeldinger Weinberg Riesling GG 2024",
        "winery": "Ökonomierat Rebholz",
        "region": "Siebeldingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Weinberg-ehrlich und saftig.",
        "description_en": "Weinberg-honest and juicy.",
        "description_fr": "Weinberg-honnête et juteux.",
        "food_pairings_de": ["Fisch"],
        "food_pairings_en": ["Fish"],
        "food_pairings_fr": ["Poisson"],
    },
    {
        "name": "Forster Ungeheuer Riesling GG 2024",
        "winery": "Bassermann-Jordan",
        "region": "Forst",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Ungeheuer-mythisch und groß.",
        "description_en": "Ungeheuer-mythical and grand.",
        "description_fr": "Ungeheuer-mythique et grandiose.",
        "food_pairings_de": ["Krustentiere"],
        "food_pairings_en": ["Crustaceans"],
        "food_pairings_fr": ["Crustacés"],
    },
    {
        "name": "Kirschgarten Spätburgunder Rosé 2024",
        "winery": "Philipp Kuhn",
        "region": "Laumersheim",
        "grape_variety": "Spätburgunder",
        "wine_color": "rosé",
        "price_category": "€€€",
        "description_de": "Rosé-zart und sommerlich.",
        "description_en": "Rosé-delicate and summery.",
        "description_fr": "Rosé-délicat et estival.",
        "food_pairings_de": ["Salate"],
        "food_pairings_en": ["Salads"],
        "food_pairings_fr": ["Salades"],
    },
    {
        "name": "Enkelswein Riesling Auslese 2023",
        "winery": "Dr. Wehrheim",
        "region": "Birkweiler",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Enkelswein-süß und familiär.",
        "description_en": "Enkelswein-sweet and familial.",
        "description_fr": "Enkelswein-doux et familial.",
        "food_pairings_de": ["Desserts"],
        "food_pairings_en": ["Desserts"],
        "food_pairings_fr": ["Desserts"],
    },
    {
        "name": "Jesuitengarten Riesling Spätlese 2024",
        "winery": "Acham-Magin",
        "region": "Forst",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Jesuitengarten-spät und edel.",
        "description_en": "Jesuitengarten-late and noble.",
        "description_fr": "Jesuitengarten-tardif et noble.",
        "food_pairings_de": ["Käseplatte"],
        "food_pairings_en": ["Cheese platter"],
        "food_pairings_fr": ["Plateau de fromages"],
    },
    {
        "name": "Bone Dry Riesling 2024",
        "winery": "Von Buhl",
        "region": "Deidesheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Bone Dry-trocken und strahlend.",
        "description_en": "Bone Dry-dry and radiant.",
        "description_fr": "Bone Dry-sec et radieux.",
        "food_pairings_de": ["Aperitif"],
        "food_pairings_en": ["Aperitif"],
        "food_pairings_fr": ["Apéritif"],
    },
    {
        "name": "Cuvée Privée Rot 2023",
        "winery": "Knipser",
        "region": "Laumersheim",
        "grape_variety": "Cuvée",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Privée-harmonisch und tief.",
        "description_en": "Privée-harmonious and deep.",
        "description_fr": "Privée-harmonieux et profond.",
        "food_pairings_de": ["Entrecôte"],
        "food_pairings_en": ["Entrecôte"],
        "food_pairings_fr": ["Entrecôte"],
    },
    {
        "name": "Deidesheimer Mäushöhle Riesling GG 2024",
        "winery": "Bürklin-Wolf",
        "region": "Deidesheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Mäushöhle-geheimnisvoll und mineralisch.",
        "description_en": "Mäushöhle-mysterious and mineral.",
        "description_fr": "Mäushöhle-mystérieux et minéral.",
        "food_pairings_de": ["Pilze"],
        "food_pairings_en": ["Mushrooms"],
        "food_pairings_fr": ["Champignons"],
    },
    {
        "name": "Im Sonnenschein Spätburgunder GG 2024",
        "winery": "Ökonomierat Rebholz",
        "region": "Siebeldingen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Sonnenschein-rot und warm, ein Abschluss der Pfälzer Lebensfreude.",
        "description_en": "Sonnenschein-red and warm, a finale of Palatinate joie de vivre.",
        "description_fr": "Sonnenschein-rouge et chaud, un final de la joie de vivre palatine.",
        "food_pairings_de": ["Dunkles Fleisch", "Schokolade"],
        "food_pairings_en": ["Dark meat", "Chocolate"],
        "food_pairings_fr": ["Viande brune", "Chocolat"],
    },
]


async def add_pfalz_wines():
    """Fügt die Pfalz-Weine zur Datenbank hinzu"""
    
    mongo_url = os.environ.get('MONGO_URL', 'mongodb://localhost:27017')
    db_name = os.environ.get('DB_NAME', 'test_database')
    
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    
    print("=" * 60)
    print("🍷 PFALZ-WEINE HINZUFÜGEN")
    print("   Die sonnige Seele des Südens")
    print("=" * 60)
    print(f"📊 Anzahl Weine: {len(PFALZ_WINES)}")
    print()
    
    # Prüfe bestehende Weine
    existing = await db.public_wines.count_documents({"region": {"$regex": "^Pfalz"}})
    print(f"📋 Bestehende Pfalz-Weine: {existing}")
    
    added = 0
    skipped = 0
    
    for wine_data in PFALZ_WINES:
        # Prüfe ob der Wein schon existiert
        exists = await db.public_wines.find_one({
            "name": wine_data["name"],
            "winery": wine_data["winery"]
        })
        
        if exists:
            print(f"⏭️  Übersprungen (existiert): {wine_data['name']}")
            skipped += 1
            continue
        
        # Erstelle den Wein-Eintrag
        wine = {
            "id": str(uuid4()),
            "name": wine_data["name"],
            "winery": wine_data["winery"],
            "country": "Deutschland",
            "region": f"Pfalz - {wine_data['region']}",
            "appellation": "Pfalz",
            "grape_variety": wine_data["grape_variety"],
            "wine_color": wine_data["wine_color"],
            "year": None,
            "description_de": wine_data["description_de"],
            "description_en": wine_data["description_en"],
            "description_fr": wine_data["description_fr"],
            "tasting_notes": None,
            "food_pairings_de": wine_data["food_pairings_de"],
            "food_pairings_en": wine_data["food_pairings_en"],
            "food_pairings_fr": wine_data["food_pairings_fr"],
            "alcohol_content": None,
            "price_category": wine_data["price_category"],
            "image_url": None,
            "rating": None,
            "created_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
        }
        
        await db.public_wines.insert_one(wine)
        print(f"✅ Hinzugefügt: {wine_data['name']} ({wine_data['winery']})")
        added += 1
    
    print()
    print("=" * 60)
    print(f"🎉 FERTIG! {added} Weine hinzugefügt, {skipped} übersprungen")
    print("=" * 60)
    
    # Zeige Gesamtzahl
    total = await db.public_wines.count_documents({})
    pfalz_total = await db.public_wines.count_documents({"region": {"$regex": "^Pfalz"}})
    print(f"\n📊 Gesamtzahl Weine in DB: {total}")
    print(f"📊 Davon Pfalz-Weine: {pfalz_total}")
    
    client.close()


if __name__ == "__main__":
    asyncio.run(add_pfalz_wines())
