#!/usr/bin/env python3
"""
Skript zum Hinzufügen der Top 50 Ahr-Weine zur Datenbank
Mit deutschen, englischen und französischen Beschreibungen

Ahr: Das Rotweinparadies der Steillagen
Spätburgunder von burgundischer Finesse
"""

import asyncio
import os
from uuid import uuid4
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

# Die 50 Ahr-Weine mit allen Details
AHR_WINES = [
    {
        "name": "Herrenberg Spätburgunder GG 2024",
        "winery": "Jean Stodden",
        "region": "Rech",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Ein seidiger Traum von Kirsche, Unterholz und feiner Würze – ein Wein, der die Seele in absolute Ahr-Perfektion und burgundische Tiefe taucht (100 Falstaff-Punkte).",
        "description_en": "A silky dream of cherry, undergrowth and fine spice – a wine that immerses the soul in absolute Ahr perfection and Burgundian depth (100 Falstaff points).",
        "description_fr": "Un rêve soyeux de cerise, de sous-bois et d'épices fines – un vin qui plonge l'âme dans la perfection absolue de l'Ahr et la profondeur bourguignonne (100 points Falstaff).",
        "food_pairings_de": ["Rehrücken", "Dunkle Schokolade"],
        "food_pairings_en": ["Saddle of venison", "Dark chocolate"],
        "food_pairings_fr": ["Selle de chevreuil", "Chocolat noir"],
    },
    {
        "name": "No. 1 Spätburgunder GG 2024",
        "winery": "J.J. Adeneuer",
        "region": "Ahrweiler",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Kraftvoll und filigran, ein No. 1 der Eleganz und Länge, das das Herz mit purer Frucht und Mineralität umfängt.",
        "description_en": "Powerful and delicate, a No. 1 of elegance and length that embraces the heart with pure fruit and minerality.",
        "description_fr": "Puissant et délicat, un No. 1 d'élégance et de longueur qui enlace le cœur avec du fruit pur et de la minéralité.",
        "food_pairings_de": ["Entenbrust", "Pilzrisotto"],
        "food_pairings_en": ["Duck breast", "Mushroom risotto"],
        "food_pairings_fr": ["Magret de canard", "Risotto aux champignons"],
    },
    {
        "name": "Dernauer Pfarrwingert Spätburgunder GG 2024",
        "winery": "Meyer-Näkel",
        "region": "Dernau",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Intensiv und mineralisch, ein Pfarrwingert-Feuer von Beeren und Schiefer – ein Tropfen, der die Sinne in Ekstase versetzt.",
        "description_en": "Intense and mineral, a Pfarrwingert fire of berries and slate – a drop that sends the senses into ecstasy.",
        "description_fr": "Intense et minéral, un feu de Pfarrwingert de baies et d'ardoise – une goutte qui met les sens en extase.",
        "food_pairings_de": ["Wild", "Gereifter Comté"],
        "food_pairings_en": ["Game", "Aged Comté"],
        "food_pairings_fr": ["Gibier", "Comté affiné"],
    },
    {
        "name": "Neuenahrer Schieferlay Spätburgunder GG 2024",
        "winery": "Deutzerhof",
        "region": "Neuenahr",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Schiefer-pur und präzise, ein Schieferlay der Frische und Tiefe, der die Seele mit kühler Noblesse erfrischt.",
        "description_en": "Slate-pure and precise, a Schieferlay of freshness and depth that refreshes the soul with cool nobility.",
        "description_fr": "Pur ardoise et précis, un Schieferlay de fraîcheur et de profondeur qui rafraîchit l'âme avec une noblesse fraîche.",
        "food_pairings_de": ["Gegrilltes Lamm", "Milde Tomme"],
        "food_pairings_en": ["Grilled lamb", "Mild Tomme"],
        "food_pairings_fr": ["Agneau grillé", "Tomme douce"],
    },
    {
        "name": "Ahrweiler Rosenthal Spätburgunder GG 2024",
        "winery": "Kreuzberg",
        "region": "Ahrweiler",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Rosenthal-romantisch und tief, ein Rosenthal der Harmonie und Frucht, das das Herz mit badischer Wärme erfüllt.",
        "description_en": "Rosenthal-romantic and deep, a Rosenthal of harmony and fruit that fills the heart with warmth.",
        "description_fr": "Rosenthal-romantique et profond, un Rosenthal d'harmonie et de fruit qui remplit le cœur de chaleur.",
        "food_pairings_de": ["Roastbeef", "Dunkles Fleisch"],
        "food_pairings_en": ["Roast beef", "Dark meat"],
        "food_pairings_fr": ["Rosbif", "Viande brune"],
    },
    {
        "name": "Heimersheimer Landskrone Spätburgunder GG 2024",
        "winery": "Nelles",
        "region": "Heimersheim",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Landskrone-königlich und robust, ein Monument der Ahr-Roten.",
        "description_en": "Landskrone-royal and robust, a monument of Ahr reds.",
        "description_fr": "Landskrone-royal et robuste, un monument des rouges de l'Ahr.",
        "food_pairings_de": ["Wildpastete", "Schokolade"],
        "food_pairings_en": ["Game pâté", "Chocolate"],
        "food_pairings_fr": ["Pâté de gibier", "Chocolat"],
    },
    {
        "name": "Neuenahrer Kirchtürmchen Spätburgunder GG 2024",
        "winery": "Burggarten",
        "region": "Neuenahr",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Kirchtürmchen-heilig und seidig, ein Kirchtürmchen der Reinheit.",
        "description_en": "Kirchtürmchen-holy and silky, a Kirchtürmchen of purity.",
        "description_fr": "Kirchtürmchen-sacré et soyeux, un Kirchtürmchen de pureté.",
        "food_pairings_de": ["Geflügel", "Pilze"],
        "food_pairings_en": ["Poultry", "Mushrooms"],
        "food_pairings_fr": ["Volaille", "Champignons"],
    },
    {
        "name": "Ahrweiler Daubhaus Spätburgunder GG 2024",
        "winery": "Julia Bertram",
        "region": "Ahrweiler",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Aufstrebend und präzise, ein Daubhaus der neuen Generation, der die Seele mit moderner Eleganz weckt.",
        "description_en": "Rising and precise, a Daubhaus of the new generation that awakens the soul with modern elegance.",
        "description_fr": "Montant et précis, un Daubhaus de la nouvelle génération qui éveille l'âme avec une élégance moderne.",
        "food_pairings_de": ["Entenbrust", "Käse"],
        "food_pairings_en": ["Duck breast", "Cheese"],
        "food_pairings_fr": ["Magret de canard", "Fromage"],
    },
    {
        "name": "Recher Herrenberg Spätburgunder Alte Reben 2023",
        "winery": "Jean Stodden",
        "region": "Rech",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Alte Reben-tief und konzentriert, ein Herrenberg der Reife.",
        "description_en": "Old vines-deep and concentrated, a Herrenberg of maturity.",
        "description_fr": "Vieilles vignes-profond et concentré, un Herrenberg de maturité.",
        "food_pairings_de": ["Rehrücken", "Blauschimmel"],
        "food_pairings_en": ["Saddle of venison", "Blue cheese"],
        "food_pairings_fr": ["Selle de chevreuil", "Bleu"],
    },
    {
        "name": "Walporzheimer Gärkammer Spätburgunder GG 2024",
        "winery": "J.J. Adeneuer",
        "region": "Walporzheim",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Gärkammer-intensiv und mineralisch, ein Kammer-Geheimnis.",
        "description_en": "Gärkammer-intense and mineral, a chamber secret.",
        "description_fr": "Gärkammer-intense et minéral, un secret de chambre.",
        "food_pairings_de": ["BBQ", "Scharfe Wurst"],
        "food_pairings_en": ["BBQ", "Spicy sausage"],
        "food_pairings_fr": ["BBQ", "Saucisse épicée"],
    },
    {
        "name": "Dernauer Schieferlay Spätburgunder GG 2024",
        "winery": "Meyer-Näkel",
        "region": "Dernau",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Schieferlay-schiefrig und tief, ein Lay der Mineralität.",
        "description_en": "Schieferlay-slaty and deep, a Lay of minerality.",
        "description_fr": "Schieferlay-ardoisé et profond, un Lay de minéralité.",
        "food_pairings_de": ["Wild", "Pilze"],
        "food_pairings_en": ["Game", "Mushrooms"],
        "food_pairings_fr": ["Gibier", "Champignons"],
    },
    {
        "name": "Mayschosser Mönchberg Spätburgunder GG 2024",
        "winery": "Deutzerhof",
        "region": "Mayschoss",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Mönchberg-mönchisch und harmonisch, ein Berg der Stille.",
        "description_en": "Mönchberg-monastic and harmonious, a mountain of silence.",
        "description_fr": "Mönchberg-monastique et harmonieux, une montagne de silence.",
        "food_pairings_de": ["Geflügel", "Gemüse"],
        "food_pairings_en": ["Poultry", "Vegetables"],
        "food_pairings_fr": ["Volaille", "Légumes"],
    },
    {
        "name": "Dernauer Pfarrwingert Spätburgunder GG 2024",
        "winery": "Kreuzberg",
        "region": "Dernau",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Pfarrwingert-kirchenwürdig und kraftvoll.",
        "description_en": "Pfarrwingert-church-worthy and powerful.",
        "description_fr": "Pfarrwingert-digne d'une église et puissant.",
        "food_pairings_de": ["Rind", "Entrecôte"],
        "food_pairings_en": ["Beef", "Entrecôte"],
        "food_pairings_fr": ["Bœuf", "Entrecôte"],
    },
    {
        "name": "B-52 Spätburgunder Reserve 2023",
        "winery": "Nelles",
        "region": "Heimersheim",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "B-52-explosiv und tief, ein Reserve der Leidenschaft.",
        "description_en": "B-52-explosive and deep, a Reserve of passion.",
        "description_fr": "B-52-explosif et profond, une Réserve de passion.",
        "food_pairings_de": ["Dunkles Fleisch"],
        "food_pairings_en": ["Dark meat"],
        "food_pairings_fr": ["Viande brune"],
    },
    {
        "name": "Heppinger Spätburgunder GG 2024",
        "winery": "Burggarten",
        "region": "Heppingen",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Heppinger-fruchtig und saftig, ein Alltags-Rot der Freude.",
        "description_en": "Heppinger-fruity and juicy, an everyday red of joy.",
        "description_fr": "Heppinger-fruité et juteux, un rouge quotidien de joie.",
        "food_pairings_de": ["Pasta", "Fondue"],
        "food_pairings_en": ["Pasta", "Fondue"],
        "food_pairings_fr": ["Pâtes", "Fondue"],
    },
    {
        "name": "Dernauer Schieferlay Spätburgunder GG 2024",
        "winery": "Julia Bertram",
        "region": "Dernau",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Schieferlay-feminin und präzise, ein Lay der Zukunft.",
        "description_en": "Schieferlay-feminine and precise, a Lay of the future.",
        "description_fr": "Schieferlay-féminin et précis, un Lay de l'avenir.",
        "food_pairings_de": ["Pilze", "Vegetarisch"],
        "food_pairings_en": ["Mushrooms", "Vegetarian"],
        "food_pairings_fr": ["Champignons", "Végétarien"],
    },
    {
        "name": "JS Spätburgunder 2024",
        "winery": "Jean Stodden",
        "region": "Rech",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "JS-signiert und edel, ein Stodden-Klassiker.",
        "description_en": "JS-signed and noble, a Stodden classic.",
        "description_fr": "JS-signé et noble, un classique de Stodden.",
        "food_pairings_de": ["Lamm"],
        "food_pairings_en": ["Lamb"],
        "food_pairings_fr": ["Agneau"],
    },
    {
        "name": "Rosenthal Spätburgunder GG 2024",
        "winery": "J.J. Adeneuer",
        "region": "Ahrweiler",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Rosenthal-romantisch und seidig.",
        "description_en": "Rosenthal-romantic and silky.",
        "description_fr": "Rosenthal-romantique et soyeux.",
        "food_pairings_de": ["Entenbrust"],
        "food_pairings_en": ["Duck breast"],
        "food_pairings_fr": ["Magret de canard"],
    },
    {
        "name": "Walporzheimer Kräuterberg Spätburgunder GG 2024",
        "winery": "Meyer-Näkel",
        "region": "Walporzheim",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Kräuterberg-würzig und tief.",
        "description_en": "Kräuterberg-spicy and deep.",
        "description_fr": "Kräuterberg-épicé et profond.",
        "food_pairings_de": ["Wild"],
        "food_pairings_en": ["Game"],
        "food_pairings_fr": ["Gibier"],
    },
    {
        "name": "Altenahrer Eck Spätburgunder GG 2024",
        "winery": "Deutzerhof",
        "region": "Altenahr",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Eck-eckig und kraftvoll, ein Eck der Stärke.",
        "description_en": "Eck-angular and powerful, an Eck of strength.",
        "description_fr": "Eck-anguleux et puissant, un Eck de force.",
        "food_pairings_de": ["Roastbeef"],
        "food_pairings_en": ["Roast beef"],
        "food_pairings_fr": ["Rosbif"],
    },
    {
        "name": "Ahrweiler Daubhaus Spätburgunder GG 2024",
        "winery": "Kreuzberg",
        "region": "Ahrweiler",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Daubhaus-historisch und mineralisch.",
        "description_en": "Daubhaus-historic and mineral.",
        "description_fr": "Daubhaus-historique et minéral.",
        "food_pairings_de": ["Käseplatte"],
        "food_pairings_en": ["Cheese platter"],
        "food_pairings_fr": ["Plateau de fromages"],
    },
    {
        "name": "Landskrone Frühburgunder GG 2024",
        "winery": "Nelles",
        "region": "Heimersheim",
        "grape_variety": "Frühburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Frühburgunder-früh und lebendig.",
        "description_en": "Frühburgunder-early and lively.",
        "description_fr": "Frühburgunder-précoce et vivant.",
        "food_pairings_de": ["Grilladen"],
        "food_pairings_en": ["Grilled meats"],
        "food_pairings_fr": ["Grillades"],
    },
    {
        "name": "Neuenahrer Schieferlay Spätburgunder GG 2024",
        "winery": "Burggarten",
        "region": "Neuenahr",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Schieferlay-schiefrig und elegant.",
        "description_en": "Schieferlay-slaty and elegant.",
        "description_fr": "Schieferlay-ardoisé et élégant.",
        "food_pairings_de": ["Pilze"],
        "food_pairings_en": ["Mushrooms"],
        "food_pairings_fr": ["Champignons"],
    },
    {
        "name": "Ahrweiler Rosenthal Spätburgunder GG 2024",
        "winery": "Julia Bertram",
        "region": "Ahrweiler",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Rosenthal-jung und aufstrebend.",
        "description_en": "Rosenthal-young and rising.",
        "description_fr": "Rosenthal-jeune et montant.",
        "food_pairings_de": ["Entenbrust"],
        "food_pairings_en": ["Duck breast"],
        "food_pairings_fr": ["Magret de canard"],
    },
    {
        "name": "Recher Herrenberg Spätburgunder Reserve 2023",
        "winery": "Jean Stodden",
        "region": "Rech",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Reserve-tief und reif.",
        "description_en": "Reserve-deep and ripe.",
        "description_fr": "Réserve-profond et mûr.",
        "food_pairings_de": ["Schokolade"],
        "food_pairings_en": ["Chocolate"],
        "food_pairings_fr": ["Chocolat"],
    },
    {
        "name": "No. 2 Spätburgunder 2024",
        "winery": "J.J. Adeneuer",
        "region": "Ahrweiler",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "No. 2-zweitbester und harmonisch.",
        "description_en": "No. 2-second best and harmonious.",
        "description_fr": "No. 2-deuxième meilleur et harmonieux.",
        "food_pairings_de": ["Geflügel"],
        "food_pairings_en": ["Poultry"],
        "food_pairings_fr": ["Volaille"],
    },
    {
        "name": "S Spätburgunder 2024",
        "winery": "Meyer-Näkel",
        "region": "Dernau",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "S-signiert und saftig.",
        "description_en": "S-signed and juicy.",
        "description_fr": "S-signé et juteux.",
        "food_pairings_de": ["Pasta"],
        "food_pairings_en": ["Pasta"],
        "food_pairings_fr": ["Pâtes"],
    },
    {
        "name": "Cossmannsches Eck Spätburgunder GG 2024",
        "winery": "Deutzerhof",
        "region": "Altenahr",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Cossmannsches Eck-geheimnisvoll und tief.",
        "description_en": "Cossmannsches Eck-mysterious and deep.",
        "description_fr": "Cossmannsches Eck-mystérieux et profond.",
        "food_pairings_de": ["Wild"],
        "food_pairings_en": ["Game"],
        "food_pairings_fr": ["Gibier"],
    },
    {
        "name": "Dernauer Schieferlay Spätburgunder GG 2024",
        "winery": "Kreuzberg",
        "region": "Dernau",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Schieferlay-mineralisch und intensiv.",
        "description_en": "Schieferlay-mineral and intense.",
        "description_fr": "Schieferlay-minéral et intense.",
        "food_pairings_de": ["BBQ"],
        "food_pairings_en": ["BBQ"],
        "food_pairings_fr": ["BBQ"],
    },
    {
        "name": "Heimersheimer Burggarten Spätburgunder GG 2024",
        "winery": "Nelles",
        "region": "Heimersheim",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Burggarten-adelig und seidig.",
        "description_en": "Burggarten-noble and silky.",
        "description_fr": "Burggarten-noble et soyeux.",
        "food_pairings_de": ["Rehrücken"],
        "food_pairings_en": ["Saddle of venison"],
        "food_pairings_fr": ["Selle de chevreuil"],
    },
    {
        "name": "Heppinger Frühburgunder 2024",
        "winery": "Burggarten",
        "region": "Heppingen",
        "grape_variety": "Frühburgunder",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Frühburgunder-früh und fruchtig.",
        "description_en": "Frühburgunder-early and fruity.",
        "description_fr": "Frühburgunder-précoce et fruité.",
        "food_pairings_de": ["Salate"],
        "food_pairings_en": ["Salads"],
        "food_pairings_fr": ["Salades"],
    },
    {
        "name": "Dernauer Hardtberg Spätburgunder GG 2024",
        "winery": "Julia Bertram",
        "region": "Dernau",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Hardtberg-hart und kraftvoll.",
        "description_en": "Hardtberg-hard and powerful.",
        "description_fr": "Hardtberg-dur et puissant.",
        "food_pairings_de": ["Lamm"],
        "food_pairings_en": ["Lamb"],
        "food_pairings_fr": ["Agneau"],
    },
    {
        "name": "Alte Reben Spätburgunder 2023",
        "winery": "Jean Stodden",
        "region": "Rech",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Alte Reben-weise und tief.",
        "description_en": "Old vines-wise and deep.",
        "description_fr": "Vieilles vignes-sage et profond.",
        "food_pairings_de": ["Blauschimmel"],
        "food_pairings_en": ["Blue cheese"],
        "food_pairings_fr": ["Bleu"],
    },
    {
        "name": "Gärkammer Reserve 2023",
        "winery": "J.J. Adeneuer",
        "region": "Walporzheim",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Gärkammer-reserviert und komplex.",
        "description_en": "Gärkammer-reserved and complex.",
        "description_fr": "Gärkammer-réservé et complexe.",
        "food_pairings_de": ["Entrecôte"],
        "food_pairings_en": ["Entrecôte"],
        "food_pairings_fr": ["Entrecôte"],
    },
    {
        "name": "Pfarrwingert Spätburgunder Auslese Trocken 2023",
        "winery": "Meyer-Näkel",
        "region": "Dernau",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Auslese-konzentriert und rot.",
        "description_en": "Auslese-concentrated and red.",
        "description_fr": "Auslese-concentré et rouge.",
        "food_pairings_de": ["Schokolade"],
        "food_pairings_en": ["Chocolate"],
        "food_pairings_fr": ["Chocolat"],
    },
    {
        "name": "Neuenahrer Frühburgunder GG 2024",
        "winery": "Deutzerhof",
        "region": "Neuenahr",
        "grape_variety": "Frühburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Frühburgunder-lebendig und frisch.",
        "description_en": "Frühburgunder-lively and fresh.",
        "description_fr": "Frühburgunder-vivant et frais.",
        "food_pairings_de": ["Grilladen"],
        "food_pairings_en": ["Grilled meats"],
        "food_pairings_fr": ["Grillades"],
    },
    {
        "name": "Ahrweiler Silberberg Spätburgunder GG 2024",
        "winery": "Kreuzberg",
        "region": "Ahrweiler",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Silberberg-strahlend und mineralisch.",
        "description_en": "Silberberg-radiant and mineral.",
        "description_fr": "Silberberg-radieux et minéral.",
        "food_pairings_de": ["Pilze"],
        "food_pairings_en": ["Mushrooms"],
        "food_pairings_fr": ["Champignons"],
    },
    {
        "name": "B-52 Reserve 2023",
        "winery": "Nelles",
        "region": "Heimersheim",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "B-52-explosiv und tief.",
        "description_en": "B-52-explosive and deep.",
        "description_fr": "B-52-explosif et profond.",
        "food_pairings_de": ["Wild"],
        "food_pairings_en": ["Game"],
        "food_pairings_fr": ["Gibier"],
    },
    {
        "name": "Neuenahrer Sonnenberg Spätburgunder GG 2024",
        "winery": "Burggarten",
        "region": "Neuenahr",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Sonnenberg-sonnig und warm.",
        "description_en": "Sonnenberg-sunny and warm.",
        "description_fr": "Sonnenberg-ensoleillé et chaud.",
        "food_pairings_de": ["Roastbeef"],
        "food_pairings_en": ["Roast beef"],
        "food_pairings_fr": ["Rosbif"],
    },
    {
        "name": "Ahrweiler Daubhaus Spätburgunder Alte Reben 2023",
        "winery": "Julia Bertram",
        "region": "Ahrweiler",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Alte Reben-tief und feminin.",
        "description_en": "Old vines-deep and feminine.",
        "description_fr": "Vieilles vignes-profond et féminin.",
        "food_pairings_de": ["Käse"],
        "food_pairings_en": ["Cheese"],
        "food_pairings_fr": ["Fromage"],
    },
    {
        "name": "JS Rosé 2024",
        "winery": "Jean Stodden",
        "region": "Rech",
        "grape_variety": "Spätburgunder",
        "wine_color": "rosé",
        "price_category": "€€€",
        "description_de": "Rosé-zart und sommerlich.",
        "description_en": "Rosé-delicate and summery.",
        "description_fr": "Rosé-délicat et estival.",
        "food_pairings_de": ["Salate"],
        "food_pairings_en": ["Salads"],
        "food_pairings_fr": ["Salades"],
    },
    {
        "name": "Rosenthal Spätburgunder Rosé 2024",
        "winery": "J.J. Adeneuer",
        "region": "Ahrweiler",
        "grape_variety": "Spätburgunder",
        "wine_color": "rosé",
        "price_category": "€€€",
        "description_de": "Rosenthal-rosa und frisch.",
        "description_en": "Rosenthal-pink and fresh.",
        "description_fr": "Rosenthal-rose et frais.",
        "food_pairings_de": ["Sommergerichte"],
        "food_pairings_en": ["Summer dishes"],
        "food_pairings_fr": ["Plats d'été"],
    },
    {
        "name": "Blanc de Noir 2024",
        "winery": "Meyer-Näkel",
        "region": "Dernau",
        "grape_variety": "Spätburgunder",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Blanc de Noir-weiß und elegant.",
        "description_en": "Blanc de Noir-white and elegant.",
        "description_fr": "Blanc de Noir-blanc et élégant.",
        "food_pairings_de": ["Fisch"],
        "food_pairings_en": ["Fish"],
        "food_pairings_fr": ["Poisson"],
    },
    {
        "name": "Weißburgunder Trocken 2024",
        "winery": "Deutzerhof",
        "region": "Neuenahr",
        "grape_variety": "Weißburgunder",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Weißburgunder-cremig und sauber.",
        "description_en": "Weißburgunder-creamy and clean.",
        "description_fr": "Weißburgunder-crémeux et propre.",
        "food_pairings_de": ["Geflügel"],
        "food_pairings_en": ["Poultry"],
        "food_pairings_fr": ["Volaille"],
    },
    {
        "name": "Portugieser Trocken 2024",
        "winery": "Kreuzberg",
        "region": "Ahrweiler",
        "grape_variety": "Portugieser",
        "wine_color": "rot",
        "price_category": "€€",
        "description_de": "Portugieser-leicht und fruchtig.",
        "description_en": "Portugieser-light and fruity.",
        "description_fr": "Portugieser-léger et fruité.",
        "food_pairings_de": ["Aperitif"],
        "food_pairings_en": ["Aperitif"],
        "food_pairings_fr": ["Apéritif"],
    },
    {
        "name": "Frühburgunder Rosé 2024",
        "winery": "Nelles",
        "region": "Heimersheim",
        "grape_variety": "Frühburgunder",
        "wine_color": "rosé",
        "price_category": "€€€",
        "description_de": "Frühburgunder-rosa und lebendig.",
        "description_en": "Frühburgunder-pink and lively.",
        "description_fr": "Frühburgunder-rose et vivant.",
        "food_pairings_de": ["Tapas"],
        "food_pairings_en": ["Tapas"],
        "food_pairings_fr": ["Tapas"],
    },
    {
        "name": "Ahrweiler Frühburgunder 2024",
        "winery": "Burggarten",
        "region": "Ahrweiler",
        "grape_variety": "Frühburgunder",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Frühburgunder-früh und saftig.",
        "description_en": "Frühburgunder-early and juicy.",
        "description_fr": "Frühburgunder-précoce et juteux.",
        "food_pairings_de": ["Grilladen"],
        "food_pairings_en": ["Grilled meats"],
        "food_pairings_fr": ["Grillades"],
    },
    {
        "name": "Pinot Madeleine 2024",
        "winery": "Julia Bertram",
        "region": "Dernau",
        "grape_variety": "Pinot Madeleine",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Pinot Madeleine-früh und feminin.",
        "description_en": "Pinot Madeleine-early and feminine.",
        "description_fr": "Pinot Madeleine-précoce et féminin.",
        "food_pairings_de": ["Salat"],
        "food_pairings_en": ["Salad"],
        "food_pairings_fr": ["Salade"],
    },
    {
        "name": "Blanc de Noir 2024",
        "winery": "Jean Stodden",
        "region": "Rech",
        "grape_variety": "Spätburgunder",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Blanc de Noir-rein und mineralisch.",
        "description_en": "Blanc de Noir-pure and mineral.",
        "description_fr": "Blanc de Noir-pur et minéral.",
        "food_pairings_de": ["Meeresfrüchte"],
        "food_pairings_en": ["Seafood"],
        "food_pairings_fr": ["Fruits de mer"],
    },
    {
        "name": "Ahrweiler Rosenthal Spätburgunder GG Alte Reben 2023",
        "winery": "J.J. Adeneuer",
        "region": "Ahrweiler",
        "grape_variety": "Spätburgunder",
        "wine_color": "rot",
        "price_category": "€€€€€",
        "description_de": "Alte Reben-rosenthal-tief und harmonisch, ein Abschluss der Ahr-Leidenschaft.",
        "description_en": "Old vines-rosenthal-deep and harmonious, a finale of Ahr passion.",
        "description_fr": "Vieilles vignes-rosenthal-profond et harmonieux, un final de la passion de l'Ahr.",
        "food_pairings_de": ["Dunkles Fleisch", "Als Meditation"],
        "food_pairings_en": ["Dark meat", "As meditation"],
        "food_pairings_fr": ["Viande brune", "En méditation"],
    },
]


async def add_ahr_wines():
    """Fügt die Ahr-Weine zur Datenbank hinzu"""
    
    mongo_url = os.environ.get('MONGO_URL', 'mongodb://localhost:27017')
    db_name = os.environ.get('DB_NAME', 'test_database')
    
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    
    print("=" * 60)
    print("🍷 AHR-WEINE HINZUFÜGEN")
    print("   Das Rotweinparadies der Steillagen")
    print("=" * 60)
    print(f"📊 Anzahl Weine: {len(AHR_WINES)}")
    print()
    
    # Prüfe bestehende Weine
    existing = await db.public_wines.count_documents({"region": {"$regex": "^Ahr"}})
    print(f"📋 Bestehende Ahr-Weine: {existing}")
    
    added = 0
    skipped = 0
    
    for wine_data in AHR_WINES:
        # Prüfe ob der Wein schon existiert
        exists = await db.public_wines.find_one({
            "name": wine_data["name"],
            "winery": wine_data["winery"]
        })
        
        if exists:
            print(f"⏭️  Übersprungen (existiert): {wine_data['name']}")
            skipped += 1
            continue
        
        # Erstelle den Wein-Eintrag
        wine = {
            "id": str(uuid4()),
            "name": wine_data["name"],
            "winery": wine_data["winery"],
            "country": "Deutschland",
            "region": f"Ahr - {wine_data['region']}",
            "appellation": "Ahr",
            "grape_variety": wine_data["grape_variety"],
            "wine_color": wine_data["wine_color"],
            "year": None,
            "description_de": wine_data["description_de"],
            "description_en": wine_data["description_en"],
            "description_fr": wine_data["description_fr"],
            "tasting_notes": None,
            "food_pairings_de": wine_data["food_pairings_de"],
            "food_pairings_en": wine_data["food_pairings_en"],
            "food_pairings_fr": wine_data["food_pairings_fr"],
            "alcohol_content": None,
            "price_category": wine_data["price_category"],
            "image_url": None,
            "rating": None,
            "created_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
        }
        
        await db.public_wines.insert_one(wine)
        print(f"✅ Hinzugefügt: {wine_data['name']} ({wine_data['winery']})")
        added += 1
    
    print()
    print("=" * 60)
    print(f"🎉 FERTIG! {added} Weine hinzugefügt, {skipped} übersprungen")
    print("=" * 60)
    
    # Zeige Gesamtzahl
    total = await db.public_wines.count_documents({})
    ahr_total = await db.public_wines.count_documents({"region": {"$regex": "^Ahr"}})
    print(f"\n📊 Gesamtzahl Weine in DB: {total}")
    print(f"📊 Davon Ahr-Weine: {ahr_total}")
    
    client.close()


if __name__ == "__main__":
    asyncio.run(add_ahr_wines())
