#!/usr/bin/env python3
"""
Skript zum Hinzufügen der Top 50 Mosel-Weine zur Datenbank
Mit deutschen, englischen und französischen Beschreibungen

Mosel: Die Königin der steilen Lagen
Kristalliner Riesling von dramatischen Schiefer-Steillagen
"""

import asyncio
import os
from uuid import uuid4
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

# Die 50 Mosel-Weine mit allen Details
MOSEL_WINES = [
    {
        "name": "Scharzhofberger Riesling Trockenbeerenauslese 2021",
        "winery": "Egon Müller",
        "region": "Wiltingen",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Ein göttlicher Nektar, flüssiges Gold aus konzentrierter Essenz – ein Wein, der die Seele in ewige Süße und Tiefe taucht.",
        "description_en": "A divine nectar, liquid gold of concentrated essence – a wine that immerses the soul in eternal sweetness and depth.",
        "description_fr": "Un nectar divin, or liquide d'essence concentrée – un vin qui plonge l'âme dans une douceur et une profondeur éternelles.",
        "food_pairings_de": ["Blauschimmelkäse", "Als Meditation"],
        "food_pairings_en": ["Blue cheese", "As meditation"],
        "food_pairings_fr": ["Fromage bleu", "En méditation"],
    },
    {
        "name": "Wehlener Sonnenuhr Riesling Auslese Goldkapsel 2022",
        "winery": "J.J. Prüm",
        "region": "Wehlen",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Golden und filigran, wie ein Sonnenstrahl durch Morgennebel – ein Tropfen, der das Herz mit unendlicher Eleganz verzaubert.",
        "description_en": "Golden and delicate, like a sunbeam through morning mist – a drop that enchants the heart with infinite elegance.",
        "description_fr": "Doré et délicat, comme un rayon de soleil à travers la brume matinale – une goutte qui enchante le cœur avec une élégance infinie.",
        "food_pairings_de": ["Foie gras", "Reifer Comté"],
        "food_pairings_en": ["Foie gras", "Aged Comté"],
        "food_pairings_fr": ["Foie gras", "Comté affiné"],
    },
    {
        "name": "Zeltinger Sonnenuhr Riesling Auslese *** 2022",
        "winery": "Markus Molitor",
        "region": "Zeltingen",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Explosiv und tief, ein Feuerwerk aus Pfirsich und Schiefer, das die Sinne in Ekstase versetzt.",
        "description_en": "Explosive and deep, a firework of peach and slate that sends the senses into ecstasy.",
        "description_fr": "Explosif et profond, un feu d'artifice de pêche et d'ardoise qui met les sens en extase.",
        "food_pairings_de": ["Asiatisches Curry", "Gereifter Gouda"],
        "food_pairings_en": ["Asian curry", "Aged Gouda"],
        "food_pairings_fr": ["Curry asiatique", "Gouda affiné"],
    },
    {
        "name": "Erdener Prälat Riesling Alte Reben Grosses Gewächs 2022",
        "winery": "Dr. Loosen",
        "region": "Erden",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Kraftvoll und mineralisch, ein roter Schiefertraum, der die Seele mit uriger Stärke umfängt.",
        "description_en": "Powerful and mineral, a red slate dream that embraces the soul with primal strength.",
        "description_fr": "Puissant et minéral, un rêve d'ardoise rouge qui enlace l'âme d'une force primale.",
        "food_pairings_de": ["Gegrilltes Lamm", "Wild"],
        "food_pairings_en": ["Grilled lamb", "Game"],
        "food_pairings_fr": ["Agneau grillé", "Gibier"],
    },
    {
        "name": "Brauneberger Juffer Sonnenuhr Riesling Auslese 2022",
        "winery": "Fritz Haag",
        "region": "Brauneberg",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Leichtfüßig und brillant, ein Tanz von Zitrus und Honig, der das Herz höher schlagen lässt.",
        "description_en": "Light-footed and brilliant, a dance of citrus and honey that makes the heart beat faster.",
        "description_fr": "Léger et brillant, une danse d'agrumes et de miel qui fait battre le cœur plus vite.",
        "food_pairings_de": ["Meeresfrüchte", "Ziegenkäse"],
        "food_pairings_en": ["Seafood", "Goat cheese"],
        "food_pairings_fr": ["Fruits de mer", "Fromage de chèvre"],
    },
    {
        "name": "Eitelsbacher Karthäuserhofberg Riesling Spätlese 2022",
        "winery": "Karthäuserhof",
        "region": "Trier",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Mystisch und fein, ein Klostergeheimnis von Apfel und Stein – pure Harmonie.",
        "description_en": "Mystical and fine, a monastery secret of apple and stone – pure harmony.",
        "description_fr": "Mystique et fin, un secret de monastère de pomme et de pierre – pure harmonie.",
        "food_pairings_de": ["Gebratene Forelle", "Milde Tomme"],
        "food_pairings_en": ["Fried trout", "Mild Tomme"],
        "food_pairings_fr": ["Truite poêlée", "Tomme douce"],
    },
    {
        "name": "Brauneberger Juffer Sonnenuhr Riesling GG 2023",
        "winery": "Schloss Lieser",
        "region": "Lieser",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Strahlend und präzise, ein Spiegel der Sonne, der die Seele mit Klarheit erfüllt.",
        "description_en": "Radiant and precise, a mirror of the sun that fills the soul with clarity.",
        "description_fr": "Radieux et précis, un miroir du soleil qui remplit l'âme de clarté.",
        "food_pairings_de": ["Gegrillter Fisch", "Salat"],
        "food_pairings_en": ["Grilled fish", "Salad"],
        "food_pairings_fr": ["Poisson grillé", "Salade"],
    },
    {
        "name": "Piesporter Goldtröpfchen Riesling Auslese 2022",
        "winery": "Reinhold Haart",
        "region": "Piesport",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Süß und lebendig, ein goldener Tropfen, der wie ein Lachen die Seele weckt.",
        "description_en": "Sweet and lively, a golden drop that awakens the soul like laughter.",
        "description_fr": "Doux et vivant, une goutte dorée qui éveille l'âme comme un rire.",
        "food_pairings_de": ["Desserts", "Scharfer Thai"],
        "food_pairings_en": ["Desserts", "Spicy Thai"],
        "food_pairings_fr": ["Desserts", "Thaï épicé"],
    },
    {
        "name": "Scharzhofberger Riesling GG 2023",
        "winery": "Van Volxem",
        "region": "Wiltingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Tief und komplex, ein Meisterwerk der Mineralität, das die Seele in meditative Ruhe taucht.",
        "description_en": "Deep and complex, a masterpiece of minerality that immerses the soul in meditative calm.",
        "description_fr": "Profond et complexe, un chef-d'œuvre de minéralité qui plonge l'âme dans un calme méditatif.",
        "food_pairings_de": ["Hummer", "Reifer Parmesan"],
        "food_pairings_en": ["Lobster", "Aged Parmesan"],
        "food_pairings_fr": ["Homard", "Parmesan affiné"],
    },
    {
        "name": "Pündericher Marienburg Riesling Felsterrasse GG 2023",
        "winery": "Clemens Busch",
        "region": "Pünderich",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Biodynamisch und wild, ein Terroir-Fels, das die Seele mit purer Naturkraft berührt.",
        "description_en": "Biodynamic and wild, a terroir rock that touches the soul with pure natural power.",
        "description_fr": "Biodynamique et sauvage, un rocher de terroir qui touche l'âme avec une puissance naturelle pure.",
        "food_pairings_de": ["Vegetarische Gerichte", "Käse"],
        "food_pairings_en": ["Vegetarian dishes", "Cheese"],
        "food_pairings_fr": ["Plats végétariens", "Fromage"],
    },
    {
        "name": "Zeltinger Schlossberg Riesling Auslese 2022",
        "winery": "Selbach-Oster",
        "region": "Zeltingen",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Zart und verlockend, ein Schlossgeheimnis von Honig und Säure.",
        "description_en": "Delicate and enticing, a castle secret of honey and acidity.",
        "description_fr": "Délicat et séduisant, un secret de château de miel et d'acidité.",
        "food_pairings_de": ["Entenleber", "Blauschimmel"],
        "food_pairings_en": ["Duck liver", "Blue cheese"],
        "food_pairings_fr": ["Foie de canard", "Bleu"],
    },
    {
        "name": "Graacher Domprobst Riesling Auslese 2022",
        "winery": "Willi Schaefer",
        "region": "Graach",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Filigran und tiefgründig, ein Domherren-Traum, der das Herz mit Eleganz umfängt.",
        "description_en": "Delicate and profound, a canon's dream that embraces the heart with elegance.",
        "description_fr": "Délicat et profond, un rêve de chanoine qui enlace le cœur avec élégance.",
        "food_pairings_de": ["Geflügel", "Pilze"],
        "food_pairings_en": ["Poultry", "Mushrooms"],
        "food_pairings_fr": ["Volaille", "Champignons"],
    },
    {
        "name": "Uhlen Roth Lay Riesling GG 2023",
        "winery": "Heymann-Löwenstein",
        "region": "Winningen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Terroir pur, rot und kraftvoll, ein Wein, der die Seele in vulkanische Leidenschaft stürzt.",
        "description_en": "Pure terroir, red and powerful, a wine that plunges the soul into volcanic passion.",
        "description_fr": "Terroir pur, rouge et puissant, un vin qui plonge l'âme dans une passion volcanique.",
        "food_pairings_de": ["Wild", "Dunkles Fleisch"],
        "food_pairings_en": ["Game", "Dark meat"],
        "food_pairings_fr": ["Gibier", "Viande brune"],
    },
    {
        "name": "Winninger Röttgen Riesling GG 2023",
        "winery": "Knebel",
        "region": "Winningen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Steil und intensiv, ein Röttgen-Feuer, das die Sinne entzündet.",
        "description_en": "Steep and intense, a Röttgen fire that ignites the senses.",
        "description_fr": "Raide et intense, un feu de Röttgen qui enflamme les sens.",
        "food_pairings_de": ["Lamm", "BBQ"],
        "food_pairings_en": ["Lamb", "BBQ"],
        "food_pairings_fr": ["Agneau", "BBQ"],
    },
    {
        "name": "Abtsberg Riesling Auslese 2022",
        "winery": "Maximin Grünhaus",
        "region": "Mertesdorf",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Adelig und harmonisch, ein Abtstraum von Frucht und Mineral.",
        "description_en": "Noble and harmonious, an abbot's dream of fruit and mineral.",
        "description_fr": "Noble et harmonieux, un rêve d'abbé de fruit et de minéral.",
        "food_pairings_de": ["Asiatisch", "Käseplatte"],
        "food_pairings_en": ["Asian cuisine", "Cheese platter"],
        "food_pairings_fr": ["Cuisine asiatique", "Plateau de fromages"],
    },
    {
        "name": "Niederberg Helden Riesling Auslese 2022",
        "winery": "Schloss Lieser",
        "region": "Lieser",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Heroisch und süß, ein Heldenepos in flüssiger Form.",
        "description_en": "Heroic and sweet, a heroic epic in liquid form.",
        "description_fr": "Héroïque et doux, une épopée héroïque sous forme liquide.",
        "food_pairings_de": ["Desserts", "Scharfes Essen"],
        "food_pairings_en": ["Desserts", "Spicy food"],
        "food_pairings_fr": ["Desserts", "Plats épicés"],
    },
    {
        "name": "Bernkasteler Doctor Riesling Spätlese 2022",
        "winery": "Dr. Thanisch",
        "region": "Bernkastel",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€€",
        "description_de": "Legendär und geheimnisvoll, ein Doctor, der die Seele heilt.",
        "description_en": "Legendary and mysterious, a Doctor that heals the soul.",
        "description_fr": "Légendaire et mystérieux, un Docteur qui guérit l'âme.",
        "food_pairings_de": ["Fisch", "Geflügel"],
        "food_pairings_en": ["Fish", "Poultry"],
        "food_pairings_fr": ["Poisson", "Volaille"],
    },
    {
        "name": "Wehlener Sonnenuhr Riesling Kabinett 2023",
        "winery": "S.A. Prüm",
        "region": "Wehlen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Leicht und tänzerisch, ein Kabinett, das das Herz mit Jugend erfrischt.",
        "description_en": "Light and dancing, a Kabinett that refreshes the heart with youth.",
        "description_fr": "Léger et dansant, un Kabinett qui rafraîchit le cœur avec jeunesse.",
        "food_pairings_de": ["Aperitif", "Salat"],
        "food_pairings_en": ["Aperitif", "Salad"],
        "food_pairings_fr": ["Apéritif", "Salade"],
    },
    {
        "name": "Maximiner Grünhaus Riesling GG 2023",
        "winery": "Studert-Prüm",
        "region": "Mertesdorf",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Klassisch und tief, ein Grünhaus-Juwel.",
        "description_en": "Classic and deep, a Grünhaus jewel.",
        "description_fr": "Classique et profond, un joyau de Grünhaus.",
        "food_pairings_de": ["Forelle", "Gemüse"],
        "food_pairings_en": ["Trout", "Vegetables"],
        "food_pairings_fr": ["Truite", "Légumes"],
    },
    {
        "name": "Enkircher Zeppwingert Riesling GG 2023",
        "winery": "Immich-Batterieberg",
        "region": "Enkirch",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Wild und ungeschliffen, ein Batterieberg-Sturm.",
        "description_en": "Wild and unpolished, a Batterieberg storm.",
        "description_fr": "Sauvage et brut, une tempête de Batterieberg.",
        "food_pairings_de": ["Wildgerichte"],
        "food_pairings_en": ["Game dishes"],
        "food_pairings_fr": ["Plats de gibier"],
    },
    {
        "name": "Wolfer Goldgrube Riesling Auslese 2022",
        "winery": "Daniel Vollenweider",
        "region": "Traben-Trarbach",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Wild und golden, ein Grubenjuwel von Honig und Säure, das die Seele in abenteuerliche Tiefe führt.",
        "description_en": "Wild and golden, a mine jewel of honey and acidity that leads the soul to adventurous depths.",
        "description_fr": "Sauvage et doré, un joyau de mine de miel et d'acidité qui mène l'âme vers des profondeurs aventureuses.",
        "food_pairings_de": ["Scharfer Thai", "Blauschimmelkäse"],
        "food_pairings_en": ["Spicy Thai", "Blue cheese"],
        "food_pairings_fr": ["Thaï épicé", "Fromage bleu"],
    },
    {
        "name": "Schubertslay Riesling GG 2023",
        "winery": "Julian Haart",
        "region": "Piesport",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Präzise und explosiv, ein junger Meisterstreich von Schiefer und Zitrus.",
        "description_en": "Precise and explosive, a young masterstroke of slate and citrus.",
        "description_fr": "Précis et explosif, un jeune coup de maître d'ardoise et d'agrumes.",
        "food_pairings_de": ["Gegrillter Fisch", "Zitronenhähnchen"],
        "food_pairings_en": ["Grilled fish", "Lemon chicken"],
        "food_pairings_fr": ["Poisson grillé", "Poulet au citron"],
    },
    {
        "name": "Bockstein Riesling GG 2023",
        "winery": "Nik Weis St. Urbans-Hof",
        "region": "Wiltingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Mineralisch und strahlend, ein Bockstein-Blick in die Ewigkeit.",
        "description_en": "Mineral and radiant, a Bockstein glimpse into eternity.",
        "description_fr": "Minéral et radieux, un aperçu de Bockstein dans l'éternité.",
        "food_pairings_de": ["Meeresfrüchte", "Frischer Salat"],
        "food_pairings_en": ["Seafood", "Fresh salad"],
        "food_pairings_fr": ["Fruits de mer", "Salade fraîche"],
    },
    {
        "name": "Saarburger Rausch Riesling Auslese 2022",
        "winery": "Forstmeister Geltz-Zilliken",
        "region": "Saarburg",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€€",
        "description_de": "Saar-elegant und süß, ein Rausch von Pfirsich und Stein.",
        "description_en": "Saar-elegant and sweet, a rush of peach and stone.",
        "description_fr": "Élégant-Sarre et doux, une ivresse de pêche et de pierre.",
        "food_pairings_de": ["Desserts", "Foie gras"],
        "food_pairings_en": ["Desserts", "Foie gras"],
        "food_pairings_fr": ["Desserts", "Foie gras"],
    },
    {
        "name": "Dorsheimer Burgberg Riesling GG 2023",
        "winery": "Schlossgut Diel",
        "region": "Dorsheim",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Burgfest und kraftvoll, ein Fels der Stärke.",
        "description_en": "Castle-strong and powerful, a rock of strength.",
        "description_fr": "Fort comme un château et puissant, un roc de force.",
        "food_pairings_de": ["Wild", "Dunkles Fleisch"],
        "food_pairings_en": ["Game", "Dark meat"],
        "food_pairings_fr": ["Gibier", "Viande brune"],
    },
    {
        "name": "Bopparder Hamm Feuerlay Riesling GG 2023",
        "winery": "Florian Weingart",
        "region": "Boppard",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Feurig und steil, ein Hamm-Feuer, das die Sinne entzündet.",
        "description_en": "Fiery and steep, a Hamm fire that ignites the senses.",
        "description_fr": "Fougueux et raide, un feu de Hamm qui enflamme les sens.",
        "food_pairings_de": ["Lamm", "BBQ"],
        "food_pairings_en": ["Lamb", "BBQ"],
        "food_pairings_fr": ["Agneau", "BBQ"],
    },
    {
        "name": "Gondorfer Gäns Riesling GG 2023",
        "winery": "Lubentiushof",
        "region": "Gondorf",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Geheimnisvoll und tief, ein Gäns-Traum von Mineral.",
        "description_en": "Mysterious and deep, a Gäns dream of mineral.",
        "description_fr": "Mystérieux et profond, un rêve de Gäns de minéral.",
        "food_pairings_de": ["Geflügel", "Pilze"],
        "food_pairings_en": ["Poultry", "Mushrooms"],
        "food_pairings_fr": ["Volaille", "Champignons"],
    },
    {
        "name": "Winninger Uhlen Blaufüßer Lay Riesling GG 2023",
        "winery": "Weingut Knebel",
        "region": "Winningen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Blau und intensiv, ein Uhlen-Monument der Frische.",
        "description_en": "Blue and intense, an Uhlen monument of freshness.",
        "description_fr": "Bleu et intense, un monument d'Uhlen de fraîcheur.",
        "food_pairings_de": ["Forelle", "Gemüse"],
        "food_pairings_en": ["Trout", "Vegetables"],
        "food_pairings_fr": ["Truite", "Légumes"],
    },
    {
        "name": "Trittenheimer Apotheke Riesling Auslese 2022",
        "winery": "Ansgar Clüsserath",
        "region": "Trittenheim",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Apotheker-heilend und süß, ein Balsam für die Seele.",
        "description_en": "Apothecary-healing and sweet, a balm for the soul.",
        "description_fr": "Guérisseur d'apothicaire et doux, un baume pour l'âme.",
        "food_pairings_de": ["Scharfes Essen", "Käse"],
        "food_pairings_en": ["Spicy food", "Cheese"],
        "food_pairings_fr": ["Plats épicés", "Fromage"],
    },
    {
        "name": "Ürziger Würzgarten Riesling Spätlese 2022",
        "winery": "Weingut Rebenhof",
        "region": "Ürzig",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Würzig und exotisch, ein Garten der Sinne.",
        "description_en": "Spicy and exotic, a garden of the senses.",
        "description_fr": "Épicé et exotique, un jardin des sens.",
        "food_pairings_de": ["Asiatisch", "Curry"],
        "food_pairings_en": ["Asian cuisine", "Curry"],
        "food_pairings_fr": ["Cuisine asiatique", "Curry"],
    },
    {
        "name": "Erdener Treppchen Riesling Auslese 2022",
        "winery": "Stein",
        "region": "Erden",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Treppensteil und konzentriert, ein Aufstieg zur Perfektion.",
        "description_en": "Staircase-steep and concentrated, an ascent to perfection.",
        "description_fr": "Raide comme un escalier et concentré, une ascension vers la perfection.",
        "food_pairings_de": ["Desserts", "Blauschimmel"],
        "food_pairings_en": ["Desserts", "Blue cheese"],
        "food_pairings_fr": ["Desserts", "Bleu"],
    },
    {
        "name": "Reiler Mullay-Hofberg Riesling GG 2023",
        "winery": "Weingut Melsheimer",
        "region": "Reil",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Biodynamisch und rein, ein Hofberg der Natürlichkeit.",
        "description_en": "Biodynamic and pure, a Hofberg of naturalness.",
        "description_fr": "Biodynamique et pur, un Hofberg de naturalité.",
        "food_pairings_de": ["Vegetarisch", "Käse"],
        "food_pairings_en": ["Vegetarian", "Cheese"],
        "food_pairings_fr": ["Végétarien", "Fromage"],
    },
    {
        "name": "Brauneberger Juffer Riesling Kabinett 2023",
        "winery": "Weingut Karp-Schreiber",
        "region": "Brauneberg",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Leicht und tänzerisch, ein Juffer-Kabinett der Freude.",
        "description_en": "Light and dancing, a Juffer Kabinett of joy.",
        "description_fr": "Léger et dansant, un Kabinett de Juffer de joie.",
        "food_pairings_de": ["Aperitif", "Salat"],
        "food_pairings_en": ["Aperitif", "Salad"],
        "food_pairings_fr": ["Apéritif", "Salade"],
    },
    {
        "name": "Piesporter Günterslay Riesling GG 2023",
        "winery": "Weingut Frieden-Berg",
        "region": "Piesport",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Friedlich und tief, ein Lay der Ruhe.",
        "description_en": "Peaceful and deep, a Lay of tranquility.",
        "description_fr": "Paisible et profond, un Lay de tranquillité.",
        "food_pairings_de": ["Fisch", "Geflügel"],
        "food_pairings_en": ["Fish", "Poultry"],
        "food_pairings_fr": ["Poisson", "Volaille"],
    },
    {
        "name": "Trittenheimer Altärchen Riesling Auslese 2022",
        "winery": "Weingut Grans-Fassian",
        "region": "Trittenheim",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Alt und weise, ein Altärchen der Süße.",
        "description_en": "Old and wise, a little altar of sweetness.",
        "description_fr": "Ancien et sage, un petit autel de douceur.",
        "food_pairings_de": ["Foie gras", "Desserts"],
        "food_pairings_en": ["Foie gras", "Desserts"],
        "food_pairings_fr": ["Foie gras", "Desserts"],
    },
    {
        "name": "Wehlener Sonnenuhr Riesling Spätlese 2023",
        "winery": "Weingut Kerpen",
        "region": "Wehlen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Sonnig und harmonisch, ein Uhrwerk der Balance.",
        "description_en": "Sunny and harmonious, a clockwork of balance.",
        "description_fr": "Ensoleillé et harmonieux, une horlogerie d'équilibre.",
        "food_pairings_de": ["Asiatisch", "Käse"],
        "food_pairings_en": ["Asian cuisine", "Cheese"],
        "food_pairings_fr": ["Cuisine asiatique", "Fromage"],
    },
    {
        "name": "Kanzemer Altenberg Riesling GG 2023",
        "winery": "Weingut von Othegraven",
        "region": "Kanzem",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Adelig und präzise, ein Altenberg der Noblesse.",
        "description_en": "Noble and precise, an Altenberg of nobility.",
        "description_fr": "Noble et précis, un Altenberg de noblesse.",
        "food_pairings_de": ["Hummer", "Parmesan"],
        "food_pairings_en": ["Lobster", "Parmesan"],
        "food_pairings_fr": ["Homard", "Parmesan"],
    },
    {
        "name": "Kröver Steffensberg Riesling GG 2023",
        "winery": "Weingut Vollenweider",
        "region": "Kröv",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Steil und wild, ein Steffensberg-Sturm.",
        "description_en": "Steep and wild, a Steffensberg storm.",
        "description_fr": "Raide et sauvage, une tempête de Steffensberg.",
        "food_pairings_de": ["Wildgerichte"],
        "food_pairings_en": ["Game dishes"],
        "food_pairings_fr": ["Plats de gibier"],
    },
    {
        "name": "Brauneberger Kammer Riesling Auslese 2022",
        "winery": "Weingut Haag",
        "region": "Brauneberg",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Kammer-geheim und süß, ein verborgener Schatz.",
        "description_en": "Chamber-secret and sweet, a hidden treasure.",
        "description_fr": "Secret de chambre et doux, un trésor caché.",
        "food_pairings_de": ["Scharfer Thai"],
        "food_pairings_en": ["Spicy Thai"],
        "food_pairings_fr": ["Thaï épicé"],
    },
    {
        "name": "Ürziger Würzgarten Riesling Auslese 2022",
        "winery": "Weingut Jos. Christoffel Jr.",
        "region": "Ürzig",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Würzig und intensiv, ein Garten der Leidenschaft.",
        "description_en": "Spicy and intense, a garden of passion.",
        "description_fr": "Épicé et intense, un jardin de passion.",
        "food_pairings_de": ["Curry", "Vegetarisch"],
        "food_pairings_en": ["Curry", "Vegetarian"],
        "food_pairings_fr": ["Curry", "Végétarien"],
    },
    {
        "name": "Brauneberger Juffer Riesling GG 2023",
        "winery": "Weingut Richard Richter",
        "region": "Brauneberg",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Reich und strukturiert, ein Juffer der Stärke.",
        "description_en": "Rich and structured, a Juffer of strength.",
        "description_fr": "Riche et structuré, un Juffer de force.",
        "food_pairings_de": ["Krustentiere", "Geflügel"],
        "food_pairings_en": ["Crustaceans", "Poultry"],
        "food_pairings_fr": ["Crustacés", "Volaille"],
    },
    {
        "name": "Graacher Himmelreich Riesling Kabinett 2023",
        "winery": "Weingut S.A. Prüm",
        "region": "Graach",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Himmlisch und leicht, ein Reich der Freude.",
        "description_en": "Heavenly and light, a realm of joy.",
        "description_fr": "Céleste et léger, un royaume de joie.",
        "food_pairings_de": ["Aperitif", "Salat"],
        "food_pairings_en": ["Aperitif", "Salad"],
        "food_pairings_fr": ["Apéritif", "Salade"],
    },
    {
        "name": "Piesporter Goldtröpfchen Riesling Spätlese 2022",
        "winery": "Weingut Willi Haag",
        "region": "Piesport",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Golden und verlockend, ein Tröpfchen der Verführung.",
        "description_en": "Golden and enticing, a droplet of seduction.",
        "description_fr": "Doré et séduisant, une gouttelette de séduction.",
        "food_pairings_de": ["Desserts", "Käse"],
        "food_pairings_en": ["Desserts", "Cheese"],
        "food_pairings_fr": ["Desserts", "Fromage"],
    },
    {
        "name": "Lorenzhöfer Riesling GG 2023",
        "winery": "Weingut Karlsmühle",
        "region": "Mertesdorf",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Lorenz-rein und mineralisch, ein Mühlrad der Frische.",
        "description_en": "Lorenz-pure and mineral, a mill wheel of freshness.",
        "description_fr": "Pur-Lorenz et minéral, une roue de moulin de fraîcheur.",
        "food_pairings_de": ["Fisch", "Gemüse"],
        "food_pairings_en": ["Fish", "Vegetables"],
        "food_pairings_fr": ["Poisson", "Légumes"],
    },
    {
        "name": "Bremmer Calmont Riesling GG 2023",
        "winery": "Weingut Franzen",
        "region": "Bremm",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Steilst und feurig, ein Calmont der Extreme.",
        "description_en": "Steepest and fiery, a Calmont of extremes.",
        "description_fr": "Le plus raide et fougueux, un Calmont des extrêmes.",
        "food_pairings_de": ["Lamm", "BBQ"],
        "food_pairings_en": ["Lamb", "BBQ"],
        "food_pairings_fr": ["Agneau", "BBQ"],
    },
    {
        "name": "Piesporter Grafenberg Riesling GG 2023",
        "winery": "Weingut Günther Steinmetz",
        "region": "Piesport",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Grafen-elegant und tief, ein Berg der Noblesse.",
        "description_en": "Count-elegant and deep, a mountain of nobility.",
        "description_fr": "Élégant-comte et profond, une montagne de noblesse.",
        "food_pairings_de": ["Wild", "Pilze"],
        "food_pairings_en": ["Game", "Mushrooms"],
        "food_pairings_fr": ["Gibier", "Champignons"],
    },
    {
        "name": "Thörnicher Ritsch Riesling Auslese 2022",
        "winery": "Weingut Hermann Ludes",
        "region": "Thörnich",
        "grape_variety": "Riesling",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Ritsch-intensiv und süß, ein Riss der Süße.",
        "description_en": "Ritsch-intense and sweet, a rift of sweetness.",
        "description_fr": "Ritsch-intense et doux, une fissure de douceur.",
        "food_pairings_de": ["Scharfes Essen"],
        "food_pairings_en": ["Spicy food"],
        "food_pairings_fr": ["Plats épicés"],
    },
    {
        "name": "Piesporter Domherr Riesling GG 2023",
        "winery": "Weingut Reuscher-Haart",
        "region": "Piesport",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Domherren-würdig und präzise, ein Herr der Mineralität.",
        "description_en": "Canon-worthy and precise, a lord of minerality.",
        "description_fr": "Digne d'un chanoine et précis, un seigneur de minéralité.",
        "food_pairings_de": ["Geflügel", "Käse"],
        "food_pairings_en": ["Poultry", "Cheese"],
        "food_pairings_fr": ["Volaille", "Fromage"],
    },
    {
        "name": "Ockfener Bockstein Riesling Kabinett 2023",
        "winery": "Weingut St. Nikolaus-Hof",
        "region": "Ockfen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Bockstein-lebendig und leicht, ein Stein der Jugend.",
        "description_en": "Bockstein-lively and light, a stone of youth.",
        "description_fr": "Bockstein-vif et léger, une pierre de jeunesse.",
        "food_pairings_de": ["Aperitif", "Salat"],
        "food_pairings_en": ["Aperitif", "Salad"],
        "food_pairings_fr": ["Apéritif", "Salade"],
    },
    {
        "name": "Scharzhofberger Riesling Spätlese 2022",
        "winery": "Weingut Von Hövel",
        "region": "Wiltingen",
        "grape_variety": "Riesling",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Hövel-adelig und harmonisch, ein Scharzhofberger Abschluss der Perfektion.",
        "description_en": "Hövel-noble and harmonious, a Scharzhofberger finale of perfection.",
        "description_fr": "Hövel-noble et harmonieux, un final de Scharzhofberger de perfection.",
        "food_pairings_de": ["Asiatisch", "Milder Käse"],
        "food_pairings_en": ["Asian cuisine", "Mild cheese"],
        "food_pairings_fr": ["Cuisine asiatique", "Fromage doux"],
    },
]


async def add_mosel_wines():
    """Fügt die Mosel-Weine zur Datenbank hinzu"""
    
    mongo_url = os.environ.get('MONGO_URL', 'mongodb://localhost:27017')
    db_name = os.environ.get('DB_NAME', 'test_database')
    
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    
    print("=" * 60)
    print("🍷 MOSEL-WEINE HINZUFÜGEN")
    print("   Die Königin der steilen Lagen")
    print("=" * 60)
    print(f"📊 Anzahl Weine: {len(MOSEL_WINES)}")
    print()
    
    # Prüfe bestehende Weine
    existing = await db.public_wines.count_documents({"region": {"$regex": "^Mosel"}})
    print(f"📋 Bestehende Mosel-Weine: {existing}")
    
    added = 0
    skipped = 0
    
    for wine_data in MOSEL_WINES:
        # Prüfe ob der Wein schon existiert
        exists = await db.public_wines.find_one({
            "name": wine_data["name"],
            "winery": wine_data["winery"]
        })
        
        if exists:
            print(f"⏭️  Übersprungen (existiert): {wine_data['name']}")
            skipped += 1
            continue
        
        # Erstelle den Wein-Eintrag
        wine = {
            "id": str(uuid4()),
            "name": wine_data["name"],
            "winery": wine_data["winery"],
            "country": "Deutschland",
            "region": f"Mosel - {wine_data['region']}",
            "appellation": "Mosel",
            "grape_variety": wine_data["grape_variety"],
            "wine_color": wine_data["wine_color"],
            "year": None,
            "description_de": wine_data["description_de"],
            "description_en": wine_data["description_en"],
            "description_fr": wine_data["description_fr"],
            "tasting_notes": None,
            "food_pairings_de": wine_data["food_pairings_de"],
            "food_pairings_en": wine_data["food_pairings_en"],
            "food_pairings_fr": wine_data["food_pairings_fr"],
            "alcohol_content": None,
            "price_category": wine_data["price_category"],
            "image_url": None,
            "rating": None,
            "created_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
        }
        
        await db.public_wines.insert_one(wine)
        print(f"✅ Hinzugefügt: {wine_data['name']} ({wine_data['winery']})")
        added += 1
    
    print()
    print("=" * 60)
    print(f"🎉 FERTIG! {added} Weine hinzugefügt, {skipped} übersprungen")
    print("=" * 60)
    
    # Zeige Gesamtzahl
    total = await db.public_wines.count_documents({})
    mosel_total = await db.public_wines.count_documents({"region": {"$regex": "^Mosel"}})
    print(f"\n📊 Gesamtzahl Weine in DB: {total}")
    print(f"📊 Davon Mosel-Weine: {mosel_total}")
    
    client.close()


if __name__ == "__main__":
    asyncio.run(add_mosel_wines())
