#!/usr/bin/env python3
"""
Skript zum Hinzufügen der Top 50 Graubündner Weine zur Datenbank
Mit deutschen, englischen und französischen Beschreibungen

Die Bündner Herrschaft - das "Burgund der Alpen"
"""

import asyncio
import os
from uuid import uuid4
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

# Die 50 Graubündner Weine mit allen Details
GRAUBUENDEN_WINES = [
    {
        "name": "Chardonnay 2019",
        "winery": "Weingut Gantenbein",
        "region": "Fläsch",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Ein goldener Sonnenstrahl, der von reifen Birnen und Vanilleflüstern erzählt – ein Wein, der die Seele in sanfte, cremige Umarmung hüllt und vergangene Sommer heraufbeschwört.",
        "description_en": "A golden sunbeam speaking of ripe pears and vanilla whispers – a wine that wraps the soul in a soft, creamy embrace and evokes past summers.",
        "description_fr": "Un rayon de soleil doré parlant de poires mûres et de murmures de vanille – un vin qui enveloppe l'âme dans une étreinte douce et crémeuse.",
        "food_pairings_de": ["Gebratenes Huhn mit Kräutern", "Tomme Vaudoise"],
        "food_pairings_en": ["Roasted chicken with herbs", "Tomme Vaudoise"],
        "food_pairings_fr": ["Poulet rôti aux herbes", "Tomme Vaudoise"],
    },
    {
        "name": "Pinot Noir 2019",
        "winery": "Weingut Gantenbein",
        "region": "Fläsch",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Elegant und filigran, mit Kirsche und Samt, der die Seele in burgundische Melancholie taucht – ein Liebesbrief in Rot, der das Herz mit leichter Traurigkeit und purer Freude erfüllt.",
        "description_en": "Elegant and delicate, with cherry and velvet that plunges the soul into Burgundian melancholy – a love letter in red that fills the heart with gentle sadness and pure joy.",
        "description_fr": "Élégant et délicat, avec de la cerise et du velours qui plonge l'âme dans la mélancolie bourguignonne – une lettre d'amour en rouge.",
        "food_pairings_de": ["Entenbrust", "Pilzrisotto"],
        "food_pairings_en": ["Duck breast", "Mushroom risotto"],
        "food_pairings_fr": ["Magret de canard", "Risotto aux champignons"],
    },
    {
        "name": "Pinot Noir Unique 2021",
        "winery": "Weingut Donatsch",
        "region": "Malans",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Tief und tanninreich, mit Leder und Beeren, die die Seele in alte Legenden eintauchen lassen – ein Monument aus Frucht und Finesse.",
        "description_en": "Deep and tannic, with leather and berries that immerse the soul in ancient legends – a monument of fruit and finesse.",
        "description_fr": "Profond et tannique, avec du cuir et des baies qui plongent l'âme dans les légendes anciennes – un monument de fruit et de finesse.",
        "food_pairings_de": ["Rehrücken", "Dunkles Fleisch"],
        "food_pairings_en": ["Saddle of venison", "Dark meat"],
        "food_pairings_fr": ["Selle de chevreuil", "Viande brune"],
    },
    {
        "name": "Chardonnay Frassa 2019",
        "winery": "Weingut Wegelin",
        "region": "Malans",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Reich und blumig, ein Chardonnay, der die Seele in goldene Sonnenuntergänge taucht – cremig, mit Nuss und Zitrus, wie ein Traum der Alpen.",
        "description_en": "Rich and floral, a Chardonnay that immerses the soul in golden sunsets – creamy, with nut and citrus, like an Alpine dream.",
        "description_fr": "Riche et floral, un Chardonnay qui plonge l'âme dans des couchers de soleil dorés – crémeux, avec de la noix et des agrumes.",
        "food_pairings_de": ["Huhn mit Kräutern", "Raclette"],
        "food_pairings_en": ["Chicken with herbs", "Raclette"],
        "food_pairings_fr": ["Poulet aux herbes", "Raclette"],
    },
    {
        "name": "Completer 2022",
        "winery": "Weingut Donatsch",
        "region": "Malans",
        "grape_variety": "Completer",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Streng und charaktervoll, mit Quitte und Mandel, der wie ein vergessenes Gebet die Seele verzaubert – rare Essenz der Bündner Tradition.",
        "description_en": "Austere and characterful, with quince and almond, enchanting the soul like a forgotten prayer – rare essence of Graubünden tradition.",
        "description_fr": "Austère et plein de caractère, avec du coing et de l'amande, enchantant l'âme comme une prière oubliée – essence rare de la tradition grisonne.",
        "food_pairings_de": ["Foie gras", "Reifer Camembert"],
        "food_pairings_en": ["Foie gras", "Aged Camembert"],
        "food_pairings_fr": ["Foie gras", "Camembert affiné"],
    },
    {
        "name": "Pinot Noir Monolith 2021",
        "winery": "Weingut Obrecht",
        "region": "Jenins",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Biodynamisch und intensiv, mit dunklen Beeren und floralen Noten, das die Seele auf Höhenflüge trägt – pure Alpenkraft in Samt.",
        "description_en": "Biodynamic and intense, with dark berries and floral notes that carry the soul to soaring heights – pure Alpine power in velvet.",
        "description_fr": "Biodynamique et intense, avec des baies noires et des notes florales qui portent l'âme vers les sommets – pure puissance alpine en velours.",
        "food_pairings_de": ["Lammkoteletts", "Wildpastete"],
        "food_pairings_en": ["Lamb chops", "Game pâté"],
        "food_pairings_fr": ["Côtelettes d'agneau", "Pâté de gibier"],
    },
    {
        "name": "Riesling-Silvaner 2024",
        "winery": "von Salis",
        "region": "Malans",
        "grape_variety": "Riesling-Silvaner",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Frisch und mineralisch, ein Weiß, der wie ein Bergquell die Seele klärt und erfrischt – drittbester der Schweiz, voller Zitrus und Stein.",
        "description_en": "Fresh and mineral, a white that cleanses and refreshes the soul like a mountain spring – third best in Switzerland, full of citrus and stone.",
        "description_fr": "Frais et minéral, un blanc qui purifie et rafraîchit l'âme comme une source de montagne – troisième meilleur de Suisse, plein d'agrumes et de pierre.",
        "food_pairings_de": ["Gegrillter Fisch", "Papet Vaudois"],
        "food_pairings_en": ["Grilled fish", "Papet Vaudois"],
        "food_pairings_fr": ["Poisson grillé", "Papet Vaudois"],
    },
    {
        "name": "Pinot Noir Gian-Battista 2018",
        "winery": "Weinbau von Tscharner",
        "region": "Chur",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Sinnlich und legendär, mit Kirsche und Gewürz, der das Herz mit unvergesslicher Tiefe umfängt – ein Geniestreich der Bündner Seele.",
        "description_en": "Sensual and legendary, with cherry and spice, embracing the heart with unforgettable depth – a masterstroke of the Graubünden soul.",
        "description_fr": "Sensuel et légendaire, avec de la cerise et des épices, embrassant le cœur avec une profondeur inoubliable – un coup de maître de l'âme grisonne.",
        "food_pairings_de": ["Ente", "Pilzragout"],
        "food_pairings_en": ["Duck", "Mushroom ragout"],
        "food_pairings_fr": ["Canard", "Ragoût de champignons"],
    },
    {
        "name": "Chardonnay Passion 2021",
        "winery": "Weingut Donatsch",
        "region": "Malans",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Opulent und harmonisch, mit Pfirsich und Eiche, das wie ein warmer Föhn die Seele streichelt.",
        "description_en": "Opulent and harmonious, with peach and oak, caressing the soul like a warm Föhn wind.",
        "description_fr": "Opulent et harmonieux, avec de la pêche et du chêne, caressant l'âme comme un foehn chaud.",
        "food_pairings_de": ["Gegrillter Lachs", "Asiatisches Gemüse"],
        "food_pairings_en": ["Grilled salmon", "Asian vegetables"],
        "food_pairings_fr": ["Saumon grillé", "Légumes asiatiques"],
    },
    {
        "name": "Pinot Noir Schöpfiwingert 2011",
        "winery": "Weingut Fromm",
        "region": "Fläsch",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Reif und filigran, ein Alter Reben-Traum von Beeren und Erde, der die Seele in nostalgische Wärme hüllt.",
        "description_en": "Mature and delicate, an old vine dream of berries and earth, wrapping the soul in nostalgic warmth.",
        "description_fr": "Mûr et délicat, un rêve de vieilles vignes de baies et de terre, enveloppant l'âme de chaleur nostalgique.",
        "food_pairings_de": ["Roastbeef", "Dunkle Schokolade"],
        "food_pairings_en": ["Roast beef", "Dark chocolate"],
        "food_pairings_fr": ["Rôti de bœuf", "Chocolat noir"],
    },
    {
        "name": "Pinot Blanc Elevé en Barrique 2024",
        "winery": "Thürer Weine",
        "region": "Maienfeld",
        "grape_variety": "Pinot Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Cremig und großes Gold, mit Apfel und Haselnuss, der die Seele mit barriqueter Tiefe berührt.",
        "description_en": "Creamy and great gold, with apple and hazelnut, touching the soul with barrel-aged depth.",
        "description_fr": "Crémeux et grand or, avec de la pomme et de la noisette, touchant l'âme avec une profondeur de barrique.",
        "food_pairings_de": ["Krebse", "Frischer Salat"],
        "food_pairings_en": ["Crayfish", "Fresh salad"],
        "food_pairings_fr": ["Écrevisses", "Salade fraîche"],
    },
    {
        "name": "Pinot Noir Tscharnergut Alte Reben 2011",
        "winery": "Weingut Donatsch",
        "region": "Jenins",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Robust und fruchtig, ein Pinot, der das Herz mit wilden Beeren und erdiger Wärme in herbstliche Wälder lockt.",
        "description_en": "Robust and fruity, a Pinot that lures the heart into autumn forests with wild berries and earthy warmth.",
        "description_fr": "Robuste et fruité, un Pinot qui attire le cœur dans les forêts d'automne avec des baies sauvages et une chaleur terreuse.",
        "food_pairings_de": ["Lammkoteletts", "Pilzragout"],
        "food_pairings_en": ["Lamb chops", "Mushroom ragout"],
        "food_pairings_fr": ["Côtelettes d'agneau", "Ragoût de champignons"],
    },
    {
        "name": "Müller-Thurgau 2023",
        "winery": "Weinbau Jenny Luzi",
        "region": "Jenins",
        "grape_variety": "Müller-Thurgau",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Frisch und aromatisch, mit Apfel und Kräutern, der wie ein erstes Erwachen im Frühling das Herz erfrischt.",
        "description_en": "Fresh and aromatic, with apple and herbs, refreshing the heart like the first awakening in spring.",
        "description_fr": "Frais et aromatique, avec de la pomme et des herbes, rafraîchissant le cœur comme le premier réveil au printemps.",
        "food_pairings_de": ["Austern", "Ziegenkäse-Platte"],
        "food_pairings_en": ["Oysters", "Goat cheese platter"],
        "food_pairings_fr": ["Huîtres", "Plateau de fromage de chèvre"],
    },
    {
        "name": "Pinot Noir Weisstorkel 2019",
        "winery": "Weingut Wegelin",
        "region": "Malans",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Elegant und präzise, mit Kirschen und Leder, das die Seele in burgundische Poesie taucht.",
        "description_en": "Elegant and precise, with cherries and leather, plunging the soul into Burgundian poetry.",
        "description_fr": "Élégant et précis, avec des cerises et du cuir, plongeant l'âme dans la poésie bourguignonne.",
        "food_pairings_de": ["Entenbrust", "Tomme Vaudoise"],
        "food_pairings_en": ["Duck breast", "Tomme Vaudoise"],
        "food_pairings_fr": ["Magret de canard", "Tomme Vaudoise"],
    },
    {
        "name": "Chardonnay Le Rosy 2018",
        "winery": "Domaine de Chambleau",
        "region": "Colombier",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Blumig und exotisch, mit Birne und Gewürzen, die die Seele in eine orientalische Gartenoase entführen.",
        "description_en": "Floral and exotic, with pear and spices, transporting the soul to an oriental garden oasis.",
        "description_fr": "Floral et exotique, avec de la poire et des épices, transportant l'âme dans une oasis de jardin oriental.",
        "food_pairings_de": ["Geflügelterrine", "Raclette"],
        "food_pairings_en": ["Poultry terrine", "Raclette"],
        "food_pairings_fr": ["Terrine de volaille", "Raclette"],
    },
    {
        "name": "Pinot Noir Pradafant 2019",
        "winery": "Georg Schlegel",
        "region": "Malans",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Einzellagen-Extraklasse, samtig und würzig, ein Rot, das die Seele mit Pfeffer und Beeren in Ekstase versetzt.",
        "description_en": "Single vineyard excellence, velvety and spicy, a red that sends the soul into ecstasy with pepper and berries.",
        "description_fr": "Excellence de parcelle unique, velouté et épicé, un rouge qui envoie l'âme en extase avec du poivre et des baies.",
        "food_pairings_de": ["BBQ-Rippen", "Scharfe Wurst"],
        "food_pairings_en": ["BBQ ribs", "Spicy sausage"],
        "food_pairings_fr": ["Côtes BBQ", "Saucisse épicée"],
    },
    {
        "name": "Completer 2022",
        "winery": "Weingut Roman Hermann",
        "region": "Fläsch",
        "grape_variety": "Completer",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Meisterwerk und streng, mit Mandel und Säure, der wie ein Hohelied die Seele erhebt.",
        "description_en": "A masterpiece, austere with almond and acidity, elevating the soul like a song of songs.",
        "description_fr": "Un chef-d'œuvre, austère avec de l'amande et de l'acidité, élevant l'âme comme un cantique des cantiques.",
        "food_pairings_de": ["Käseplatte", "Gebratenes Forellenfilet"],
        "food_pairings_en": ["Cheese platter", "Pan-fried trout fillet"],
        "food_pairings_fr": ["Plateau de fromages", "Filet de truite poêlé"],
    },
    {
        "name": "Pinot Noir Saliser Grande Selection 2019",
        "winery": "Georg Schlegel",
        "region": "Malans",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "20/20-Pinot mit enormem Potenzial, fruchtig und robust, der das Herz mit imperierender Kraft erhebt.",
        "description_en": "20/20 Pinot with enormous potential, fruity and robust, elevating the heart with imperial power.",
        "description_fr": "Pinot 20/20 avec un potentiel énorme, fruité et robuste, élevant le cœur avec une puissance impériale.",
        "food_pairings_de": ["Wild", "Pilze"],
        "food_pairings_en": ["Game", "Mushrooms"],
        "food_pairings_fr": ["Gibier", "Champignons"],
    },
    {
        "name": "Sauvignon Blanc 2023",
        "winery": "Weingut Obrecht",
        "region": "Jenins",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Nervös und aromatisch, mit Grapefruit und Kräutern, das wie ein Bergnebel die Seele klärt.",
        "description_en": "Nervous and aromatic, with grapefruit and herbs, clearing the soul like mountain mist.",
        "description_fr": "Nerveux et aromatique, avec du pamplemousse et des herbes, purifiant l'âme comme la brume de montagne.",
        "food_pairings_de": ["Meeresfrüchte", "Sommergemüse"],
        "food_pairings_en": ["Seafood", "Summer vegetables"],
        "food_pairings_fr": ["Fruits de mer", "Légumes d'été"],
    },
    {
        "name": "Pinot Noir Lupa 2020",
        "winery": "Georg Schlegel",
        "region": "Malans",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Unvergleichlich trinkbar, mit Kirschen und Geheimnissen, der das Herz mit leichter Freude erheitert.",
        "description_en": "Incomparably drinkable, with cherries and secrets, cheering the heart with light joy.",
        "description_fr": "Incomparablement buvable, avec des cerises et des secrets, égayant le cœur d'une joie légère.",
        "food_pairings_de": ["Pasta Bolognese", "Herzhaftes Brot"],
        "food_pairings_en": ["Pasta Bolognese", "Hearty bread"],
        "food_pairings_fr": ["Pâtes bolognaise", "Pain rustique"],
    },
    {
        "name": "Chardonnay Surmaturé 2019",
        "winery": "Weingut Fromm",
        "region": "Fläsch",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Reich und honigartig, ein Surmaturé, der wie ein Traum die Seele umhüllt.",
        "description_en": "Rich and honeyed, a surmaturé that wraps the soul like a dream.",
        "description_fr": "Riche et miellé, un surmaturé qui enveloppe l'âme comme un rêve.",
        "food_pairings_de": ["Foie gras", "Desserts"],
        "food_pairings_en": ["Foie gras", "Desserts"],
        "food_pairings_fr": ["Foie gras", "Desserts"],
    },
    {
        "name": "Pinot Noir 2023",
        "winery": "Weingut Sprecher von Bernegg",
        "region": "Fläsch",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Filigran und fruchtig, ein Windhauch aus Kirschen, der das Herz mit alpiner Frische weckt.",
        "description_en": "Delicate and fruity, a breath of cherries that awakens the heart with Alpine freshness.",
        "description_fr": "Délicat et fruité, un souffle de cerises qui éveille le cœur avec la fraîcheur alpine.",
        "food_pairings_de": ["Entenbrust", "Pilze"],
        "food_pairings_en": ["Duck breast", "Mushrooms"],
        "food_pairings_fr": ["Magret de canard", "Champignons"],
    },
    {
        "name": "Malvasier 2022",
        "winery": "Weingut Möhr-Niggli",
        "region": "Fläsch",
        "grape_variety": "Malvasier",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Exotisch und würzig, mit Apfel und Gewürzen, die wie ein Geheimnis die Seele verzaubern.",
        "description_en": "Exotic and spicy, with apple and spices that enchant the soul like a secret.",
        "description_fr": "Exotique et épicé, avec de la pomme et des épices qui enchantent l'âme comme un secret.",
        "food_pairings_de": ["Asiatische Gerichte", "Gebratener Tofu"],
        "food_pairings_en": ["Asian dishes", "Fried tofu"],
        "food_pairings_fr": ["Plats asiatiques", "Tofu frit"],
    },
    {
        "name": "Pinot Noir 2021",
        "winery": "Weingut Christian Herrmann",
        "region": "Maienfeld",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Tief und mineralisch, mit dunklen Früchten, die wie ein Abgrund die Seele fesselt.",
        "description_en": "Deep and mineral, with dark fruits that captivate the soul like an abyss.",
        "description_fr": "Profond et minéral, avec des fruits noirs qui captivent l'âme comme un abîme.",
        "food_pairings_de": ["Rindfleisch", "Wild"],
        "food_pairings_en": ["Beef", "Game"],
        "food_pairings_fr": ["Bœuf", "Gibier"],
    },
    {
        "name": "Pinot Blanc 2020",
        "winery": "Weingut Giani Boner",
        "region": "Jenins",
        "grape_variety": "Pinot Blanc",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Zart und blumig, ein Blanc, der die Seele mit valaisanischer Reinheit erfüllt – frisch und nervös.",
        "description_en": "Delicate and floral, a Blanc that fills the soul with Valaisan purity – fresh and nervous.",
        "description_fr": "Délicat et floral, un Blanc qui remplit l'âme de pureté valaisanne – frais et nerveux.",
        "food_pairings_de": ["Fisch", "Salate"],
        "food_pairings_en": ["Fish", "Salads"],
        "food_pairings_fr": ["Poisson", "Salades"],
    },
    {
        "name": "Pinot Noir 2023",
        "winery": "Weingut Familie Hansruedi Adank",
        "region": "Fläsch",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Samten und fruchtig, ein Pinot, der das Herz mit warmer Umarmung beschenkt.",
        "description_en": "Velvety and fruity, a Pinot that gifts the heart with a warm embrace.",
        "description_fr": "Velouté et fruité, un Pinot qui offre au cœur une étreinte chaleureuse.",
        "food_pairings_de": ["Pasta mit Tomatensauce", "Käse"],
        "food_pairings_en": ["Pasta with tomato sauce", "Cheese"],
        "food_pairings_fr": ["Pâtes à la sauce tomate", "Fromage"],
    },
    {
        "name": "Chardonnay 2022",
        "winery": "Weingut Thomas Studach",
        "region": "Malans",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Elegant und strukturiert, mit Apfel und Mineral, das wie ein Tanz die Seele erheitert.",
        "description_en": "Elegant and structured, with apple and mineral, cheering the soul like a dance.",
        "description_fr": "Élégant et structuré, avec de la pomme et du minéral, égayant l'âme comme une danse.",
        "food_pairings_de": ["Huhn mit Kräutern", "Raclette"],
        "food_pairings_en": ["Chicken with herbs", "Raclette"],
        "food_pairings_fr": ["Poulet aux herbes", "Raclette"],
    },
    {
        "name": "Pinot Noir 2021",
        "winery": "Weingut Eichholz",
        "region": "Fläsch",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Würzig und intensiv, ein Rot, das die Seele mit orientalischem Zauber umhüllt.",
        "description_en": "Spicy and intense, a red that wraps the soul in oriental magic.",
        "description_fr": "Épicé et intense, un rouge qui enveloppe l'âme de magie orientale.",
        "food_pairings_de": ["Gewürzhähnchen", "Auberginen"],
        "food_pairings_en": ["Spiced chicken", "Eggplant"],
        "food_pairings_fr": ["Poulet épicé", "Aubergines"],
    },
    {
        "name": "Completer 2023",
        "winery": "Weingut Pelizzatti Perego",
        "region": "Jenins",
        "grape_variety": "Completer",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Feminine Eleganz, mit Veilchen und Säure, der das Herz mit Seide und Feuer erobert.",
        "description_en": "Feminine elegance, with violet and acidity, conquering the heart with silk and fire.",
        "description_fr": "Élégance féminine, avec de la violette et de l'acidité, conquérant le cœur avec de la soie et du feu.",
        "food_pairings_de": ["Perlhuhn mit Morcheln"],
        "food_pairings_en": ["Guinea fowl with morels"],
        "food_pairings_fr": ["Pintade aux morilles"],
    },
    {
        "name": "Pinot Noir 2022",
        "winery": "Silas Hörler",
        "region": "Fläsch",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Präzise und charaktervoll, ein Neuling der Elite, der die Seele mit erdiger Wärme umfängt.",
        "description_en": "Precise and characterful, a newcomer to the elite, embracing the soul with earthy warmth.",
        "description_fr": "Précis et plein de caractère, un nouveau venu dans l'élite, embrassant l'âme avec une chaleur terreuse.",
        "food_pairings_de": ["Ente", "Pilzrisotto"],
        "food_pairings_en": ["Duck", "Mushroom risotto"],
        "food_pairings_fr": ["Canard", "Risotto aux champignons"],
    },
    {
        "name": "Chardonnay 2021",
        "winery": "Weingut Manfred Meier",
        "region": "Zizers",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Überraschend und tief, mit Nuss und Zitrus, das wie ein alter Freund die Seele in nostalgische Wärme hüllt.",
        "description_en": "Surprising and deep, with nut and citrus, wrapping the soul in nostalgic warmth like an old friend.",
        "description_fr": "Surprenant et profond, avec de la noix et des agrumes, enveloppant l'âme de chaleur nostalgique comme un vieil ami.",
        "food_pairings_de": ["Foie gras", "Reifer Käse"],
        "food_pairings_en": ["Foie gras", "Aged cheese"],
        "food_pairings_fr": ["Foie gras", "Fromage affiné"],
    },
    {
        "name": "Pinot Noir 2023",
        "winery": "Weingut Jan Luzi",
        "region": "Malans",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Filigran und robust, ein Pinot, der die Seele mit imperierender Kraft erhebt.",
        "description_en": "Delicate yet robust, a Pinot that elevates the soul with imperial power.",
        "description_fr": "Délicat mais robuste, un Pinot qui élève l'âme avec une puissance impériale.",
        "food_pairings_de": ["Lamm", "Pilze"],
        "food_pairings_en": ["Lamb", "Mushrooms"],
        "food_pairings_fr": ["Agneau", "Champignons"],
    },
    {
        "name": "Müller-Thurgau 2023",
        "winery": "Gutsbetrieb Engel AG",
        "region": "Herrschaft",
        "grape_variety": "Müller-Thurgau",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Frisch und vielschichtig, ein Weiß, der das Herz mit kindlicher Freude weckt.",
        "description_en": "Fresh and multilayered, a white that awakens the heart with childlike joy.",
        "description_fr": "Frais et complexe, un blanc qui éveille le cœur avec une joie enfantine.",
        "food_pairings_de": ["Tapas", "Lachs"],
        "food_pairings_en": ["Tapas", "Salmon"],
        "food_pairings_fr": ["Tapas", "Saumon"],
    },
    {
        "name": "Pinot Noir 2022",
        "winery": "Weingut Treib de Jürg",
        "region": "Maienfeld",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Dynamisch und harmonisch, ein Neuling, der wie ein Chor die Seele erhebt.",
        "description_en": "Dynamic and harmonious, a newcomer that elevates the soul like a choir.",
        "description_fr": "Dynamique et harmonieux, un nouveau venu qui élève l'âme comme un chœur.",
        "food_pairings_de": ["Dunkles Fleisch"],
        "food_pairings_en": ["Dark meat"],
        "food_pairings_fr": ["Viande brune"],
    },
    {
        "name": "Sauvignon Blanc 2023",
        "winery": "Weingut Irene Grünenfelder",
        "region": "Jenins",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Hoch und aromatisch, mit Mandeln und Nektarinen, das die Seele auf Höhenflüge trägt.",
        "description_en": "High and aromatic, with almonds and nectarines, carrying the soul to soaring heights.",
        "description_fr": "Haut et aromatique, avec des amandes et des nectarines, portant l'âme vers les sommets.",
        "food_pairings_de": ["Käseplatte", "Forelle"],
        "food_pairings_en": ["Cheese platter", "Trout"],
        "food_pairings_fr": ["Plateau de fromages", "Truite"],
    },
    {
        "name": "Pinot Noir Barrique 2021",
        "winery": "Weingut Scadenagut",
        "region": "Malans",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Barriqué und tief, ein Pinot, der die Seele in symphonische Tiefe taucht.",
        "description_en": "Barrel-aged and deep, a Pinot that plunges the soul into symphonic depth.",
        "description_fr": "Élevé en barrique et profond, un Pinot qui plonge l'âme dans une profondeur symphonique.",
        "food_pairings_de": ["Ente", "Pilzragout"],
        "food_pairings_en": ["Duck", "Mushroom ragout"],
        "food_pairings_fr": ["Canard", "Ragoût de champignons"],
    },
    {
        "name": "Chardonnay 2023",
        "winery": "Weingut Francisca Obrecht",
        "region": "Jenins",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Opulent und blumig, ein Tropfen, der das Herz mit sommerlicher Leichtigkeit umfängt.",
        "description_en": "Opulent and floral, a drop that embraces the heart with summery lightness.",
        "description_fr": "Opulent et floral, une goutte qui embrasse le cœur avec une légèreté estivale.",
        "food_pairings_de": ["Sommergerichte", "Frischkäse"],
        "food_pairings_en": ["Summer dishes", "Fresh cheese"],
        "food_pairings_fr": ["Plats d'été", "Fromage frais"],
    },
    {
        "name": "Pinot Noir 2022",
        "winery": "Weingut Peter Wegelin",
        "region": "Malans",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Traditionell und rein, ein Tropfen, der das Herz mit Bergfrische reinigt.",
        "description_en": "Traditional and pure, a drop that cleanses the heart with mountain freshness.",
        "description_fr": "Traditionnel et pur, une goutte qui purifie le cœur avec la fraîcheur de la montagne.",
        "food_pairings_de": ["Fischfilet", "Salat"],
        "food_pairings_en": ["Fish fillet", "Salad"],
        "food_pairings_fr": ["Filet de poisson", "Salade"],
    },
    {
        "name": "Malvasier 2023",
        "winery": "Weingut Donatsch",
        "region": "Malans",
        "grape_variety": "Malvasier",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Exotisch und würzig, ein Weiß, der das Herz mit orientalischem Flair verzaubert.",
        "description_en": "Exotic and spicy, a white that enchants the heart with oriental flair.",
        "description_fr": "Exotique et épicé, un blanc qui enchante le cœur avec un flair oriental.",
        "food_pairings_de": ["Curry", "Vegetarische Gerichte"],
        "food_pairings_en": ["Curry", "Vegetarian dishes"],
        "food_pairings_fr": ["Curry", "Plats végétariens"],
    },
    {
        "name": "Pinot Noir 2021",
        "winery": "Weingut Roman Hermann",
        "region": "Fläsch",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Komplex und harmonisch, ein Assemblage, der die Seele in göttliche Ekstase versetzt.",
        "description_en": "Complex and harmonious, an assemblage that sends the soul into divine ecstasy.",
        "description_fr": "Complexe et harmonieux, un assemblage qui envoie l'âme en extase divine.",
        "food_pairings_de": ["Entrecôte", "Schokolade"],
        "food_pairings_en": ["Entrecôte", "Chocolate"],
        "food_pairings_fr": ["Entrecôte", "Chocolat"],
    },
    {
        "name": "Chardonnay Grand Cru 2022",
        "winery": "Weingut Sprecher von Bernegg",
        "region": "Fläsch",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Reich und strukturiert, ein Grand Cru, der die Seele in städtischer Eleganz badet.",
        "description_en": "Rich and structured, a Grand Cru that bathes the soul in urban elegance.",
        "description_fr": "Riche et structuré, un Grand Cru qui baigne l'âme dans l'élégance urbaine.",
        "food_pairings_de": ["Krustentiere", "Geflügel"],
        "food_pairings_en": ["Crustaceans", "Poultry"],
        "food_pairings_fr": ["Crustacés", "Volaille"],
    },
    {
        "name": "Pinot Blanc 2023",
        "winery": "Weingut Gantenbein",
        "region": "Fläsch",
        "grape_variety": "Pinot Blanc",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Nervös und lebendig, ein Funke Glycin und Grapefruit, der das Herz mit alpiner Frische weckt.",
        "description_en": "Nervous and lively, a spark of glycine and grapefruit that awakens the heart with Alpine freshness.",
        "description_fr": "Nerveux et vif, une étincelle de glycine et de pamplemousse qui éveille le cœur avec la fraîcheur alpine.",
        "food_pairings_de": ["Krebse", "Kräutersuppe"],
        "food_pairings_en": ["Crayfish", "Herb soup"],
        "food_pairings_fr": ["Écrevisses", "Soupe aux herbes"],
    },
    {
        "name": "Pinot Noir Amarone-Style 2023",
        "winery": "Weingut Möhr-Niggli",
        "region": "Fläsch",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Tief und amaronig, ein Rot, das wie ein Abgrund die Seele fesselt.",
        "description_en": "Deep and Amarone-like, a red that captivates the soul like an abyss.",
        "description_fr": "Profond et de style Amarone, un rouge qui captive l'âme comme un abîme.",
        "food_pairings_de": ["Stark gewürzte Fleischgerichte"],
        "food_pairings_en": ["Heavily spiced meat dishes"],
        "food_pairings_fr": ["Plats de viande très épicés"],
    },
    {
        "name": "Completer 2021",
        "winery": "Weingut Fromm",
        "region": "Fläsch",
        "grape_variety": "Completer",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Historisch und elegant, ein Wein, der die Seele mit zeitloser Tiefe berührt.",
        "description_en": "Historic and elegant, a wine that touches the soul with timeless depth.",
        "description_fr": "Historique et élégant, un vin qui touche l'âme avec une profondeur intemporelle.",
        "food_pairings_de": ["Geflügel", "Meeresfrüchte"],
        "food_pairings_en": ["Poultry", "Seafood"],
        "food_pairings_fr": ["Volaille", "Fruits de mer"],
    },
    {
        "name": "Pinot Noir Reserve 2022",
        "winery": "Weingut Christian Herrmann",
        "region": "Maienfeld",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Filigran und fruchtig, ein Windhauch aus Kirschen, der das Herz mit leichter Traurigkeit und purer Freude erfüllt.",
        "description_en": "Delicate and fruity, a breath of cherries that fills the heart with gentle sadness and pure joy.",
        "description_fr": "Délicat et fruité, un souffle de cerises qui remplit le cœur d'une douce tristesse et d'une joie pure.",
        "food_pairings_de": ["Entenbrust", "Pilze"],
        "food_pairings_en": ["Duck breast", "Mushrooms"],
        "food_pairings_fr": ["Magret de canard", "Champignons"],
    },
    {
        "name": "Chardonnay Classic 2023",
        "winery": "Weingut Thomas Studach",
        "region": "Malans",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Frisch und ausgewogen, ein Chardonnay, der das Herz mit klassischer Freude erheitert.",
        "description_en": "Fresh and balanced, a Chardonnay that cheers the heart with classic joy.",
        "description_fr": "Frais et équilibré, un Chardonnay qui égaye le cœur avec une joie classique.",
        "food_pairings_de": ["Fondue", "Rind"],
        "food_pairings_en": ["Fondue", "Beef"],
        "food_pairings_fr": ["Fondue", "Bœuf"],
    },
    {
        "name": "Pinot Noir Alte Reben 2021",
        "winery": "Weingut Familie Hansruedi Adank",
        "region": "Fläsch",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Reich und beerig, ein Pinot, der die Seele in bündnerische Wälder entführt.",
        "description_en": "Rich and berry-filled, a Pinot that transports the soul to Graubünden forests.",
        "description_fr": "Riche et fruité, un Pinot qui transporte l'âme dans les forêts des Grisons.",
        "food_pairings_de": ["Lammkoteletts", "Käse"],
        "food_pairings_en": ["Lamb chops", "Cheese"],
        "food_pairings_fr": ["Côtelettes d'agneau", "Fromage"],
    },
    {
        "name": "Sauvignon Blanc 2022",
        "winery": "Weingut Eichholz",
        "region": "Fläsch",
        "grape_variety": "Sauvignon Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Elegant und pfeffrig, ein Blanc, der die Seele mit orientalischem Zauber umhüllt.",
        "description_en": "Elegant and peppery, a Blanc that wraps the soul in oriental magic.",
        "description_fr": "Élégant et poivré, un Blanc qui enveloppe l'âme de magie orientale.",
        "food_pairings_de": ["Gewürzhähnchen", "Auberginen"],
        "food_pairings_en": ["Spiced chicken", "Eggplant"],
        "food_pairings_fr": ["Poulet épicé", "Aubergines"],
    },
    {
        "name": "Malvasier Hybrid 2023",
        "winery": "Weingut Pelizzatti Perego",
        "region": "Jenins",
        "grape_variety": "Malvasier",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Innovativ und fruchtig, ein Hybrid, der das Herz mit moderner Freude erfüllt.",
        "description_en": "Innovative and fruity, a hybrid that fills the heart with modern joy.",
        "description_fr": "Innovant et fruité, un hybride qui remplit le cœur de joie moderne.",
        "food_pairings_de": ["Grillgemüse", "Fisch"],
        "food_pairings_en": ["Grilled vegetables", "Fish"],
        "food_pairings_fr": ["Légumes grillés", "Poisson"],
    },
    {
        "name": "Pinot Noir Gipfelblick 2023",
        "winery": "Weingut Giani Boner",
        "region": "Jenins",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Hoch und rein, ein Pinot, der wie ein Gipfelblick die Seele erweitert.",
        "description_en": "High and pure, a Pinot that expands the soul like a summit view.",
        "description_fr": "Haut et pur, un Pinot qui élargit l'âme comme une vue du sommet.",
        "food_pairings_de": ["Käseplatte", "Leichte Vorspeisen"],
        "food_pairings_en": ["Cheese platter", "Light appetizers"],
        "food_pairings_fr": ["Plateau de fromages", "Entrées légères"],
    },
]


async def add_graubuenden_wines():
    """Add the Top 50 Graubünden wines to the database"""
    
    mongo_url = os.environ.get("MONGO_URL")
    db_name = os.environ.get("DB_NAME", "wine_sommelier")
    
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    
    print("=" * 60)
    print("🏔️  TOP 50 GRAUBÜNDNER WEINE - IMPORT")
    print("   Die Bündner Herrschaft - das 'Burgund der Alpen'")
    print("=" * 60)
    print()
    
    added = 0
    skipped = 0
    
    for wine in GRAUBUENDEN_WINES:
        # Check if wine already exists
        existing = await db.public_wines.find_one({
            "name": wine["name"],
            "winery": wine["winery"]
        })
        
        if existing:
            print(f"  ⏭️  {wine['name']} ({wine['winery']}) - bereits vorhanden")
            skipped += 1
            continue
        
        wine_doc = {
            "id": str(uuid4()),
            "name": wine["name"],
            "winery": wine["winery"],
            "country": "Schweiz",
            "region": f"Graubünden - {wine['region']}",
            "appellation": "AOC Graubünden",
            "grape_variety": wine["grape_variety"],
            "wine_color": wine["wine_color"],
            "price_category": wine["price_category"],
            "description_de": wine["description_de"],
            "description_en": wine["description_en"],
            "description_fr": wine["description_fr"],
            "food_pairings_de": wine["food_pairings_de"],
            "food_pairings_en": wine["food_pairings_en"],
            "food_pairings_fr": wine["food_pairings_fr"],
            "created_at": datetime.now(timezone.utc).isoformat(),
            "source": "Top 50 Graubündner Weine - Grand Prix du Vin Suisse 2025, Falstaff, GaultMillau, VINUM"
        }
        
        await db.public_wines.insert_one(wine_doc)
        print(f"  ✅ {wine['name']} ({wine['winery']})")
        added += 1
    
    print()
    print("=" * 60)
    print(f"🎉 IMPORT ABGESCHLOSSEN!")
    print(f"   Hinzugefügt: {added}")
    print(f"   Übersprungen: {skipped}")
    print("=" * 60)
    
    # Gesamtzahl prüfen
    total = await db.public_wines.count_documents({})
    swiss = await db.public_wines.count_documents({"country": "Schweiz"})
    graubuenden = await db.public_wines.count_documents({"region": {"$regex": "Graubünden", "$options": "i"}})
    genf = await db.public_wines.count_documents({"region": {"$regex": "Genf", "$options": "i"}})
    tessin = await db.public_wines.count_documents({"region": {"$regex": "Tessin", "$options": "i"}})
    waadt = await db.public_wines.count_documents({"region": {"$regex": "Waadt", "$options": "i"}})
    wallis = await db.public_wines.count_documents({"region": {"$regex": "Wallis", "$options": "i"}})
    
    print(f"\n📊 Datenbank-Status:")
    print(f"   Gesamte Weine: {total}")
    print(f"   Schweizer Weine: {swiss}")
    print(f"   - Graubünden: {graubuenden}")
    print(f"   - Genf: {genf}")
    print(f"   - Tessin: {tessin}")
    print(f"   - Waadt: {waadt}")
    print(f"   - Wallis: {wallis}")
    print(f"\n   Prost aus den Bergen! 🏔️🇨🇭")

if __name__ == "__main__":
    asyncio.run(add_graubuenden_wines())
