#!/usr/bin/env python3
"""
Skript zum Hinzufügen der Top 50 Tessiner Weine zur Datenbank
Mit deutschen, englischen und französischen Beschreibungen
"""

import asyncio
import os
from uuid import uuid4
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

# Die 50 Tessiner Weine mit allen Details
TESSIN_WINES = [
    {
        "name": "Bianco di Merlot Kallagora 2023",
        "winery": "Agriloro",
        "region": "Arzo",
        "grape_variety": "Merlot",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Ein Weißwein aus roten Trauben – hell wie ein Morgennebel über dem See, mit Pfirsich und Jasmin, der die Seele in zarte, fast erotische Leichtigkeit hüllt.",
        "description_en": "A white wine from red grapes – bright as morning mist over the lake, with peach and jasmine, wrapping the soul in delicate, almost erotic lightness.",
        "description_fr": "Un vin blanc de raisins rouges – clair comme la brume matinale sur le lac, avec de la pêche et du jasmin, enveloppant l'âme d'une légèreté délicate, presque érotique.",
        "food_pairings_de": ["Burrata mit frischen Feigen"],
        "food_pairings_en": ["Burrata with fresh figs"],
        "food_pairings_fr": ["Burrata aux figues fraîches"],
    },
    {
        "name": "Quattromani 2021",
        "winery": "Gialdi – Brivio – Tamborini – Zündel",
        "region": "Mendrisio",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Der heilige Gral des Tessins: vier Meisterhände, ein Wein wie schwarze Seide, Cassis, Tabak und Bergamotte – ein Kuss, der ewig nachhallt.",
        "description_en": "The holy grail of Ticino: four master hands, a wine like black silk, cassis, tobacco and bergamot – a kiss that echoes forever.",
        "description_fr": "Le saint Graal du Tessin : quatre mains de maître, un vin comme de la soie noire, cassis, tabac et bergamote – un baiser qui résonne à jamais.",
        "food_pairings_de": ["Geschmorte Rindsbäckchen", "36 Monate Comté"],
        "food_pairings_en": ["Braised beef cheeks", "36-month Comté"],
        "food_pairings_fr": ["Joues de bœuf braisées", "Comté 36 mois"],
    },
    {
        "name": "Sottobosco 2022",
        "winery": "Brivio",
        "region": "Mendrisio",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Wild und mystisch, nach feuchtem Waldboden, Trüffel und dunklen Beeren – ein Rot, das die Seele in die magischen Kastanienwälder von Malcantone entführt.",
        "description_en": "Wild and mystical, of damp forest floor, truffle and dark berries – a red that transports the soul to the magical chestnut forests of Malcantone.",
        "description_fr": "Sauvage et mystique, de sous-bois humide, truffe et baies sombres – un rouge qui transporte l'âme dans les forêts magiques de châtaigniers du Malcantone.",
        "food_pairings_de": ["Rehmedaillons mit Steinpilzen"],
        "food_pairings_en": ["Venison medallions with porcini"],
        "food_pairings_fr": ["Médaillons de chevreuil aux cèpes"],
    },
    {
        "name": "Castello di Morcote Riserva 2020",
        "winery": "Castello di Morcote",
        "region": "Morcote",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Wie ein Sonnenuntergang über dem Lago di Lugano in flüssiger Form: samtig, balsamisch, mit Lakritz und Rosen – ein Wein, der weint vor Schönheit.",
        "description_en": "Like a sunset over Lake Lugano in liquid form: velvety, balsamic, with licorice and roses – a wine that weeps with beauty.",
        "description_fr": "Comme un coucher de soleil sur le lac de Lugano sous forme liquide : velouté, balsamique, avec de la réglisse et des roses – un vin qui pleure de beauté.",
        "food_pairings_de": ["Ossobuco alla Ticinese"],
        "food_pairings_en": ["Ossobuco Ticinese style"],
        "food_pairings_fr": ["Ossobuco à la tessinoise"],
    },
    {
        "name": "Trento Riserva 2020",
        "winery": "Christian Zündel",
        "region": "Lugano",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Explosiv und doch elegant, schwarze Kirsche, Grafit, Minze – ein Merlot, der das Herz mit südlicher Glut und nördlicher Präzision schlagen lässt.",
        "description_en": "Explosive yet elegant, black cherry, graphite, mint – a Merlot that makes the heart beat with southern fire and northern precision.",
        "description_fr": "Explosif mais élégant, cerise noire, graphite, menthe – un Merlot qui fait battre le cœur avec le feu du sud et la précision du nord.",
        "food_pairings_de": ["Gegrillte Costata di manzo"],
        "food_pairings_en": ["Grilled beef rib steak"],
        "food_pairings_fr": ["Côte de bœuf grillée"],
    },
    {
        "name": "Balin 2021",
        "winery": "Guido Brivio Platinum",
        "region": "Mendrisio",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Der teuerste und seltenste Merlot der Schweiz – wie flüssiges Rubinviolett, unendlich tief, mit 100 Punkten in manchen Jahren. Ein Mysterium.",
        "description_en": "The most expensive and rarest Merlot in Switzerland – like liquid ruby violet, infinitely deep, with 100 points in some years. A mystery.",
        "description_fr": "Le Merlot le plus cher et le plus rare de Suisse – comme du violet rubis liquide, infiniment profond, avec 100 points certaines années. Un mystère.",
        "food_pairings_de": ["Zu den größten Momenten des Lebens"],
        "food_pairings_en": ["For life's greatest moments"],
        "food_pairings_fr": ["Pour les plus grands moments de la vie"],
    },
    {
        "name": "Ronco di Belmont 2021",
        "winery": "Matasci",
        "region": "Tenero",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Klassisch und sinnlich, rote Rosen, Pflaume, ein Merlot, der wie eine Umarmung von Nonna schmeckt.",
        "description_en": "Classic and sensual, red roses, plum, a Merlot that tastes like a hug from Nonna.",
        "description_fr": "Classique et sensuel, roses rouges, prune, un Merlot qui a le goût d'un câlin de Nonna.",
        "food_pairings_de": ["Polenta con brasato"],
        "food_pairings_en": ["Polenta with braised meat"],
        "food_pairings_fr": ["Polenta au brasato"],
    },
    {
        "name": "Convento 2021",
        "winery": "Valsangiacomo",
        "region": "Mendrisio",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Aus 100-jährigen Reben im alten Klostergarten – fast sakral, mit Weihrauch, Schokolade und Amarena.",
        "description_en": "From 100-year-old vines in the old monastery garden – almost sacred, with incense, chocolate and amarena cherry.",
        "description_fr": "De vignes centenaires dans l'ancien jardin du monastère – presque sacré, avec de l'encens, du chocolat et de l'amarena.",
        "food_pairings_de": ["Wildschweinragout"],
        "food_pairings_en": ["Wild boar ragout"],
        "food_pairings_fr": ["Ragoût de sanglier"],
    },
    {
        "name": "Terre Alte Bianco 2022",
        "winery": "Gialdi",
        "region": "Mendrisio",
        "grape_variety": "Chardonnay, Merlot Bianco",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Ein rarer Weiß-Assemblage – cremig, mit Ananas und Haselnuss, ein Tropfen, der die Seele streichelt.",
        "description_en": "A rare white assemblage – creamy, with pineapple and hazelnut, a drop that caresses the soul.",
        "description_fr": "Un rare assemblage blanc – crémeux, avec de l'ananas et de la noisette, une goutte qui caresse l'âme.",
        "food_pairings_de": ["Risotto mit Safran und Luganighe"],
        "food_pairings_en": ["Risotto with saffron and Luganighe sausage"],
        "food_pairings_fr": ["Risotto au safran et Luganighe"],
    },
    {
        "name": "SanZeno Riserva 2019",
        "winery": "Cantina Kopp von der Crone Visini",
        "region": "Barbengo",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Feminine Eleganz aus alten Reben – Veilchen, Grafit, eine Merlot-Dame, die das Herz mit Seide und Feuer erobert.",
        "description_en": "Feminine elegance from old vines – violet, graphite, a Merlot lady who conquers the heart with silk and fire.",
        "description_fr": "Élégance féminine de vieilles vignes – violette, graphite, une dame Merlot qui conquiert le cœur avec soie et feu.",
        "food_pairings_de": ["Perlhuhn mit Morcheln"],
        "food_pairings_en": ["Guinea fowl with morels"],
        "food_pairings_fr": ["Pintade aux morilles"],
    },
    {
        "name": "Il Canto della Terra 2021",
        "winery": "Delea",
        "region": "Losone",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Wie ein gregorianischer Choral in Rot – tief, spirituell, mit Schiefer und schwarzen Oliven.",
        "description_en": "Like a Gregorian chant in red – deep, spiritual, with slate and black olives.",
        "description_fr": "Comme un chant grégorien en rouge – profond, spirituel, avec de l'ardoise et des olives noires.",
        "food_pairings_de": ["Geschmolzener Bitto", "Taleggio"],
        "food_pairings_en": ["Melted Bitto", "Taleggio"],
        "food_pairings_fr": ["Bitto fondu", "Taleggio"],
    },
    {
        "name": "Carato Riserva 2020",
        "winery": "Vinattieri Ticinesi",
        "region": "Lugano",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Ein monumentaler Merlot, 24 Monate Barrique, Tabak, Leder, Brombeere – ein Wein, der wie ein alter Gentleman spricht.",
        "description_en": "A monumental Merlot, 24 months barrique, tobacco, leather, blackberry – a wine that speaks like an old gentleman.",
        "description_fr": "Un Merlot monumental, 24 mois de barrique, tabac, cuir, mûre – un vin qui parle comme un vieux gentleman.",
        "food_pairings_de": ["Bistecca alla Fiorentina"],
        "food_pairings_en": ["Bistecca alla Fiorentina"],
        "food_pairings_fr": ["Bistecca alla Fiorentina"],
    },
    {
        "name": "Costa del Sole 2023",
        "winery": "Cantina Pelossi",
        "region": "Monteggio",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€",
        "description_de": "Leichtfüßig und sonnig, ein Merlot für jeden Tag, der trotzdem die Seele tanzen lässt.",
        "description_en": "Light-footed and sunny, a Merlot for every day that still makes the soul dance.",
        "description_fr": "Léger et ensoleillé, un Merlot de tous les jours qui fait quand même danser l'âme.",
        "food_pairings_de": ["Caprese", "Grillgemüse"],
        "food_pairings_en": ["Caprese", "Grilled vegetables"],
        "food_pairings_fr": ["Caprese", "Légumes grillés"],
    },
    {
        "name": "Merlot Selezione d'Ottobre 2022",
        "winery": "Tamborini",
        "region": "Lamone",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Spät gelesen, fast amaronig – ein Kuss aus getrockneten Rosen und Schokolade.",
        "description_en": "Late harvested, almost Amarone-like – a kiss of dried roses and chocolate.",
        "description_fr": "Vendangé tardivement, presque amaronien – un baiser de roses séchées et de chocolat.",
        "food_pairings_de": ["Torta di pane", "Gorgonzola dolce"],
        "food_pairings_en": ["Bread pudding", "Gorgonzola dolce"],
        "food_pairings_fr": ["Gâteau de pain", "Gorgonzola dolce"],
    },
    {
        "name": "Arzo Gran Riserva 2020",
        "winery": "Agriloro",
        "region": "Arzo",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Aus dem heißesten Fleck des Tessins – vulkanisch, pfeffrig, mit Graphit und schwarzer Johannisbeere.",
        "description_en": "From the hottest spot in Ticino – volcanic, peppery, with graphite and blackcurrant.",
        "description_fr": "Du point le plus chaud du Tessin – volcanique, poivré, avec du graphite et du cassis.",
        "food_pairings_de": ["Lammcarrée mit Rosmarin"],
        "food_pairings_en": ["Rack of lamb with rosemary"],
        "food_pairings_fr": ["Carré d'agneau au romarin"],
    },
    {
        "name": "Settimo 2021",
        "winery": "Cantina Settemaggio",
        "region": "Castel San Pietro",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Ein Merlot wie Samt auf der Zunge, mit Veilchen und Lakritz – pure Verführung.",
        "description_en": "A Merlot like velvet on the tongue, with violet and licorice – pure seduction.",
        "description_fr": "Un Merlot comme du velours sur la langue, avec de la violette et de la réglisse – pure séduction.",
        "food_pairings_de": ["Risotto al nero mit Tintenfisch"],
        "food_pairings_en": ["Black risotto with squid"],
        "food_pairings_fr": ["Risotto nero aux calamars"],
    },
    {
        "name": "Rosso del Don 2021",
        "winery": "Cantina Il Cavaliere",
        "region": "Morbio Inferiore",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Tief, fast schwarz, mit Espresso und Trüffel – ein Wein für Mitternacht und Geheimnisse.",
        "description_en": "Deep, almost black, with espresso and truffle – a wine for midnight and secrets.",
        "description_fr": "Profond, presque noir, avec de l'espresso et de la truffe – un vin pour minuit et les secrets.",
        "food_pairings_de": ["48 Monate Parmigiano"],
        "food_pairings_en": ["48-month Parmigiano"],
        "food_pairings_fr": ["Parmigiano 48 mois"],
    },
    {
        "name": "Merlot L'Inizio 2023",
        "winery": "Huber Vini",
        "region": "Coldrerio",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€",
        "description_de": "Der junge Wilde – frisch, saftig, voller Lebenslust.",
        "description_en": "The young wild one – fresh, juicy, full of joie de vivre.",
        "description_fr": "Le jeune sauvage – frais, juteux, plein de joie de vivre.",
        "food_pairings_de": ["Pizza Margherita aus dem Holzofen"],
        "food_pairings_en": ["Wood-fired Pizza Margherita"],
        "food_pairings_fr": ["Pizza Margherita au feu de bois"],
    },
    {
        "name": "Vigna d'Antan 2019",
        "winery": "Guido Brivio",
        "region": "Mendrisio",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Aus ungepfropften Urreben – ein archaischer, wilder Merlot, der die Seele in die Zeit vor der Reblaus zurückversetzt.",
        "description_en": "From ungrafted original vines – an archaic, wild Merlot that transports the soul to the time before phylloxera.",
        "description_fr": "De vignes originales non greffées – un Merlot archaïque et sauvage qui transporte l'âme à l'époque d'avant le phylloxéra.",
        "food_pairings_de": ["Brasato al Merlot"],
        "food_pairings_en": ["Beef braised in Merlot"],
        "food_pairings_fr": ["Brasato au Merlot"],
    },
    {
        "name": "Chilestro 2021",
        "winery": "Cantina Chiodi",
        "region": "Ascona",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Biodynamisch, ungeschminkt, mit Erdbeeren und Kräutern – ein Natur pur.",
        "description_en": "Biodynamic, unadorned, with strawberries and herbs – pure nature.",
        "description_fr": "Biodynamique, sans fard, avec des fraises et des herbes – nature pure.",
        "food_pairings_de": ["Vitello tonnato"],
        "food_pairings_en": ["Vitello tonnato"],
        "food_pairings_fr": ["Vitello tonnato"],
    },
    {
        "name": "Bianco Rovere 2022",
        "winery": "Gialdi",
        "region": "Mendrisio",
        "grape_variety": "Merlot",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Eichenveredelter Weißmerlot, wie flüssiges Gold.",
        "description_en": "Oak-aged white Merlot, like liquid gold.",
        "description_fr": "Merlot blanc élevé en chêne, comme de l'or liquide.",
        "food_pairings_de": ["Seezunge"],
        "food_pairings_en": ["Sole"],
        "food_pairings_fr": ["Sole"],
    },
    {
        "name": "Sinfonia 2021",
        "winery": "Terreni alla Maggia",
        "region": "Ascona",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Harmonisches Cuvée, singt im Glas.",
        "description_en": "Harmonious cuvée that sings in the glass.",
        "description_fr": "Cuvée harmonieuse qui chante dans le verre.",
        "food_pairings_de": ["Kaninchen"],
        "food_pairings_en": ["Rabbit"],
        "food_pairings_fr": ["Lapin"],
    },
    {
        "name": "Montagna Magica 2020",
        "winery": "Cantina Monti",
        "region": "Cademario",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Mystisch, nach Kastanienhonig.",
        "description_en": "Mystical, of chestnut honey.",
        "description_fr": "Mystique, de miel de châtaignier.",
        "food_pairings_de": ["Polenta e funghi"],
        "food_pairings_en": ["Polenta with mushrooms"],
        "food_pairings_fr": ["Polenta aux champignons"],
    },
    {
        "name": "Merlot La Preziosa 2022",
        "winery": "Delea",
        "region": "Losone",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Süßlicher Schmelz, fast erotisch.",
        "description_en": "Sweet melting sensation, almost erotic.",
        "description_fr": "Fondu sucré, presque érotique.",
        "food_pairings_de": ["Tiramisù"],
        "food_pairings_en": ["Tiramisù"],
        "food_pairings_fr": ["Tiramisù"],
    },
    {
        "name": "Barrique Rosso 2021",
        "winery": "Cantina Sociale Mendrisio",
        "region": "Mendrisio",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€",
        "description_de": "Volkstümlich und doch edel.",
        "description_en": "Folk-like yet noble.",
        "description_fr": "Populaire et pourtant noble.",
        "food_pairings_de": ["Salumi"],
        "food_pairings_en": ["Cured meats"],
        "food_pairings_fr": ["Charcuterie"],
    },
    {
        "name": "Origine 2021",
        "winery": "Cantina Il Cavaliere",
        "region": "Morbio Inferiore",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Der pure Anfang, kraftvoll und ehrlich.",
        "description_en": "The pure beginning, powerful and honest.",
        "description_fr": "Le pur commencement, puissant et honnête.",
        "food_pairings_de": ["Ossobuco"],
        "food_pairings_en": ["Ossobuco"],
        "food_pairings_fr": ["Ossobuco"],
    },
    {
        "name": "Merlot Solo 2023",
        "winery": "Vinattieri Ticinesi",
        "region": "Lugano",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Einzellage, stolz und allein.",
        "description_en": "Single vineyard, proud and alone.",
        "description_fr": "Parcelle unique, fier et seul.",
        "food_pairings_de": ["Grilladen"],
        "food_pairings_en": ["Grilled meats"],
        "food_pairings_fr": ["Grillades"],
    },
    {
        "name": "Rosato del Ticino 2024",
        "winery": "Matasci",
        "region": "Tenero",
        "grape_variety": "Merlot",
        "wine_color": "rosé",
        "price_category": "€€",
        "description_de": "Sommer in Rosa, nach Himbeeren.",
        "description_en": "Summer in pink, of raspberries.",
        "description_fr": "L'été en rose, de framboises.",
        "food_pairings_de": ["Caprese"],
        "food_pairings_en": ["Caprese"],
        "food_pairings_fr": ["Caprese"],
    },
    {
        "name": "Merlot Sassi Grossi 2021",
        "winery": "Klaus Eneroth",
        "region": "Ligornetto",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Steinig, mineralisch, großartig.",
        "description_en": "Stony, mineral, magnificent.",
        "description_fr": "Pierreux, minéral, magnifique.",
        "food_pairings_de": ["Wild"],
        "food_pairings_en": ["Game"],
        "food_pairings_fr": ["Gibier"],
    },
    {
        "name": "Bagarino 2022",
        "winery": "Cantina Kopp von der Crone",
        "region": "Barbengo",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€",
        "description_de": "Leicht, fröhlich, süffig.",
        "description_en": "Light, cheerful, quaffable.",
        "description_fr": "Léger, joyeux, gouleyant.",
        "food_pairings_de": ["Antipasti"],
        "food_pairings_en": ["Antipasti"],
        "food_pairings_fr": ["Antipasti"],
    },
    {
        "name": "Meride Riserva 2020",
        "winery": "Cantina La Montanina",
        "region": "Meride",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Uralte Terrassen, tiefe Seele.",
        "description_en": "Ancient terraces, deep soul.",
        "description_fr": "Terrasses ancestrales, âme profonde.",
        "food_pairings_de": ["Risotto nero"],
        "food_pairings_en": ["Black risotto"],
        "food_pairings_fr": ["Risotto nero"],
    },
    {
        "name": "Dogaia 2021",
        "winery": "Cantina Dogaia",
        "region": "Castel San Pietro",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Modern, sauber, präzise.",
        "description_en": "Modern, clean, precise.",
        "description_fr": "Moderne, propre, précis.",
        "food_pairings_de": ["Thunfischtatar"],
        "food_pairings_en": ["Tuna tartare"],
        "food_pairings_fr": ["Tartare de thon"],
    },
    {
        "name": "Merlot Vigna Vecchia 2019",
        "winery": "Pelossi – Greina",
        "region": "Monteggio",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Ehrwürdig und sanft.",
        "description_en": "Venerable and gentle.",
        "description_fr": "Vénérable et doux.",
        "food_pairings_de": ["Gereifter Käse"],
        "food_pairings_en": ["Aged cheese"],
        "food_pairings_fr": ["Fromage affiné"],
    },
    {
        "name": "Castello Luigi 2021",
        "winery": "Luigi Zanini",
        "region": "Rivera",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Der Patriarch aller Tessiner Merlots.",
        "description_en": "The patriarch of all Ticino Merlots.",
        "description_fr": "Le patriarche de tous les Merlots tessinois.",
        "food_pairings_de": ["Zu allem Großen"],
        "food_pairings_en": ["For all grand occasions"],
        "food_pairings_fr": ["Pour toutes les grandes occasions"],
    },
    {
        "name": "Rosso di Clara 2022",
        "winery": "Clara Gentili",
        "region": "Novazzano",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Weibliche Kraft, rote Frucht.",
        "description_en": "Feminine strength, red fruit.",
        "description_fr": "Force féminine, fruit rouge.",
        "food_pairings_de": ["Pasta al ragù"],
        "food_pairings_en": ["Pasta with ragù"],
        "food_pairings_fr": ["Pâtes au ragù"],
    },
    {
        "name": "Merlot Bianco 2023",
        "winery": "Cantina Huber",
        "region": "Coldrerio",
        "grape_variety": "Merlot",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Frisch wie Morgentau.",
        "description_en": "Fresh as morning dew.",
        "description_fr": "Frais comme la rosée du matin.",
        "food_pairings_de": ["Ceviche"],
        "food_pairings_en": ["Ceviche"],
        "food_pairings_fr": ["Ceviche"],
    },
    {
        "name": "Ligornetto 2021",
        "winery": "Cantina Latini",
        "region": "Ligornetto",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Samtig, fast süß.",
        "description_en": "Velvety, almost sweet.",
        "description_fr": "Velouté, presque sucré.",
        "food_pairings_de": ["Schokoladendessert"],
        "food_pairings_en": ["Chocolate dessert"],
        "food_pairings_fr": ["Dessert au chocolat"],
    },
    {
        "name": "Merlot La Torre 2020",
        "winery": "Cantina Torre",
        "region": "Riva San Vitale",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Turmhoch, monumental.",
        "description_en": "Tower-high, monumental.",
        "description_fr": "Haut comme une tour, monumental.",
        "food_pairings_de": ["Rindsfilet"],
        "food_pairings_en": ["Beef fillet"],
        "food_pairings_fr": ["Filet de bœuf"],
    },
    {
        "name": "Sotto il Bosco 2022",
        "winery": "Cantina Boschetto",
        "region": "Stabio",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Waldig, geheimnisvoll.",
        "description_en": "Woody, mysterious.",
        "description_fr": "Boisé, mystérieux.",
        "food_pairings_de": ["Pilzrisotto"],
        "food_pairings_en": ["Mushroom risotto"],
        "food_pairings_fr": ["Risotto aux champignons"],
    },
    {
        "name": "Merlot Armonia 2023",
        "winery": "Cantina Carrara",
        "region": "Castel San Pietro",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€",
        "description_de": "Ausgewogen, singt im Mund.",
        "description_en": "Balanced, sings in the mouth.",
        "description_fr": "Équilibré, chante en bouche.",
        "food_pairings_de": ["Kalbsleber"],
        "food_pairings_en": ["Calf liver"],
        "food_pairings_fr": ["Foie de veau"],
    },
    {
        "name": "Vino della Pace 2021",
        "winery": "Coop. Astoria",
        "region": "Mendrisio",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€",
        "description_de": "Friedenswein, weich und tröstend.",
        "description_en": "Peace wine, soft and comforting.",
        "description_fr": "Vin de paix, doux et réconfortant.",
        "food_pairings_de": ["Zu Freunden"],
        "food_pairings_en": ["With friends"],
        "food_pairings_fr": ["Entre amis"],
    },
    {
        "name": "Merlot Granito 2021",
        "winery": "Cantina Il Bosco",
        "region": "Stabio",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Granit pur, straff und lang.",
        "description_en": "Pure granite, taut and long.",
        "description_fr": "Pur granit, tendu et long.",
        "food_pairings_de": ["Lamm"],
        "food_pairings_en": ["Lamb"],
        "food_pairings_fr": ["Agneau"],
    },
    {
        "name": "Rosé Luna 2024",
        "winery": "Gialdi",
        "region": "Mendrisio",
        "grape_variety": "Merlot",
        "wine_color": "rosé",
        "price_category": "€€",
        "description_de": "Mondlicht in Rosa.",
        "description_en": "Moonlight in pink.",
        "description_fr": "Clair de lune en rose.",
        "food_pairings_de": ["Sommerabenden"],
        "food_pairings_en": ["Summer evenings"],
        "food_pairings_fr": ["Soirées d'été"],
    },
    {
        "name": "Merlot Viti Vecchie 2020",
        "winery": "Cantina Nobile",
        "region": "Mendrisio",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Alte Reben, tiefe Weisheit.",
        "description_en": "Old vines, deep wisdom.",
        "description_fr": "Vieilles vignes, sagesse profonde.",
        "food_pairings_de": ["Meditation"],
        "food_pairings_en": ["Meditation"],
        "food_pairings_fr": ["Méditation"],
    },
    {
        "name": "Sogno di Luigi 2021",
        "winery": "Zanini",
        "region": "Rivera",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Ein Traum in Rot.",
        "description_en": "A dream in red.",
        "description_fr": "Un rêve en rouge.",
        "food_pairings_de": ["Liebe"],
        "food_pairings_en": ["Love"],
        "food_pairings_fr": ["Amour"],
    },
    {
        "name": "Merlot Selezione 2023",
        "winery": "Coop. Mendrisio",
        "region": "Mendrisio",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€",
        "description_de": "Der beste Alltags-Merlot.",
        "description_en": "The best everyday Merlot.",
        "description_fr": "Le meilleur Merlot du quotidien.",
        "food_pairings_de": ["Zu jedem Tag"],
        "food_pairings_en": ["For every day"],
        "food_pairings_fr": ["Pour chaque jour"],
    },
    {
        "name": "Barrique Selezione Oro 2020",
        "winery": "Tamborini",
        "region": "Lamone",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Golden und üppig.",
        "description_en": "Golden and opulent.",
        "description_fr": "Doré et opulent.",
        "food_pairings_de": ["Festen"],
        "food_pairings_en": ["Celebrations"],
        "food_pairings_fr": ["Fêtes"],
    },
    {
        "name": "Merlot Collina d'Oro 2022",
        "winery": "Cantina Collina d'Oro",
        "region": "Collina d'Oro",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Goldener Hügel, goldener Wein.",
        "description_en": "Golden hill, golden wine.",
        "description_fr": "Colline dorée, vin doré.",
        "food_pairings_de": ["Sonnenuntergängen"],
        "food_pairings_en": ["Sunsets"],
        "food_pairings_fr": ["Couchers de soleil"],
    },
    {
        "name": "Il Merlot del Nonno 2021",
        "winery": "Cantina Ermotti",
        "region": "Bioggio",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€",
        "description_de": "Großvaters Merlot, voller Geschichten.",
        "description_en": "Grandfather's Merlot, full of stories.",
        "description_fr": "Le Merlot de grand-père, plein d'histoires.",
        "food_pairings_de": ["Familie"],
        "food_pairings_en": ["Family"],
        "food_pairings_fr": ["Famille"],
    },
    {
        "name": "Merlot Ticino DOC Vigneti delle Terre di Pedemonte 2024",
        "winery": "Terre di Pedemonte",
        "region": "Pedemonte",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€",
        "description_de": "Der pure, nackte, wunderschöne Tessiner Merlot – wie ein offenes Herz.",
        "description_en": "The pure, naked, beautiful Ticino Merlot – like an open heart.",
        "description_fr": "Le Merlot tessinois pur, nu et magnifique – comme un cœur ouvert.",
        "food_pairings_de": ["Zu allem, was das Leben schön macht"],
        "food_pairings_en": ["Everything that makes life beautiful"],
        "food_pairings_fr": ["Tout ce qui rend la vie belle"],
    },
]

async def add_tessin_wines():
    """Fügt alle 50 Tessiner Weine zur Datenbank hinzu"""
    
    client = AsyncIOMotorClient(os.environ.get('MONGO_URL'))
    db = client[os.environ.get('DB_NAME', 'test_database')]
    
    print("=" * 60)
    print("🍷 TOP 50 TESSINER WEINE - Import")
    print("   Il cuore del Ticino in forma liquida!")
    print("=" * 60)
    
    added = 0
    skipped = 0
    
    for wine in TESSIN_WINES:
        # Prüfen ob Wein bereits existiert
        existing = await db.public_wines.find_one({
            "name": wine["name"],
            "winery": wine["winery"]
        })
        
        if existing:
            print(f"  ⏭️  {wine['name']} ({wine['winery']}) - già presente")
            skipped += 1
            continue
        
        # Wein-Dokument erstellen
        wine_doc = {
            "id": str(uuid4()),
            "name": wine["name"],
            "winery": wine["winery"],
            "country": "Schweiz",
            "region": f"Tessin - {wine['region']}",
            "appellation": "Ticino DOC",
            "grape_variety": wine["grape_variety"],
            "wine_color": wine["wine_color"],
            "price_category": wine["price_category"],
            "description_de": wine["description_de"],
            "description_en": wine["description_en"],
            "description_fr": wine["description_fr"],
            "food_pairings_de": wine["food_pairings_de"],
            "food_pairings_en": wine["food_pairings_en"],
            "food_pairings_fr": wine["food_pairings_fr"],
            "created_at": datetime.now(timezone.utc).isoformat(),
            "source": "Top 50 Tessiner Weine - Ticino DOC, Merlot del Ticino Gran Premio, GaultMillau 2024/2025"
        }
        
        await db.public_wines.insert_one(wine_doc)
        print(f"  ✅ {wine['name']} ({wine['winery']})")
        added += 1
    
    print()
    print("=" * 60)
    print(f"🎉 IMPORT COMPLETATO!")
    print(f"   Aggiunto: {added}")
    print(f"   Saltato: {skipped}")
    print("=" * 60)
    
    # Gesamtzahl prüfen
    total = await db.public_wines.count_documents({})
    swiss = await db.public_wines.count_documents({"country": "Schweiz"})
    tessin = await db.public_wines.count_documents({"region": {"$regex": "Tessin", "$options": "i"}})
    waadt = await db.public_wines.count_documents({"region": {"$regex": "Waadt", "$options": "i"}})
    wallis = await db.public_wines.count_documents({"region": {"$regex": "Wallis", "$options": "i"}})
    print(f"\n📊 Datenbank-Status:")
    print(f"   Gesamte Weine: {total}")
    print(f"   Schweizer Weine: {swiss}")
    print(f"   - Tessin: {tessin}")
    print(f"   - Waadt: {waadt}")
    print(f"   - Wallis: {wallis}")
    print(f"\n   Salute, amore e sole del sud! 🇮🇹🇨🇭")

if __name__ == "__main__":
    asyncio.run(add_tessin_wines())
