#!/usr/bin/env python3
"""
Skript zum Hinzufügen der Top 50 Neuenburger Weine zur Datenbank
Mit deutschen, englischen und französischen Beschreibungen

Neuenburg - Frische des Sees und Jura-Zauber
"""

import asyncio
import os
from uuid import uuid4
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

# Die 50 Neuenburger Weine mit allen Details
NEUENBURG_WINES = [
    {
        "name": "Cuvée Louis Edouard Mauler 2016",
        "winery": "Maison Mauler",
        "region": "Neuenburg",
        "grape_variety": "Assemblage",
        "wine_color": "schaumwein",
        "price_category": "€€€€",
        "description_de": "Ein perlender Traum, der von goldenen Blasen und reifen Birnen erzählt – ein Wein, der die Seele in festliche Ekstase versetzt und vergangene Feste heraufbeschwört.",
        "description_en": "A sparkling dream speaking of golden bubbles and ripe pears – a wine that sends the soul into festive ecstasy and evokes past celebrations.",
        "description_fr": "Un rêve pétillant parlant de bulles dorées et de poires mûres – un vin qui envoie l'âme en extase festive et évoque les fêtes passées.",
        "food_pairings_de": ["Austern", "Frischer Ziegenkäse"],
        "food_pairings_en": ["Oysters", "Fresh goat cheese"],
        "food_pairings_fr": ["Huîtres", "Fromage de chèvre frais"],
    },
    {
        "name": "Les Bovardes Pinot Noir 2022",
        "winery": "Domaine de Chambleau",
        "region": "Colombier",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Tief und solar, mit roten Früchten und seidenen Tanninen, der wie ein Sonnenuntergang über dem See die Seele in bio-dynamische Wärme hüllt.",
        "description_en": "Deep and solar, with red fruits and silky tannins, wrapping the soul in biodynamic warmth like a sunset over the lake.",
        "description_fr": "Profond et solaire, avec des fruits rouges et des tanins soyeux, enveloppant l'âme de chaleur biodynamique comme un coucher de soleil sur le lac.",
        "food_pairings_de": ["Rehrücken", "Pilzrisotto"],
        "food_pairings_en": ["Saddle of venison", "Mushroom risotto"],
        "food_pairings_fr": ["Selle de chevreuil", "Risotto aux champignons"],
    },
    {
        "name": "Œil de Perdrix 2024",
        "winery": "Caves de la Ville de Neuchâtel",
        "region": "Neuenburg",
        "grape_variety": "Pinot Noir",
        "wine_color": "rosé",
        "price_category": "€€",
        "description_de": "Zartrosa und verlockend, ein Rosé, der das Herz mit Erdbeere und mineralischer Frische umwebt – pure, sommerliche Sinnlichkeit.",
        "description_en": "Delicate pink and alluring, a rosé that weaves around the heart with strawberry and mineral freshness – pure, summery sensuality.",
        "description_fr": "Rose délicat et séduisant, un rosé qui enveloppe le cœur de fraise et de fraîcheur minérale – pure sensualité estivale.",
        "food_pairings_de": ["Salate mit Erdbeeren", "Gegrillter Lachs"],
        "food_pairings_en": ["Salads with strawberries", "Grilled salmon"],
        "food_pairings_fr": ["Salades aux fraises", "Saumon grillé"],
    },
    {
        "name": "Œil de Perdrix Sélection Tradition 2024",
        "winery": "Caves du Château d'Auvernier",
        "region": "Auvernier",
        "grape_variety": "Pinot Noir",
        "wine_color": "rosé",
        "price_category": "€€€",
        "description_de": "Frisch und blumig, mit Pfirsich und Kräutern, der wie ein Flüstern des Sees die Seele erfrischt und verjüngt.",
        "description_en": "Fresh and floral, with peach and herbs, refreshing and rejuvenating the soul like a whisper from the lake.",
        "description_fr": "Frais et floral, avec de la pêche et des herbes, rafraîchissant et rajeunissant l'âme comme un murmure du lac.",
        "food_pairings_de": ["Papet Vaudois", "Meeresfrüchte"],
        "food_pairings_en": ["Papet Vaudois", "Seafood"],
        "food_pairings_fr": ["Papet Vaudois", "Fruits de mer"],
    },
    {
        "name": "Lacrima Nobilis 2022",
        "winery": "Les Caves du Prieuré",
        "region": "Bevaix",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Elegant und filigran, mit Kirsche und Leder, das die Seele in burgundische Melancholie taucht – ein edler Tropfen der Tradition.",
        "description_en": "Elegant and delicate, with cherry and leather, plunging the soul into Burgundian melancholy – a noble drop of tradition.",
        "description_fr": "Élégant et délicat, avec de la cerise et du cuir, plongeant l'âme dans la mélancolie bourguignonne – une noble goutte de tradition.",
        "food_pairings_de": ["Entenbrust", "Tomme Vaudoise"],
        "food_pairings_en": ["Duck breast", "Tomme Vaudoise"],
        "food_pairings_fr": ["Magret de canard", "Tomme Vaudoise"],
    },
    {
        "name": "Neuchâtel Pinot Noir 2023",
        "winery": "Sandoz Vins",
        "region": "Cressier",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Robust und beerig, ein Pinot, der das Herz mit wilden Beeren und erdiger Wärme in herbstliche Wälder lockt.",
        "description_en": "Robust and berry-filled, a Pinot that lures the heart into autumn forests with wild berries and earthy warmth.",
        "description_fr": "Robuste et fruité, un Pinot qui attire le cœur dans les forêts d'automne avec des baies sauvages et une chaleur terreuse.",
        "food_pairings_de": ["Lammkoteletts", "Wildpastete"],
        "food_pairings_en": ["Lamb chops", "Game pâté"],
        "food_pairings_fr": ["Côtelettes d'agneau", "Pâté de gibier"],
    },
    {
        "name": "Neuchâtel Pinot Noir Barrique 2023",
        "winery": "Sandoz Vins",
        "region": "Cressier",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Würzig und intensiv, mit Eiche und Beeren, das wie ein warmer Föhn die Seele in Ekstase versetzt.",
        "description_en": "Spicy and intense, with oak and berries, sending the soul into ecstasy like a warm Föhn wind.",
        "description_fr": "Épicé et intense, avec du chêne et des baies, envoyant l'âme en extase comme un foehn chaud.",
        "food_pairings_de": ["BBQ-Rippen", "Scharfe Wurst"],
        "food_pairings_en": ["BBQ ribs", "Spicy sausage"],
        "food_pairings_fr": ["Côtes BBQ", "Saucisse épicée"],
    },
    {
        "name": "Pinot Noir 2023",
        "winery": "Les Vins de Boris Keller",
        "region": "Milvignes",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Nervös und aromatisch, mit Grapefruit und Kräutern, der wie ein Bergquell die Seele klärt und Hoffnung weckt.",
        "description_en": "Nervous and aromatic, with grapefruit and herbs, clearing the soul like a mountain spring and awakening hope.",
        "description_fr": "Nerveux et aromatique, avec du pamplemousse et des herbes, purifiant l'âme comme une source de montagne et éveillant l'espoir.",
        "food_pairings_de": ["Krebse", "Frischer Salat"],
        "food_pairings_en": ["Crayfish", "Fresh salad"],
        "food_pairings_fr": ["Écrevisses", "Salade fraîche"],
    },
    {
        "name": "Œil de Perdrix 2024",
        "winery": "Caves des Lauriers – Jungo & Fellmann",
        "region": "Cressier",
        "grape_variety": "Pinot Noir",
        "wine_color": "rosé",
        "price_category": "€€",
        "description_de": "Knackig und erfrischend, ein Rosé, der wie ein Lachen die Seele weckt – lebendig und unbeschwert.",
        "description_en": "Crisp and refreshing, a rosé that awakens the soul like laughter – lively and carefree.",
        "description_fr": "Croquant et rafraîchissant, un rosé qui éveille l'âme comme un rire – vif et insouciant.",
        "food_pairings_de": ["Fischfilet", "Sommergemüse"],
        "food_pairings_en": ["Fish fillet", "Summer vegetables"],
        "food_pairings_fr": ["Filet de poisson", "Légumes d'été"],
    },
    {
        "name": "Pinot Noir Vieilles Vignes Bio 2023",
        "winery": "Domaine du Pampre",
        "region": "Peseux",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Reich und honigartig, ein Bio-Pinot, der wie ein Traum die Seele umhüllt – tief und authentisch.",
        "description_en": "Rich and honeyed, an organic Pinot that wraps the soul like a dream – deep and authentic.",
        "description_fr": "Riche et miellé, un Pinot bio qui enveloppe l'âme comme un rêve – profond et authentique.",
        "food_pairings_de": ["Foie gras", "Reifer Camembert"],
        "food_pairings_en": ["Foie gras", "Aged Camembert"],
        "food_pairings_fr": ["Foie gras", "Camembert affiné"],
    },
    {
        "name": "Pinot Noir 2023",
        "winery": "Domaine Hôpital Pourtalès",
        "region": "Neuenburg",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Filigran und fruchtig, mit Kirschen und Geheimnissen, der das Herz mit leichter Traurigkeit und purer Freude erfüllt.",
        "description_en": "Delicate and fruity, with cherries and secrets, filling the heart with gentle sadness and pure joy.",
        "description_fr": "Délicat et fruité, avec des cerises et des secrets, remplissant le cœur d'une douce tristesse et d'une joie pure.",
        "food_pairings_de": ["Entenbrust", "Pilze"],
        "food_pairings_en": ["Duck breast", "Mushrooms"],
        "food_pairings_fr": ["Magret de canard", "Champignons"],
    },
    {
        "name": "Pinot Noir Barrique 2022",
        "winery": "Domaine Hôpital Pourtalès",
        "region": "Neuenburg",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Samten und fruchtig, ein Barrique, der das Herz mit Pflaume und Schokolade in tiefe Zufriedenheit wiegt.",
        "description_en": "Velvety and fruity, a barrique that rocks the heart into deep contentment with plum and chocolate.",
        "description_fr": "Velouté et fruité, une barrique qui berce le cœur dans une profonde satisfaction avec de la prune et du chocolat.",
        "food_pairings_de": ["Roastbeef", "Dunkle Schokolade"],
        "food_pairings_en": ["Roast beef", "Dark chocolate"],
        "food_pairings_fr": ["Rôti de bœuf", "Chocolat noir"],
    },
    {
        "name": "Œil de Perdrix 2024",
        "winery": "Caves de la Béroche",
        "region": "Saint-Blaise",
        "grape_variety": "Pinot Noir",
        "wine_color": "rosé",
        "price_category": "€€",
        "description_de": "Rein und mineralisch, ein Tropfen, der das Herz mit Bergfrische reinigt – kühler und klar.",
        "description_en": "Pure and mineral, a drop that cleanses the heart with mountain freshness – cool and clear.",
        "description_fr": "Pur et minéral, une goutte qui purifie le cœur avec la fraîcheur de la montagne – frais et clair.",
        "food_pairings_de": ["Austern", "Leichte Vorspeisen"],
        "food_pairings_en": ["Oysters", "Light appetizers"],
        "food_pairings_fr": ["Huîtres", "Entrées légères"],
    },
    {
        "name": "Blanc Béroche 2024",
        "winery": "Caves de la Béroche",
        "region": "Saint-Blaise",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Frisch und blumig, ein Chasselas, der die Seele in goldene Sonnenuntergänge taucht.",
        "description_en": "Fresh and floral, a Chasselas that immerses the soul in golden sunsets.",
        "description_fr": "Frais et floral, un Chasselas qui plonge l'âme dans des couchers de soleil dorés.",
        "food_pairings_de": ["Huhn mit Kräutern", "Raclette"],
        "food_pairings_en": ["Chicken with herbs", "Raclette"],
        "food_pairings_fr": ["Poulet aux herbes", "Raclette"],
    },
    {
        "name": "Non-Filtré 2024",
        "winery": "Caves des Lauriers – Jungo & Fellmann",
        "region": "Cressier",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Sprudelnd und fröhlich, ein Schaumwein, der die Seele mit kindlicher Freude weckt – ungeschliffen und vital.",
        "description_en": "Bubbly and cheerful, a sparkling wine that awakens the soul with childlike joy – unrefined and vital.",
        "description_fr": "Pétillant et joyeux, un vin mousseux qui éveille l'âme avec une joie enfantine – brut et vital.",
        "food_pairings_de": ["Tapas", "Lachs"],
        "food_pairings_en": ["Tapas", "Salmon"],
        "food_pairings_fr": ["Tapas", "Saumon"],
    },
    {
        "name": "Château d'Auvernier Sélection Tradition 2024",
        "winery": "Caves du Château d'Auvernier",
        "region": "Auvernier",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Ikonisch und tief, mit Honig und Stein, das wie ein Erbe die Seele berührt.",
        "description_en": "Iconic and deep, with honey and stone, touching the soul like an heritage.",
        "description_fr": "Iconique et profond, avec du miel et de la pierre, touchant l'âme comme un héritage.",
        "food_pairings_de": ["Geflügel", "Meeresfrüchte"],
        "food_pairings_en": ["Poultry", "Seafood"],
        "food_pairings_fr": ["Volaille", "Fruits de mer"],
    },
    {
        "name": "Château d'Auvernier Non Filtré 2024",
        "winery": "Caves du Château d'Auvernier",
        "region": "Auvernier",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Lebendig und salzig, ein Tropfen, der das Herz mit Meeresbrise umweht.",
        "description_en": "Lively and salty, a drop that caresses the heart with sea breeze.",
        "description_fr": "Vif et salé, une goutte qui caresse le cœur avec la brise marine.",
        "food_pairings_de": ["Schalentiere", "Zitronenhähnchen"],
        "food_pairings_en": ["Shellfish", "Lemon chicken"],
        "food_pairings_fr": ["Crustacés", "Poulet au citron"],
    },
    {
        "name": "Cru de la Ville 2024",
        "winery": "Caves de la Ville de Neuchâtel",
        "region": "Neuenburg",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Elegant und strukturiert, mit Apfel und Mineral, das wie ein Tanz die Seele erheitert.",
        "description_en": "Elegant and structured, with apple and mineral, cheering the soul like a dance.",
        "description_fr": "Élégant et structuré, avec de la pomme et du minéral, égayant l'âme comme une danse.",
        "food_pairings_de": ["Asiatische Gerichte", "Gebratener Tofu"],
        "food_pairings_en": ["Asian dishes", "Fried tofu"],
        "food_pairings_fr": ["Plats asiatiques", "Tofu frit"],
    },
    {
        "name": "Le Charmeur 2024",
        "winery": "Caves des Lauriers – Jungo & Fellmann",
        "region": "Cressier",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Exotisch und würzig, ein Weiß, der das Herz mit orientalischem Flair verzaubert.",
        "description_en": "Exotic and spicy, a white that enchants the heart with oriental flair.",
        "description_fr": "Exotique et épicé, un blanc qui enchante le cœur avec un flair oriental.",
        "food_pairings_de": ["Curry", "Vegetarische Gerichte"],
        "food_pairings_en": ["Curry", "Vegetarian dishes"],
        "food_pairings_fr": ["Curry", "Plats végétariens"],
    },
    {
        "name": "Champréveyres Chasselas 2023",
        "winery": "Alain Gerber",
        "region": "Hauterive",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Fruchtig und ausgewogen, ein Chasselas, der das Herz mit erdiger Wärme umfängt.",
        "description_en": "Fruity and balanced, a Chasselas that embraces the heart with earthy warmth.",
        "description_fr": "Fruité et équilibré, un Chasselas qui embrasse le cœur avec une chaleur terreuse.",
        "food_pairings_de": ["Fondue", "Rind"],
        "food_pairings_en": ["Fondue", "Beef"],
        "food_pairings_fr": ["Fondue", "Bœuf"],
    },
    {
        "name": "Cru d'Hauterive Pinot Noir 2022",
        "winery": "Alain Gerber",
        "region": "Hauterive",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Tief und tanninreich, mit Leder und Beeren, die die Seele in alte Legenden eintauchen lassen.",
        "description_en": "Deep and tannic, with leather and berries that immerse the soul in ancient legends.",
        "description_fr": "Profond et tannique, avec du cuir et des baies qui plongent l'âme dans les légendes anciennes.",
        "food_pairings_de": ["Rehrücken", "Dunkles Fleisch"],
        "food_pairings_en": ["Saddle of venison", "Dark meat"],
        "food_pairings_fr": ["Selle de chevreuil", "Viande brune"],
    },
    {
        "name": "Expression Chardonnay 2023",
        "winery": "Alain Gerber",
        "region": "Hauterive",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Cremig und blumig, ein Chardonnay, der die Seele in sonnendurchflutete Gärten entführt.",
        "description_en": "Creamy and floral, a Chardonnay that transports the soul to sun-drenched gardens.",
        "description_fr": "Crémeux et floral, un Chardonnay qui transporte l'âme dans des jardins ensoleillés.",
        "food_pairings_de": ["Gegrillter Lachs", "Asiatisches Gemüse"],
        "food_pairings_en": ["Grilled salmon", "Asian vegetables"],
        "food_pairings_fr": ["Saumon grillé", "Légumes asiatiques"],
    },
    {
        "name": "Divico 2023",
        "winery": "Domaine Divernois",
        "region": "Milvignes",
        "grape_variety": "Divico",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Robust und fruchtig, ein Piwi, der die Seele mit innovativer Kraft stärkt.",
        "description_en": "Robust and fruity, a Piwi that strengthens the soul with innovative power.",
        "description_fr": "Robuste et fruité, un Piwi qui renforce l'âme avec une puissance innovante.",
        "food_pairings_de": ["Wild", "Pilze"],
        "food_pairings_en": ["Game", "Mushrooms"],
        "food_pairings_fr": ["Gibier", "Champignons"],
    },
    {
        "name": "Harmonie 2023",
        "winery": "Domaine Divernois",
        "region": "Milvignes",
        "grape_variety": "Assemblage",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Harmonisch und komplex, ein Assemblage, der wie ein Chor die Seele erhebt.",
        "description_en": "Harmonious and complex, an assemblage that elevates the soul like a choir.",
        "description_fr": "Harmonieux et complexe, un assemblage qui élève l'âme comme un chœur.",
        "food_pairings_de": ["Lamm", "Dunkles Fleisch"],
        "food_pairings_en": ["Lamb", "Dark meat"],
        "food_pairings_fr": ["Agneau", "Viande brune"],
    },
    {
        "name": "Instant Plaisir Rosé 2024",
        "winery": "Domaine Divernois",
        "region": "Milvignes",
        "grape_variety": "Pinot Noir",
        "wine_color": "rosé",
        "price_category": "€€",
        "description_de": "Leicht und verlockend, ein Rosé, der wie ein Flüstern die Seele mit Sommerfreude erfüllt.",
        "description_en": "Light and alluring, a rosé that fills the soul with summer joy like a whisper.",
        "description_fr": "Léger et séduisant, un rosé qui remplit l'âme de joie estivale comme un murmure.",
        "food_pairings_de": ["Tapas", "Lachs"],
        "food_pairings_en": ["Tapas", "Salmon"],
        "food_pairings_fr": ["Tapas", "Saumon"],
    },
    {
        "name": "Chasselas 2024",
        "winery": "Sandoz Vins",
        "region": "Cressier",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Frisch und aromatisch, ein Chasselas, der wie ein erstes Erwachen im Frühling das Herz erfrischt.",
        "description_en": "Fresh and aromatic, a Chasselas that refreshes the heart like the first awakening in spring.",
        "description_fr": "Frais et aromatique, un Chasselas qui rafraîchit le cœur comme le premier réveil au printemps.",
        "food_pairings_de": ["Austern", "Ziegenkäse-Platte"],
        "food_pairings_en": ["Oysters", "Goat cheese platter"],
        "food_pairings_fr": ["Huîtres", "Plateau de fromage de chèvre"],
    },
    {
        "name": "Le 1808 Chasselas Effervescent 2023",
        "winery": "Domaine Hôpital Pourtalès",
        "region": "Neuenburg",
        "grape_variety": "Chasselas",
        "wine_color": "schaumwein",
        "price_category": "€€€",
        "description_de": "Perlend und mystisch, ein Effervescent, der die Seele alchemistisch verändert.",
        "description_en": "Sparkling and mystical, an effervescent that alchemically transforms the soul.",
        "description_fr": "Pétillant et mystique, un effervescent qui transforme l'âme de manière alchimique.",
        "food_pairings_de": ["Wild", "Reifer Käse"],
        "food_pairings_en": ["Game", "Aged cheese"],
        "food_pairings_fr": ["Gibier", "Fromage affiné"],
    },
    {
        "name": "Pinot Noir Clos de la Perrière 2022",
        "winery": "Domaine Saint-Sébaste",
        "region": "Saint-Blaise",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Biodynamisch und tief, ein Clos, der wie ein Geheimnis die Seele berührt.",
        "description_en": "Biodynamic and deep, a Clos that touches the soul like a secret.",
        "description_fr": "Biodynamique et profond, un Clos qui touche l'âme comme un secret.",
        "food_pairings_de": ["Rindfleisch", "Wild"],
        "food_pairings_en": ["Beef", "Game"],
        "food_pairings_fr": ["Bœuf", "Gibier"],
    },
    {
        "name": "Chasselas Vieilles Vignes 2023",
        "winery": "Domaine Saint-Sébaste",
        "region": "Saint-Blaise",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Reich und beerig, ein Vieilles Vignes, der die Seele in neuenburgische Wälder entführt.",
        "description_en": "Rich and berry-filled, a Vieilles Vignes that transports the soul to Neuchâtel forests.",
        "description_fr": "Riche et fruité, un Vieilles Vignes qui transporte l'âme dans les forêts neuchâteloises.",
        "food_pairings_de": ["Lammkoteletts", "Käse"],
        "food_pairings_en": ["Lamb chops", "Cheese"],
        "food_pairings_fr": ["Côtelettes d'agneau", "Fromage"],
    },
    {
        "name": "Orange Wine 2023",
        "winery": "Domaine Saint-Sébaste",
        "region": "Saint-Blaise",
        "grape_variety": "Chasselas",
        "wine_color": "orange",
        "price_category": "€€€",
        "description_de": "Innovativ und würzig, ein Orange, der das Herz mit moderner Freude erfüllt.",
        "description_en": "Innovative and spicy, an Orange wine that fills the heart with modern joy.",
        "description_fr": "Innovant et épicé, un vin Orange qui remplit le cœur de joie moderne.",
        "food_pairings_de": ["Grillgemüse", "Fisch"],
        "food_pairings_en": ["Grilled vegetables", "Fish"],
        "food_pairings_fr": ["Légumes grillés", "Poisson"],
    },
    {
        "name": "Chasselas 2023",
        "winery": "Domaine des Landions",
        "region": "Cortaillod",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Hoch und aromatisch, mit Mandeln und Nektarinen, das die Seele auf Höhenflüge trägt.",
        "description_en": "High and aromatic, with almonds and nectarines, carrying the soul to soaring heights.",
        "description_fr": "Haut et aromatique, avec des amandes et des nectarines, portant l'âme vers les sommets.",
        "food_pairings_de": ["Käseplatte", "Gebratenes Forellenfilet"],
        "food_pairings_en": ["Cheese platter", "Pan-fried trout fillet"],
        "food_pairings_fr": ["Plateau de fromages", "Filet de truite poêlé"],
    },
    {
        "name": "Pinot Noir 2022",
        "winery": "Domaine des Landions",
        "region": "Cortaillod",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Samtig und elegant, ein Pinot, der das Herz mit burgundischer Poesie umfängt.",
        "description_en": "Velvety and elegant, a Pinot that embraces the heart with Burgundian poetry.",
        "description_fr": "Velouté et élégant, un Pinot qui embrasse le cœur avec la poésie bourguignonne.",
        "food_pairings_de": ["Ente", "Pilzgerichte"],
        "food_pairings_en": ["Duck", "Mushroom dishes"],
        "food_pairings_fr": ["Canard", "Plats aux champignons"],
    },
    {
        "name": "Chardonnay 2023",
        "winery": "Domaine de la Maison Carrée",
        "region": "Auvernier",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Opulent und harmonisch, mit Pfirsich und Eiche, das wie ein warmer Föhn die Seele streichelt.",
        "description_en": "Opulent and harmonious, with peach and oak, caressing the soul like a warm Föhn wind.",
        "description_fr": "Opulent et harmonieux, avec de la pêche et du chêne, caressant l'âme comme un foehn chaud.",
        "food_pairings_de": ["Gegrilltes Huhn", "Tomme"],
        "food_pairings_en": ["Grilled chicken", "Tomme"],
        "food_pairings_fr": ["Poulet grillé", "Tomme"],
    },
    {
        "name": "Œil de Perdrix 2023",
        "winery": "Domaine de la Maison Carrée",
        "region": "Auvernier",
        "grape_variety": "Pinot Noir",
        "wine_color": "rosé",
        "price_category": "€€",
        "description_de": "Zart und blumig, ein Rosé, der die Seele mit valaisanischer Reinheit erfüllt.",
        "description_en": "Delicate and floral, a rosé that fills the soul with Valaisan purity.",
        "description_fr": "Délicat et floral, un rosé qui remplit l'âme de pureté valaisanne.",
        "food_pairings_de": ["Fisch", "Salate"],
        "food_pairings_en": ["Fish", "Salads"],
        "food_pairings_fr": ["Poisson", "Salades"],
    },
    {
        "name": "Merlot 2022",
        "winery": "Jacques Tatasciore",
        "region": "Cressier",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Weich und fruchtig, ein Merlot, der das Herz mit warmer Umarmung beschenkt.",
        "description_en": "Soft and fruity, a Merlot that gifts the heart with a warm embrace.",
        "description_fr": "Doux et fruité, un Merlot qui offre au cœur une étreinte chaleureuse.",
        "food_pairings_de": ["Pasta mit Tomatensauce", "Käse"],
        "food_pairings_en": ["Pasta with tomato sauce", "Cheese"],
        "food_pairings_fr": ["Pâtes à la sauce tomate", "Fromage"],
    },
    {
        "name": "Pinot Noir Réserve 2022",
        "winery": "Caves Alain Gerber",
        "region": "Hauterive",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Monumental und samtig, ein Réserve, der die Seele in göttliche Ekstase versetzt.",
        "description_en": "Monumental and velvety, a Réserve that sends the soul into divine ecstasy.",
        "description_fr": "Monumental et velouté, une Réserve qui envoie l'âme en extase divine.",
        "food_pairings_de": ["Entrecôte", "Schokolade"],
        "food_pairings_en": ["Entrecôte", "Chocolate"],
        "food_pairings_fr": ["Entrecôte", "Chocolat"],
    },
    {
        "name": "Gewürztraminer PULP 2024",
        "winery": "Lavanchy Vins",
        "region": "Neuenburg",
        "grape_variety": "Gewürztraminer",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Exotisch und intensiv, ein Gewürz, der wie ein Traum die Seele umhüllt.",
        "description_en": "Exotic and intense, a Gewürztraminer that wraps the soul like a dream.",
        "description_fr": "Exotique et intense, un Gewürztraminer qui enveloppe l'âme comme un rêve.",
        "food_pairings_de": ["Foie gras", "Desserts"],
        "food_pairings_en": ["Foie gras", "Desserts"],
        "food_pairings_fr": ["Foie gras", "Desserts"],
    },
    {
        "name": "Sauvignier 2024",
        "winery": "Lavanchy Vins",
        "region": "Neuenburg",
        "grape_variety": "Sauvignier Gris",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Nervös und lebendig, ein Blanc, der die Seele mit alpiner Frische weckt.",
        "description_en": "Nervous and lively, a Blanc that awakens the soul with Alpine freshness.",
        "description_fr": "Nerveux et vif, un Blanc qui éveille l'âme avec la fraîcheur alpine.",
        "food_pairings_de": ["Krebse", "Kräutersuppe"],
        "food_pairings_en": ["Crayfish", "Herb soup"],
        "food_pairings_fr": ["Écrevisses", "Soupe aux herbes"],
    },
    {
        "name": "Chasselas Non Filtré 2024",
        "winery": "Caves de la Béroche",
        "region": "Saint-Blaise",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Frisch und vielschichtig, ein Non Filtré, der das Herz mit kindlicher Freude weckt.",
        "description_en": "Fresh and multilayered, a Non Filtré that awakens the heart with childlike joy.",
        "description_fr": "Frais et complexe, un Non Filtré qui éveille le cœur avec une joie enfantine.",
        "food_pairings_de": ["Tapas", "Lachs"],
        "food_pairings_en": ["Tapas", "Salmon"],
        "food_pairings_fr": ["Tapas", "Saumon"],
    },
    {
        "name": "Pinot Noir 2023",
        "winery": "Domaine Bouvet-Jabloir",
        "region": "Auvernier",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Filigran und robust, ein Pinot, der die Seele mit imperierender Kraft erhebt.",
        "description_en": "Delicate yet robust, a Pinot that elevates the soul with imperial power.",
        "description_fr": "Délicat mais robuste, un Pinot qui élève l'âme avec une puissance impériale.",
        "food_pairings_de": ["Lamm", "Pilze"],
        "food_pairings_en": ["Lamb", "Mushrooms"],
        "food_pairings_fr": ["Agneau", "Champignons"],
    },
    {
        "name": "Chardonnay 2023",
        "winery": "Domaine Bouvet-Jabloir",
        "region": "Auvernier",
        "grape_variety": "Chardonnay",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Reich und strukturiert, ein Grand Cru, der die Seele in städtischer Eleganz badet.",
        "description_en": "Rich and structured, a Grand Cru that bathes the soul in urban elegance.",
        "description_fr": "Riche et structuré, un Grand Cru qui baigne l'âme dans l'élégance urbaine.",
        "food_pairings_de": ["Krustentiere", "Geflügel"],
        "food_pairings_en": ["Crustaceans", "Poultry"],
        "food_pairings_fr": ["Crustacés", "Volaille"],
    },
    {
        "name": "Œil de Perdrix 2024",
        "winery": "Caves Alain Gerber",
        "region": "Hauterive",
        "grape_variety": "Pinot Noir",
        "wine_color": "rosé",
        "price_category": "€€",
        "description_de": "Sonnig und fruchtig, ein Rosé, der das Herz mit sommerlicher Leichtigkeit umfängt.",
        "description_en": "Sunny and fruity, a rosé that embraces the heart with summery lightness.",
        "description_fr": "Ensoleillé et fruité, un rosé qui embrasse le cœur avec une légèreté estivale.",
        "food_pairings_de": ["Sommergerichte", "Frischkäse"],
        "food_pairings_en": ["Summer dishes", "Fresh cheese"],
        "food_pairings_fr": ["Plats d'été", "Fromage frais"],
    },
    {
        "name": "Chasselas 2023",
        "winery": "Domaine de Chambleau",
        "region": "Colombier",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Mineralisch und nervös, ein Chasselas, der die Seele mit seefrischem Wind umweht.",
        "description_en": "Mineral and nervous, a Chasselas that caresses the soul with lake-fresh wind.",
        "description_fr": "Minéral et nerveux, un Chasselas qui caresse l'âme avec le vent frais du lac.",
        "food_pairings_de": ["Schalentiere", "Zitronenhähnchen"],
        "food_pairings_en": ["Shellfish", "Lemon chicken"],
        "food_pairings_fr": ["Crustacés", "Poulet au citron"],
    },
    {
        "name": "Pinot Noir 2022",
        "winery": "Caves du Prieuré",
        "region": "Bevaix",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Tief und amaronig, ein Rot, das wie ein Abgrund die Seele fesselt.",
        "description_en": "Deep and Amarone-like, a red that captivates the soul like an abyss.",
        "description_fr": "Profond et de style Amarone, un rouge qui captive l'âme comme un abîme.",
        "food_pairings_de": ["Stark gewürzte Fleischgerichte"],
        "food_pairings_en": ["Heavily spiced meat dishes"],
        "food_pairings_fr": ["Plats de viande très épicés"],
    },
    {
        "name": "Chasselas 2024",
        "winery": "Caves des Lauriers",
        "region": "Cressier",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Historisch und elegant, ein Wein, der die Seele mit zeitloser Tiefe berührt.",
        "description_en": "Historic and elegant, a wine that touches the soul with timeless depth.",
        "description_fr": "Historique et élégant, un vin qui touche l'âme avec une profondeur intemporelle.",
        "food_pairings_de": ["Geflügel", "Meeresfrüchte"],
        "food_pairings_en": ["Poultry", "Seafood"],
        "food_pairings_fr": ["Volaille", "Fruits de mer"],
    },
    {
        "name": "Merlot 2023",
        "winery": "Sandoz Vins",
        "region": "Cressier",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Frisch und ausgewogen, ein Merlot, der das Herz mit klassischer Freude erheitert.",
        "description_en": "Fresh and balanced, a Merlot that cheers the heart with classic joy.",
        "description_fr": "Frais et équilibré, un Merlot qui égaye le cœur avec une joie classique.",
        "food_pairings_de": ["Fondue", "Rind"],
        "food_pairings_en": ["Fondue", "Beef"],
        "food_pairings_fr": ["Fondue", "Bœuf"],
    },
    {
        "name": "Viognier 2023",
        "winery": "Domaine du Pampre",
        "region": "Peseux",
        "grape_variety": "Viognier",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Reich und beerig, ein Viognier, der die Seele in neuenburgische Wälder entführt.",
        "description_en": "Rich and berry-filled, a Viognier that transports the soul to Neuchâtel forests.",
        "description_fr": "Riche et fruité, un Viognier qui transporte l'âme dans les forêts neuchâteloises.",
        "food_pairings_de": ["Lammkoteletts", "Käse"],
        "food_pairings_en": ["Lamb chops", "Cheese"],
        "food_pairings_fr": ["Côtelettes d'agneau", "Fromage"],
    },
    {
        "name": "Pinot Gris 2022",
        "winery": "Domaine Hôpital Pourtalès",
        "region": "Neuenburg",
        "grape_variety": "Pinot Gris",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Elegant und pfeffrig, ein Gris, der die Seele mit orientalischem Zauber umhüllt.",
        "description_en": "Elegant and peppery, a Gris that wraps the soul in oriental magic.",
        "description_fr": "Élégant et poivré, un Gris qui enveloppe l'âme de magie orientale.",
        "food_pairings_de": ["Gewürzhähnchen", "Auberginen"],
        "food_pairings_en": ["Spiced chicken", "Eggplant"],
        "food_pairings_fr": ["Poulet épicé", "Aubergines"],
    },
    {
        "name": "Flétri 2023",
        "winery": "Caves de la Ville de Neuchâtel",
        "region": "Neuenburg",
        "grape_variety": "Chasselas",
        "wine_color": "süsswein",
        "price_category": "€€€€",
        "description_de": "Süß und komplex, ein Edelsüßer, der das Herz mit nobler Verführung erfüllt.",
        "description_en": "Sweet and complex, a noble sweet wine that fills the heart with noble seduction.",
        "description_fr": "Doux et complexe, un vin liquoreux qui remplit le cœur d'une noble séduction.",
        "food_pairings_de": ["Desserts", "Blauschimmelkäse"],
        "food_pairings_en": ["Desserts", "Blue cheese"],
        "food_pairings_fr": ["Desserts", "Fromage bleu"],
    },
    {
        "name": "Chasselas Grand Cru 2024",
        "winery": "Alain Gerber",
        "region": "Hauterive",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Hoch und rein, ein Grand Cru, der wie ein Gipfelblick die Seele erweitert.",
        "description_en": "High and pure, a Grand Cru that expands the soul like a summit view.",
        "description_fr": "Haut et pur, un Grand Cru qui élargit l'âme comme une vue du sommet.",
        "food_pairings_de": ["Käseplatte", "Leichte Vorspeisen"],
        "food_pairings_en": ["Cheese platter", "Light appetizers"],
        "food_pairings_fr": ["Plateau de fromages", "Entrées légères"],
    },
]


async def add_neuenburg_wines():
    """Add the Top 50 Neuchâtel wines to the database"""
    
    mongo_url = os.environ.get("MONGO_URL")
    db_name = os.environ.get("DB_NAME", "wine_sommelier")
    
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    
    print("=" * 60)
    print("🏔️  TOP 50 NEUENBURGER WEINE - IMPORT")
    print("   Frische des Sees und Jura-Zauber")
    print("=" * 60)
    print()
    
    added = 0
    skipped = 0
    
    for wine in NEUENBURG_WINES:
        # Check if wine already exists
        existing = await db.public_wines.find_one({
            "name": wine["name"],
            "winery": wine["winery"]
        })
        
        if existing:
            print(f"  ⏭️  {wine['name']} ({wine['winery']}) - bereits vorhanden")
            skipped += 1
            continue
        
        wine_doc = {
            "id": str(uuid4()),
            "name": wine["name"],
            "winery": wine["winery"],
            "country": "Schweiz",
            "region": f"Neuenburg - {wine['region']}",
            "appellation": "AOC Neuchâtel",
            "grape_variety": wine["grape_variety"],
            "wine_color": wine["wine_color"],
            "price_category": wine["price_category"],
            "description_de": wine["description_de"],
            "description_en": wine["description_en"],
            "description_fr": wine["description_fr"],
            "food_pairings_de": wine["food_pairings_de"],
            "food_pairings_en": wine["food_pairings_en"],
            "food_pairings_fr": wine["food_pairings_fr"],
            "created_at": datetime.now(timezone.utc).isoformat(),
            "source": "Top 50 Neuenburger Weine - Sélection des Vins de Neuchâtel 2024/2025, GaultMillau, Falstaff, Grand Prix du Vin Suisse"
        }
        
        await db.public_wines.insert_one(wine_doc)
        print(f"  ✅ {wine['name']} ({wine['winery']})")
        added += 1
    
    print()
    print("=" * 60)
    print(f"🎉 IMPORT ABGESCHLOSSEN!")
    print(f"   Hinzugefügt: {added}")
    print(f"   Übersprungen: {skipped}")
    print("=" * 60)
    
    # Gesamtzahl prüfen
    total = await db.public_wines.count_documents({})
    swiss = await db.public_wines.count_documents({"country": "Schweiz"})
    neuenburg = await db.public_wines.count_documents({"region": {"$regex": "Neuenburg", "$options": "i"}})
    graubuenden = await db.public_wines.count_documents({"region": {"$regex": "Graubünden", "$options": "i"}})
    genf = await db.public_wines.count_documents({"region": {"$regex": "Genf", "$options": "i"}})
    tessin = await db.public_wines.count_documents({"region": {"$regex": "Tessin", "$options": "i"}})
    waadt = await db.public_wines.count_documents({"region": {"$regex": "Waadt", "$options": "i"}})
    wallis = await db.public_wines.count_documents({"region": {"$regex": "Wallis", "$options": "i"}})
    
    print(f"\n📊 Datenbank-Status:")
    print(f"   Gesamte Weine: {total}")
    print(f"   Schweizer Weine: {swiss}")
    print(f"   - Neuenburg: {neuenburg}")
    print(f"   - Graubünden: {graubuenden}")
    print(f"   - Genf: {genf}")
    print(f"   - Tessin: {tessin}")
    print(f"   - Waadt: {waadt}")
    print(f"   - Wallis: {wallis}")
    print(f"\n   À votre santé! 🍷🇨🇭")

if __name__ == "__main__":
    asyncio.run(add_neuenburg_wines())
