#!/usr/bin/env python3
"""
Skript zum Hinzufügen der Top 50 Walliser Weine zur Datenbank
Mit deutschen, englischen und französischen Beschreibungen
"""

import asyncio
import os
from uuid import uuid4
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

# Die 50 Walliser Weine mit allen Details
WALLIS_WINES = [
    {
        "name": "Petite Arvine Grain par Grain 2018",
        "winery": "Marie-Thérèse Chappaz",
        "region": "Fully",
        "grape_variety": "Petite Arvine",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Ein Wein wie ein flüsternder Bergbach: frisch, mineralisch, mit Zitrusnoten, die an verirrte Sommerträume erinnern und die Seele mit salziger Lebendigkeit umhüllen.",
        "description_en": "A wine like a whispering mountain stream: fresh, mineral, with citrus notes that recall lost summer dreams and envelop the soul with salty vitality.",
        "description_fr": "Un vin comme un ruisseau de montagne murmurant : frais, minéral, avec des notes d'agrumes qui rappellent des rêves d'été égarés et enveloppent l'âme d'une vivacité salée.",
        "food_pairings_de": ["Gegrillter Fisch", "Ziegenkäse-Creme"],
        "food_pairings_en": ["Grilled fish", "Goat cheese cream"],
        "food_pairings_fr": ["Poisson grillé", "Crème de chèvre"],
    },
    {
        "name": "Cayas 2009",
        "winery": "Jean-René Germanier",
        "region": "Vétroz",
        "grape_variety": "Heida",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Ein zeitloser Poet unter den Weißen, reif und golden, der von Aprikosenkonfitüre und Honig träumt – ein Schluck, der die Vergänglichkeit des Lebens in ewiger Harmonie feiert.",
        "description_en": "A timeless poet among whites, ripe and golden, dreaming of apricot jam and honey – a sip that celebrates life's transience in eternal harmony.",
        "description_fr": "Un poète intemporel parmi les blancs, mûr et doré, rêvant de confiture d'abricot et de miel – une gorgée qui célèbre l'éphémère de la vie en harmonie éternelle.",
        "food_pairings_de": ["Foie gras", "Reifer Camembert"],
        "food_pairings_en": ["Foie gras", "Aged Camembert"],
        "food_pairings_fr": ["Foie gras", "Camembert affiné"],
    },
    {
        "name": "Fendant 2022",
        "winery": "Cave Jean-Claude et Vérène Mabillard",
        "region": "Champlan",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Leichtfüßig wie ein Tanz auf den Terrassen, mit knackiger Säure und Apfelaromen, die das Herz mit kindlicher Freude erfüllen.",
        "description_en": "Light-footed as a dance on the terraces, with crisp acidity and apple aromas that fill the heart with childlike joy.",
        "description_fr": "Léger comme une danse sur les terrasses, avec une acidité croquante et des arômes de pomme qui remplissent le cœur d'une joie enfantine.",
        "food_pairings_de": ["Frische Austern", "Raclette"],
        "food_pairings_en": ["Fresh oysters", "Raclette"],
        "food_pairings_fr": ["Huîtres fraîches", "Raclette"],
    },
    {
        "name": "Johannisberg Fernand Cina 2022",
        "winery": "Fernand Cina",
        "region": "Salquenen",
        "grape_variety": "Silvaner",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Eine warme Umarmung aus Pfirsich und Kräutern, der die Seele in sonnendurchflutete Wiesen entführt – pure, emotionale Wärme in jedem Tropfen.",
        "description_en": "A warm embrace of peach and herbs that transports the soul to sun-drenched meadows – pure, emotional warmth in every drop.",
        "description_fr": "Une étreinte chaleureuse de pêche et d'herbes qui transporte l'âme vers des prairies ensoleillées – une chaleur pure et émotionnelle dans chaque goutte.",
        "food_pairings_de": ["Geflügelterrine", "Sommergemüse"],
        "food_pairings_en": ["Poultry terrine", "Summer vegetables"],
        "food_pairings_fr": ["Terrine de volaille", "Légumes d'été"],
    },
    {
        "name": "Heida Grand Métral 2022",
        "winery": "Provins",
        "region": "Sion",
        "grape_variety": "Heida",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Hochalpin und mystisch, mit Mandeln und Nektarinen, die wie ein Echo der Alpen wehen – ein Wein, der die Seele auf Höhenflüge trägt.",
        "description_en": "High alpine and mystical, with almonds and nectarines that drift like an echo of the Alps – a wine that carries the soul to great heights.",
        "description_fr": "Haut-alpin et mystique, avec des amandes et des nectarines qui flottent comme un écho des Alpes – un vin qui porte l'âme vers les sommets.",
        "food_pairings_de": ["Käseplatte", "Gebratenes Forellenfilet"],
        "food_pairings_en": ["Cheese platter", "Pan-fried trout fillet"],
        "food_pairings_fr": ["Plateau de fromages", "Filet de truite poêlé"],
    },
    {
        "name": "Jean des Crêtes Petite Arvine 2022",
        "winery": "Maison Maye",
        "region": "Riddes",
        "grape_variety": "Petite Arvine",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Nervös und lebendig, ein Funke Glycin und Grapefruit, der das Herz mit alpiner Frische weckt und verjüngt.",
        "description_en": "Nervous and vibrant, a spark of wisteria and grapefruit that awakens and rejuvenates the heart with alpine freshness.",
        "description_fr": "Nerveux et vivant, une étincelle de glycine et de pamplemousse qui éveille et rajeunit le cœur avec une fraîcheur alpine.",
        "food_pairings_de": ["Krebse", "Leichte Kräutersuppe"],
        "food_pairings_en": ["Crayfish", "Light herb soup"],
        "food_pairings_fr": ["Écrevisses", "Soupe légère aux herbes"],
    },
    {
        "name": "Syrah 2022",
        "winery": "Domaine Claudy Clavien",
        "region": "Miège",
        "grape_variety": "Syrah",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Dunkel und leidenschaftlich, mit Pfeffer und Beeren, die wie ein verbotener Kuss die Sinne entzünden – ein roter Sturm, der die Seele bebt.",
        "description_en": "Dark and passionate, with pepper and berries that ignite the senses like a forbidden kiss – a red storm that shakes the soul.",
        "description_fr": "Sombre et passionné, avec du poivre et des baies qui enflamment les sens comme un baiser interdit – une tempête rouge qui fait trembler l'âme.",
        "food_pairings_de": ["Lammragout", "Dunkle Schokolade"],
        "food_pairings_en": ["Lamb ragout", "Dark chocolate"],
        "food_pairings_fr": ["Ragoût d'agneau", "Chocolat noir"],
    },
    {
        "name": "Cornalin Les Empereurs 2022",
        "winery": "Cave La Romaine",
        "region": "Flanthey",
        "grape_variety": "Cornalin",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Samten und fruchtig, ein veloutierter Traum von Kirschen und Wald, der die Seele in sanfte Umarmung wiegt.",
        "description_en": "Velvety and fruity, a smooth dream of cherries and forest that cradles the soul in gentle embrace.",
        "description_fr": "Velouté et fruité, un rêve soyeux de cerises et de forêt qui berce l'âme dans une douce étreinte.",
        "food_pairings_de": ["Wildpastete", "Pilzrisotto"],
        "food_pairings_en": ["Game pâté", "Mushroom risotto"],
        "food_pairings_fr": ["Pâté de gibier", "Risotto aux champignons"],
    },
    {
        "name": "Dôle Salquenen Fernand Cina 2022",
        "winery": "Fernand Cina",
        "region": "Salquenen",
        "grape_variety": "Pinot Noir, Gamay",
        "wine_color": "rot",
        "price_category": "€€",
        "description_de": "Frisch und fruchtig, ein Duett aus Pinot Noir und Gamay, das wie ein Spaziergang durch herbstliche Weinberge das Herz erheitert.",
        "description_en": "Fresh and fruity, a duet of Pinot Noir and Gamay that gladdens the heart like a walk through autumn vineyards.",
        "description_fr": "Frais et fruité, un duo de Pinot Noir et Gamay qui réjouit le cœur comme une promenade dans les vignobles d'automne.",
        "food_pairings_de": ["Rindfleisch-Tartar", "Käsefondue"],
        "food_pairings_en": ["Beef tartare", "Cheese fondue"],
        "food_pairings_fr": ["Tartare de bœuf", "Fondue au fromage"],
    },
    {
        "name": "Humagne Rouge de Fully 2022",
        "winery": "Cave Jean Maret Anthony Baselgia",
        "region": "Fully",
        "grape_variety": "Humagne Rouge",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Robust und temperamentvoll, mit wilden Früchten und Violetten, die die Seele mit uriger Kraft durchfluten.",
        "description_en": "Robust and spirited, with wild fruits and violets that flood the soul with primal strength.",
        "description_fr": "Robuste et fougueux, avec des fruits sauvages et des violettes qui inondent l'âme d'une force primitive.",
        "food_pairings_de": ["Gegrilltes Steak", "Wildgerichte"],
        "food_pairings_en": ["Grilled steak", "Game dishes"],
        "food_pairings_fr": ["Steak grillé", "Plats de gibier"],
    },
    {
        "name": "Fendant 2021",
        "winery": "Cave les Sentes",
        "region": "Sierre",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Rein und mineralisch, ein kühler Hauch von Zitrone, der wie ein Bergnebel die Seele klärt und erfrischt.",
        "description_en": "Pure and mineral, a cool breath of lemon that clears and refreshes the soul like mountain mist.",
        "description_fr": "Pur et minéral, un souffle frais de citron qui clarifie et rafraîchit l'âme comme la brume de montagne.",
        "food_pairings_de": ["Meeresfrüchte", "Frischer Salat"],
        "food_pairings_en": ["Seafood", "Fresh salad"],
        "food_pairings_fr": ["Fruits de mer", "Salade fraîche"],
    },
    {
        "name": "Johannisberg l'Orpailleur 2021",
        "winery": "Frédéric Dumoulin",
        "region": "Uvrier",
        "grape_variety": "Silvaner",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Elegant und blumig, ein Wein, der die Seele in goldene Sonnenuntergänge taucht.",
        "description_en": "Elegant and floral, a wine that immerses the soul in golden sunsets.",
        "description_fr": "Élégant et floral, un vin qui plonge l'âme dans des couchers de soleil dorés.",
        "food_pairings_de": ["Huhn mit Kräutern", "Milde Raclette"],
        "food_pairings_en": ["Herb chicken", "Mild Raclette"],
        "food_pairings_fr": ["Poulet aux herbes", "Raclette douce"],
    },
    {
        "name": "Païen Les Écrins 2020",
        "winery": "Cave la Colombe",
        "region": "Conthey",
        "grape_variety": "Heida",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Exotisch und würzig, mit Apfel und Gewürzen, die wie ein Geheimnis die Seele verzaubern.",
        "description_en": "Exotic and spicy, with apple and spices that enchant the soul like a secret.",
        "description_fr": "Exotique et épicé, avec de la pomme et des épices qui enchantent l'âme comme un secret.",
        "food_pairings_de": ["Asiatische Gerichte", "Gebratener Tofu"],
        "food_pairings_en": ["Asian dishes", "Pan-fried tofu"],
        "food_pairings_fr": ["Plats asiatiques", "Tofu poêlé"],
    },
    {
        "name": "Petite Arvine de Chamoson La Vouettaz 2021",
        "winery": "Cave Colline de Daval",
        "region": "Sierre",
        "grape_variety": "Petite Arvine",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Lebendig und salzig, ein Tropfen, der die Seele mit Meeresbrise und Bergluft umweht.",
        "description_en": "Vibrant and salty, a drop that envelops the soul with sea breeze and mountain air.",
        "description_fr": "Vivant et salé, une goutte qui enveloppe l'âme de brise marine et d'air de montagne.",
        "food_pairings_de": ["Schalentiere", "Zitronenhähnchen"],
        "food_pairings_en": ["Shellfish", "Lemon chicken"],
        "food_pairings_fr": ["Crustacés", "Poulet au citron"],
    },
    {
        "name": "Dôle les Coteaux de Sierre 2021",
        "winery": "Cave Sinclair",
        "region": "Loc-sur-Sierre",
        "grape_variety": "Pinot Noir, Gamay",
        "wine_color": "rot",
        "price_category": "€€",
        "description_de": "Ausgewogen und beerig, ein Wein, der das Herz mit erdiger Wärme umfängt.",
        "description_en": "Balanced and berry-rich, a wine that embraces the heart with earthy warmth.",
        "description_fr": "Équilibré et fruité, un vin qui embrasse le cœur d'une chaleur terreuse.",
        "food_pairings_de": ["Pasta Bolognese", "Herzhaftes Brot"],
        "food_pairings_en": ["Pasta Bolognese", "Hearty bread"],
        "food_pairings_fr": ["Pâtes bolognaise", "Pain rustique"],
    },
    {
        "name": "Humagne Rouge Ardévaz 2020",
        "winery": "Domaines Rouvinez",
        "region": "Sierre",
        "grape_variety": "Humagne Rouge",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Tief und tanninreich, mit Noten von Leder und Beeren, die die Seele in alte Legenden eintauchen lassen.",
        "description_en": "Deep and tannic, with notes of leather and berries that immerse the soul in ancient legends.",
        "description_fr": "Profond et tannique, avec des notes de cuir et de baies qui plongent l'âme dans d'anciennes légendes.",
        "food_pairings_de": ["Rehrücken", "Dunkles Fleisch"],
        "food_pairings_en": ["Saddle of venison", "Dark meat"],
        "food_pairings_fr": ["Selle de chevreuil", "Viande brune"],
    },
    {
        "name": "Syrah 2020",
        "winery": "Celliers de Vétroz Famille Fontannaz",
        "region": "Vétroz",
        "grape_variety": "Syrah",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Würzig und intensiv, ein Feuerwerk aus Pfeffer und Brombeeren, das die Sinne in Ekstase versetzt.",
        "description_en": "Spicy and intense, a firework of pepper and blackberries that sends the senses into ecstasy.",
        "description_fr": "Épicé et intense, un feu d'artifice de poivre et de mûres qui envoie les sens en extase.",
        "food_pairings_de": ["BBQ-Rippen", "Scharfe Wurst"],
        "food_pairings_en": ["BBQ ribs", "Spicy sausage"],
        "food_pairings_fr": ["Côtes BBQ", "Saucisse épicée"],
    },
    {
        "name": "Cornalin Réserve 2020",
        "winery": "Cave La Romaine",
        "region": "Flanthey",
        "grape_variety": "Cornalin",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Komplex und elegant, mit Kirschen und Gewürzen, die die Seele in sanfter Tiefe baden.",
        "description_en": "Complex and elegant, with cherries and spices that bathe the soul in gentle depth.",
        "description_fr": "Complexe et élégant, avec des cerises et des épices qui baignent l'âme dans une douce profondeur.",
        "food_pairings_de": ["Ente", "Pilzragout"],
        "food_pairings_en": ["Duck", "Mushroom ragout"],
        "food_pairings_fr": ["Canard", "Ragoût de champignons"],
    },
    {
        "name": "Pinot Noir Hurlevent 2021",
        "winery": "Les Fils de Ch. Favre",
        "region": "Sion",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Filigran und fruchtig, ein Windhauch aus Kirschen, der das Herz mit leichter Traurigkeit und purer Freude erfüllt.",
        "description_en": "Delicate and fruity, a breath of wind carrying cherries that fills the heart with gentle sadness and pure joy.",
        "description_fr": "Délicat et fruité, un souffle de vent de cerises qui remplit le cœur d'une légère tristesse et d'une joie pure.",
        "food_pairings_de": ["Entenbrust", "Pilze"],
        "food_pairings_en": ["Duck breast", "Mushrooms"],
        "food_pairings_fr": ["Magret de canard", "Champignons"],
    },
    {
        "name": "Grain Pinot Charrat 2021",
        "winery": "Domaine Chappaz",
        "region": "Fully",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Reich und beerig, ein Pinot, der die Seele in valaisanische Wälder entführt.",
        "description_en": "Rich and berry-laden, a Pinot that transports the soul to Valaisan forests.",
        "description_fr": "Riche et fruité, un Pinot qui transporte l'âme dans les forêts valaisannes.",
        "food_pairings_de": ["Lammkoteletts", "Käse"],
        "food_pairings_en": ["Lamb chops", "Cheese"],
        "food_pairings_fr": ["Côtelettes d'agneau", "Fromage"],
    },
    {
        "name": "La Magdalena 2021",
        "winery": "André Fontannaz",
        "region": "Vétroz",
        "grape_variety": "Assemblage",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Tief und mineralisch, mit dunklen Früchten, die wie ein Geheimnis die Seele berühren.",
        "description_en": "Deep and mineral, with dark fruits that touch the soul like a secret.",
        "description_fr": "Profond et minéral, avec des fruits noirs qui touchent l'âme comme un secret.",
        "food_pairings_de": ["Rindfleisch", "Wild"],
        "food_pairings_en": ["Beef", "Game"],
        "food_pairings_fr": ["Bœuf", "Gibier"],
    },
    {
        "name": "Syrah AOC Valais 2021",
        "winery": "Albert Mathier & Fils",
        "region": "Salquenen",
        "grape_variety": "Syrah",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Elegant und pfeffrig, ein Wein, der die Seele mit orientalischem Zauber umhüllt.",
        "description_en": "Elegant and peppery, a wine that envelops the soul with oriental magic.",
        "description_fr": "Élégant et poivré, un vin qui enveloppe l'âme de magie orientale.",
        "food_pairings_de": ["Gewürzhähnchen", "Auberginen"],
        "food_pairings_en": ["Spiced chicken", "Eggplant"],
        "food_pairings_fr": ["Poulet épicé", "Aubergines"],
    },
    {
        "name": "Merlot Les Serpentines 2021",
        "winery": "Gérald Besse",
        "region": "Martigny",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Weich und fruchtig, ein Merlot, der das Herz mit samtenen Umarmungen beschenkt.",
        "description_en": "Soft and fruity, a Merlot that gifts the heart with velvety embraces.",
        "description_fr": "Doux et fruité, un Merlot qui offre au cœur des étreintes veloutées.",
        "food_pairings_de": ["Pasta mit Tomatensauce", "Käse"],
        "food_pairings_en": ["Pasta with tomato sauce", "Cheese"],
        "food_pairings_fr": ["Pâtes sauce tomate", "Fromage"],
    },
    {
        "name": "Cuvée Madame Rosmarie Mathier Rouge 2021",
        "winery": "Albert Mathier",
        "region": "Salquenen",
        "grape_variety": "Assemblage",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Assemblage aus Tradition, mit Beeren und Gewürzen, die die Seele in familiäre Wärme tauchen.",
        "description_en": "A traditional assemblage, with berries and spices that immerse the soul in familial warmth.",
        "description_fr": "Un assemblage traditionnel, avec des baies et des épices qui plongent l'âme dans une chaleur familiale.",
        "food_pairings_de": ["Roastbeef", "Schokoladendessert"],
        "food_pairings_en": ["Roast beef", "Chocolate dessert"],
        "food_pairings_fr": ["Rôti de bœuf", "Dessert au chocolat"],
    },
    {
        "name": "Brûlefer Fendant de Sion",
        "winery": "Provins",
        "region": "Sion",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Knackig und erfrischend, ein Fendant, der wie ein Lachen die Seele weckt.",
        "description_en": "Crisp and refreshing, a Fendant that awakens the soul like laughter.",
        "description_fr": "Croquant et rafraîchissant, un Fendant qui éveille l'âme comme un rire.",
        "food_pairings_de": ["Fischfilet", "Salat"],
        "food_pairings_en": ["Fish fillet", "Salad"],
        "food_pairings_fr": ["Filet de poisson", "Salade"],
    },
    {
        "name": "Fendant Les Mazots",
        "winery": "Maurice Gay",
        "region": "Sion",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Mineralisch und rein, ein Tropfen, der die Seele mit Bergfrische reinigt.",
        "description_en": "Mineral and pure, a drop that cleanses the soul with mountain freshness.",
        "description_fr": "Minéral et pur, une goutte qui purifie l'âme avec la fraîcheur de la montagne.",
        "food_pairings_de": ["Austern", "Leichte Vorspeisen"],
        "food_pairings_en": ["Oysters", "Light appetizers"],
        "food_pairings_fr": ["Huîtres", "Amuse-bouches légers"],
    },
    {
        "name": "Fendant sans Culotte",
        "winery": "Maurice Gay",
        "region": "Sion",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Frech und sprudelnd, ein Wein, der das Herz mit unbeschwertem Genuss erfüllt.",
        "description_en": "Cheeky and effervescent, a wine that fills the heart with carefree pleasure.",
        "description_fr": "Effronté et pétillant, un vin qui remplit le cœur d'un plaisir insouciant.",
        "food_pairings_de": ["Tapas", "Käse"],
        "food_pairings_en": ["Tapas", "Cheese"],
        "food_pairings_fr": ["Tapas", "Fromage"],
    },
    {
        "name": "Fendant Grand Cru Ville de Sion",
        "winery": "Provins",
        "region": "Sion",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Edel und strukturiert, ein Grand Cru, der die Seele in städtischer Eleganz badet.",
        "description_en": "Noble and structured, a Grand Cru that bathes the soul in urban elegance.",
        "description_fr": "Noble et structuré, un Grand Cru qui baigne l'âme dans l'élégance urbaine.",
        "food_pairings_de": ["Krustentiere", "Geflügel"],
        "food_pairings_en": ["Crustaceans", "Poultry"],
        "food_pairings_fr": ["Crustacés", "Volaille"],
    },
    {
        "name": "Soleil du Valais Fendant",
        "winery": "Provins",
        "region": "Sion",
        "grape_variety": "Chasselas",
        "wine_color": "weiss",
        "price_category": "€€",
        "description_de": "Sonnig und fruchtig, ein Wein, der das Herz mit sommerlicher Leichtigkeit umfängt.",
        "description_en": "Sunny and fruity, a wine that embraces the heart with summery lightness.",
        "description_fr": "Ensoleillé et fruité, un vin qui embrasse le cœur d'une légèreté estivale.",
        "food_pairings_de": ["Sommergerichte", "Frischkäse"],
        "food_pairings_en": ["Summer dishes", "Fresh cheese"],
        "food_pairings_fr": ["Plats d'été", "Fromage frais"],
    },
    {
        "name": "Cornalin 2023",
        "winery": "Charles Bonvin",
        "region": "Sion",
        "grape_variety": "Cornalin",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Fruchtig und robust, ein Cornalin, der die Seele mit erdiger Kraft stärkt.",
        "description_en": "Fruity and robust, a Cornalin that strengthens the soul with earthy power.",
        "description_fr": "Fruité et robuste, un Cornalin qui renforce l'âme d'une puissance terreuse.",
        "food_pairings_de": ["Wild", "Pilze"],
        "food_pairings_en": ["Game", "Mushrooms"],
        "food_pairings_fr": ["Gibier", "Champignons"],
    },
    {
        "name": "Cornalin",
        "winery": "Philippe Varone",
        "region": "Sion",
        "grape_variety": "Cornalin",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Intensiv und tanninreich, ein Tropfen, der wie ein Bergsturm die Sinne weckt.",
        "description_en": "Intense and tannic, a drop that awakens the senses like a mountain storm.",
        "description_fr": "Intense et tannique, une goutte qui éveille les sens comme une tempête de montagne.",
        "food_pairings_de": ["Lamm", "Dunkles Fleisch"],
        "food_pairings_en": ["Lamb", "Dark meat"],
        "food_pairings_fr": ["Agneau", "Viande brune"],
    },
    {
        "name": "Cornalin 2023",
        "winery": "Yvo Mathier",
        "region": "Salquenen",
        "grape_variety": "Cornalin",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Samtig und würzig, ein Wein, der die Seele in tiefe Reflexion taucht.",
        "description_en": "Velvety and spicy, a wine that plunges the soul into deep reflection.",
        "description_fr": "Velouté et épicé, un vin qui plonge l'âme dans une profonde réflexion.",
        "food_pairings_de": ["Ragouts", "Käse"],
        "food_pairings_en": ["Ragouts", "Cheese"],
        "food_pairings_fr": ["Ragoûts", "Fromage"],
    },
    {
        "name": "Dôle du Valais",
        "winery": "Emery",
        "region": "Sierre",
        "grape_variety": "Pinot Noir, Gamay",
        "wine_color": "rot",
        "price_category": "€€",
        "description_de": "Frisch und ausgewogen, ein Dôle, der das Herz mit klassischer Freude erheitert.",
        "description_en": "Fresh and balanced, a Dôle that gladdens the heart with classic joy.",
        "description_fr": "Frais et équilibré, une Dôle qui réjouit le cœur d'une joie classique.",
        "food_pairings_de": ["Fondue", "Rind"],
        "food_pairings_en": ["Fondue", "Beef"],
        "food_pairings_fr": ["Fondue", "Bœuf"],
    },
    {
        "name": "Oeil de Perdrix Mon Amour Rosé Pinot Noir",
        "winery": "Sélection Hugi",
        "region": "Wallis",
        "grape_variety": "Pinot Noir",
        "wine_color": "rosé",
        "price_category": "€€",
        "description_de": "Zartrosa und verlockend, ein Rosé, der die Seele mit sommerlicher Sinnlichkeit umwebt.",
        "description_en": "Delicate pink and alluring, a Rosé that weaves the soul with summery sensuality.",
        "description_fr": "Rose délicat et séduisant, un Rosé qui tisse l'âme d'une sensualité estivale.",
        "food_pairings_de": ["Salate", "Lachs"],
        "food_pairings_en": ["Salads", "Salmon"],
        "food_pairings_fr": ["Salades", "Saumon"],
    },
    {
        "name": "Heida AOC Valais",
        "winery": "Cave Fin Bec",
        "region": "Saillon",
        "grape_variety": "Heida",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Aromatisch und mineralisch, ein Heida, der wie ein Hohelied die Seele erhebt.",
        "description_en": "Aromatic and mineral, a Heida that uplifts the soul like a canticle.",
        "description_fr": "Aromatique et minéral, un Heida qui élève l'âme comme un cantique.",
        "food_pairings_de": ["Käse", "Fisch"],
        "food_pairings_en": ["Cheese", "Fish"],
        "food_pairings_fr": ["Fromage", "Poisson"],
    },
    {
        "name": "Petite Arvine 1883",
        "winery": "Maurice Gay",
        "region": "Sion",
        "grape_variety": "Petite Arvine",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Historisch und elegant, ein Wein, der die Seele mit zeitloser Tiefe berührt.",
        "description_en": "Historic and elegant, a wine that touches the soul with timeless depth.",
        "description_fr": "Historique et élégant, un vin qui touche l'âme d'une profondeur intemporelle.",
        "food_pairings_de": ["Geflügel", "Meeresfrüchte"],
        "food_pairings_en": ["Poultry", "Seafood"],
        "food_pairings_fr": ["Volaille", "Fruits de mer"],
    },
    {
        "name": "Petite Arvine Nobles Cépages",
        "winery": "Provins",
        "region": "Sion",
        "grape_variety": "Petite Arvine",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Rein und lebendig, ein Tropfen, der das Herz mit nobler Frische erfrischt.",
        "description_en": "Pure and vibrant, a drop that refreshes the heart with noble freshness.",
        "description_fr": "Pur et vivant, une goutte qui rafraîchit le cœur d'une fraîcheur noble.",
        "food_pairings_de": ["Krebse", "Kräuterdesserts"],
        "food_pairings_en": ["Crayfish", "Herb desserts"],
        "food_pairings_fr": ["Écrevisses", "Desserts aux herbes"],
    },
    {
        "name": "Petite Arvine",
        "winery": "Philippe Varone",
        "region": "Sion",
        "grape_variety": "Petite Arvine",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Zitrusfrisch und salzig, ein Arvine, der die Seele auf Reisen schickt.",
        "description_en": "Citrus-fresh and salty, an Arvine that sends the soul traveling.",
        "description_fr": "Frais d'agrumes et salé, un Arvine qui envoie l'âme en voyage.",
        "food_pairings_de": ["Gegrillter Fisch", "Zitronengerichte"],
        "food_pairings_en": ["Grilled fish", "Lemon dishes"],
        "food_pairings_fr": ["Poisson grillé", "Plats au citron"],
    },
    {
        "name": "Petite Arvine 2023",
        "winery": "Yvo Mathier",
        "region": "Salquenen",
        "grape_variety": "Petite Arvine",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Intensiv und mineralisch, ein Wein, der wie ein Gebet die Seele beruhigt.",
        "description_en": "Intense and mineral, a wine that calms the soul like a prayer.",
        "description_fr": "Intense et minéral, un vin qui apaise l'âme comme une prière.",
        "food_pairings_de": ["Hummer", "Milder Käse"],
        "food_pairings_en": ["Lobster", "Mild cheese"],
        "food_pairings_fr": ["Homard", "Fromage doux"],
    },
    {
        "name": "Païen Les Serpentines 2018",
        "winery": "Gérald Besse",
        "region": "Martigny",
        "grape_variety": "Heida",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Gewürzt und exotisch, ein Païen, der das Herz mit orientalischem Flair verzaubert.",
        "description_en": "Spiced and exotic, a Païen that enchants the heart with oriental flair.",
        "description_fr": "Épicé et exotique, un Païen qui enchante le cœur d'un flair oriental.",
        "food_pairings_de": ["Curry", "Vegetarische Gerichte"],
        "food_pairings_en": ["Curry", "Vegetarian dishes"],
        "food_pairings_fr": ["Curry", "Plats végétariens"],
    },
    {
        "name": "Dieu de Viège Assemblage 2021",
        "winery": "Chanton Weine",
        "region": "Visp",
        "grape_variety": "Assemblage",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Komplex und harmonisch, ein Assemblage, der die Seele in göttliche Ekstase versetzt.",
        "description_en": "Complex and harmonious, an assemblage that sends the soul into divine ecstasy.",
        "description_fr": "Complexe et harmonieux, un assemblage qui envoie l'âme en extase divine.",
        "food_pairings_de": ["Entrecôte", "Schokolade"],
        "food_pairings_en": ["Entrecôte", "Chocolate"],
        "food_pairings_fr": ["Entrecôte", "Chocolat"],
    },
    {
        "name": "Profondo Diversitas 2020",
        "winery": "Cave du Rhodan - Mounir Weine",
        "region": "Salquenen",
        "grape_variety": "Assemblage",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Tief und amaronig, ein Rot, das wie ein Abgrund die Seele fesselt.",
        "description_en": "Deep and Amarone-like, a red that captivates the soul like an abyss.",
        "description_fr": "Profond et amaronien, un rouge qui captive l'âme comme un abîme.",
        "food_pairings_de": ["Stark gewürzte Fleischgerichte"],
        "food_pairings_en": ["Heavily spiced meat dishes"],
        "food_pairings_fr": ["Plats de viande très épicés"],
    },
    {
        "name": "Pinot Noir Collection F 2020",
        "winery": "Les Fils de Ch. Favre",
        "region": "Sion",
        "grape_variety": "Pinot Noir",
        "wine_color": "rot",
        "price_category": "€€€€",
        "description_de": "Elegant und filigran, ein Pinot, der das Herz mit burgundischer Poesie umfängt.",
        "description_en": "Elegant and delicate, a Pinot that embraces the heart with Burgundian poetry.",
        "description_fr": "Élégant et délicat, un Pinot qui embrasse le cœur de poésie bourguignonne.",
        "food_pairings_de": ["Ente", "Pilzgerichte"],
        "food_pairings_en": ["Duck", "Mushroom dishes"],
        "food_pairings_fr": ["Canard", "Plats aux champignons"],
    },
    {
        "name": "Humagne Blanc",
        "winery": "Défayes & Crettenand",
        "region": "Leytron",
        "grape_variety": "Humagne Blanc",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Frisch und blumig, ein Weiß, das die Seele mit valaisanischer Reinheit erfüllt.",
        "description_en": "Fresh and floral, a white that fills the soul with Valaisan purity.",
        "description_fr": "Frais et floral, un blanc qui remplit l'âme de pureté valaisanne.",
        "food_pairings_de": ["Fisch", "Salate"],
        "food_pairings_en": ["Fish", "Salads"],
        "food_pairings_fr": ["Poisson", "Salades"],
    },
    {
        "name": "Ermitage",
        "winery": "Gilles Besse",
        "region": "Martigny",
        "grape_variety": "Marsanne",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Reich und honigartig, ein Surmaturé, der wie ein Traum die Seele umhüllt.",
        "description_en": "Rich and honeyed, a late harvest that envelops the soul like a dream.",
        "description_fr": "Riche et miellé, un surmaturé qui enveloppe l'âme comme un rêve.",
        "food_pairings_de": ["Foie gras", "Desserts"],
        "food_pairings_en": ["Foie gras", "Desserts"],
        "food_pairings_fr": ["Foie gras", "Desserts"],
    },
    {
        "name": "Merlot",
        "winery": "Valentina Andrei",
        "region": "Saillon",
        "grape_variety": "Merlot",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Weich und fruchtig, ein Merlot, der das Herz mit warmer Umarmung beschenkt.",
        "description_en": "Soft and fruity, a Merlot that gifts the heart with a warm embrace.",
        "description_fr": "Doux et fruité, un Merlot qui offre au cœur une étreinte chaleureuse.",
        "food_pairings_de": ["Pasta", "Käse"],
        "food_pairings_en": ["Pasta", "Cheese"],
        "food_pairings_fr": ["Pâtes", "Fromage"],
    },
    {
        "name": "Alchimie Blanche Ermitage",
        "winery": "Christophe Abbet",
        "region": "Martigny",
        "grape_variety": "Marsanne",
        "wine_color": "weiss",
        "price_category": "€€€€",
        "description_de": "Mystisch und komplex, ein Wein, der die Seele alchemistisch verändert.",
        "description_en": "Mystical and complex, a wine that alchemically transforms the soul.",
        "description_fr": "Mystique et complexe, un vin qui transforme alchimiquement l'âme.",
        "food_pairings_de": ["Wild", "Reifer Käse"],
        "food_pairings_en": ["Game", "Aged cheese"],
        "food_pairings_fr": ["Gibier", "Fromage affiné"],
    },
    {
        "name": "Les Empereurs Cornalin",
        "winery": "Joël Briguet",
        "region": "Corin",
        "grape_variety": "Cornalin",
        "wine_color": "rot",
        "price_category": "€€€",
        "description_de": "Kaiserlich und robust, ein Cornalin, der die Seele mit imperierender Kraft erhebt.",
        "description_en": "Imperial and robust, a Cornalin that uplifts the soul with commanding power.",
        "description_fr": "Impérial et robuste, un Cornalin qui élève l'âme d'une puissance impérieuse.",
        "food_pairings_de": ["Lamm", "Pilze"],
        "food_pairings_en": ["Lamb", "Mushrooms"],
        "food_pairings_fr": ["Agneau", "Champignons"],
    },
    {
        "name": "Ardévine",
        "winery": "Cave Ardévaz",
        "region": "Leytron",
        "grape_variety": "Assemblage",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Innovativ und fruchtig, ein Hybrid, der das Herz mit moderner Freude erfüllt.",
        "description_en": "Innovative and fruity, a hybrid that fills the heart with modern joy.",
        "description_fr": "Innovant et fruité, un hybride qui remplit le cœur d'une joie moderne.",
        "food_pairings_de": ["Grillgemüse", "Fisch"],
        "food_pairings_en": ["Grilled vegetables", "Fish"],
        "food_pairings_fr": ["Légumes grillés", "Poisson"],
    },
    {
        "name": "Heida Les Fers de Lance 2023",
        "winery": "Philippe Constantin",
        "region": "Salgesch",
        "grape_variety": "Heida",
        "wine_color": "weiss",
        "price_category": "€€€",
        "description_de": "Hoch und rein, ein Heida, der wie ein Gipfelblick die Seele erweitert.",
        "description_en": "High and pure, a Heida that expands the soul like a summit view.",
        "description_fr": "Haut et pur, un Heida qui élargit l'âme comme une vue du sommet.",
        "food_pairings_de": ["Käseplatte", "Leichte Vorspeisen"],
        "food_pairings_en": ["Cheese platter", "Light appetizers"],
        "food_pairings_fr": ["Plateau de fromages", "Amuse-bouches légers"],
    },
]

async def add_wallis_wines():
    """Fügt alle 50 Walliser Weine zur Datenbank hinzu"""
    
    client = AsyncIOMotorClient(os.environ.get('MONGO_URL'))
    db = client[os.environ.get('DB_NAME', 'test_database')]
    
    print("=" * 60)
    print("🍷 TOP 50 WALLISER WEINE - Import")
    print("=" * 60)
    
    added = 0
    skipped = 0
    
    for wine in WALLIS_WINES:
        # Prüfen ob Wein bereits existiert
        existing = await db.public_wines.find_one({
            "name": wine["name"],
            "winery": wine["winery"]
        })
        
        if existing:
            print(f"  ⏭️  {wine['name']} ({wine['winery']}) - bereits vorhanden")
            skipped += 1
            continue
        
        # Wein-Dokument erstellen
        wine_doc = {
            "id": str(uuid4()),
            "name": wine["name"],
            "winery": wine["winery"],
            "country": "Schweiz",
            "region": f"Wallis - {wine['region']}",
            "appellation": "AOC Valais",
            "grape_variety": wine["grape_variety"],
            "wine_color": wine["wine_color"],
            "price_category": wine["price_category"],
            "description_de": wine["description_de"],
            "description_en": wine["description_en"],
            "description_fr": wine["description_fr"],
            "food_pairings_de": wine["food_pairings_de"],
            "food_pairings_en": wine["food_pairings_en"],
            "food_pairings_fr": wine["food_pairings_fr"],
            "created_at": datetime.now(timezone.utc).isoformat(),
            "source": "Top 50 Walliser Weine - Étoiles du Valais, Falstaff, GaultMillau"
        }
        
        await db.public_wines.insert_one(wine_doc)
        print(f"  ✅ {wine['name']} ({wine['winery']})")
        added += 1
    
    print()
    print("=" * 60)
    print(f"🎉 IMPORT ABGESCHLOSSEN!")
    print(f"   Hinzugefügt: {added}")
    print(f"   Übersprungen: {skipped}")
    print("=" * 60)
    
    # Gesamtzahl prüfen
    total = await db.public_wines.count_documents({})
    swiss = await db.public_wines.count_documents({"country": "Schweiz"})
    print(f"\n📊 Datenbank-Status:")
    print(f"   Gesamte Weine: {total}")
    print(f"   Schweizer Weine: {swiss}")

if __name__ == "__main__":
    asyncio.run(add_wallis_wines())
