import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  de: {
    // Navigation
    nav_home: 'Home',
    nav_pairing: 'Pairing',
    nav_cellar: 'Keller',
    nav_sommelier: 'Claude',
    nav_blog: 'Blog',
    nav_feed: 'Community',
    nav_grapes: 'Rebsorten',
    nav_wine_database: 'Wein-DB',
    
    // Home Page
    hero_tagline: 'Die Entdeckung des reinen Genusses',
    hero_title: 'Claude – Ihr Master Sommelier',
    hero_description: 'Master of Wine und leidenschaftlicher Koch. Die einzige Empfehlung, die nichts verkauft, außer Ihrem perfekten Moment. Entdecken Sie die Harmonie von Wein und Speise – unabhängig, ehrlich, genussvoll.',
    cta_pairing: 'Wein-Pairing starten',
    cta_cellar: 'Mein Weinkeller',
    philosophy_tagline: 'Unsere Philosophie',
    philosophy_title: 'Wein als Kultur & bewusster Genuss',
    philosophy_text1: 'Wein ist mehr als ein Getränk – er ist ein Erlebnis, ein Stück Lebensfreude und ein tief verwurzelter Teil unserer Zivilisation. Er erzählt Geschichten von Terroir und Handwerk und ist der ideale Begleiter für die schönsten Momente – in der Partnerschaft, im Kreis der Familie, mit Freund:innen oder bei geschäftlichen Anlässen.',
    philosophy_text2: 'Als WINE.PAIRING.ONLINE sehen wir Wein vor allem als idealen Essensbegleiter. Er hat die Fähigkeit, ein Gericht zu vollenden, Aromen zu verstärken und jeden Bissen in einen bewussten Genussmoment zu verwandeln. In einer Zeit, in der Genussmittel wie Wein, Bier und Spirituosen zunehmend stigmatisiert werden, setzen wir ein bewusst positives Zeichen: Wein, achtsam und moderat genossen, ist eine Bereicherung des Lebens und ein Ausdruck von Kultur.',
    philosophy_quote: '„Tauchen Sie ein in eine Welt, in der jeder Schluck bewusster Genuss ist und Qualität vor Quantität steht."',
    feature_pairing_title: 'Intelligentes Pairing',
    feature_pairing_desc: 'Geben Sie Ihr Gericht ein und erhalten Sie die perfekte Weinempfehlung – aus Ihrem Keller oder allgemein.',
    feature_scanner_title: 'Etiketten-Scanner',
    feature_scanner_desc: 'Fotografieren Sie Ihre Weinetiketten und lassen Sie die KI alle wichtigen Informationen erfassen.',
    feature_sommelier_title: 'Persönlicher Sommelier',
    feature_sommelier_desc: 'Fragen Sie unseren virtuellen Sommelier alles rund um Wein – persönlich und ohne Verkaufsdruck.',
    
    // Claude Persona
    claude_intro_short: 'Über 20 Jahre Erfahrung in Spitzenrestaurants – jetzt in Ihrer Küche, ganz ohne Verkaufsdruck.',
    claude_bio_title: 'Claude – Ihr virtueller Sommelier',
    claude_bio_text1: 'Claude hat über zwei Jahrzehnte in internationalen Sternerestaurants gearbeitet – zuerst am Herd, später als Sommelier. Er liebt es, Gerichte nicht nur technisch, sondern auch emotional zu verstehen.',
    claude_bio_text2: 'Seine Spezialität ist es, Säure, Süße, Bitterkeit und Textur so zu übersetzen, dass Wein und Speise wie aus einer Hand wirken. Statt Verkaufsdruck setzt er auf klare, ehrliche Empfehlungen – so, als würde er direkt an Ihrem Tisch stehen. Für ihn steht bewusster Genuss im Mittelpunkt: Wein soll Momente veredeln, nicht dominieren.',
    
    // Pairing Page
    pairing_tagline: 'Wein-Pairing',
    pairing_title: 'Was möchten Sie essen?',
    pairing_description: 'Beschreiben Sie Ihr Gericht und unser virtueller Sommelier empfiehlt den perfekten Wein.',
    pairing_label: 'Ihr Gericht',
    pairing_placeholder: 'z.B. Gegrilltes Rinderfilet mit Rosmarin-Kartoffeln und Rotwein-Jus...',
    pairing_use_cellar: 'Aus meinem Keller empfehlen',
    pairing_wine_preference: 'Welche Weinart bevorzugen Sie?',
    pairing_all_types: 'Alle Weinarten',
    pairing_white: 'Weißwein',
    pairing_red: 'Rotwein',
    pairing_rose: 'Roséwein',
    pairing_sparkling: 'Schaumwein',
    pairing_sweet: 'Süßwein',
    pairing_button: 'Empfehlung erhalten',
    pairing_loading: 'Claude analysiert... (ca. 5-10 Sek.)',
    pairing_result_title: 'Sommelier-Empfehlung',
    pairing_result_for: 'für',
    pairing_cellar_matches: 'Passende Weine aus Ihrem Keller:',
    pairing_history: 'Letzte Empfehlungen',
    pairing_voice_hint: 'Tippen Sie auf das Mikrofon, um Ihr Gericht zu diktieren',
    pairing_more_details: 'Mehr Details anzeigen',
    pairing_pro_mode_title: 'Profi-Modus – Gaumen-Übersetzer',
    pairing_pro_mode_subtitle: 'Standard: Claude entscheidet selbst. Hier können Kenner bei Bedarf feinjustieren, wie sich das Gericht auf dem Gaumen anfühlt.',
    pairing_dim_richness: 'Reichhaltigkeit',
    pairing_dim_freshness: 'Frische',
    pairing_dim_sweetness: 'Süße',
    pairing_dim_spice: 'Würze',
    pairing_dim_hint_low: 'leicht',
    pairing_dim_hint_high: 'intensiv',
    pairing_why_title: 'Warum dieses Pairing funktioniert',
    pairing_why_fallback: 'Claude erklärt hier gleich in einfachen Worten, warum Wein und Gericht auf Ihrem Gaumen zusammenfinden – entlang Reichhaltigkeit, Frische, Süße und Würze.',
    
    // Feed Page
    feed_tagline: 'Genuss-Community',
    feed_title: 'Pairing-Erlebnisse',
    feed_description: 'Teilen Sie Ihre Wein-Pairing Entdeckungen und lassen Sie sich von anderen inspirieren.',
    feed_members: 'Mitglieder',
    feed_experiences: 'Erlebnisse',
    feed_top_pairings: 'Top Pairings',
    feed_set_name: 'Wie möchten Sie in der Community genannt werden?',
    feed_your_name: 'Ihr Name',
    feed_save_name: 'Speichern',
    feed_share_experience: 'Erlebnis teilen',
    feed_new_post: 'Neues Pairing-Erlebnis',
    feed_new_post_desc: 'Teilen Sie Ihre Entdeckung mit der Community.',
    feed_dish_placeholder: 'Was haben Sie gegessen?',
    feed_wine_placeholder: 'Welchen Wein?',
    feed_rating: 'Wie war die Harmonie?',
    feed_experience_placeholder: 'Beschreiben Sie Ihr Erlebnis... (optional)',
    feed_add_photo: 'Foto hinzufügen (optional)',
    feed_publish: 'Veröffentlichen',
    feed_empty_title: 'Noch keine Erlebnisse',
    feed_empty_desc: 'Seien Sie der Erste, der ein Pairing-Erlebnis teilt!',
    feed_first_post: 'Erstes Erlebnis teilen',
    feed_name_required: 'Bitte geben Sie einen Namen ein',
    feed_fields_required: 'Bitte füllen Sie Gericht und Wein aus',
    feed_post_created: 'Erlebnis geteilt!',
    feed_post_deleted: 'Erlebnis gelöscht',
    feed_confirm_delete: 'Möchten Sie dieses Erlebnis wirklich löschen?',
    feed_delete_forbidden: 'Sie können nur Ihre eigenen Erlebnisse löschen',
    feed_write_comment: 'Kommentar schreiben...',
    feed_just_now: 'Gerade eben',
    feed_minutes_ago: 'Min.',
    feed_hours_ago: 'Std.',
    feed_days_ago: 'Tage',
    
    // Cellar Page
    cellar_tagline: 'Mein Weinkeller',
    cellar_title: 'Ihre Schatzkammer',
    cellar_filter_all: 'Alle Weine',
    cellar_scan: 'Etikett scannen',
    cellar_add: 'Wein hinzufügen',
    cellar_empty_title: 'Ihr Keller ist noch leer',
    cellar_empty_desc: 'Fügen Sie Ihren ersten Wein hinzu oder scannen Sie ein Etikett.',
    cellar_empty_button: 'Ersten Wein hinzufügen',
    cellar_scan_title: 'Weinetikett scannen',
    cellar_scan_desc: 'Fotografieren Sie das Etikett, um den Wein automatisch zu erfassen.',
    cellar_scan_prompt: 'Klicken Sie hier, um ein Foto aufzunehmen',
    cellar_scanning: 'Analysiere Etikett...',
    cellar_add_title: 'Neuen Wein hinzufügen',
    cellar_add_desc: 'Fügen Sie einen Wein zu Ihrem Keller hinzu.',
    cellar_wine_name: 'Weinname *',
    cellar_region: 'Region',
    cellar_year: 'Jahrgang',
    cellar_grape: 'Rebsorte',
    cellar_notes: 'Notizen',
    cellar_upload_image: 'Bild hochladen (optional)',
    cellar_save: 'Wein speichern',
    
    // Chat Page
    chat_title: 'Claude – Ihr Sommelier',
    chat_subtitle: 'Master of Wine & leidenschaftlicher Koch – keine Verkaufsabsicht, nur ehrliche Beratung.',
    chat_empty: 'Stellen Sie Claude eine Frage über Wein...',
    chat_suggestion1: 'Welcher Wein zu Pasta?',
    chat_suggestion2: 'Rotwein oder Weißwein?',
    chat_suggestion3: 'Was macht einen großen Wein aus?',
    chat_placeholder: 'Fragen Sie Claude...',
    chat_voice_hint: 'Tippen Sie auf das Mikrofon, um zu sprechen',
    
    // Grapes
    grapes_tagline: 'Rebsorten-Lexikon',
    grapes_title: 'Die Welt der Rebsorten',
    grapes_description: 'Entdecken Sie die Seele jeder Traube – poetisch beschrieben, mit perfekten Speisen-Pairings.',
    grapes_all: 'Alle',
    grapes_white: 'Weißwein',
    grapes_red: 'Rotwein',
    grapes_empty: 'Keine Rebsorten gefunden',
    grapes_back: 'Zurück zu allen Rebsorten',
    grapes_synonyms: 'Auch bekannt als',
    grapes_body: 'Körper',
    grapes_acidity: 'Säure',
    grapes_tannin: 'Tannin',
    grapes_aging: 'Ausbau',
    grapes_primary_aromas: 'Primäraromen',
    grapes_tertiary_aromas: 'Tertiäraromen',
    grapes_perfect_pairings: 'Perfekt zu',
    grapes_main_regions: 'Hauptanbaugebiete',
    pairing_filter_country: 'Land',
    pairing_filter_trend: 'Trendküche',
    pairing_filter_bestseller: 'Bestseller-Kategorie',

    // Admin Grapes
    admin_grapes_tagline: 'Interne Sommelier-Werkbank',
    admin_grapes_title: 'Rebsorten verwalten',
    admin_grapes_description: 'Generieren Sie neue Rebsorten mit Claude und halten Sie alle Daten für Suche und Pairing konsistent.',
    admin_grapes_refresh: 'Aktualisieren',
    admin_grapes_refreshing: 'Aktualisiere...',
    admin_grapes_normalize_title: 'Daten normalisieren',
    admin_grapes_normalize_button: 'Normalisierung ausführen',
    admin_grapes_normalizing: 'Normalisiere...',
    admin_grapes_normalize_help: 'Skaliert Körper, Säure und Tannin auf ein einheitliches Schema (leicht/mittel/vollmundig bzw. niedrig/mittel/hoch) und bereinigt Aroma- und Speisen-Tags.',
    admin_grapes_generate_title: 'Neue Rebsorte mit Claude generieren',
    admin_grapes_generate_name: 'Name der Rebsorte',
    admin_grapes_generate_name_placeholder: 'z.B. Garnacha, Blaufränkisch...',
    admin_grapes_generate_type: 'Weintyp',
    admin_grapes_generate_type_auto: 'Automatisch erkennen',
    admin_grapes_generate_hint: 'Stil-Hinweis (optional)',
    admin_grapes_generate_hint_placeholder: 'z.B. mediterran, saftig, ideal zu gegrilltem Fleisch',
    admin_grapes_generate_button: 'Rebsorte generieren',
    admin_grapes_generate_running: 'Claude generiert...',
    admin_grapes_last_generated: 'Zuletzt generierte Rebsorte',
    admin_grapes_list_title: 'Bestehende Rebsorten',
    admin_grapes_filter_placeholder: 'Nach Name oder Synonym suchen...',
    admin_grapes_list_empty: 'Keine Rebsorten gefunden.',
    admin_grapes_error_load: 'Rebsorten konnten nicht geladen werden.',
    admin_grapes_error_name_required: 'Bitte geben Sie einen Rebsortennamen ein.',
    admin_grapes_generate_success: 'Rebsorte erfolgreich generiert.',
    admin_grapes_generate_error: 'Fehler bei der Rebsorten-Generierung.',
    admin_grapes_normalize_done: 'Normalisierung abgeschlossen.',
    admin_grapes_normalize_error: 'Fehler bei der Normalisierung.',

    // Admin Dishes
    admin_dishes_tagline: 'Interne Speisenbibliothek',
    admin_dishes_title: 'Gerichte verwalten',
    admin_dishes_description: 'Erzeugen Sie strukturierte Gerichte mit Claude und nutzen Sie sie als Grundlage für präzise Weinempfehlungen.',
    admin_dishes_refresh: 'Aktualisieren',
    admin_dishes_refreshing: 'Aktualisiere...',
    admin_dishes_seed_title: 'Speisen-Datenbank befüllen',
    admin_dishes_seed_button: 'Seed-Batch starten',
    admin_dishes_seed_running: 'Seed-Batch läuft...',
    admin_dishes_seed_help: 'Startet einen Hintergrundjob, der eine kuratierte Liste internationaler Bestseller- und Länderküchen-Gerichte durch Claude strukturiert anlegen lässt.',
    admin_dishes_generate_title: 'Neues Gericht mit Claude generieren',
    admin_dishes_generate_name: 'Name des Gerichts',
    admin_dishes_generate_name_placeholder: 'z.B. Burger, Pad Thai, Spaghetti Bolognese...',
    admin_dishes_generate_country: 'Land (optional)',
    admin_dishes_generate_country_placeholder: 'z.B. Italien, Thailand, USA...',
    admin_dishes_generate_trend: 'Trendküche (optional)',
    admin_dishes_generate_trend_placeholder: 'z.B. Thai, Streetfood, Fine Dining...',
    admin_dishes_generate_category: 'Bestseller-Kategorie (optional)',
    admin_dishes_generate_category_placeholder: 'z.B. burger, pasta, steak, fisch...',
    admin_dishes_generate_button: 'Gericht generieren',
    admin_dishes_generate_running: 'Claude generiert...',
    admin_dishes_last_generated: 'Zuletzt generiertes Gericht',
    admin_dishes_list_title: 'Bestehende Gerichte',
    admin_dishes_filter_placeholder: 'Nach Gericht, Land oder Kategorie suchen...',
    admin_dishes_list_empty: 'Keine Gerichte gefunden.',
    admin_dishes_error_load: 'Gerichte konnten nicht geladen werden.',
    admin_dishes_error_name_required: 'Bitte geben Sie einen Gerichtsnamen ein.',
    admin_dishes_generate_success: 'Gericht erfolgreich generiert.',
    admin_dishes_generate_error: 'Fehler bei der Gerichte-Generierung.',
    admin_dishes_seed_started: 'Seed-Batch gestartet ({count} Gerichte).',
    admin_dishes_seed_error: 'Fehler beim Starten des Seed-Batches.',
    admin_dishes_labels_protein: 'Protein',
    admin_dishes_labels_method: 'Garmethode',
    admin_dishes_labels_sauce: 'Saucenbasis',
    admin_dishes_labels_aromas: 'Aromen',
    admin_dishes_labels_texture: 'Textur',
    admin_dishes_labels_intensity: 'Intensität',
    admin_dishes_labels_spice: 'Schärfe',
    admin_dishes_labels_fat: 'Fettgehalt',
    admin_dishes_more_details: 'Mehr Details anzeigen',
    
    // Blog
    blog_tagline: 'Wein-Wissen',
    blog_title: 'Der Sommelier Blog',
    blog_description: 'Tipps, Wissen und Geschichten rund um die Welt des Weins.',
    blog_read_more: 'Weiterlesen',
    blog_all: 'Alle Artikel',
    blog_cat_tipps: 'Tipps',
    blog_cat_wissen: 'Wissen',
    blog_cat_pairings: 'Pairings',
    blog_cat_regionen: 'Regionen',
    blog_back: 'Zurück zum Blog',
    blog_share: 'Teilen',
    blog_related: 'Ähnliche Artikel',
    
    // Common
    error_dish_required: 'Bitte geben Sie ein Gericht ein',
    error_wine_name: 'Bitte geben Sie einen Weinnamen ein',
    error_general: 'Ein Fehler ist aufgetreten',
    success_wine_added: 'Wein hinzugefügt!',
    success_wine_deleted: 'Wein gelöscht',
    success_label_scanned: 'Etikett erfolgreich gescannt!',
    success_recommendation: 'Empfehlung erhalten!',
    listening: 'Ich höre zu...',
    voice_not_supported: 'Spracherkennung wird in Ihrem Browser nicht unterstützt'
  },
  en: {
    nav_home: 'Home',
    nav_pairing: 'Pairing',
    nav_cellar: 'Cellar',
    nav_sommelier: 'Claude',
    nav_blog: 'Blog',
    nav_feed: 'Community',
    nav_grapes: 'Grapes',
    nav_wine_database: 'Wine DB',
    hero_tagline: 'The Discovery of Pure Enjoyment',
    hero_title: 'Claude – Your Master Sommelier',
    hero_description: 'Master of Wine and passionate chef. The only recommendation that sells nothing but your perfect moment. Discover the harmony of wine and food – independent, honest, delightful.',
    cta_pairing: 'Start Wine Pairing',
    cta_cellar: 'My Wine Cellar',
    philosophy_tagline: 'Our Philosophy',
    philosophy_title: 'Born from Frustration',
    philosophy_text1: 'The world of wine is overloaded with expert gatekeeping and sales-driven complexity. Most wine apps force you to either speak like a sommelier or buy like a customer.',
    philosophy_text2: 'We bring the sommelier\'s logic to your kitchen – based on 30 years of expertise and systematic analysis of acidity, bitterness, and sweetness. Human at the core, precise in execution.',
    philosophy_quote: '"Don\'t plan around the wine. Start with the food."',
    feature_pairing_title: 'Smart Pairing',
    feature_pairing_desc: 'Enter your dish and receive the perfect wine recommendation – from your cellar or in general.',
    feature_scanner_title: 'Label Scanner',
    feature_scanner_desc: 'Photograph your wine labels and let AI capture all important information.',
    feature_sommelier_title: 'Personal Sommelier',
    feature_sommelier_desc: 'Ask our virtual sommelier anything about wine – personal and without sales pressure.',
    
    // Claude persona
    claude_intro_short: 'Over 20 years of experience in top restaurants – now in your kitchen, with zero sales agenda.',
    claude_bio_title: 'Claude – Your Virtual Sommelier',
    claude_bio_text1: 'Claude has spent more than two decades in international fine dining – first in the kitchen, then as a sommelier. He loves to understand dishes not only technically but also emotionally.',
    claude_bio_text2: 'His speciality is translating acidity, sweetness, bitterness and texture so that wine and food feel as if they came from the same hand. Instead of selling, he focuses on clear, honest recommendations – as if he were standing right at your table. For him, mindful enjoyment comes first: wine should elevate the moment, not dominate it.',
    pairing_tagline: 'Wine Pairing',
    pairing_title: 'What would you like to eat?',
    pairing_description: 'Describe your dish and our virtual sommelier will recommend the perfect wine.',
    pairing_label: 'Your Dish',
    pairing_placeholder: 'e.g. Grilled beef fillet with rosemary potatoes and red wine jus...',
    pairing_use_cellar: 'Recommend from my cellar',
    pairing_wine_preference: 'Which wine type do you prefer?',
    pairing_filter_country: 'Country',
    pairing_filter_trend: 'Trend cuisine',
    pairing_filter_bestseller: 'Bestseller category',
    pairing_all_types: 'All wine types',
    pairing_white: 'White Wine',
    pairing_red: 'Red Wine',
    pairing_rose: 'Rosé Wine',
    pairing_sparkling: 'Sparkling Wine',
    pairing_sweet: 'Sweet Wine',
    pairing_button: 'Get Recommendation',
    pairing_loading: 'Claude analyzing... (approx. 5-10 sec)',
    pairing_result_title: 'Sommelier Recommendation',
    pairing_result_for: 'for',
    pairing_cellar_matches: 'Matching wines from your cellar:',
    pairing_history: 'Recent Recommendations',
    pairing_voice_hint: 'Tap the microphone to dictate your dish',
    pairing_more_details: 'Show more details',
    pairing_pro_mode_title: 'Pro Mode – Palate Translator',
    pairing_pro_mode_subtitle: 'Default: Claude decides automatically. Here experts can fine-tune how the dish feels on the palate if they want to.',
    pairing_dim_richness: 'Richness',
    pairing_dim_freshness: 'Freshness',
    pairing_dim_sweetness: 'Sweetness',
    pairing_dim_spice: 'Spice',
    pairing_dim_hint_low: 'low',
    pairing_dim_hint_high: 'intense',
    pairing_why_title: 'Why this pairing works',
    pairing_why_fallback: 'Claude will soon explain here in simple words why wine and dish work together on your palate – along richness, freshness, sweetness and spice.',
    cellar_tagline: 'My Wine Cellar',
    cellar_title: 'Your Treasure Chamber',
    cellar_filter_all: 'All Wines',
    cellar_scan: 'Scan Label',
    cellar_add: 'Add Wine',
    cellar_empty_title: 'Your cellar is still empty',
    cellar_empty_desc: 'Add your first wine or scan a label.',
    cellar_empty_button: 'Add First Wine',
    cellar_scan_title: 'Scan Wine Label',
    cellar_scan_desc: 'Photograph the label to automatically capture the wine.',
    cellar_scan_prompt: 'Click here to take a photo',
    cellar_scanning: 'Analyzing label...',
    cellar_add_title: 'Add New Wine',
    cellar_add_desc: 'Add a wine to your cellar.',
    cellar_wine_name: 'Wine Name *',
    cellar_region: 'Region',
    cellar_year: 'Vintage',
    cellar_grape: 'Grape Variety',
    cellar_notes: 'Notes',
    cellar_upload_image: 'Upload image (optional)',
    cellar_save: 'Save Wine',
    chat_title: 'Claude – Your Sommelier',
    chat_subtitle: 'Master of Wine & passionate chef – no sales agenda, just honest advice.',
    chat_empty: 'Ask Claude a question about wine...',
    chat_suggestion1: 'Which wine with pasta?',
    chat_suggestion2: 'Red or white wine?',
    chat_suggestion3: 'What makes a great wine?',
    chat_placeholder: 'Ask Claude...',
    chat_voice_hint: 'Tap the microphone to speak',
    // Grapes
    grapes_tagline: 'Grape Lexicon',
    grapes_title: 'The World of Grapes',
    grapes_description: 'Discover the soul of each grape – poetically described, with perfect food pairings.',
    grapes_all: 'All',
    grapes_white: 'White Wine',
    grapes_red: 'Red Wine',
    grapes_empty: 'No grape varieties found',
    grapes_back: 'Back to all grapes',
    grapes_synonyms: 'Also known as',
    grapes_body: 'Body',
    grapes_acidity: 'Acidity',
    grapes_tannin: 'Tannin',
    grapes_aging: 'Aging',
    grapes_primary_aromas: 'Primary Aromas',
    grapes_tertiary_aromas: 'Tertiary Aromas',
    grapes_perfect_pairings: 'Perfect with',
    grapes_main_regions: 'Main Regions',

    // Admin Grapes
    admin_grapes_tagline: 'Internal Sommelier Workbench',
    admin_grapes_title: 'Manage Grape Varieties',
    admin_grapes_description: 'Generate new grape varieties with Claude and keep all data consistent for search and pairing.',
    admin_grapes_refresh: 'Refresh',
    admin_grapes_refreshing: 'Refreshing...',
    admin_grapes_normalize_title: 'Normalize Data',
    admin_grapes_normalize_button: 'Run Normalization',
    admin_grapes_normalizing: 'Normalizing...',
    admin_grapes_normalize_help: 'Scales body, acidity and tannin to a unified scheme (light/medium/full-bodied and low/medium/high) and cleans up aroma and food tags.',
    admin_grapes_generate_title: 'Generate New Grape with Claude',
    admin_grapes_generate_name: 'Grape name',
    admin_grapes_generate_name_placeholder: 'e.g. Garnacha, Blaufränkisch...',
    admin_grapes_generate_type: 'Wine type',
    admin_grapes_generate_type_auto: 'Detect automatically',
    admin_grapes_generate_hint: 'Style hint (optional)',
    admin_grapes_generate_hint_placeholder: 'e.g. Mediterranean, juicy, ideal with grilled meat',
    admin_grapes_generate_button: 'Generate grape variety',
    admin_grapes_generate_running: 'Claude is generating...',
    admin_grapes_last_generated: 'Last generated grape variety',
    admin_grapes_list_title: 'Existing grape varieties',
    admin_grapes_filter_placeholder: 'Search by name or synonym...',
    admin_grapes_list_empty: 'No grape varieties found.',
    admin_grapes_error_load: 'Could not load grape varieties.',
    admin_grapes_error_name_required: 'Please enter a grape name.',
    admin_grapes_generate_success: 'Grape variety generated successfully.',
    admin_grapes_generate_error: 'Error generating grape variety.',
    admin_grapes_normalize_done: 'Normalization completed.',
    admin_grapes_normalize_error: 'Error during normalization.',

    // Admin Dishes
    admin_dishes_tagline: 'Internal Dish Library',
    admin_dishes_title: 'Manage Dishes',
    admin_dishes_description: 'Generate structured dishes with Claude and use them as a foundation for precise wine recommendations.',
    admin_dishes_refresh: 'Refresh',
    admin_dishes_refreshing: 'Refreshing...',
    admin_dishes_seed_title: 'Populate Dish Database',
    admin_dishes_seed_button: 'Start seed batch',
    admin_dishes_seed_running: 'Seed batch running...',
    admin_dishes_seed_help: 'Starts a background job that lets Claude create a curated list of bestseller and country cuisine dishes in a structured way.',
    admin_dishes_generate_title: 'Generate New Dish with Claude',
    admin_dishes_generate_name: 'Dish name',
    admin_dishes_generate_name_placeholder: 'e.g. Burger, Pad Thai, Spaghetti Bolognese...',
    admin_dishes_generate_country: 'Country (optional)',
    admin_dishes_generate_country_placeholder: 'e.g. Italy, Thailand, USA...',
    admin_dishes_generate_trend: 'Trend cuisine (optional)',
    admin_dishes_generate_trend_placeholder: 'e.g. Thai, streetfood, fine dining...',
    admin_dishes_generate_category: 'Bestseller category (optional)',
    admin_dishes_generate_category_placeholder: 'e.g. burger, pasta, steak, fish...',
    admin_dishes_generate_button: 'Generate dish',
    admin_dishes_generate_running: 'Claude is generating...',
    admin_dishes_last_generated: 'Last generated dish',
    admin_dishes_list_title: 'Existing dishes',
    admin_dishes_filter_placeholder: 'Search by dish, country or category...',
    admin_dishes_list_empty: 'No dishes found.',
    admin_dishes_error_load: 'Could not load dishes.',
    admin_dishes_error_name_required: 'Please enter a dish name.',
    admin_dishes_generate_success: 'Dish generated successfully.',
    admin_dishes_generate_error: 'Error generating dish.',
    admin_dishes_seed_started: 'Seed batch started ({count} dishes).',
    admin_dishes_seed_error: 'Error starting seed batch.',
    admin_dishes_labels_protein: 'Protein',
    admin_dishes_labels_method: 'Cooking method',
    admin_dishes_labels_sauce: 'Sauce base',
    admin_dishes_labels_aromas: 'Aromas',
    admin_dishes_labels_texture: 'Texture',
    admin_dishes_labels_intensity: 'Intensity',
    admin_dishes_labels_spice: 'Spice level',
    admin_dishes_labels_fat: 'Fat level',
    admin_dishes_more_details: 'Show more details',
    // Feed
    feed_tagline: 'Wine Community',
    feed_title: 'Pairing Experiences',
    feed_description: 'Share your wine pairing discoveries and get inspired by others.',
    feed_members: 'Members',
    feed_experiences: 'Experiences',
    feed_top_pairings: 'Top Pairings',
    feed_set_name: 'What would you like to be called in the community?',
    feed_your_name: 'Your Name',
    feed_save_name: 'Save',
    feed_share_experience: 'Share Experience',
    feed_new_post: 'New Pairing Experience',
    feed_new_post_desc: 'Share your discovery with the community.',
    feed_dish_placeholder: 'What did you eat?',
    feed_wine_placeholder: 'Which wine?',
    feed_rating: 'How was the harmony?',
    feed_experience_placeholder: 'Describe your experience... (optional)',
    feed_add_photo: 'Add photo (optional)',
    feed_publish: 'Publish',
    feed_empty_title: 'No experiences yet',
    feed_empty_desc: 'Be the first to share a pairing experience!',
    feed_first_post: 'Share first experience',
    feed_name_required: 'Please enter a name',
    feed_fields_required: 'Please fill in dish and wine',
    feed_post_created: 'Experience shared!',
    feed_post_deleted: 'Experience deleted',
    feed_confirm_delete: 'Do you really want to delete this experience?',
    feed_delete_forbidden: 'You can only delete your own experiences',
    feed_write_comment: 'Write a comment...',
    feed_just_now: 'Just now',
    feed_minutes_ago: 'min',
    feed_hours_ago: 'hrs',
    feed_days_ago: 'days',
    // Blog
    blog_tagline: 'Wine Knowledge',
    blog_title: 'The Sommelier Blog',
    blog_description: 'Tips, knowledge and stories from the world of wine.',
    blog_read_more: 'Read more',
    blog_all: 'All Articles',
    blog_cat_tipps: 'Tips',
    blog_cat_wissen: 'Knowledge',
    blog_cat_pairings: 'Pairings',
    blog_cat_regionen: 'Regions',
    blog_back: 'Back to Blog',
    blog_share: 'Share',
    blog_related: 'Related Articles',
    error_dish_required: 'Please enter a dish',
    error_wine_name: 'Please enter a wine name',
    error_general: 'An error occurred',
    success_wine_added: 'Wine added!',
    success_wine_deleted: 'Wine deleted',
    success_label_scanned: 'Label scanned successfully!',
    success_recommendation: 'Recommendation received!',
    listening: 'Listening...',
    voice_not_supported: 'Voice recognition is not supported in your browser'
  },
  fr: {
    nav_home: 'Accueil',
    nav_pairing: 'Accords',
    nav_cellar: 'Cave',
    nav_sommelier: 'Claude',
    nav_blog: 'Blog',
    nav_feed: 'Communauté',
    nav_grapes: 'Cépages',
    nav_wine_database: 'Vins DB',
    hero_tagline: 'La Découverte du Pur Plaisir',
    hero_title: 'Claude – Votre Sommelier Master',
    hero_description: 'Master of Wine et chef passionné. La seule recommandation qui ne vend rien, sauf votre moment parfait. Découvrez l\'harmonie du vin et des mets – indépendant, honnête, délicieux.',
    cta_pairing: 'Commencer l\'accord',
    cta_cellar: 'Ma Cave à Vin',
    philosophy_tagline: 'Notre Philosophie',
    philosophy_title: 'Né de la Frustration',
    philosophy_text1: 'Le monde du vin est surchargé de gardiens experts et de complexité commerciale. La plupart des applications de vin vous obligent à parler comme un sommelier ou à acheter comme un client.',
    philosophy_text2: 'Nous apportons la logique du sommelier dans votre cuisine – basée sur 30 ans d\'expertise et l\'analyse systématique de l\'acidité, de l\'amertume et de la douceur. Humain au cœur, précis dans l\'exécution.',
    philosophy_quote: '«Ne planifiez pas autour du vin. Commencez par le plat.»',
    feature_pairing_title: 'Accord Intelligent',
    feature_pairing_desc: 'Entrez votre plat et recevez la recommandation de vin parfaite – de votre cave ou en général.',
    feature_scanner_title: 'Scanner d\'Étiquette',
    feature_scanner_desc: 'Photographiez vos étiquettes de vin et laissez l\'IA capturer toutes les informations importantes.',
    feature_sommelier_title: 'Sommelier Personnel',
    feature_sommelier_desc: 'Demandez à notre sommelier virtuel tout sur le vin – personnel et sans pression commerciale.',
    
    // Persona de Claude
    claude_intro_short: 'Plus de 20 ans d’expérience en haute gastronomie – maintenant dans votre cuisine, sans aucune intention de vente.',
    claude_bio_title: 'Claude – Votre Sommelier Virtuel',
    claude_bio_text1: 'Claude a passé plus de deux décennies dans des restaurants gastronomiques internationaux – d’abord en cuisine, puis comme sommelier. Il aime comprendre les plats non seulement techniquement, mais aussi émotionnellement.',
    claude_bio_text2: 'Sa spécialité est de traduire acidité, douceur, amertume et texture pour que le vin et le plat donnent l’impression de venir de la même main. Au lieu de vendre, il mise sur des recommandations claires et honnêtes – comme s’il se tenait directement à votre table. Pour lui, le plaisir conscient passe avant tout : le vin doit sublimer le moment, pas le dominer.',
    pairing_tagline: 'Accord Mets-Vin',
    pairing_title: 'Que voulez-vous manger?',
    pairing_description: 'Décrivez votre plat et notre sommelier virtuel recommandera le vin parfait.',
    pairing_label: 'Votre Plat',
    pairing_placeholder: 'ex. Filet de bœuf grillé aux pommes de terre romarin et jus de vin rouge...',
    pairing_use_cellar: 'Recommander de ma cave',
    pairing_wine_preference: 'Quel type de vin préférez-vous?',
    pairing_all_types: 'Tous les types de vin',
    pairing_white: 'Vin Blanc',
    pairing_red: 'Vin Rouge',
    pairing_rose: 'Vin Rosé',
    pairing_sparkling: 'Vin Mousseux',
    pairing_sweet: 'Vin Doux',
    pairing_button: 'Obtenir une Recommandation',
    pairing_loading: 'Claude analyse... (env. 5-10 sec)',
    pairing_result_title: 'Recommandation du Sommelier',
    pairing_result_for: 'pour',
    pairing_cellar_matches: 'Vins correspondants de votre cave:',
    pairing_history: 'Recommandations Récentes',
    pairing_voice_hint: 'Appuyez sur le microphone pour dicter votre plat',
    pairing_pro_mode_title: 'Mode Pro – Traducteur de Palais',
    pairing_pro_mode_subtitle: 'Par défaut, Claude décide tout seul. Ici, les connaisseurs peuvent affiner la sensation du plat en bouche s’ils le souhaitent.',
    pairing_dim_richness: 'Richesse',
    pairing_dim_freshness: 'Fraîcheur',
    pairing_dim_sweetness: 'Douceur',
    pairing_dim_spice: 'Épice',
    pairing_dim_hint_low: 'léger',
    pairing_dim_hint_high: 'intense',
    pairing_why_title: 'Pourquoi cet accord fonctionne',
    pairing_why_fallback: 'Claude expliquera ici, en mots simples, pourquoi le vin et le plat fonctionnent ensemble sur votre palais – selon la richesse, la fraîcheur, la douceur et l’épice.',
    cellar_tagline: 'Ma Cave à Vin',
    cellar_title: 'Votre Trésor',
    cellar_filter_all: 'Tous les Vins',
    cellar_scan: 'Scanner l\'Étiquette',
    cellar_add: 'Ajouter un Vin',
    cellar_empty_title: 'Votre cave est encore vide',
    cellar_empty_desc: 'Ajoutez votre premier vin ou scannez une étiquette.',
    cellar_empty_button: 'Ajouter le Premier Vin',
    cellar_scan_title: 'Scanner l\'Étiquette',
    cellar_scan_desc: 'Photographiez l\'étiquette pour capturer automatiquement le vin.',
    cellar_scan_prompt: 'Cliquez ici pour prendre une photo',
    cellar_scanning: 'Analyse de l\'étiquette...',
    cellar_add_title: 'Ajouter un Nouveau Vin',
    cellar_add_desc: 'Ajoutez un vin à votre cave.',
    cellar_wine_name: 'Nom du Vin *',
    cellar_region: 'Région',
    cellar_year: 'Millésime',
    cellar_grape: 'Cépage',
    cellar_notes: 'Notes',
    cellar_upload_image: 'Télécharger une image (optionnel)',
    cellar_save: 'Enregistrer le Vin',
    chat_title: 'Claude – Votre Sommelier',
    chat_subtitle: 'Master of Wine & chef passionné – pas d\'objectif de vente, juste des conseils honnêtes.',
    chat_empty: 'Posez une question à Claude sur le vin...',
    chat_suggestion1: 'Quel vin avec des pâtes?',
    chat_suggestion2: 'Vin rouge ou blanc?',
    chat_suggestion3: 'Qu\'est-ce qui fait un grand vin?',
    chat_placeholder: 'Demandez à Claude...',
    chat_voice_hint: 'Appuyez sur le microphone pour parler',
    // Grapes
    grapes_tagline: 'Lexique des Cépages',
    grapes_title: 'Le Monde des Cépages',
    grapes_description: 'Découvrez l\'âme de chaque raisin – décrit poétiquement, avec des accords mets-vins parfaits.',
    grapes_all: 'Tous',
    grapes_white: 'Vin Blanc',
    grapes_red: 'Vin Rouge',
    grapes_empty: 'Aucun cépage trouvé',
    grapes_back: 'Retour aux cépages',
    grapes_synonyms: 'Aussi connu sous',
    grapes_body: 'Corps',
    grapes_acidity: 'Acidité',
    grapes_tannin: 'Tanin',
    grapes_aging: 'Élevage',
    grapes_primary_aromas: 'Arômes Primaires',
    grapes_tertiary_aromas: 'Arômes Tertiaires',
    grapes_perfect_pairings: 'Parfait avec',
    grapes_main_regions: 'Régions Principales',

    // Admin Grapes
    admin_grapes_tagline: 'Atelier Sommelier Interne',
    admin_grapes_title: 'Gérer les Cépages',
    admin_grapes_description: 'Générez de nouveaux cépages avec Claude et gardez toutes les données cohérentes pour la recherche et les accords mets-vins.',
    admin_grapes_refresh: 'Rafraîchir',
    admin_grapes_refreshing: 'Rafraîchissement...',
    admin_grapes_normalize_title: 'Normaliser les Données',
    admin_grapes_normalize_button: 'Lancer la Normalisation',
    admin_grapes_normalizing: 'Normalisation...',
    admin_grapes_normalize_help: 'Met le corps, l\'acidité et les tanins sur une échelle unifiée (léger/moyen/corsé et faible/moyen/élevé) et nettoie les étiquettes d\'arômes et de mets.',
    admin_grapes_generate_title: 'Générer un Nouveau Cépage avec Claude',
    admin_grapes_generate_name: 'Nom du cépage',
    admin_grapes_generate_name_placeholder: 'par ex. Garnacha, Blaufränkisch...',
    admin_grapes_generate_type: 'Type de vin',
    admin_grapes_generate_type_auto: 'Détecter automatiquement',
    admin_grapes_generate_hint: 'Indication de style (optionnelle)',
    admin_grapes_generate_hint_placeholder: 'par ex. méditerranéen, juteux, idéal avec des viandes grillées',
    admin_grapes_generate_button: 'Générer le cépage',
    admin_grapes_generate_running: 'Claude génère...',
    admin_grapes_last_generated: 'Dernier cépage généré',
    admin_grapes_list_title: 'Cépages existants',
    admin_grapes_filter_placeholder: 'Rechercher par nom ou synonyme...',
    admin_grapes_list_empty: 'Aucun cépage trouvé.',
    admin_grapes_error_load: 'Impossible de charger les cépages.',
    admin_grapes_error_name_required: 'Veuillez saisir un nom de cépage.',
    admin_grapes_generate_success: 'Cépage généré avec succès.',
    admin_grapes_generate_error: 'Erreur lors de la génération du cépage.',
    admin_grapes_normalize_done: 'Normalisation terminée.',
    admin_grapes_normalize_error: 'Erreur lors de la normalisation.',

    // Admin Dishes
    admin_dishes_tagline: 'Bibliothèque Interne des Plats',
    admin_dishes_title: 'Gérer les Plats',
    admin_dishes_description: 'Générez des plats structurés avec Claude et utilisez-les comme base pour des recommandations de vins précises.',
    admin_dishes_refresh: 'Rafraîchir',
    admin_dishes_refreshing: 'Rafraîchissement...',
    admin_dishes_seed_title: 'Remplir la Base de Données des Plats',
    admin_dishes_seed_button: 'Lancer le seed batch',
    admin_dishes_seed_running: 'Seed batch en cours...',
    admin_dishes_seed_help: 'Lance une tâche en arrière-plan qui demande à Claude de créer une liste de plats best-sellers et de cuisines du monde de manière structurée.',
    admin_dishes_generate_title: 'Générer un Nouveau Plat avec Claude',
    admin_dishes_generate_name: 'Nom du plat',
    admin_dishes_generate_name_placeholder: 'par ex. Burger, Pad Thaï, Spaghetti Bolognaise...',
    admin_dishes_generate_country: 'Pays (optionnel)',
    admin_dishes_generate_country_placeholder: 'par ex. Italie, Thaïlande, États-Unis...',
    admin_dishes_generate_trend: 'Cuisine tendance (optionnelle)',
    admin_dishes_generate_trend_placeholder: 'par ex. thaï, streetfood, fine dining...',
    admin_dishes_generate_category: 'Catégorie best-seller (optionnelle)',
    admin_dishes_generate_category_placeholder: 'par ex. burger, pasta, steak, poisson...',
    admin_dishes_generate_button: 'Générer le plat',
    admin_dishes_generate_running: 'Claude génère...',
    admin_dishes_last_generated: 'Dernier plat généré',
    admin_dishes_list_title: 'Plats existants',
    admin_dishes_filter_placeholder: 'Rechercher par plat, pays ou catégorie...',
    admin_dishes_list_empty: 'Aucun plat trouvé.',
    admin_dishes_error_load: 'Impossible de charger les plats.',
    admin_dishes_error_name_required: 'Veuillez saisir un nom de plat.',
    admin_dishes_generate_success: 'Plat généré avec succès.',
    admin_dishes_generate_error: 'Erreur lors de la génération du plat.',
    admin_dishes_seed_started: 'Seed batch lancé ({count} plats).',
    admin_dishes_seed_error: 'Erreur lors du lancement du seed batch.',
    admin_dishes_labels_protein: 'Protéine',
    admin_dishes_labels_method: 'Méthode de cuisson',
    admin_dishes_labels_sauce: 'Base de sauce',
    admin_dishes_labels_aromas: 'Arômes',
    admin_dishes_labels_texture: 'Texture',
    admin_dishes_labels_intensity: 'Intensité',
    admin_dishes_labels_spice: 'Piquant',
    admin_dishes_labels_fat: 'Teneur en gras',
    admin_dishes_more_details: 'Afficher plus de détails',
    // Feed
    feed_tagline: 'Communauté du Vin',
    feed_title: 'Expériences d\'Accords',
    feed_description: 'Partagez vos découvertes d\'accords mets-vins et inspirez-vous des autres.',
    feed_members: 'Membres',
    feed_experiences: 'Expériences',
    feed_top_pairings: 'Meilleurs Accords',
    feed_set_name: 'Comment souhaitez-vous être appelé dans la communauté?',
    feed_your_name: 'Votre Nom',
    feed_save_name: 'Enregistrer',
    feed_share_experience: 'Partager une Expérience',
    feed_new_post: 'Nouvelle Expérience d\'Accord',
    feed_new_post_desc: 'Partagez votre découverte avec la communauté.',
    feed_dish_placeholder: 'Qu\'avez-vous mangé?',
    feed_wine_placeholder: 'Quel vin?',
    feed_rating: 'Comment était l\'harmonie?',
    feed_experience_placeholder: 'Décrivez votre expérience... (optionnel)',
    feed_add_photo: 'Ajouter une photo (optionnel)',
    feed_publish: 'Publier',
    feed_empty_title: 'Pas encore d\'expériences',
    feed_empty_desc: 'Soyez le premier à partager une expérience d\'accord!',
    feed_first_post: 'Partager la première expérience',
    feed_name_required: 'Veuillez entrer un nom',
    feed_fields_required: 'Veuillez remplir le plat et le vin',
    feed_post_created: 'Expérience partagée!',
    feed_post_deleted: 'Expérience supprimée',
    feed_confirm_delete: 'Voulez-vous vraiment supprimer cette expérience?',
    feed_delete_forbidden: 'Vous ne pouvez supprimer que vos propres expériences',
    feed_write_comment: 'Écrire un commentaire...',
    feed_just_now: 'À l\'instant',
    feed_minutes_ago: 'min',
    feed_hours_ago: 'h',
    feed_days_ago: 'jours',
    // Blog
    blog_tagline: 'Savoir Vinicole',
    blog_title: 'Le Blog du Sommelier',
    blog_description: 'Conseils, connaissances et histoires du monde du vin.',
    blog_read_more: 'Lire la suite',
    blog_all: 'Tous les Articles',
    blog_cat_tipps: 'Conseils',
    blog_cat_wissen: 'Savoir',
    blog_cat_pairings: 'Accords',
    blog_cat_regionen: 'Régions',
    blog_back: 'Retour au Blog',
    blog_share: 'Partager',
    blog_related: 'Articles similaires',
    error_dish_required: 'Veuillez entrer un plat',
    error_wine_name: 'Veuillez entrer un nom de vin',
    error_general: 'Une erreur s\'est produite',
    success_wine_added: 'Vin ajouté!',
    success_wine_deleted: 'Vin supprimé',
    success_label_scanned: 'Étiquette scannée avec succès!',
    success_recommendation: 'Recommandation reçue!',
    listening: 'J\'écoute...',
    voice_not_supported: 'La reconnaissance vocale n\'est pas prise en charge par votre navigateur'
  }
};

const languageNames = {
  de: 'Deutsch',
  en: 'English',
  fr: 'Français'
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('wine-app-language');
    return saved || 'de';
  });

  useEffect(() => {
    localStorage.setItem('wine-app-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['de'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languageNames, languages: Object.keys(translations) }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
